h2o/h2o

- include/h2o/serverutil.h
- lib/common/serverutil.c
- src/main.c
This uses sysconf to get the value of the number of online processing cores.  This works in both OSX 10.8.5 and Linux 3.13.0-36-generic, but it doesn't look there's Windows support that we have to worry about?
I'm not sure that sysconf could mess up an return a negative number, and we can't initialize the static config with a runtime function, so we initialize the static struct to 1, and only reassign if the sysconf value if it's greater.
You can check this value from the command line via `getconf NPROCESSORS_ONLN`.  We use this value by default (as long as it's above 1), unless you have set a value in your config file, which takes precedent.  Not sure if we should be using max procs minus one?
> based default thread count on getconf NPROCESSORS_ONLIN Fixes #24

- include/h2o/http2.h
- include/h2o/string_.h
- lib/common/http1client.c
- lib/core/headers.c
- lib/core/token_table.h
- lib/http1.c
- lib/http2/connection.c
- lib/http2/hpack.c
- misc/tokens.pl
- t/00unit/lib/http2/hpack.c
Considering the fact that [HTTP2 spec. states that header names must be lower-cased](http://http2.github.io/http2-spec/#rfc.section.8.1.2), for simplicity and performance we should better use lower-cased names internally.
> Internally keep header names lower-cased

- include/h2o.h
- lib/handler/configurator/proxy.c
- lib/handler/proxy.c
I added the following functions in order to pass some information about the original request to a upstream server.
- add X-Forwarded-For and X-Forwarded-Proto to request header.
- add proxy.preserve_host directive. To send Host header from client to upstream
X-Forwarded-For and X-Forwarded-Proto are de-facto standard for identifying the original request. Many application servers and middlewares support these header.
> Send remote address, used protocol and incoming host header to upstream

- include/h2o/string_.h
- lib/common/string.c
- lib/http1.c
- t/50file-config.t
source:
- https://www.igvita.com/2013/05/01/deploying-webp-via-accept-content-negotiation/
- http://blogs.msdn.com/b/ieinternals/archive/2009/06/17/vary-header-prevents-caching-in-ie.aspx
- http://blogs.msdn.com/b/ie/archive/2010/07/14/caching-improvements-in-internet-explorer-9.aspx
> Do not send Vary header if the client is MSIE

- include/h2o/memory.h
to silence 4 null pointer warnings from static
analysis #107
Also, `_Noreturn` [seems to be](http://stackoverflow.com/a/21646860/1027966) part of C11, and [MSVS has](http://msdn.microsoft.com/en-us/library/k6ktzx3s.aspx) `__declspec(noreturn)`. Not sure we want C11 features or if the M$ thing id C++ only?  Closing #108 in favor of this.
> Mark functions either noreturn or returns_nonnull

- include/h2o.h
- include/h2o/http1.h
- include/h2o/http2.h
- lib/core/config.c
- lib/core/context.c
- lib/http1.c
- lib/http2/connection.c
- lib/http2/frame.c
- src/main.c
The server should gracefully shutdown the connection and exit when receiving SIGTERM.
The PR is implemented as follows:
* core
* the server immediately closes the listening sockets when receiving SIGTERM
* the server exits with status code zero once all the connections get closed
* http1
* after receiving SIGTERM, all the HTTP/1 responses will have `Connection: close` set
* persistent connections will eventually get closed as the idle timeout expires or after handling the next request (since it would contain the `Connection: close` header)
* http2
* GOAWAY (stream_id=INT32_MAX) is sent for every stream when SIGTERM is received
* after one second, the server stops accepting new requests, and sends GOAWAY with `last_stream_id` set to the last stream ID that has been handled
* after then, …
> gracefully shutdown on SIGTERM

- src/main.c
This patch fixes #123 issue.
I confirmed that building h2o is successful after applying this patch on FreeBSD 10.1.
> Include for using macros related to 'wait'

- include/h2o/string_.h
- lib/common/http1client.c
- lib/common/string.c
- lib/handler/file.c
- lib/http1.c
- lib/http2/connection.c
- t/00unit/lib/common/string.c
As suggested in by @igrigorik in https://github.com/h2o/h2o/pull/133#issuecomment-72927404 application developers may want to set attributes against each URL being pushed.
In case of an application server requesting the reverse proxy to do so, we would need to use a name-value paired response header like `X-Server-Push: URL=http://server/pushed.css; PRIORITY=256`.
This PR implements such parser by extending the existing tokenizer (for headers like `Cache-Control`).
> implement parser for name-value pairs

- lib/common/socket/evloop.c.h
- lib/common/socket/evloop/kqueue.c.h
As can be found [here](https://github.com/h2o/h2o/blob/f6709ce/lib/common/socket/evloop.c.h#L62), only OS X (among the BSD systems) have used the kqueue until now.
This PR fixes the issue, enabling the kqueue-based backend for FreeBSD, NetBSD, and OpenBSD as well.
> enable kqueue on all BSDs

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/linklist.h
- include/h2o/multithread.h
- include/h2o/serverutil.h
- lib/common/multithread.c
- lib/common/serverutil.c
- lib/common/socket/evloop/select.c.h
- lib/core/context.c
- src/main.c
- t/00unit/lib/common/multithread.c
- t/00unit/test.c
- t/00unit/test.h
At the moment H2O uses signals for notifying other threads, however it cannot be used for general purpose (e.g. sharing a prefixed number of connections upstream, or using a dedicated thread for communicating with memcached (#120)), as it has TOCTOU issues.
There are two options to fix the problem, one is to use platform-dependent features like `signalfd` to integrate signal handling with poll-based event loop; the other is to switch to `pipe` based messaging.
This PR uses the latter approach (which can be optimized in case of linux by using `eventfd`).
> Introduce pipe-based inter-thread messaging

- h2o.xcodeproj/project.pbxproj
- lib/handler/access_log.c
- t/50access-log.t
lib/handler/access_log.c should lowercase the supplied header names, or it is impossible to log the header when the specified name includes a upper-case character (e.g. `%{User-agent}i`).
relates to #36
> fix access-log failing to log headers when specified using uppercase letters

- lib/handler/mimemap.c
According to [RFC4627](http://www.rfc-editor.org/rfc/rfc4627.txt), `application/json` is appropriate for JSON.
> add new media type(application/json) to default media types

- lib/handler/proxy.c
- t/50reverse-proxy-config.t
- t/50reverse-proxy.t
- t/assets/upstream.psgi
quote [Hypertext Transfer Protocol version 2 section 8.1.2.5](http://http2.github.io/http2-spec/index.html#CompressCookie):
> If there are multiple Cookie header fields after decompression, these MUST be concatenated into a single octet string using the two octet delimiter of 0x3B, 0x20 (the ASCII string "; ") before being passed into a non-HTTP/2 context, such as an HTTP/1.1 connection, or a generic HTTP server application.
> merge the cookie headers sent from HTTP/2 clients

- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- lib/common/http1client.c
- lib/handler/configurator/proxy.c
- lib/handler/proxy.c
- t/50reverse-proxy-upstream-down.t
- t/50reverse-proxy.t
This PR does the following:
* removes the `proxy.keepalive` configuration directive
* the upstream connections become non-persistent if `proxy.keepalive.timeout: 0`
* upstream connections by default are persistent, since the dafault value of `proxy.keepalive.timeout` is `2000` (in milliseconds)
> simplify the proxy configuration (remove `proxy.keepalive`)

- include/h2o/http2.h
- lib/http2/connection.c
Fixes behaviors found by h2spec v0.0.6 not conforming to the HTTP/2 spec., with https://github.com/summerwind/h2spec/pull/19 being the only exception.
> Fix issues found by h2spec v0.0.6

- examples/doc_root/index.html
The current sample page was not valid HTML since it was using `<header>` instead of `<head>` tag.
Not a huge deal, but for the sample page of a standards compliant web server, this seemed like it shouldn't be overlooked! :smile:
> Fix invalid HTML in sample page

- share/h2o/fetch-ocsp-response
- t/90live-fetch-ocsp-response.t
Some OCSP responder (eg: www.startssl.com) requires HTTP `Host` header.
```
sending OCSP request to http://ocsp.startssl.com/sub/class4/server/ca
Error querying OCSP responsder
140192127325856:error:27076072:OCSP routines:PARSE_HTTP_LINE1:server response error:ocsp_ht.c:250:Code=400,Reason=Bad Request
OpenSSL exitted abnormally: openssl ocsp -issuer /tmp/a0m9_V78bN/issuer.crt -cert /tmp/4nKFjVVJ1H -url http://ocsp.startssl.com/sub/class4/server/ca -noverify -respout /tmp/a0m9_V78bN/resp.der :    not ok 2 - fetch-ocsp-response exitted with status:19200
1..2
not ok 6 - www.startssl.com
```
> Add 'Host' header to OCSP request

- include/h2o/http2.h
fixes https://github.com/h2o/h2o/issues/173#issuecomment-75215769
> global variables need to be marked as `extern`

- src/main.c
type of somaxconn is unsigned short in kernel. So a maximum value is not 65536 but 65535.
https://github.com/torvalds/linux/commit/5f671d6b4ec3e6d66c2a868738af2cdea09e7509
> fixed invalid somaxconn value.

- lib/http2/hpack.c
- t/assets/upstream.psgi
The encoder emits an assertion failure in case the header value is expected to become equal to or longer after being huffman encoded, as the huffman encoding function returns an unexpected value (in such case the function should have return zero whereas it actually returns -1).
The PR fixes the issue in response to #185.
> [http2] fix assertion failure in hpack encoder

- lib/common/http1client.c
The bug may lead to internal state corruption, as it may set `h2o_socket_buffer_prototype._initial_buf.size` to a non-zero value (happens when the HTTP response from upstream is received in multiple number of packets, and if the last packet did not contain any response body).
> fix `bytes_read` becoming incorrect when response is not received at once

- lib/handler/proxy.c
- t/50reverse-proxy.t
As suggested by @tatsuhiro-t and @Lukasa in tweets: http://twitter.com/tatsuhiro_t/status/569886046982316032 and http://twitter.com/Lukasaoz/status/569972529571495936.
The header emitted looks like: `via: 2 127.0.0.1.xip.io:8081` (RFC 7230 suggests that `HTTP/` portion of the protocol be removed).
> Send `Via` header to upstream server

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/url.h
- lib/common/url.c
- lib/core/config.c
- lib/core/context.c
- lib/core/proxy.c
- lib/core/request.c
- lib/handler/access_log.c
- lib/handler/chunked.c
- lib/handler/configurator/proxy.c
- lib/handler/configurator/reproxy.c
- lib/handler/proxy.c
- lib/handler/reproxy.c
- lib/http1.c
- lib/http2/connection.c
- lib/http2/hpack.c
- lib/websocket.c
- src/main.c
- t/00unit/lib/core/proxy.c
- t/00unit/lib/handler/file.c
- t/00unit/lib/http2/hpack.c
- t/00unit/test.c
- t/50reverse-proxy-config.t
- t/50reverse-proxy.t
- t/80issues61.t
- t/assets/upstream.psgi
This PR modifies the request handling procedure of H2O to support internal redirects, specifically by:
* create `h2o_req_t::input` for preserving the original request
* create function `h2o_reprocess_request` that internally re-issues a request with request attributes (e.g. method, authority, path) being altered
* move the proxy implementation into core, as it would be the _default_ handler for handling internally-redirected responses
* the reverse proxy handler merely _redirects_ the request (so that it would be handled by the now internalized proxy implementation)
The beauty of the new approach is that the proxy implementation can be shared with the reverse-proxy and the `x-reproxy-url` handler (see also #187), and that it is capable of handling `x-reproxy-url` header that points to a …
> Internal redirect

- include/h2o.h
- lib/core/config.c
- lib/core/configurator.c
- lib/core/request.c
- t/50reverse-proxy-config.t
- t/assets/upstream.psgi
add a counter (that can be configured by using the `max-delegations` directive; default is 5) that limits the maximum count of delegations (amends #197).
> limit max. number of delegations (i.e. `X-Reproxy-URL`)

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/string_.h
- lib/common/string.c
- lib/handler/configurator/headers.c
- lib/handler/headers.c
- src/main.c
- t/00unit/lib/common/string.c
- t/00unit/lib/handler/headers.c
- t/00unit/test.c
- t/00unit/test.h
- t/50headers.t
This PR implements directives to tweak the response headers; model after [`Headers` directive of Apache](http://httpd.apache.org/docs/2.4/en/mod/mod_headers.html#header).
It provides following directives: `header.add`, `header.append`, `header.merge`, `header.set`, `header.setifempty`, `header.unset`.
see #196
> add directives to tweak the headers

- examples/libh2o/http1client.c
- include/h2o/http1client.h
- include/h2o/socketpool.h
- lib/common/http1client.c
- lib/common/socketpool.c
- lib/core/context.c
- lib/core/proxy.c
- lib/handler/proxy.c
This is a performance improvement (& simplification).
The PR converts `h2o_http1client_connect`, `h2o_http1client_connect_with_pool`, `h2o_socketpool_connect` to tail calls, and let them call the supplied callback synchronously when possible.
> do not use `zero_timeout` in http1client

- lib/core/request.c
- lib/handler/file.c
- t/00unit/lib/handler/file.c
- t/40pathconf-redirect.t
- t/50reverse-proxy.t
Since using absurl may cause issues with hostname rewrites.
Also fixes the `[lib/core/proxy.c] in request:/files/:I/O error (head)` error in t/50reverse-proxy.t introduced in #202; the error was due to the use of `req->input.authority` in [lib/core/request.c line 92](https://github.com/h2o/h2o/blob/283459211df8e2a9c1561728fa831cc23269bb10/lib/core/request.c#L92).  The line was causing the proxy to connect to H2O's TLS port.
> use abspath (not absurl) for redirecting to directory

- include/h2o/socketpool.h
> Include '<netinet/in.h>' for using 'struct sockaddr_in'

- lib/common/socket/evloop/kqueue.c.h
The server may crash on NetBSD when the proxy module tries to maintain a persistent connection to upstream servers.
This is because `EV_SET` of NetBSD causes side-effects to the arguments.  In 9d9ff2e we had added a wrapper function to fix the issue, but there was an oversight.
> fix crash on netbsd when upstream connection is persistent

- include/h2o/socket/evloop.h
> empty struct should not be used in C code

- lib/http2/connection.c
Endpoint should close the connection with PROTOCOL_ERROR when receiving a DATA frame on an idle/closed stream.
> fix HTTP/2 compliance issue found by h2spec v0.08

- lib/handler/mimemap.c
WebP is a future anticipated image format. 
Though I think it may included in default MIME-types, so what do you think? > @kazuho
> Added webp to mime types

- src/main.c
When compiling against openssl with compression support, h2o is using it, becoming vulnerable to CRIME attacks.
> Disable TLS compression

- lib/common/multithread.c
- lib/common/socketpool.c
- lib/http2/scheduler.c
As original code does not handling allocation-error, `h2o_mem_alloc()` is better.
> use h2o_malloc instead of malloc for allocation-error.

- lib/core/proxy.c
- t/50reverse-proxy/test.pl
fixes #266 (while maintaining the exponential back-off algorithm for calculating the next allocation size).
note: should better use `__builtin_clz` for rounding up the number by power of two.
> Fix memory corruption when proxying large cookie headers

- include/h2o/timeout.h
- lib/common/socket/evloop.c.h
- lib/common/socket/uv-binding.c.h
- lib/common/timeout.c
As discussed in http://blog.kazuhooku.com/2014/09/the-reasons-why-i-stopped-using-libuv.html the embedded event loop is designed to call i/o completion callbacks ASAP, so that memory can be freed before handling the next connection.
However the timeout callbacks were not called in such a manner, and therefore the HTTP/2 connection layer was using more memory than it should (the protocol handler was not reusing a single ~80KB block for many connections which is feasible for HTTP/2 64KB connection window).
> process pending callbacks ASAP (for every timeout callback)

- lib/common/http1client.c
The proxy fails to determine by using status code that response is expected to contain body (the code is referring to a wrong value).  Therefore, if the upstream server sends either 204 or 304 response and if the connection is persistent, H2O errorneously waits for content from upstream until `proxy.timeout.io` expires or until upstream closes the connection.
This PR fixes the issue; also adjusts the code to preserve connection if possible in case the response is not known to contain body.
fixes #274
> fix laggy response if upstream sends a response known not to contain body

- src/main.c
Because original code does not check the return value of `strdup()`.
> use h2o_strdup() instead of strdup().

- CMakeLists.txt
- examples/libh2o/simple.c
- examples/libh2o/websocket.c
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/url.h
- lib/core/config.c
- lib/core/configurator.c
- lib/core/context.c
- lib/core/request.c
- lib/handler/access_log.c
- src/main.c
- t/00unit/issues/293.c
- t/00unit/lib/handler/file.c
- t/00unit/test.c
- t/00unit/test.h
reimplements the lookup logic of host-level conf to be as follows:
* compares hostnames case-less
* host-level configuration _wo. port number_ matches the requests coming in to the default ports (i.e. http coming into port 80 __and__ https coming into port 443)
* host-level configuration _with port number_ matches the requests with host headers wo. port number
The original logic was simply using memcmp for comparing hostport.
fixes #293
> refactor virtual-host lookup

- src/main.c
There is a lack of error-handling for `EC_KEY_new_by_curve_name()`.
> imporved error handling for setup_ecc_key().

- lib/handler/file.c
Sends 503 (instead of 403) in case the file descriptor table is full.
fixes #301
> send 503 in case of ENFILE or EMFILE

- CMakeLists.txt
- examples/libh2o/http1client.c
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/hostinfo.h
- include/h2o/http1client.h
- include/h2o/socketpool.h
- lib/common/hostinfo.c
- lib/common/http1client.c
- lib/common/socketpool.c
- lib/core/proxy.c
- lib/handler/proxy.c
- t/00unit/lib/common/hostinfo.c
- t/00unit/test.c
- t/00unit/test.h
This PR fixes a potential use-after free issue in hostname lookup, by copying the `name` and `serv` passed into `h2o_hostinfo_getaddr`.
It also refactors the API of the related functions, removes an unused property: `h2o_http1client_t::pool`.
relates to #306
> fix potential use-after-free issue during hostname lookup

- lib/handler/access_log.c
The original approach (`popen` + `dup` + `pclose`) blocks on `pclose` in case of Linux.
> use `pipe` and `posix_spawnp` for spawning a piped logger

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o/serverutil.h
- lib/common/serverutil.c
- lib/handler/access_log.c
- share/h2o/annotate-backtrace-symbols
- src/main.c
The PR sets a signal handler for fatal signals that emits the stacktrace to standard error (or the error log file).
It uses an external wrapper (that calls addr2line) to look-up the corresponding source lines.
> dump stacktrace in case of fatal error

- lib/common/serverutil.c
- lib/handler/access_log.c
This causes compiler warnings and they are no longer necessary by #331 change.
> Remove unused variable declarations

- lib/handler/access_log.c
- src/main.c
Fix three file descriptor leaks found.
The combination of 47b5c51 and d978e0d was leading to restart failures when logs are emitted via pipes.  Due to the bug fixed in d978e0d the logging process was not exitting when the server dies, and since the listening port (passed in from `start_server`) was not marked as `FD_CLOEXEC` and thus was passed to the logging process, it was unable to spawn the server once again.
> Fixes file-descriptor leaks being found

- include/h2o.h
- include/h2o/http2_scheduler.h
- lib/core/configurator.c
- lib/http2/connection.c
- lib/http2/scheduler.c
At the moment, Chrome falls behind Firefox in prioritizing the asset files, as discussed in http://blog.kazuhooku.com/2015/04/dependency-based-prioritization-makes.html.
This PR implements a workaround in the server-side by raising the priority to maximum of requests that are likely against asset files.  The reprioritization is not applied to HTTP2 connections that use priority trees (e.g. Firefox).
> reprioritize blocking asset files (`.js`, `.css`) for Chrome

- include/h2o/http2_internal.h
- lib/http2/connection.c
- lib/http2/stream.c
Contrary to the HTTP/2 spec, the pull-type handler of H2O (which is used by its reverse proxy implementation) decrements the number of open streams when it receives the end of the response from upstream servers.
The fact leads to the issue reported in #341.  This PR fixes the problem.
> decrement the stream counters after sending the entire response

- src/main.c
Introduced `tcp-fastopen` as the new directive. It takes 1 argument for the maximum queue length.
By default, the value of `tcp-fastopen` is zero (In this case, TCP Fast Open is disabled). Because TCP Fast Open is not always available. 
```yaml
tcp-fastopen: 4096
```
> Feature: TCP Fast Open implementaion.

- examples/libh2o/simple.c
- examples/libh2o/websocket.c
- include/h2o.h
- include/h2o/socket.h
- include/h2o/socket/uv-binding.h
- lib/common/socket/evloop.c.h
- lib/common/socket/uv-binding.c.h
- lib/core/proxy.c
- lib/handler/access_log.c
- lib/handler/fastcgi.c
- lib/http1.c
- lib/http2/connection.c
- t/00unit/lib/handler/fastcgi.c
- t/00unit/test.c
This PR adds three things,
* refactors the socket and `h2o_conn_t`, adding `get_peername` callback to obtain the peer address (instead of providing a pointer to `struct sockaddr`)
* adds `get_sockname` callback to obtain the local address
* the fastcgi handler uses `get_sockname` callback to build `SERVER_ADDR` and `SERVER_PORT` properties of `FCGI_PARAMS`
amends #346
> provide getsockname and getpeername wrappers (send `SERVER_(ADDR|PORT)` to fastcgi)

- include/h2o.h
- include/h2o/url.h
- lib/handler/configurator/fastcgi.c
- lib/handler/configurator/redirect.c
- lib/handler/fastcgi.c
- lib/handler/file.c
- lib/handler/redirect.c
- t/00unit/lib/handler/fastcgi.c
- t/00unit/lib/handler/redirect.c
This PR implements features that are sufficient to support WordPress-style URL rewrites without stepping into the mod_rewrite-hell.
For example, with the PR it becomes possible to map `/2015/06/15/blogpost/` internally to `/index.php/2015/06/15/blogpost/` in case no file was found.
The approach is a combination of:
* the file handler passes the request through to the next handler if it failed to find the file
* adds `internal` attribute to `redirect` handler, so that it could be used for declaring internal redirections
With these features, it is possible to support WordPress-like URL rewrites by setting the configuration directive like:
```
file.custom-handler:
extension: .php
fastcgi.spawn: "PHP_FCGI_CHILDREN=10 exec php-cgi"
hosts:
"hostname":
paths:
/:
file.dir: /www/root/dir   # serve …
```
> Implement features to sufficient to support WordPress URL rewrites

- share/h2o/fetch-ocsp-response
Previously, we only used -header when openssl_version starts with
"OpenSSL 1.".  This is because the availability of -header is limited
to that series.  But it turns out that LibreSSL also has this option,
but its version line starts with "LibreSSL ", which does not match our
regexp, and some ocsp responder fails because of lack of Host header
field.  This commit fixes this problem, by allowing sending -header if
version string starts with "LibreSSL ".  LibreSSL's first release tag
is 2.0.0, which is based on OpenSSL 1.0.1h, so it should have -header
option.  Also this commit include fixes to include port part to
ocsp_host.  Technically, Host header field should include port number
(it can omit it if it is a default port for the scheme).
> fetch-ocsp-response: Support LibreSSL

- src/main.c
In #356 we have added support for TCP Fast Open which is enabled by default (if `TCP_FASTOPEN` is defined in the header files).
However, people may use the server complied in an environment with `TCP_FASTOPEN` defined, and use the binary in an environment (i.e. kernel) that does not support the feature (see the comments on the pull-req).  In such situation, the server fails to boot up due to the fact that it exits with a fatal error if `setsockopt(TCP_FASTOPEN)` fails.
This PR changes how the error is being handled.  Instead of refusing to start, the server now just emits a warning and continues to operate if `setsockopt(TCP_FASTOPEN)` fails.
> Emit warning (instead of fatal error) when failing to set TCP Fast Open

- src/main.c
`execinfo.h` is not part of the C standard library, so we need to verify
which implementation is being used to see if it's available.
> Include execinfo.h if it is available (glibc)

- h2o.xcodeproj/project.pbxproj
- lib/common/socket/evloop.c.h
- lib/common/socket/evloop/poll.c.h
`select` has been the backend for OSes that do not support `epoll` nor `kqueue`.
However, the backend has had issues when handling large number of sockets, as discussed in #287.
This PR fixes the issue by replacing the default (i.e. fallback) backend from using `select` to `poll`.
> introduce `poll`-based backend for i/o multiplexing, replacing `select`

- .travis.yml
- CMakeLists.txt
- examples/libh2o/simple.c
- examples/libh2o/websocket.c
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/http1.h
- include/h2o/http2.h
- include/h2o/socket.h
- include/h2o/socket/evloop.h
- lib/common/multithread.c
- lib/common/socket.c
- lib/common/socket/evloop.c.h
- lib/common/socket/uv-binding.c.h
- lib/core/util.c
- lib/http1.c
- lib/http2/connection.c
- src/main.c
- t/00unit/lib/core/util.c
- t/00unit/test.c
- t/00unit/test.h
- t/40proxy-protocol.t
The PROXY protocol is a simple protocol defined in http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt.  As discussed in #350, it is useful for running a TCP-based server behind L4-level load balancers such as HAProxy or Amazon AWS ELB.
This PR implements version 1 of the protocol.
The server can be configured to accept the protocol by adding `proxy-protocol: ON` to the `listen` directive, e.g.:
```
listen:
port: 443
proxy-protocol: ON
ssl:
...
```
> Add support for PROXY protocol

- include/h2o.h
- lib/core/config.c
- lib/core/configurator.c
- lib/core/context.c
- lib/core/util.c
- t/40proxy-protocol.t
H2O lacks timeout configuration for TLS handshake and the PROXY protocol recently added in #386.
This PR implements the timeout with the configuration variable named `handshake-timeout`.
> Configurable timeout for TLS handshake and the PROXY protocol

- lib/handler/fastcgi.c
- t/50fastcgi.t
- t/assets/upstream.psgi
As suggested in #397 some FastCGI-based web applications use `HTTPS` variable of the input to determine the protocol.
This PR changes the fastcgi handler of H2O to automatically set the variable.
FWIW a complete list of variables that could possibly be set by the Apache HTTP server can be found [here](http://httpd.apache.org/docs/2.4/mod/mod_ssl.html).
> pass `HTTPS: on` to fcgi app. if the connection is HTTPS

- CMakeLists.txt
- examples/h2o_mruby/hello.rb
- include/h2o/mruby.h
- lib/handler/mruby.c
- lib/handler/mruby/class/core.c
- lib/handler/mruby/class/request.c
- lib/handler/mruby/init.c
- t/50mruby.t
- t/50mruby/max_header.rb
h2o_mruby support H2O class of mruby. For now, I implemented `H2O.max_headers` method.
```ruby
H2O.max_headers #=> 100
```
> [h2o_mruby] Add H2O class and simple method

- examples/h2o_mruby/hello.rb
- lib/handler/mruby.c
- lib/handler/mruby/class/request.c
- t/50mruby.t
- t/50mruby/headers_in.rb
- t/50mruby/headers_out.rb
- t/50mruby/hello.rb
Hello @kazuho !!
I implemented some method which control both request and response headers. 
- hello.rb
```ruby
$ cat examples/h2o_mruby/hello.rb 
h = "hello"
m =  "from h2o_mruby"
ua = r.headers_in["User-Agent"].to_s
accept = r.headers_in["Accept"].to_s
new_ua = r.headers_in["User-Agent"] = "new-#{ua}-h2o_mruby"
r.headers_out["Hoge"] = "fuga"
hoge = r.headers_out["Hoge"]
msg = h + " " + m + " from " + ua + ":" + new_ua + " " + accept + " " + hoge
r.log_error msg
nil                                                                   
```
- curl
```
$ curl 127.0.0.1:8080/ -v -H User-Agent:h2o_mruby_test
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> Accept: */*
> …
```
> [h2o_mruby] Add header method on on_req

- include/h2o/mruby.h
- lib/handler/mruby.c
- lib/handler/mruby/class/core.c
- t/50mruby.t
- t/50mruby/index.html
- t/50mruby/return_declined.rb
- t/50mruby/return_status.rb
`H2O.return` method send http status code to clients, or decline to send response for next handler. It's useful in practice. If using this method, you can write access control which is the selective restriction of access to a place or other resource. But, I don't implement the method of request parameters yet like `H2O::Request#uri` or `H2O::Request#filename`. So I'll implement these method as soon!
- return http status code
```ruby
H2O.return 404, "not found", "not found"
```
- decline to send response for next handler
```ruby
H2O.return H2O::DECLINED
```
> [h2o_mruby] Add the method which return status code or declined behavior to h2o

- lib/common/socket.c
- src/ssl.c
Clear expired entries in session cache every `lifetime / 4` seconds, instead of relying on OpenSSL to clear them every 255 handshake attempts (which we cannot be certain when it happens).
> Normally the session cache is checked for expired sessions every 255 connections using the SSL_CTX_flush_sessions function. Since this may lead to a delay which cannot be controlled, the automatic flushing may be disabled and SSL_CTX_flush_sessions can be called explicitly by the application.
> [SSL_CTX_set_session_cache_mode, SSL_CTX_get_session_cache_mode - enable/disable session caching](https://www.openssl.org/docs/ssl/SSL_CTX_set_session_cache_mode.html)
relates to #395
> explicitly collect the expired entries of the internal session cache

- examples/h2o_mruby/hello.rb
- include/h2o/mruby.h
- lib/handler/mruby/class/request.c
- t/50mruby.t
- t/50mruby/authority.rb
- t/50mruby/hostname.rb
- t/50mruby/method.rb
- t/50mruby/query.rb
- t/50mruby/uri.rb
Hello @kazuho !!
I implemented some H2O::Request methods. For example, executed `curl 127.0.0.1:8080/index.html?a=1`: 
```ruby
r.hostname    #=> "127.0.0.1:8080"
r.authority   #=> "127.0.0.1:8080"
r.uri         #=> "/index.html?a=1"
r.path        #=> "/index.html?a=1"
r.method      #=> "GET"
r.qeury       #=> "?a=1"
```
> [h2o_mruby] Add some H2O::Request methods

- CMakeLists.txt
- lib/handler/configurator/mruby.c
- lib/handler/mruby.c
- lib/handler/mruby/class/core.c
- lib/handler/mruby/class/request.c
- lib/handler/mruby/init.c
This PR simplifies the build rules of the mruby handler as follows:
* only compile and link the mruby handler if `-DWITH_MRUBY=ON` is specified
* remove `#if H2O_USE_MRUBY` from source files
* abort CMake configuration if `-DWITH_MRUBY=ON` is used and if libmruby was not found
> Simplify the build rules of the mruby handler

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/serverutil.h
- lib/common/serverutil.c
- lib/handler/configurator/fastcgi.c
- src/main.c
- src/setuidgid.c
The fastcgi process spawned by `fastcgi.spawn` is executed before H2O calls `setuid`.  So in case the server is spawned with root privileges (is a requirement if it needs to listen to port 80 or 443), the process gets spawned with root privileges.
As discussed in http://d.hatena.ne.jp/hirose31/20130808/1375965331, there are several ways to drop the privileges by using wrapper commands within the argument of the configuration directive.  But it is not easy for an ordinary user to install and use them correctly.
Therefore this PR does the following:
* by default, change the uid (and group privileges) of the spawned process to that specified using the global `user` directive (in other words, fastcgi processes will be run under the same privileges as the H2O server)
* optionally accept a …
> setuid the process spawned by `fastcgi.spawn`

- src/ssl.c
AFAIK Glibc is the only Libc that defaults to reader-preferred rwlock.
> should specify writer-preferred rwlock on Glibc

- lib/handler/fastcgi.c
fixes #424 #425 
FastCGI handler is incorrectly concatenating the values using `,` instead of adding separate line of headers when it receives more than one headers with same name from an FastCGI application.
The problem leads to login issues on FastCGI applications that send out multiple `Set-Cookie` headers at once, since the browser failed to decode the values of `Set-Cookie` header concatenated by `,`.
> do not concatenate the headers (ex. Set-Cookie) sent by the app

- CMakeLists.txt
- examples/h2o_mruby/hello.rb
- lib/handler/mruby/class/connection.c
- lib/handler/mruby/init.c
- t/50mruby.t
- t/50mruby/remote_ip.rb
Hello @kazuho !!
I added H2O::Connection#remote_ip for ipaddress based access controls.
For example,
```ruby
deny_list = %w{
192.168.0.11
}
if deny_list.include? H2O::Connection.new.remote_ip
H2O.return 403, "Forbidden", "Forbidden"
end
```
> Add H2O::Connection class and remote_ip method

- include/h2o.h
- include/h2o/configurator.h
- lib/core/config.c
- lib/core/configurator.c
- lib/core/request.c
- lib/handler/configurator/file.c
- lib/handler/file.c
- lib/handler/mimemap.c
- t/00unit/lib/handler/mimemap.c
Still WIP; blocker of: #413 #432
For on-the-fly gzip, we need a flag in mimemap declaring whether if certain type is compressible (e.g. text/html) or not (e.g. image/jpeg).  For cache-aware server push, we need a flag declaring whether if certain type is likely a blocking asset (e.g. JavaScript or CSS) or not (e.g. images).
This PR adds such flags to the mimemap.
> mimemap with attributes

- CMakeLists.txt
- deps/golombset/README.md
- deps/golombset/golombset.h
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/http2.h
- include/h2o/http2_casper.h
- include/h2o/http2_internal.h
- lib/core/configurator.c
- lib/http2/casper.c
- lib/http2/connection.c
- lib/http2/stream.c
- t/00unit/lib/http2/casper.c
- t/00unit/test.c
- t/00unit/test.h
- t/40server-push.t
- t/assets/doc_root/index.js
This PR implements cache-aware server push using cookies.
ToDo:
* note: this is only necessary for cookie-based approach; when using SW we can build an accurate fingerprint on the client-side by iterating through the SW cache
part of #421
> cache-aware server push (cookie-based)

- lib/handler/file.c
- t/00unit/lib/handler/file.c
For conformance with RFC 7232 section 4.1; quote:
> The server generating a 304 response MUST generate any of the following header fields that would have been sent in a 200 (OK) response to the same request: Cache-Control, Content-Location, Date, ETag, Expires, and Vary.
> 
> Since the goal of a 304 response is to minimize information transfer when the recipient already has one or more cached representations, a sender SHOULD NOT generate representation metadata other than the above listed fields unless said metadata exists for the purpose of guiding cache updates (e.g., Last-Modified might be useful if the response does not have an ETag field).
> send `etag` (and `vary` if necessary) within 304 response

- lib/handler/mruby/class/core.c
Hi @matsumoto-r san, @kazuho san,
I want to change response headers with not only `H2O.return H2O::DECLINED` but `H2O.return [statuscode]`.
For example,
```
r.headers_out["WWW-Authenticate"] = %Q(Basic realm="Enter your ID/Pass")
H2O.return 401, "Unauthorized", "See you in the next dimension!"
```
So why don't we keep modified headers with `h2o_send_error` in `h2o_mrb_return`?
> Keep modified headers on H2O.return

- share/h2o/kill-on-close
When the standalone server is invoked in foreground and if Ctrl-C is pressed, shell sends SIGINT to the process group, which kills the `kill-on-close` script along with the standalone server, therefore leaving `php-cgi` processes running as orphans.
> ignore SIGINT in `kill-on-close` (and wait until parent shuts down)

- lib/handler/mruby/class/request.c
- t/50mruby.t
- t/50mruby/proxy/proxy.html
- t/50mruby/reverse_proxy.rb
Hi @kazuho !!
h2o_mruby supports simple reverse proxy method. Please review it :)
```ruby
backends = [
"http://192.168.0.101:8888/",
"http://192.168.0.102:8888/",
"http://192.168.0.103:8888/",
"http://192.168.0.104:8888/",
]
if r.uri == "/proxy.html"
r.reprocess_request backends[rand(backends.length)] 
else
H2O.return H2O::DECLINED
end
```
> [h2o_mruby] support simple reverse proxy feature in mruby handler

- lib/handler/mruby/class/request.c
When `H2O::Request#headers_{in,out}` method created `H2O::Headers_{in,out}` object, the object like `r.headers_out["x-hogehoge"]` sometimes break or varnish. It seems that the object was sometimes collected as garbage by mruby. This PR fixed this issue. h2o_mruby allocate memory in h2o memory pool instead of using the ptr of mruby object. Same problem was issued in ngx_mruby. 
ref: https://github.com/matsumoto-r/ngx_mruby/issues/125
ref: https://github.com/matsumoto-r/ngx_mruby/pull/126
- reproduse
```ruby
r.headers_out["x-hogehoge"] = "hello"
r.log_error "x-hogehoge:  #{r.headers_out['x-hogehoge']}"
H2O.return H2O::DECLINED
```
```
./h2o -c examples/h2o_mruby/h2o.conf 2>&1 | grep x-hogehoge
```
and run this command:
```
ab -k -c 100 -n 100000 …
```
> [h2o_mruby] Fix bug; headers object sometimes break or varnish

- t/40unix-socket.t
> no U option to Debian

- share/h2o/fetch-ocsp-response
With OpenSSL <= 1.0.1, openssl ocsp command still returns exit code 0,
even if verification was failed.  If that happens certain string is
emitted in stderr, so check that string and if exists, treat it as
error.  This issue was fixed in OpenSSL 1.0.2.
At least OpenSSL 1.0.2, openssl ocsp command still returns exit code
0, even if responder returned non-successful status code (e.g.,
trylater(3)).  We are not sure this is intentional or not.  To handle
this, we again check certain error string in stdout, and if it is
found, treat it as error.
> fetch-ocsp-response: Handle spurious openssl exist status 0

- lib/handler/access_log.c
- t/50access-log.t
As reported in #462, unnecessary NUL character is emitted when the `format` attribute of `access-log` directive ends with a header substitution instruction (e.g. `%{...}i` or `%{...}o`).
This happens only if the substitution instruction exists at the end of the format attribute; i.e. `format: "%{user-agent}i"` is affected, but `format: "\"%{user-agent}i\""` is not.
> NUL emitted in access log after `%{...}i` and `%{...}o`

- lib/handler/configurator/mruby.c
- t/50mruby.t
This PR makes breaking changes to `mruby.handler` and `mruby.handler_path` in the following two ways.
* changes `mruby.handler_path` to `mruby.handler-file`
* since other directives use `-`, and files are referred by _file_ rather than _path_ (ex. `certificate-file`)
* changes the preference in which the mruby directives are handled, so that they are processed along with the other handler definition directives (e.g. `file.dir`, `redirect`, ...)
* in other words, if you want to apply mruby handler before other handler directives such as `file.dir`, you would need to define the mruby directives _above_ `file.dir`
* one of the good effects of doing so is that you can now use mruby for recovering from 404 errors by the file handler (by defining the mruby handler below `file.dir`)
Hopefully …
> [mruby] **breaking change** unify the way mruby handlers are named / applied

- include/h2o.h
- include/h2o/mruby_.h
- include/h2o/url.h
- lib/core/request.c
- lib/handler/mruby/class/request.c
- t/50mruby.t
- t/50mruby/proxy/proxy.html
makes following changes:
* `reprocess_request` now follows the interface of `h2o_reprocess_request` it internally redirects the request to given URL (instead of using the supplied URL as a prefix)
* accept non-absolute forms of URLs in `reprocess_request`
* accept https URLs as well
* refer to `req->(authority|hostname|path)` instead of `req->input.*`, so that mruby handler can work on URLs being rewritten
* detect and return 502 error if the mruby handler internally redirects to itself
> accept non-absolute forms of URLs in `reprocess_request`

- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/class/core.c
- lib/handler/mruby/class/request.c
This PR does the following:
* add `state` flag (in place of `is_last`) to detect mruby trying to sennd response more than once
* error is raised in such case
* also raises error if the handler attempts modify response headers (and HTTP2 push paths) after response is sent
* also switches from `mrb_str_to_cstr` to `mrb_str_to_str` to take care of the mruby handler returning a non-string object
> raise error when the mruby handler tries to send response more than once

- include/h2o/http2_internal.h
- lib/http2/hpack.c
- lib/http2/stream.c
- t/00unit/lib/http2/hpack.c
Oops!  `content-length` header was never sent under HTTP2.
> [http2] send content-length header when possible

- misc/libressl.mk
set `--disable-asm` to avoid compile error of libressl 2.2.2 on OSX.
see also: https://github.com/libressl-portable/portable/issues/121
> fix error when building with libressl on OSX

- lib/http2/connection.c
Especially in case of cache-aware server push, pushed requests are often cancelled.  However, even in such case the server was sending `PUSH_PROMISE` frame if the handler that served the request was running synchronously (e.g. file handler).
> do not send `PUSH_PROMISE` if the push is cancelled for a synchronous handler

- include/h2o/token.h
- lib/core/proxy.c
- lib/core/token_table.h
- lib/http2/stream.c
- misc/tokens.pl
This is necessary, since the cookie-based implementation of cache-aware server-push will not work unless it is guaranteed that responses arrive in the order they are sent (by the server).
part of #421
> disable cache-aware server-push if proxy is detected

- lib/http2/stream.c
Push status (including ones cancelled by casper (see #421)) is now stored in `x-http2-push` header.
You can distinguish them in the logs by emitting the header to the logs (by using `%{x-http2-push}o` directive, see https://h2o.examp1e.net/configure/access_log_directives.html#access-log).
* if the value is `-` then it is an ordinary request
* if the value is `pushed` then it is a pushed request
* if the value is `cancelled` then it is a push request cancelled by casper
> emit push status to `x-http2-push` header

- h2o.xcodeproj/project.pbxproj
- lib/handler/mruby.c
- t/50mruby.t
[The specification of Rack](http://www.rubydoc.info/github/rack/rack/file/SPEC) states that the existence of `#each` is the only requirement for the headers and body objects returned by a Rack handler (in other words we should not expect that they are a hash or an array).
This PR fixes the issue by calling the `each` method of the objects if necessary.  And the good effect of it is that with the change it becomes possible to pass `File` objects as the body.
part of #478
> use `#each` when parsing the result returned by mruby handler

- lib/handler/mruby.c
- t/50mruby.t
> split the header value supplied by Rack with `\n` before sending

- include/h2o.h
- lib/common/string.c
- lib/core/configurator.c
- lib/handler/mimemap.c
- t/00unit/lib/common/string.c
- t/00unit/lib/handler/mimemap.c
- t/50gzip.t
MIME-map attributes (`is_compressible` flag and priority) should be configurable by end user.
part of #421
> configurable mime attributes

- examples/h2o_mruby/hello.rb
Current sample app raises error:
> [examples/h2o_mruby/h2o.conf:14] in command mruby.handler-file, failed to compile file:examples/h2o_mruby/hello.rb:examples/h2o_mruby/hello.rb:6: uninitialized constant H2O (NameError)
> use rack-based API for sample mruby app

- lib/common/time.c
> fix typo: PACK4 -> PACK3

- misc/mruby_config.rb
If oniguruma.h is installed, H2O (with mruby support enabled) fails to build mruby with an error stating that `libonig.a` could not be found.
This PR fixes the issue by calling `#bundle_onigmo` method of mruby-onig-regexp.
fixes: #501
refs: http://twitter.com/take_cheeze/status/643020697762070528
> fix build error when oniguruma is installed

- lib/handler/mruby.c
This patch is to support `rack.errors` on rack-based API.
The value of `rack.errors` is just $stderr object.  It's same as Rack::Handler::CGI and Rack::Handler::WEBrick.
> mruby: support env["rack.errors"]

- CMakeLists.txt
- deps/neverbleed/.gitignore
- deps/neverbleed/LICENSE
- deps/neverbleed/README.md
- deps/neverbleed/neverbleed.c
- deps/neverbleed/neverbleed.h
- deps/neverbleed/test.c
- h2o.xcodeproj/project.pbxproj
- src/main.c
> Neverbleed is an OpenSSL engine that runs RSA private key operations in an isolated process, thereby minimizing the risk of private key leak in case of vulnerability such as Heartbleed.
https://github.com/h2o/neverbleed
> use neverbleed

- deps/cloexec/cloexec.c
- lib/common/socket/evloop.c.h
Respects macro named `H2O_USE_ACCEPT4` on whether or not to use `accept4`.
* if the value is `0`, `accept4` is not used
* if the value is `1`, `accept4` is used
* if the value is unset, it is determined by the default rule (i.e. enable on Linux or FreeBSD>=10)
partial fix to #524
> determine whether or not to use accept4 using macro

- srcdoc/configure/mruby_directives.mt
Fix typo in docs: `mruby-` -> `mruby.`
Thank you for your hard work with v1.5.0!
> Fixing typo in docs: mruby- -> mruby.

- lib/http2/scheduler.c
2^(-log 2 x) is 1/x:
http://www.wolframalpha.com/input/?i=Simplify[2^[-[log[2%2Cx]]]]
> simplifying the formula to map weight to priority.

- lib/http2/scheduler.c
Fixes stall when transferring reprioritized stream only (typically when sending only .js or .css on Chrome), after #550 being merged (i.e. version 1.5.1).
> fix stall when only reprioritized stream is being transferred

- lib/http2/hpack.c
- t/00unit/lib/http2/hpack.c
HPACK encoder of H2O has so far been failing to use name index only for compressing the headers.
This PR fixes the issue (is a rework of improvement suggested by @tatsuhiro-t in #571).
> record the smallest dynamic name index and use the value, for better compression ratio

- lib/http2/connection.c
This PR fixes two issues:
* crash when H2O receives many HEADERS frames specifying streams not open as dependencies
* change the error code from INTERNAL_ERROR to ENHANCE_YOUR_CALM when too many idle streams receive PRIORITY frames
> fix behavior when HEADERS frame specifies a stream not open as a dependency

- include/h2o.h
- lib/core/util.c
- lib/http2/connection.c
- src/main.c
H2O does not include "http/1.1" in the NPN protocol selection list (which is sent to client).  Clients may consider that the server does not support "http/1.1" even though it does.
This PR adds "http/1.1" to the list of the protocols to fix the issue.
The server should also send ALPN response when "http/1.1" is selected (since doing so would prevent OpenSSL from sending NPN protocol selection list).
> include "http/1.1" in npn protocol selection

- lib/handler/access_log.c
- src/main.c
Fixes `access-log: | ...` returning "bad file descriptor" error on startup when using OS X.
> do not request close of fd that is implicitly closed in `h2o_spawnp`

- lib/http2/connection.c
Maximum upstream bandwidth of H2O can be calculated as `SETTINGS_INITIAL_WINDOW_SIZE / 2 / RTT`, considering the fact that the server sends `WINDOW_UPDATE` frame when more than half of the receive window gets consumed.
That means that current value of SETTINGS_INITIAL_WINDOW_SIZE` set to 256KB limits maximum of upstream bandwidth to 1.25MB/s on a connection with 100ms RTT.
This value is below what we could expect on some networks (e.g. connection bet. the Pacific Ocean), and should better be raised.
The new value has been chosen so that it would be more than double of the max value of `/proc/sys/net/ipv4/tcp_rmem`, so that the size of the TCP receive window would be the bottleneck before that of the HTTP2 server does.
> increase SETTINGS_INITIAL_WINDOW_SIZE from 256KB to 16MB

- lib/handler/access_log.c
- t/50access-log.t
According to http://httpd.apache.org/docs/2.4/mod/mod_log_config.html.en:
> %U 	The URL path requested, not including any query string.
however H2O emits protocol and authority as well.
> `%U` must be mapped to URL-path

- include/h2o.h
- include/h2o/http1.h
- include/h2o/http2.h
- include/h2o/http2_internal.h
- lib/core/context.c
- lib/core/request.c
- lib/core/util.c
- lib/handler/access_log.c
- lib/http1.c
- lib/http2/connection.c
- t/50access-log.t
implements:
* `%{request-header-time}x` - time spent receiving request headers
* `%{request-body-time}x` - time spent receiving request body
* `%{request-total-time}x` - sum of request-header-time and request-body-time
* `%{process-time}x` - time spent after receiving request, before starting to send response
* `%{response-time}x` - time spent sending response
* `%{duration}x` sum of request-total-time, process-time, response-time
edit:
* added `%{connect-time}x` - time spent for connection establishment (i.e. since connection gets accept(2)-ed until first octet of the request is received)
> collect and log various timings

- lib/handler/access_log.c
- t/50access-log.t
adds support for:
* `%{...}t` in which `...` is passed to strftime(3)
* `%{sec}t`, `%{msec}t`, `%{usec}t`, `%{msec_frac}t`, `%{usec_frac}t`
does not implement:
* `begin:` and `end:` modifier (pull requests are welcome)
see http://httpd.apache.org/docs/2.4/mod/mod_log_config.html.en
> support `%{...}t` compatible with Apache HTTP server

- include/h2o.h
- lib/handler/configurator/fastcgi.c
- src/main.c
Changes the value to 65535 (was 128).
ref. http://uzulla.hateblo.jp/entry/2015/10/07/021122
> increase backlog size of unix socket created by `fastcgi.spawn`

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/filecache.h
- lib/common/filecache.c
- lib/core/context.c
- lib/handler/file.c
- src/main.c
For devices using 10ge connection but not-so-powerful CPU serving static files, the cost of open(2) and close(2) becomes an issue.
Implementing an in-memory cache is one way to address the issue, but doing so does consume memory and therefore cannot be enabled by default.
OTOH a file descriptor cache that shares a file descriptor _only when a file is opened more than once_ is a good approach for the following reasons:
* reduces the number of open(2) / close(2) being called
* MAY reduce the number of files opened at the same time
The cache implemented by this PR also have following characteristics:
* file descriptor cache is freed every once the event loop
* the maximum entries kept open by the file desriptor cache is 2x the max. concurrency of HTTP/2 connection
relates to: #139
> implement open file cache

- include/h2o/socket/evloop.h
- lib/common/socket/evloop.c.h
- lib/http2/connection.c
At the moment, write to an HTTP/2 connection is always delayed until all readable sockets are read.  The good point of the approach is that we can collect as much data as possible before deciding what to send (ref. HTTP/2 prioritization).
The downside is that the performance and memory footprint becomes worse, since we need to collect all incoming data to memory before emitting anything.
This PR tries to fix the downside without degrading the quality of prioritization, by sending data immediately if _only_ when we process incoming data on an H2 connection, and there is no write in-flight.
If the expectation is true that typically we will have a write in-flight when prioritization is at most necessary, this change will not cause negligible effect on the prioritization quality.
> write immediately after reading data from h2 connection

- include/h2o.h
- include/h2o/http2_casper.h
- include/h2o/http2_internal.h
- lib/core/proxy.c
- lib/core/request.c
- lib/handler/access_log.c
- lib/handler/fastcgi.c
- lib/handler/mruby.c
- lib/http1.c
- lib/http2/casper.c
- lib/http2/connection.c
- lib/http2/stream.c
- t/00unit/lib/http2/casper.c
- t/00unit/test.c
- t/40server-push.t
Thanks to the mruby handler it has now become practical to specify resources to push, and then request backend server to process the response.  And that means that the server can push resources while the request is processed by the backend.
This PR modifies the internals to do so, instead of keeping a list of paths pushed until the response headers are finalized.
> start push ASAP

- lib/http2/connection.c
Though unlikely, HTTP/1 handler might fail to send upgrade response.  And in such case, HTTP/2 connection object must be closed without calling `h2o_socket_close`.
> fix null access when upgrading to HTTP/2 fails

- include/h2o/http2_internal.h
- lib/http2/connection.c
- lib/http2/stream.c
Fixes regression caused by #352 (originally fixed in #132).
> fix too-many-streams error with h2load

- deps/mruby-digest/.gitignore
- deps/mruby-digest/.travis.yml
- deps/mruby-digest/Makefile
- deps/mruby-digest/README.md
- deps/mruby-digest/mrbgem.rake
- deps/mruby-digest/mrblib/digest.rb
- deps/mruby-digest/run_test.rb
- deps/mruby-digest/src/digest.c
- deps/mruby-digest/src/picohash.h
- deps/mruby-digest/test/digest.rb
- h2o.xcodeproj/project.pbxproj
- share/h2o/mruby/htpasswd.rb
- t/50mruby-htpasswd.t
- t/assets/.htpasswd
Tasks:
Format of htpasswd file is specified in https://httpd.apache.org/docs/2.2/misc/password_encryptions.html.
relates to #203
> support basic-authentication using .htpasswd

- lib/common/url.c
- lib/core/config.c
- lib/core/configurator.c
- lib/core/request.c
- t/00unit/lib/common/url.c
- t/40virtual-host.t
This PR enhances the server to accept hostnames with wildcard in the first part of the FQDN.
Such support is essential when using wildcard SSL certificates as discussed in https://github.com/h2o/h2o/issues/543#issuecomment-158438938.
> support wildcard hostname

- lib/handler/fastcgi.c
Special headers must not be transferred; e.g. transfer-encoding header should be dropped, since it is the task of the HTTP server (not fastcgi app) to apply such encoding.
Such filtering already existed in the HTTP proxy, but did not in the FastCGI implementation.
> drop special headers passed from FastCGI application

- lib/http2/hpack.c
- t/00unit/lib/http2/hpack.c
H2O uses `h2o_token_t` to represent some of the often-used headers.  Most of them have a corresponding entry in the static table of HPACK, but some don't (see [token.pl line 153](https://github.com/h2o/h2o/blob/v1.6.0/misc/tokens.pl#L153)).
However, the HPACK encoder has made an incorrect assumption that a header name represented using `h2o_token_t` always has an entry in the HPACK static table, and the fact has lead to incorrect output or server crash when upstream (i.e. proxy, fastcgi, mruby) emits one of thoese headers.
> fix HPACK encoder error (and crash) when trying to encode a token wo. hpack index

- lib/common/socket/evloop/epoll.c.h
Fixes the issue pointed out in https://github.com/h2o/h2o/pull/603#issuecomment-167414622.
Fortunately the impact of this bug is considered low, since the code path that gets affected by the reported issue solely exists to detect logic flaw in the server and never actually gets executed.
> fix broken mutex

- deps/mruby-input-steam/.travis.yml
- deps/mruby-input-steam/LICENSE
- deps/mruby-input-steam/README.md
- deps/mruby-input-steam/Rakefile
- deps/mruby-input-steam/build_config.rb
- deps/mruby-input-steam/mrbgem.rake
- deps/mruby-input-steam/mrblib/input_stream.rb
- deps/mruby-input-steam/src/input_stream.c
- deps/mruby-input-steam/src/input_stream.h
- deps/mruby-input-steam/test/input_stream.rb
- examples/h2o_mruby/hello.rb
- lib/handler/mruby.c
I made a patch to support `rack.input` on rack-based API.
`rack.input` is IO-like object to use request body. (see http://www.rubydoc.info/github/rack/rack/file/SPEC#The_Input_Stream )
In CRuby, `rack.input` is usually an StringIO object.  There is a StringIO gem in mruby (https://github.com/ksss/mruby-stringio), but Input Stream does not need much methods and does need speed, so I made new mrbgem mruby-input-stream.
> mruby: support env[rack.input]

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/chunked.c
- lib/handler/mruby/http_request.c
- t/50mruby-http-request.t
> progressive response from mruby

- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/http_request.c
Guard calls to `mrb_str_to_str` using try-catch; or it will abort if an error is raised during the conversion.
part of #643
> fix crash in mrb_str_to_str

- lib/handler/mruby/http_request.c
- t/50mruby-http-request.t
Implements `InputStream#as_str` for converting content obtained by `http_request` to string.
Since the method triggers a fiber switch, I have evaded naming it `#to_str` so that it would not be called via C functions.
part of #643
> implement InputStream#as_str

- lib/handler/mruby.c
Hi @kazuho san,
I found that HTTP header names which are generated on mruby handler are not lowercased at this time.
For instance, when I use the code shown in [#624 (comment)](https://github.com/h2o/h2o/pull/624#issuecomment-165454959), Chrome stops page loading and returns "ERR_SPDY_PROTOCOL_ERROR".
In more detail, here is a debug log captured by the Chrome.
```
t=1664741 [st=   29]    HTTP2_SESSION_RECV_HEADERS
--> fin = false
--> :status: 401
server: h2o/1.7.0-alpha1
date: Tue, 29 Dec 2015 05:05:38 GMT
Content-Type: text/plain
WWW-Authenticate: Basic realm="Members only"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
content-security-policy: upgrade-insecure-requests
content-length: 24
--> stream_id = 1
t=1664741 [st=   29]    HTTP2_SESSION_SEND_RST_STREAM …
```
> Convert header name to lowercase in mruby handler

- lib/common/multithread.c
As far as I know H2O does not register/unregister multithread receiver dynamically.
It is, however, another story for programs using libh2o.
We should add missing mutex synchronization for editing multithread queue
in h2o_multithread_register_receiver() and h2o_multithread_unregister_receiver().
> [h2o-lib] bugfix: mutex on multithread_queue

- lib/handler/mruby.c
- lib/handler/mruby/chunked.c
- t/50mruby-http-request.t
Respect the value of `content-length` header set by mruby, and:
* if 3rd element of the Rack response is an array, then:
* trim supplied content if it is too long
* adjust content-length if supplied content is too short
* if 3rd element of the Rack response is not an array, then:
* trim supplied content if it is too long
* abruptly close the persistent connection if supplied content is too short
part of #643
> send content length when possible

- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/chunked.c
- lib/handler/mruby/http_request.c
- t/50mruby-http-request.t
> skip mruby layer when sending data obtained using `http_request`

- src/main.c
- t/50sni.t
Follows #634
As I said in https://github.com/h2o/h2o/issues/543#issuecomment-158438938 , I'm planning to use the wildcard support for wildcard certificates with SNI, but change in #634 seems not to support SNI.
> Consider wildcard hostnames on SNI

- lib/handler/configurator/errordoc.c
- t/50errordoc.t
```
killed (got 0)
spawning /home/ykzts/work/h2o/h2o... [/tmp/K8fHALM1vj:7] in command error-doc, argument must be either of: sequence, mapping
not ok 4 - multi-error
server failed to start (got 19968)
```
:cry::cry::cry:
> Fixed a bug that cannot specify multiple error documents

- h2o.xcodeproj/project.pbxproj
- lib/common/socketpool.c
- t/50reverse-proxy-disconnected-keepalive.t
If you are using persistent HTTP/1 connections to upstream servers, __it is very important to configure your upstream server to have a greater timeout value than H2O__ (configured via `proxy.timeout.keepalive`), as discussed in https://github.com/h2o/h2o/issues/281#issuecomment-92568622.
However, I have heard that Nginx occasionally closes downstream connections earlier than the configured timeout, and that the behavior is causing issues to the user.
This PR tries to remedy the issue by checking the health of a pooled connection just before being reused.  When H2O first encounters an unexpectedly-closed pooled connection, it will report an warning to give the users a chance to reconsider their configuration.
Note that __we cannot 100% fix the problem due to the restrictions of HTTP/1 (see …
> detect upstream close of a pooled socket before reuse

- lib/handler/redirect.c
- t/50redirect.t
> uri-escape the user-supplied portion of the redirect path

- lib/handler/file.c
- t/50file.t
```
spawning /home/ykzts/work/h2o/build/h2o... [INFO] raised RLIMIT_NOFILE to 65536
h2o server (pid:20172) is ready to serve requests
done
not ok 1 - status
killing /home/ykzts/work/h2o/build/h2o... received SIGTERM, gracefully shutting down
fetch-ocsp-response (using OpenSSL 1.0.1k 8 Jan 2015)
failed to extract ocsp URI from examples/h2o/server.crt
1..1
not ok 1 - trailing-slash
```
> Fixed a bug that returns 403 when the trailing slash in the URI

- lib/http1.c
- t/40websocket.t
attached failing test.
On logging websocket upgraded request, SEGV occurs when `log_access` tries to get peername. Because `http1.c`:`on_upgrade_complete` detaches `req->conn->sock`.
I tried to write a patch, but I thought this can't be fixed with simple patch, so submitting issue earlier.
IMO remote address should be logged, but detaching socket makes it impossible. So I guess we have to add new member for keeping peername in `h2o_conn_t`? There are several ways to achieve this, but I can't determine which is the best.
```
(lldb) bt
* thread #2: tid = 0x1a835b7, 0x000000010000afd5 h2o`h2o_socket_getpeername(sock=0x0000000000000000, sa=0x000070000030e440) + 21 at socket.c:435, stop reason = EXC_BAD_ACCESS (code=1, address=0x40)
* frame #0: 0x000000010000afd5 …
```
> crash after upgrading request to websocket when access log is enabled

- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/http_request.c
Current design pushes down the arena value to callees so that they could restore the arena when operation is complete.  The positive side of the design is that it would help us restore the arena earlier, and that there is more chance of callees getting tail-call optimized.  The downside is that we need to assert that the arena is restored in more code paths.
As has been reported in #699, we have failed to assert that the arena is always being restored.  I have found that such code is also missing [here](https://github.com/h2o/h2o/blob/f0e3af1/lib/handler/mruby/http_request.c#L153).
Now that we have found multiple occurrences of such failures we should switch to a more conservative design: maintain GC arena at the highest level; i.e. restore the GC state within the functions that collect …
> fix and reduce the risk of GC-arena related leaks

- lib/core/config.c
- lib/core/configurator.c
Every key of the `hosts` mapping MUST be unique; however there were no checks that assert the requirement.
relates to https://github.com/h2o/h2o/issues/704#issuecomment-172453334
> refuse to start when a duplicate host entry has been found

- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- lib/core/proxy.c
- lib/core/request.c
- lib/handler/errordoc.c
- lib/handler/reproxy.c
- t/50reverse-proxy/test.pl
- t/80issues-from-proxy-reproxy-to-different-host.t
implements #704
Also fixes an issue that leads to a wrong response being sent when an internal redirect is triggered (e.g. error-doc, reproxy) after proxy is used, and if the authority of the source and destination of the redirect differ.
> support relative URI in x-reproxy-url header

- lib/handler/fastcgi.c
- lib/handler/proxy.c
fixes a double-free bug in configuration phase; reported in https://github.com/h2o/h2o/issues/717#issuecomment-173837892.
> handlers must not `free` pointers returned by `h2o_create_handler`

- CMakeLists.txt
The build configuration script (i.e. CMakeLists.txt) searches for optional dependencies (e.g. libuv) and sets the include path to the library before setting include paths for the files provided by H2O.
It means that if an older version of H2O is installed next to libuv (or other dependencies), the compiler will use the files in the installed directory instead of the ones in the source directory (for example, if libuv and an older version of H2O is installed under `/usr/local`, GCC option will be `-I /usr/local/include -I /path/to/h2o/include`).
This PR fixes the issue by moving the `INCLUDE_DIRECTORIES` command that specifies project-level search paths above the commands that specify the include paths for external dependencies.
> fix build error when an older version of H2O is installed aside with an optional external dependency

- lib/common/http1client.c
When upstream sends a response that neither has `content-length` nor `transfer-encoding` is used, the response that could not be sent immediately gets truncated within the http1 client.
> fix response getting truncated when neither content-length nor transfer-encoding is used

- lib/http2/connection.c
`PUSH_PROMISE` frames must be sent in the ascending order of the stream id.
However, when the number of in-flight requests exceeds the limit imposed by `http2-max-concurrent-requests-per-connection` (default: 100), there is a chance that they get sent in a wrong order.
This PR changes the code so that contents would get pushed only if there is no pending requests within the internal queue (that implements the aforementioned limit).
fixes #726
> fix PUSH_PROMISE sent in wrong order when under high pressure

- doc/configure/access_log_directives.html
`failed to compile log format: unknown escape sequence: %>`
> invalid format in Example of access_log document

- deps/yoml/.gitmodules
- deps/yoml/test-yoml.c
- deps/yoml/yoml-parser.h
- h2o.xcodeproj/project.pbxproj
- t/80yaml-merge.t
Implements [Merge Key Language-Independent Type for YAML™ Version 1.1](http://yaml.org/type/merge.html) for h2o.conf.
With this PR, it is possible to _inherit_ a YAML node and overrwrite some of the properties.
As an example, the snippet below reuses the SSL attributes defined for `host1.example.com` in `host2example.com`.
```yaml
hosts:
host1.example.com:
listen:
port: 443
ssl: &ssl_base
key-file: /path/to/host1.key
certificate-file: /path/to/host1.crt
minimum-version: TLSv1.1
cipher-suite: ...
cipher-preference: server
...
host2.example.com:
listen:
port: 443
ssl:
<<: *ssl_base
key-file: /path/to/host2.key
certificate-file: /path/to/host2.crt
...
```
see also: https://github.com/h2o/yoml/pull/2, relates to: #758 #764 #772
> support `<<` in h2o.conf

- lib/common/socket/evloop/poll.c.h
possible leftover from #735 ?
trying out h2o 1.7.0 today, and compiler complains:
```
[lib/common/socket/evloop/poll.c.h]:
error: macro "h2o_vector_reserve" passed 4 arguments, but takes just 3
```
...defined in https://github.com/h2o/h2o/blob/master/include/h2o/memory.h#L255
[am using the (fallback) poll interface since my platform doesn't support the others]
possibly an oversight from the above PR?
(alternatively also solved it by renaming `h2o_vector_reserve` back to `h2o_vector__reserve`)
anyway thanks kazuho for the 1.7.0 release, and mingodad for the initial PR
great work from both of you!
> fix build issue with poll backend: h2o_vector_reserve

- lib/handler/mruby.c
Such code did not exist for the fast path (though it was implemented for the chunked sender).
This is a requirement by the HTTP/2 spec.:
> A request or response is also malformed if the value of a content-length header field does not equal the sum of the DATA frame payload lengths that form the body.
> [RFC 7540 Section 8.1.2.6](http://http2.github.io/http2-spec/index.html#malformed)
Fixes #778
> truncate body to the size specified with `content-length`

- t/40pathconf-redirect.t
- t/40protocol.t
- t/50errordoc.t
- t/50fastcgi-cgi.t
- t/50fastcgi.t
- t/50file-range.t
- t/50gzip.t
- t/50mruby-http-request.t
- t/50mruby.t
- t/50post-size-limit.t
- t/50redirect.t
- t/50reverse-proxy/test.pl
- t/50server-starter.t
- t/80issues61.t
- t/Util.pm
Until now, the test scripts have used curl for mostly HTTP/1 tests, while using nghttp2 for HTTP/2 tests.  When curl was intended to be used for HTTP/2 testing, `--http2` option was explicitely specified.
However, it seems that newer versions of Curl (with support for HTTP/2) seem to silently use HTTP/2 based on the result of ALPN, which is causing two troubles for us:
* some tests fail (due to HTTP/2 being used)
* HTTPS/1 tests are no longer executed (since curl would use HTTP/2)
This PR solves the issues by changing the test scripts to use curl for both HTTP/1 and HTTP/2 tests.
Still WIP.
> by default, run both http/1 and http/2 tests using curl

- CMakeLists.txt
Install `(path/to/src/)share/h2o/mruby/htpasswd.rb` (or other script files in the future) to the system (e.g. `/usr/share/h2o/mruby/*.rb`)
> install share/h2o/mruby scripts to system

- include/h2o/multithread.h
- lib/common/multithread.c
- src/main.c
`notify_all_threads` must be async-signal-safe (thus should not call `malloc`), since it is invoked by `on_sigterm`.
> avoid using malloc in signal handler

- examples/libh2o/simple.c
- examples/libh2o/websocket.c
- include/h2o.h
- lib/core/config.c
- lib/core/configurator.c
- t/00unit/issues/293.c
- t/00unit/lib/handler/fastcgi.c
- t/00unit/lib/handler/file.c
- t/00unit/lib/handler/redirect.c
We have changed the interpretation of `path` in #820.  We need to give users of libh2o the chance to learn that it has been changed and to update their code.
Therefore, we intentionally change the number of arguments accepted by the function.
> change signature of `h2o_config_register_path`

- lib/common/socket/evloop.c.h
This PR caps the maximum size of the buffer passed to read(2) to 1GB.
Note: [`man 2 read` of FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=read&sektion=2) has a following statement
```
[EINVAL]		The value nbytes is greater than INT_MAX.
```
in contrast to POSIX that state as follows:
```
If the value of nbyte is greater than {SSIZE_MAX}, the result is implementation-defined.
```
http://pubs.opengroup.org/onlinepubs/9699919799/functions/pread.html
The man page of OS X does not state such limitation exists, but seem to behave the same way as FreeBSD does.
Fixes #821
> truncate the 3rd argument of `read` below `INT_MAX` to avoid FreeBSD / OS X limitation

- src/ssl.c
It turns out that even when configured to disable ticket-based resumption, the use of session ticket was not turned off, but instead the default configuration for session ticket was used.
fixes #819
> disable use of session tickets when requested

- src/main.c
This change should add support for stronger curves (e.g. secp384r1).
relates to #713
> automatically negotiate ecdh curve (works on OpenSSL & libressl)

- include/h2o.h
- lib/core/headers.c
- lib/handler/compress.c
- lib/handler/expires.c
- lib/handler/file.c
- t/00unit/lib/core/headers.c
Fixes https://github.com/h2o/h2o/issues/767#issuecomment-184016839.
While this is not strictly a bug, it is better not to have duplicate tokens in a header using 1# rule; e.g. `Vary: accept-encoding, accept-encoding`.
> don't append a header token already set

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- lib/core/context.c
- lib/core/logconf.c
- lib/handler/access_log.c
- lib/handler/configurator/status.c
- lib/handler/status.c
- lib/http1.c
- lib/http2/connection.c
- share/h2o/status/index.html
- src/main.c
Still WIP. The strategy is:
* use the core of access-log to stringify the requests in-flight
* provide web I/F that emits the in-flight requests in JSON
* provide HTML that obtains the JSON using XHR and renders it
implements #430
> implement server-status

- lib/common/memcached.c
The bug is that memcached client impl. does not free memory allocated for SET / DELETE commands.
> Fix memory leak when using TLS resumption w. memcached backend

- include/h2o.h
- lib/core/request.c
- lib/core/util.c
- t/00unit/lib/core/util.c
- t/40server-push.t
Until now, H2 push (with the `link` header) has intentionally been disabled after delegation (i.e. internal redirect).
This is because a delegation might include a change in the orgin of the HTTP request, while H2 only allows requests to be pushed from the same origin as the main request.
This PR address the issue.  It adds a code that compares the origin of the delegated request against that sent by the client; and if the two match, pushes the resources specified by the `link` header.
fixes #860
> support H2 push after delegation

- lib/core/logconf.c
Some elements of the h2o_logconf_t structure are dynamically allocated
when calling h2o_logconf_compile(). Add a bitfield that tells us whether
we need to free the structure or not.
> Fix leaks in the h2o_logconf_t structure

- share/h2o/fetch-ocsp-response
Fixed in my error log.
```
Undefined subroutine &main::die called at /usr/local/share/h2o/fetch-ocsp-response line 139.
```
```
OpenSSL exitted abnormally: openssl x509 -in /path/to/fullchain.pem -noout -ocsp_uri: at /usr/local/share/h2o/fetch-ocsp-response line 139.
> fix error "Undefined subroutine &main::die called at fetch-ocsp-response line 139."

- src/main.c
If `SIGTERM` is received by `h2o` before the initialization phase of
`run_loop` (in particular the h2o_multihread_register_receiver  calls),
we might end up calling `h2o_multithread_send_message` on uninitialized
structures, causing a crash (seen when running the tests suite on a
heavy loaded machine):
```
killing <path>/local/src/h2o-fastly/h2o... received fatal signal 11; backtrace follows
<path>/local/src/h2o-fastly/h2o[0x5019c2] on_sigfatal at <path>/local/src/h2o-fastly/src/main.c:1164
/lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0)[0x2b517dfffcb0] ??
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x2b517dff9e84] ??
<path>/local/src/h2o-fastly/h2o(h2o_multithread_send_message+0x2a)[0x44e8e3] h2o_multithread_send_message at …
```
> slow init crash on sigterm

- t/40server-push.t
The test fails if mruby is not compiled in:
```
$ perl t/40server-push.t
spawning plackup... Plack::Handler::Starlet: Accepting connections at
http://0:50442/
done
spawning ./h2o... [/tmp/DmSUDngTuA:7] unknown command: mruby.handler
killing plackup... killed (got 0)
server failed to start (got 19968)
not ok 1 - basic
```
This patch skips the test if mruby is not compiled in
> `t/40server-push.t` fails when `h2o` is compiled with WITH_MRUBY=OFF

- lib/common/hostinfo.c
After starting one lookup thread, `queue.num_threads_idle` will be `1` forever, and so the check for idle threads in `h2o__hostinfo_getaddr_dispatch` will always think there is an idle thread, and h2o will be stuck with 1 forever.
With this change, a thread is marked idle while it's waiting on the condvar, but marked busy while its blocked on `getaddrinfo`, so h2o will properly start to spawn more threads up to the configured maximum.
> mark when hostinfo threads are idle

- lib/core/configurator.c
- lib/http1.c
- lib/http2/hpack.c
- t/50servername.t
Add two configuration options that allow to control what h2o displays in
the 'Server:' http header:
- server-name: this will allow to specify the contents of the 'Server:'
header.
- display-server-name: defaults to "ON". When set to "OFF", h2o won't
emit the header in the responses it generates.
> Configurable Server: header

- include/h2o.h
- include/h2o/socket.h
- lib/common/socket.c
- lib/common/socket/evloop.c.h
- lib/common/socket/uv-binding.c.h
- lib/http1.c
- lib/http2/connection.c
Introduce `h2o_get_sock_fd()` that can be use to obtain the underlying
fd of a `h2o_socket_t` structure. This returns -1 if the socket isn't
valid anymore.
> An API to access the underlying fd of a h2o_socket_t

- include/h2o/multithread.h
- lib/common/multithread.c
- src/main.c
Introduces a configuration directive named `num-ocsp-updaters` to limit the number of OCSP updater processes run at once.  The default value of the directive is set to 10.
fixes #862
> limit ocsp updater concurrency

- include/h2o.h
- lib/core/proxy.c
- lib/handler/configurator/proxy.c
adds a global configuration directive named `proxy.preserve-x-forwarded-proto` which, if set to `ON`, instructs the reverse proxy to preserve the value of the `x-forwarded-proto` header passed from downstream.
Note that users should not set this variable to `ON` in case H2O is directly accepting connections from a third party, since, an attacker connecting over HTTP may try to spoof oneself to be using HTTPS by using the header.
implements #883
> user-configurable option for preserving `x-forwarded-proto`

- lib/core/proxy.c
Log and error when hitting a non eos error in `proxy.c:on_body()`
> Add error logging in on_body

- deps/ssl-conservatory/openssl/openssl_hostname_validation.c
> fix build error on CentOS 7 (due to definition of `tolower`)

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o/cache.h
- lib/common/cache.c
- t/00unit/lib/common/cache.c
- t/00unit/test.c
- t/00unit/test.h
Implements in-memory cache for storing arbitrary types of data
* accessible from multiple threads
* support for early refetch
Will be useful for implementing things like caching proxy / client-side TLS session cache.
> in-memory cache

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o/cache.h
- include/h2o/http2_internal.h
- lib/common/cache.c
- lib/http2/connection.c
- t/00unit/lib/common/cache.c
- t/00unit/test.c
- t/00unit/test.h
- t/40server-push.t
When an application emits a `link: rel=preload` header, the H2 implementation refers to a _push memo_ to see if it has already pushed the specified resource over the same connection.  If the answer is true, the implementation ignores the header.  If the answer is false, then it pushed the specified resource (if other conditions are met).
The memo is implemented as:
* uses #887 to implement a LRU cache of 1,024 entries at maximum
* hash codes (X31) of URLs being pushed are stored in the LRU cache
implements #896
> don't push the same resource twice over a single H2 connection

- lib/common/cache.c
> Fix `h2o_cache_calchash` to take into account the whole key value when

- lib/handler/configurator/mruby.c
A typo in `mruby.c:on_config_exit()` prevented releasing the memory
allocated in previous mruby directives.
> Fix mruby directives initialization time leak

- deps/mruby-onig-regexp/mrbgem.rake
The cause of #902 seems that Onigmo (the regex engine used by our mruby implementation) is built without multithread support.  This PR fixes the issue.
> fix race condition in mruby regex handler

- lib/common/memory.c
Use `posix_fallocate` for allocating file-backed storage (mmaped), instead of `ftruncate`.
`ftruncate` create a sparse file, and disk space allocation is delayed until data is actually being written.  In our case, we use memory access (though `mmap`) to write data.  That means that when the OS fails to allocate disk space, H2O receives SIGBUS.
This PR fixes the issue by replacing `ftruncate` with `posix_fallocate` on platforms that support it; the latter function allocates disk space eagerly, so there is no risk of getting SIGBUS.
fixes #909
> fix SIGBUS when temporary disk space is full

- src/main.c
The memory buffer of H2O creates temporary files that are mmaped (see `h2o_buffer_reserve`).  Until now, the path of the directory in which the files are created has been hard-coded to `/tmp`.
However, it is desirable to have it configurable, considering the fact that many deployments have `/tmp` using tmpfs.  On such systems, the total size of the buffer would be restricted by the size of physical memory (and swap space), which might be too small in case H2O is used to proxy many large objects.
relates to: #902, #910
> add configuration directive for customizing the path of temporary buffer files

- include/h2o.h
- lib/core/proxy.c
- lib/core/request.c
- lib/handler/fastcgi.c
- lib/handler/mruby.c
mruby handler is currently dropping all the link headers _except_ those that were successfully pushed.
This PR changes the behavior to always send downstream the header being set, which aligns with the behavior to the other handlers (fastcgi, proxy).
> preserve link header

- lib/common/url.c
- t/00unit/lib/common/url.c
h2o_url_stringify typically ends up crashing due to an uninitialized pointer access.
Note: the function is never called by the standalone server.
> fix crash in h2o_url_stringify

- include/h2o/http1client.h
- lib/common/http1client.c
- lib/core/proxy.c
- t/40server-push.t
- t/assets/upstream.psgi
WIP. Implements https://github.com/h2o/h2o/issues/672#issuecomment-218410576.
relates to https://github.com/kazuho/Starlet/pull/29
> push resources specified by 1xx + `link: rel=preload` sent from application server

- lib/http2/connection.c
As suggested in the FIXME comment, copy the remaining bytes for
and continue processing.
Reported by Tim Newsham
> on_connection_upgrade asserts if extra bytes are sent after the first request

- lib/common/memory.c
Have the function increment `x` and `y` so that all the blocks are
swapped. This doesn't affect the current code as the only caller uses a
structure smaller than 256 bytes.
Reported by Tim Newsham
> h2o_mem_swap only swaps the first 256 bytes at most

- lib/common/memcached.c
The `REQ_TYPE_DELETE` case is missing a break, causing it to fallthrough
to the following case, which dereferences `req`, which we just freed.
Reported by Tim Newsham
> Possible use-after-free in memcached.c::writer_main()

- include/h2o.h
- lib/handler/compress.c
- lib/handler/configurator/compress.c
- srcdoc/configure/compress_directives.mt
Add a `compress-min-size` configuration parameter that controls the
minimum size that an object needs to have for us to compress it.
> Make the minimum size for compression configurable

- include/h2o.h
- lib/core/config.c
- lib/core/configurator.c
- lib/http2/connection.c
Some users may want to just send `link: rel=preload` headers without H2 push.
> configuration directive to disable H2 push

- lib/http2/connection.c
The code ended up passing a negative value to the array index. Remove
the confusing double negative.
> Invalid write when incrementing http2 errors

- src/main.c
- srcdoc/configure/base_directives.mt
This adds a two new top level config options to the `h2o` daemon:
- `crash-handler`: takes a path to a script to execute if `h2o` receives
a fatal signal.
- `crash-handler-args`: takes arguments to pass to the crash handler
The default behavior to invoke 'share/h2o/annotate-backtrace-symbols' is
preserved.
> Add a custom crash handler directive

- include/h2o/http1client.h
- lib/common/http1client.c
- lib/core/proxy.c
Instead of relying on an incomplete definition of `struct phr_header`.
Fixes #942
> define `h2o_http1client_header_t` which is a copy of `phr_header`

- CMakeLists.txt
- examples/libh2o/latency-optimization.c
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/http2_internal.h
- include/h2o/http2_scheduler.h
- include/h2o/socket.h
- include/h2o/socket/evloop.h
- lib/common/socket.c
- lib/common/socket/evloop.c.h
- lib/common/socket/evloop/epoll.c.h
- lib/common/socket/evloop/kqueue.c.h
- lib/common/socket/evloop/poll.c.h
- lib/core/config.c
- lib/core/configurator.c
- lib/http2/connection.c
- lib/http2/scheduler.c
- t/00unit/lib/common/socket.c
WIP.
The basic idea is to only write(2) data that can be immediately sent by the TCP/IP stack, by using TCP_NOTSENT_LOWAT and TCP_INFO.
> minimize HTTP/2 request latency

- include/h2o.h
- lib/core/request.c
- lib/core/util.c
- t/00unit/lib/core/util.c
- t/40server-push-multiple.t
https://tools.ietf.org/html/rfc5988 appears to allow multiple links in the
'Link:' header. AFAIU, the grammar doesn't allow it explicitly, but the example
section does explicitly list such a link header:
```
Link: </TheBook/chapter2>;
rel="previous"; title*=UTF-8'de'letztes%20Kapitel,
</TheBook/chapter4>;
rel="next"; title*=UTF-8'de'n%c3%a4chstes%20Kapitel
```
This patch makes h2o_extract_push_path_from_link_header extract several
paths when found.
> Support multiple links in a Link: header

- h2o.xcodeproj/project.pbxproj
- lib/handler/status/requests.c
Preceding comma was inserted into the `requests` array of the JSON status if the first thread that executes `requests_status_per_thread` was handling zero requests.
Also simplifies the code.
> fix corrupt JSON emitted by status handler

- lib/handler/status.c
- lib/handler/status/events.c
- lib/handler/status/requests.c
In #893, collection of per-request stats has accidentally been serialized, blocking all the threads until all the requests have been collected.  This PR fixes the issue by limiting the serialized execution to only when the JSON-serialized data gets concatenated.
@deweerdt Can you please take a look at this PR, since it moves the responsibility of serializing the per-thread callback from the caller to the callbacks?
> concurrent collection of request stats

- lib/core/proxy.c
- t/80dup-host-headers.t
When h2o acts as a proxy between an h2 client and an http/1.1 server, it
will generate the http/1.1 Host header by using the `:authority:` h2
pseudo header. Unfortunately, if a h2 `host:` header is already present,
the http/1.1 request will have two Host headers, which will make the
request invalid.
AFAIU, RFC7540 language doesn't explicitely state what to do in the
case where `:authority:` and `host:` are present, but preferring
`:authority:` intuitively makes more sense since both in h2 and http/1.1
the http authority should be the same. See also another discussion on
the subject (with the same conclusion) here:
https://github.com/nghttp2/nghttp2/issues/317
> h2 -> http/1.1 proxy: don't forward two 'host:' headers

- lib/http2/hpack.c
- t/00unit/lib/http2/hpack.c
`decode_string` is missing a check that `src` hasn't gone over `src_end`
between the call to `decode_int` and `decode_huffman`.
As a result, we can:
- decode an int
- reach the end of the buffer
- then call `decode_huffman` having `src` greater than `src_end`, and
thus read past the buffer
This patch fixes the issue by adding a check that `src` is smaller than
`src_end` before calling `decode_huffman`.
The patch also makes the code a bit more defensive by replacing `src ==
src_end` checks with `src <= src_end`, this will make the code more
robust to such mistakes should there be any in the future.
Finally, we add a test case in `t/00unit/lib/http2/hpack.c` that
reproduces the issue: without the patch, we read past the buffer and
`decode_string` doesn't fail.
> Hpack parsing issue

- lib/core/util.c
- t/50redirect.t
From https://tools.ietf.org/html/rfc3986#section-3.3 'Path' :
path-absolute = "/" [ segment-nz *( "/" segment ) ]
segment       = *pchar
segment-nz    = 1*pchar
segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
; non-zero-length segment without any colon ":"
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
Since ':' is part of the allowed characters, The code should leave the
character as-is. Leaving the character as-is also matches the behavior
observed on Firefox, Chrome, Safari and IE.
> h2o_build_destination: don't escape ':' in the 'path' section of the url

- t/00unit/lib/core/util.c
The intention is to test a variant ending with a slash and another
without slash
> test_build_destination tests the same pathconf twice

- src/ssl.c
as discussed a separate PR with the add_lock callback using atomic builtins for the increment.
also added comment about the dynamic locks - implemented and instrumented the callbacks and they are indeed not used.
> set add_lock callback to prevent unnecessary lock-add-unlock

- include/h2o/http2_casper.h
- lib/http2/casper.c
- lib/http2/stream.c
- t/00unit/lib/http2/casper.c
Change of etag value should not cause an HTTP response to be pushed, since the client would ignore the push in case it already has the response freshly-cached.
> don't use etag for calculating casper cookie

- lib/handler/fastcgi.c
- t/50fastcgi.t
In current implementation, environment variables set using `setenv` configuration directive does not overwrite the received HTTP request headers. The bug makes us impossible to use the directive to block attacks trying to exploit [httpoxy](https://httpoxy.org/) vulnerability.
This PR is a quick fix for the issue so that we can use the directive to prevent the attack.
Note that there are other issues in how we build FastCGI request parameters:
* even with this fixed, `setenv` cannot cannot rewrite specially-treated headers like `HTTP_HOST`
* `unsetenv` cannot be used for resetting `HTTP_*`, etc.
* if a request header with a same name appears more than once, only the last value is transmitted to the application; we must repeated headers are not comma-concatenated
So we _might_ fix all these …
> [fastcgi] environment variable overwrites `HTTP_*`

- include/h2o.h
- lib/core/config.c
- lib/core/proxy.c
- lib/handler/configurator/proxy.c
- srcdoc/configure/proxy_directives.mt
- t/50reverse-dont-add-x-forwarded-headers.t
There are setups where it might not be desirable to add the headers at
all (for example if H2O is not terminating the TLS connection, it will
set `x-forwarded-for:localhost`).
We add a `proxy.emit-x-forwarded-headers` global config option that
instructs H2O not to add or append `x-forwarded-for` and
`x-forwarded-proto`. This option is `OFF` by default.
> Add an option to prevent emiting x-forwarded-* headers

- include/h2o/serverutil.h
- lib/common/serverutil.c
- lib/common/socket/evloop.c.h
- lib/handler/access_log.c
- lib/handler/configurator/fastcgi.c
- lib/handler/mruby.c
- src/ssl.c
This patch makes needlessly global function static. The functions were
reported by `-Wmissing-prototypes`. There's also a minor cleanup to add an
explicit list of arguments for `h2o_numproc`
> [minor cleanup] Make needlessly global functions static

- .travis.yml
This PR prepares some prerequisites for tests.
(1) 9894fc1
Currently, tests that need http2-enabled curl are skipped. So build curl.
(2) 43dd3c1
Currently, t/50fastcgi.t is skipped because
```
> perl -MPlack::Handler::FCGI -e1
Can't locate FCGI.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/share/perl5/Plack/Handler/FCGI.pm line 8.
BEGIN failed--compilation aborted at /usr/share/perl5/Plack/Handler/FCGI.pm line 8.
Compilation failed in require.
BEGIN failed--compilation aborted.
```
To use Plack::Handler::FCGI, we need to install FCGI and FCGI::ProcManager.
Additionally we need to install latest Plack for allowing SERVER_PROTOCOL=HTTP/2.
> Prepare some prerequisites for tests

- deps/yoml/test-yoml.c
- deps/yoml/yoml-parser.h
updates yoml to fix #1007 (see https://github.com/h2o/yoml/issues/4 for details)
> fix assertion failure when YAML alias and merge is used in certain way

- share/h2o/mruby/dos_detector.rb
- share/h2o/mruby/lru_cache.rb
- t/50mruby-dos-detector.t
This adds a mruby handler for DoS attack detection.
The default detecting strategy is simply counting requests, based on the following:
* https://github.com/stanaka/mod_dosdetector
* https://github.com/matsumoto-r/http-dos-detector
but the behavior can be changed by setting parameters, or creating new strategies.
> add dos_detector mruby handler

- doc/configure/file_directives.html
- srcdoc/configure/file_directives.mt
The `file.send-gzip` documentation contained a (maybe legacy) link to `file_directives.html#send-compressed` which does not exist and was changed to `file_directives.html#file.send-compressed`.
Also, the prefix was added to the link text, as this is common throughout the documentation.
> Fixed bad link in File Directives documentation

- .travis.yml
@kazuho instead of https://github.com/h2o/h2o/pull/1027, I tried to use TravisCI's custom hostname feature.
I tried this in my private another repo, and it worked well.
> add custom hosts for testing

- .clang-format
Use `SortIncludes: false` to prevent clang-format from sorting the headers (requires clang-format 3.9).
> add SortIncludes: false

- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- lib/core/proxy.c
- lib/core/util.c
- lib/handler/configurator/proxy.c
- lib/handler/proxy.c
- t/50reverse-proxy-proxy-protocol.t
Implements #602.
Note that this feature can be used only when `proxy.timeout.keepalive` is set to zero, since otherwise we would need to implement a per-connection socket pool (relates to #919).
ToDo:
> add option to send proxy header to upstream

- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/mruby_.h
- lib/core/context.c
- lib/handler/configurator/mruby.c
- lib/handler/mruby.c
- lib/handler/mruby/chunked.c
- lib/handler/mruby/http_request.c
- share/h2o/mruby/acl.rb
- share/h2o/mruby/bootstrap.rb
- t/00unit.mruby/acl.rb
Fix the issue mentioned at https://github.com/h2o/h2o/issues/987
Let each thread share mruby context between handlers to reduce memory consumption.
I tried in my local macbook under the following condition:
* 64 thread
* 20 mruby handlers (simply fallthrough to the next handler)
* sent 1000 requests to warmup
The result is:
Before this fix: 912,612KB of resident size
After this fix: 64,852KB of resident size
> share mruby state and constants between handlers

- lib/http2/connection.c
- t/80one-byte-window.t
When receiving a window update message, mark the stream as active if the
stream is about to close. This allows the http2 subsystem to properly
close the stream.
The stream could otherwise become stuck if it stopped writing because
there was no space available in the stream, since no other activity
would wake it up.
I believe this fixes issue https://github.com/h2o/h2o/issues/1035 . When this is addressed, we'll be able to revert c7f376b6a8686ac174e2f74d29e7f90eb34a5a8e in PR #1031 , I've verified that this fix does address the issue.
> http2: one byte window connection hung

- include/h2o.h
- include/h2o/http2_internal.h
- include/h2o/memory.h
- lib/http2/frame.c
We introduce `H2O_BUILD_ASSERT` that can be used to write built-time
assertions.
We then use this macro in order to check that the `errnum` argument of
`h2o_http2_encode_rst_stream_frame` is positive.
> Add a build time check for `h2o_http2_encode_rst_stream_frame`

- lib/http2/connection.c
The RFC states that 'PRIORITY can be sent and received in any stream
state'. We correctly accept the `PRIORITY` frame on an `IDLE` stream,
however the code in `handle_headers_frame` would then send a `GOAWAY`
frame on a subsequent `HEADERS` frame.
This happened because the existing code would expect `stream` to only
exist if the `HEADERS` frame had been received, but that also happens
when a `PRIORITY` frame has been received.
We fix this by having `handle_headers_frame` accept `HEADERS` frames if
`stream` exists and is `IDLE`.
This issue was reported by @Lukasa, including a repro case here:
https://github.com/python-hyper/hyper-h2/issues/302
> Don't send GOAWAY if a PRIORITY frame is sent before the HEADERS

- lib/core/configurator.c
Make `paths` directive accept a sequence of mappings.
As mentioned in https://github.com/h2o/h2o/issues/559#issuecomment-218327572 , `paths` directive expect a handler list, which ordering is important, so I believe a sequence is better and clearer than a mapping.
We can now write as follows:
```
paths:
/:
- mruby.handler: proc {|env| [399, {"foo"=>"FOO"}, []]}
- mruby.handler: proc {|env| [399, {"bar"=>"BAR"}, []]}
- file.dir: examples/doc_root
```
> accept sequence of mappings as path config node

- deps/picohttpparser/.clang-format
- deps/picohttpparser/.gitattributes
- deps/picohttpparser/.gitmodules
- deps/picohttpparser/Jamfile
- deps/picohttpparser/bench.c
- deps/picohttpparser/picohttpparser.c
- deps/picohttpparser/picohttpparser.h
- deps/picohttpparser/test.c
- h2o.xcodeproj/project.pbxproj
- lib/http1.c
- t/40bad-request.t
Validates HTTP/1 headers (request headers sent from client and response heaoders sent from upstream server) using the same rules as #974 does for HTTP/2.
> validate H1 headers

- CMakeLists.txt
- deps/libgkc/gkc.c
- deps/libgkc/gkc.h
- deps/libgkc/test.c
- include/h2o.h
- include/h2o/time_.h
- lib/core/configurator.c
- lib/core/logconf.c
- lib/handler/configurator/status.c
- lib/handler/status.c
- lib/handler/status/durations.c
- src/main.c
- t/50status.t
This commit adds duration and jemalloc statistics, both are optional:
jemalloc is enabled at compile time and the duration statistics are
enabled by a 'duration-stats' configuration keyword.
The commit also adds a total number of connections counter.
Duration statistics build on the existing per request duration stats
that are available for logging, each observation is stored in a
structure that allows computing quantiles. When the status page is
queried, values for the minimal, 25th, 50th, 75th and 99th percentile
are output.
> Additional stats

- deps/picohttpparser/picohttpparser.c
- deps/picohttpparser/picohttpparser.h
- include/h2o.h
- include/h2o/http2_internal.h
- lib/common/http1client.c
- lib/core/proxy.c
- lib/core/request.c
- lib/handler/chunked.c
- lib/handler/compress.c
- lib/handler/compress/brotli.cc
- lib/handler/compress/gzip.c
- lib/handler/errordoc.c
- lib/handler/fastcgi.c
- lib/handler/file.c
- lib/handler/http2_debug_state.c
- lib/handler/mruby.c
- lib/handler/mruby/chunked.c
- lib/handler/reproxy.c
- lib/handler/status.c
- lib/handler/throttle_resp.c
- lib/http1.c
- lib/http2/connection.c
- lib/http2/stream.c
- t/00unit/test.c
- t/50chunked-encoding-proxying.t
When a `transfer-encoding:chunked` transfer is interrupted in the
backend by a connection close, H2O currently just closes the frontend
stream.
This makes it not possible for the client to know that it's receiving
truncated data, whereas it would be possible over plain HTTP/1.1, since
the last chunk would be missing - Chrome and curl both report errors on
truncated HTTP/1.1 chunked transfers, FF and Safari do not, as far as
I can tell -.
This adds a test that checks that a broken `transfer-encoding:chunked`
transfer is translated into a `RST_STREAM` over H2.
> Broken http/1.1 chunked body is silently relayed

- lib/handler/file/_templates.c.h
- lib/handler/file/templates.c.h
The [man page](http://man7.org/linux/man-pages/man3/readdir_r.3.html) recommends using `readdir(3)` instead, since the implementation is thread safe as long as the directory streams are used by different threads.
> `readdir_r(3)` is deprecated since glibc 2.24

- lib/handler/file/_templates.c.h
- lib/handler/file/templates.c.h
The proposed approach does the following:
* use readdir(3) on Linux
* use readdir(3) on platforms without `#define NAME_MAX`
* since it is known that it is hard to obtain the correct size of the buffer that needs to be passed to readdir_r, see see https://womble.decadent.org.uk/readdir_r-advisory.html
* for others use readdir_r(3), since there is no guarantee that readdir(3) is MT-safe
follow up for #1046
> use readdir(3) on Solaris and others that lack `#define NAME_MAX`

- deps/libgkc/gkc.c
- examples/h2o/h2o.conf
- lib/handler/reproxy.c
Use uint64_t so that the code is 32 bit safe
> libgkc: fix 32-bit solaris 11 warnings

- lib/handler/mruby/http_request.c
set pointer to the object before calling `h2o_http1client_connect` since on_connect callback might get fired before the callto `h2o_http1client_connect` returns (fixes #1061)
> Fix mruby handler becoming unusable after a failed connection in http_request on FreeBSD

- lib/core/configurator.c
- lib/handler/configurator/expires.c
- lib/handler/configurator/fastcgi.c
- lib/handler/configurator/proxy.c
Changes the format strings of scan functions to use `SCN*`, not `PRI*`
> fix scan format to use SCN*

- src/main.c
Fixed the issue mentioned in https://github.com/h2o/h2o/issues/635.
To get TCP Fast Open works in OS X,
* `setsockopt` must be called while the socket is listening
* option_value for `setsockopt`must be `1`
> fix tcp-fastopen in osx

- lib/handler/mimemap.c
This PR changes the default `is_compressible` attribute of JavaScript and JSON files from OFF to ON.
fixes #655
> mark js, json as compressible by default

- lib/common/socket/uv-binding.c.h
libuv will call connect callback after uv_close, so the callback should ignore when status == UV_ECANCELED
> Fix crash on connect timeout

- lib/core/config.c
changes the default value of `min_rtt` from `UINT_MAX` (effectively disables the feature) to 50ms.
50ms has been chosen as a default, with the expectation that mobile connections would typically benefit from this optimization.
> enable TCP latency optimization by default

- include/h2o.h
- lib/core/config.c
- lib/core/configurator.c
- lib/core/logconf.c
- lib/core/request.c
- t/50access-log.t
The log directive for the purpose is `%{error}x`.
Also, a configuration directive named `error-log.emit-request-errors` is added to disable request-level logging to error log.
> provide option to emit request-level errors into access log

- lib/http2/http2_debug_state.c
Use PRIu64 instead of 'lu' for time_t.
> Improve format specifier for portability

- lib/core/proxy.c
- t/80reverse-proxy-missing-content-length-for-post.t
The RFC encourages senders to send a `content-length:` header, even
when it's zero for POST or PUT when no `transfer-encoding` header is
present.
Failing to do so actually leads to some servers issuing a `411 Length
Required` response over HTTP/1, since it's not possible for them to tell
if they got the full request body.
This ambiguity doesn't exist over HTTP/2, since the protocol provides
framing, so some browsers (Safari and Chrome) omit the `content-length:`
header over HTTP/2. H2O should add the header when translating such
requests to HTTP/1.
This commit has the proxy translation layer add a `content-length:`
header if needed, that is when a POST or PUT method is used and there's
no `transfer-encoding` header.
> proxy http/2 to http/1: POST+body is missing a content-length

- lib/handler/compress.c
This seems like the right thing to do, since we would send a compressed
object, should a client send the right headers. This mimics the behavior
of mod_deflate: https://github.com/apache/httpd/blob/trunk/modules/filters/mod_deflate.c#L728
> Add 'vary: accept-encoding' when we did not compress due to the contents of the 'accept-encoding' header

- lib/common/socket/evloop/kqueue.c.h
The problem is, in kqueue, registering a change (more specifically `EV_DELETE` `EVFILT_WRITE` change event) multiple times  causes `ENOENT` error in result event list, and it causes the server crush (by assertion in `write_pending` function).
Quote [man kqueue](https://www.freebsd.org/cgi/man.cgi?query=kqueue) :
```
When kevent() call fails with EINTR error, all changes in the changelist have been applied.
```
This PR fixes that issue by suppressing multiple registering of the same changes.
> suppress registering kevent changes multiple times

- lib/common/socket/evloop/kqueue.c.h
As we discussed, we shouldn't retry kevent call here to handle timeout and other signals properly.
> stop retrying kevent call (redo #1109)

- src/main.c
Otherwise, the server will continue to return an outdated OCSP response if the updater first succeeds and then fails returning a parmanent failure, as reported in #1102.
> reset OCSP stapling data when the updater returns a permanent failure

- lib/handler/configurator/fastcgi.c
- t/90root-fastcgi-php.t
The directory containing the socket file should be owned by the FastCGI client, not the FastCGI server.
fixes #1089
> fix fastcgi connection error if `fastcgi.spawn` is used with uid specified

- t/50fastcgi.t
I stumbled on this while tracking down test failures. It sounds like the
intent was to test the 2x2 matrix rather than testing the (1,1) case
twice.
> t/50fastcgi.t: cover the (!tcp, keepalive) case

- t/50http2_debug_state.t
curl changed the way the HTTP/2 response status header is reported:
https://github.com/curl/curl/commit/8243a9581b7782bc2af29e8421952d0e669f9e9e
Before 7.49.1 it was HTTP/2.0, after that it's HTTP/2
Alter the regexp to reflect that.
> Fix t/50http2_debug_state.t to dectect both HTTP/2 and HTTP/2.0

- lib/handler/proxy.c
This came up when discussing https://github.com/h2o/h2o/pull/919, but i believe it's an issue that we can address separately. This only prevents lower casing unix socket paths, and doesn't address the header rewrite. I believe header rewrite might not make much sense with unix socket anyway? What do you think?
> proxy: don't normalize a unix path to lower case

- include/h2o/http2_internal.h
- lib/http2/connection.c
- lib/http2/stream.c
`PRIORITY` frames can be sent for idle streams, and shouldn't affect the
number of open streams. When registering a stream, determine whether the
registration comes from a `PRIORITY` frame or not, and if it is, don't
affect the `max_open` stream id.
Not doing so resulted in the server closing the connection with a
`PROTOCOL_ERROR` when a `PRIORITY` frame for stream id 3 was followed by
a `HEADER` frame for stream id 1.
@Kriechi provided a minimal repro case
here: https://github.com/mitmproxy/mitmproxy/issues/1824#issuecomment-265709060
I've proposed a PR for h2spec to cover the case:
https://github.com/summerwind/h2spec/pull/67/files
> Don't bump `conn->pull_stream_ids.max_open` for PRIORITY frames

- include/h2o/http2_internal.h
- lib/http2/connection.c
- lib/http2/stream.c
Redo #1136. The original approach failed to update max_open when receiving PRIORITY and then HEADERS on a single stream.
> update max_open in h2o_http2_stream_prepare_for_request

- deps/mruby-require/mrbgem.rake
I suppose that the comment-out to remove the mruby-tempfile dependency was erroneously removed with this commit.
https://github.com/h2o/h2o/commit/d484cbad1a050b6a1681cd3d801c661637925fc9#diff-891bddc59ae138f3b8b586dcd0eb5de2R8
This causes the following error during compilation.
```
(in /root/h2o/h2o-master/deps/mruby)
rake aborted!
mgem not found: mruby-tempfile
Rakefile:26:in `load'
make[2]: *** [CMakeFiles/mruby.dir/build.make:57: CMakeFiles/mruby] Error 1
make[1]: *** [CMakeFiles/Makefile2:504: CMakeFiles/mruby.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```
This patch removes mruby-tempfile dependency as before.
Thanks.
> Fix compilation error (Remove mruby-tempfile dependency)

- lib/http1.c
- lib/http2/connection.c
This PR fixes two issues that can happen if the upgrade from HTTP/1 to HTTP/2 fails.
> HTTP/1 -> HTTP/2 uprade error fixes

- lib/core/logconf.c
- t/50access-log.t
Since that is what Apache does; see #1153.
> `%{set-cookie}o` should log all the set-cookie headers concatenated

- lib/core/logconf.c
- t/50access-log.t
> add support for `%{local|remote}p`

- src/main.c
- srcdoc/configure/base_directives.mt
If this parameter is set to true, the crash handler will wait until the
pipe opened to the crash handler is closed by it. This is useful if the
crash handler is ptracing the main process in order to get more
information.
> Add a `crash-handler.wait-pipe-close` parameter

- include/h2o/url.h
- lib/common/url.c
- lib/core/proxy.c
- lib/handler/proxy.c
This is a fixed version of #1130 . It adds a boolean in the `h2o_url_t` structure to indicate whether the host name contains a unix path or not. The matching for header rewrite takes that into account, and uses `strcasecmp` when appropriate.
> Proxy dont normalize unix path

- include/h2o.h
- lib/core/proxy.c
- lib/core/request.c
- lib/core/util.c
- t/00unit/lib/core/util.c
- t/40server-push-attrs.t
- t/assets/upstream.psgi
When this is set, H2O will interpret the `rel=preload` link as a header
we only want to use for H2 pushes, rather than something we also want to
push to the client. So we'll be removing that attribute from the link
header. If there's only one link, we remove the full header.
This is change is there to allow HTTP/1 clients to express HTTP/2 pushes
in a way that doesn't affect the response sent to the client.
> Pushes: support a x-http2-push-only attribute

- lib/http2/connection.c
This PR fixes a bug of loop of PING frame. Currently H2O will respond even if it is a PING frame with the ACK flag enabled. This behavior will cause a loop of PING frame.
> Send PING frame only when ACK flag does not specified

- include/h2o.h
- include/h2o/socket.h
- include/h2o/string_.h
- lib/common/socket.c
- lib/core/logconf.c
- lib/handler/status/requests.c
- lib/http1.c
- lib/http2/connection.c
- t/50access-log.t
replaces https://github.com/h2o/h2o/pull/1147 because somehow i messed that up.
i tried to fix the issues, but i'm unsure about the correct algo for `h2o_base64_encode_capacity`.
http://stackoverflow.com/questions/1533113/calculate-the-size-to-a-base-64-encoded-message
suggests:
`((len * 4) / 3) + (len / 96) + 6`
also not sure why the ci fails
> log session id

- include/h2o/socket.h
- lib/common/socket.c
- lib/core/util.c
as discussed at https://github.com/h2o/h2o/pull/1087#discussion_r98603694, we shouldn't remove tls session cache actively.
Regarding [the manual](https://www.openssl.org/docs/man1.0.1/ssl/SSL_CTX_sess_set_remove_cb.html), there are 3 triggers the remove callback gets called:
> The remove_session_cb() is called, whenever the SSL engine removes a session from the internal cache. This happens
> 
> * when the session is removed because it is expired
> * or when a connection was not shutdown cleanly.
> * It also happens for all sessions in the internal session cache when SSL_CTX_free is called.
For the first one, currently we're using memcached (and redis in near future) which have their own expiration feature, so there's no need to remove explicitly.
For the second, we would not want to …
> stop removing session cache from memcached

- fuzz/driver.cc
so that the storage doesn't go out of scope when `LLVMFuzzerTestOneInput` returns.
> make tmpname static 

- lib/handler/mruby.c
By this PR, h2o
* outputs detailed error message in the case the user didn't run `make install` and `preloads.rb` cannot be found
* doesn't load `preloads.rb` from current directory
> adds better error message when preloads.rb not found

- deps/libgkc/gkc.c
@deweerdt Does the change look reasonable? This is the only place we use `typeof` and `({...})`.
> rewrite using standard C

- include/h2o.h
- lib/core/config.c
- lib/core/configurator.c
- lib/core/context.c
- lib/http2/connection.c
- srcdoc/configure/http2_directives.mt
- t/80graceful-shutdown.t
- t/assets/upstream.psgi
On graceful shutdown, after the second GOAWAY message has been written,
it should be possible for use to safely close the connection, without
necessarily waiting for all streams to be processed.
> add timeout for closing connections at the graceful shutdown

- lib/common/socket/evloop.c.h
How about such realization of h2o_evloop_destroy?
It is nicely commented. 
In short: dispose all sockets, free memory used by sockets and then free memory used by event loop structure.
some warnings on compilation  warning: assignment makes pointer from integer without a cast [-Wint-conversion], but compiling fine.
> implementation of h2o_evloop_destroy

- lib/http1.c
When sending a '400 Bad request', stop reading from the socket. Not
doing so risks having `handle_incoming_request` being called a second
time, and assert because a write is already scheduled:
```
do_write                h2o/lib/common/socket/evloop.c.h:257:5
h2o_socket_write        h2o/lib/common/socket.c:576:9
send_bad_request        h2o/lib/http1.c:413:5
handle_incoming_request h2o/lib/http1.c:490:13
reqread_on_read         h2o/lib/http1.c:506:9
read_on_ready           h2o/lib/common/socket/evloop.c.h:235:5
```
> Stop reading from the socket after sending a '400 Bad request'

- include/h2o.h
- lib/core/config.c
- lib/core/proxy.c
- lib/handler/configurator/proxy.c
- t/50reverse-proxy-added-headers.t
This commit adds a `emit-via-header` knob. When set to true, the `via:`
header is added by the proxy layer (concatenating to an existing header
if necessary), otherwise the header is left as-is. The setting defaults
to true.
> [proxy]: Add a knob controlling the `via:` header

- lib/core/logconf.c
- t/50access-log.t
by magically removing the surrounding quotes if the specifier is the only thing that is within a string literal.
The chart below shows when the surrounding quotes get removed.
|format string|when `%foo` is `bar`|when `%foo` is null|
|---|---|---|
|`%foo`|`bar`|`null`|
|`"%foo"`|`"bar"`|`null`|
|`"baz%foo"`|`"bazbar"`|`"baznull"`
amends #1208
> in JSON logging, emit `null` without surrounding quotes

- lib/core/configurator.c
Otherwise, a request that did not match to any of the path-level configuration (e.g. no configuration for `/` vs. a request to `/`) will not be logged by an access-log directive at the global- or host-level.
> Apply global and host-level configuration to fallback paths.

- include/h2o.h
- lib/core/logconf.c
- lib/core/request.c
- t/50access-log.t
Note that the default is `>` (i.e. final) for backward compatibility.
implements #1162
> support `<`, `>` modifiers that specify to log either the original or the final response

- include/h2o/multithread.h
- lib/common/multithread.c
- src/main.c
It's possible that not all threads have started by the time other
threads start to serve requests.
This is in particular problematic with the status handler: the
on_req_json function relies on on_context_init being called for all
threads, but in fact the call of h2o_multithread_register_receiver
might be racing against the value of self->receivers.size.
This results in more threads being called than
collector->num_remaining_threads_atomic. A consequence of this can be
that either send_response is not called (and the fd of the request
is leaked), or on final() being called twice (leading to a possible
double free).
This commit solves the issue by introducing a barrier-like API that we use
as a synchronization point at startup time. By doing this, it's not possible
anymore that threads …
> Sync threads on startup

- lib/handler/configurator/mruby.c
- lib/handler/mruby.c
I think there are 3 problems:
1. lineno parsed in compilation phase is not passed to mruby handler (this causes lineno mismatch when mruby exception is raised)
2. yaml's lineno is 0-origin, but we want 1-origin lineno
3. problems with Block Scalar Style (see: https://github.com/h2o/yoml/pull/6)
> fix mruby code lineno

- include/h2o/memory.h
- lib/common/memory.c
- lib/common/string.c
- lib/core/logconf.c
- lib/core/request.c
- lib/handler/configurator/errordoc.c
- lib/handler/mruby.c
- lib/http1.c
- lib/http2/cache_digests.c
- lib/http2/frame.c
- src/ssl.c
This PR contains fixes for issues detected by `ubsan` when running `make check`. There a three commits:
- Passing `NULL` and `0` as`src` and `len` respectively to `memcpy`
- Passing the `base` argument to `bsearch` as NULL
- Using `((type *)0)->a - ((type *)0)->b` to compute an offset in a struct
To my knowledge, these doesn't alter the behavior of H2O, nor they fix an existing real life issue.
> undefined behavior fixes

- srcdoc/configure/compress_directives.mt
"brotli" is invalid parameter in compress section. Replaced with br in srcdocs.
> Fixed typo in docs source (brotli -> br)

- share/h2o/fetch-ocsp-response
due to an incompatible change introduced in OpenSSL 1.1.0. In prior versions, the `-header` argument took two arguments; first one being the name of the header and second being the value of the header. In 1.1.0, it became a single argument in form of `name=value`.
Fixes #1267
> Fix OCSP stapling error when OpenSSL 1.1.0 is used

- lib/handler/mruby.c
When building a Rack object, we pre-sort the headers  so that we can merge the headers having same names in O(N log N) cost.
For the purpose, the sort algorithm needs to be stable, so that the order of the values of the headers having the same name does not get changed.
Current way of using `qsort` doesn't satisfy the requirement; hence this PR.
> retain the order of headers having the same names

- share/h2o/fetch-ocsp-response
As pointed out in #1274, the version check code introduced in #1270 did not take the case of LibreSSL into consideration.
This PR fixes the issue by applying the patch provided by @csmk in #1274.
> fix OCSP stapling failure when LibreSSL ised used

- lib/common/memory.c
> Make sure `h2o_mem_alloc_pool` returns a valid pointer when size is 0

- srcdoc/configure/http2_directives.mt
- srcdoc/configure/mruby.mt
Not setting the `as=` attribute might be technically incorrect (i'm
still trying to figure that out), and definitely causes interoperability
issues with Chrome, causing it to re-fetch pushed resources.
> [doc] rel=preload examples missing `as=` attribute

- lib/handler/mruby.c
- t/40server-push-attrs.t
@worenga and @utrenkner mentioned [here](https://github.com/h2o/h2o/issues/1303#issuecomment-302641870) that `rel=preload` headers with `x-http2-push-only` would still present when the headers were added via the mruby directive. This PR fixes it and add mruby test coverage.
> support x-http2-push-only in the mruby handler as well

- src/main.c
- "Initialiser in not constant". related to the pthread barrier conf field.
- Initialising it in main instead.
> build fix under solaris based oses :

- CMakeLists.txt
- fuzz/driver.cc
The existing `CMakeLists.txt` contains a superfluous linker directive for `-fsanitize=address`. google/oss-fuzz has recently started experimenting with additional Clang sanitizers; [this directive causes build errors](https://github.com/google/oss-fuzz/issues/585) when used with other sanitizer/coverage options.
This patch removes the superfluous directive and fixes an error in `fuzz/driver.cc` that was causing memsan fuzz runs to report a bug and exit immediately.
> Remove superfluous san/cov flags for fuzz builds

- include/h2o/multithread.h
- src/main.c
The change made in #1300 implies that `pthread_mutex_t` is declared in a specific way even though the structure is organized in different ways depending on the OS.
The fact was leading for us seeing the following compiler warning on OS X.
```
/mydev/h2o/src/main.c:187:7: warning: braces around scalar initializer [-Wbraced-scalar-init]
{{{0}}},                                /* startup_sync_barrier */
^~~
1 warning generated.
```
This PR attempts to fix the issue address by  #1300 in another way; by changing how `H2O_BARRIER_INIT` and avoiding use of the macro at runtime.
> fix compiler warning

- t/40env.t
- t/40redis-session-resumption.t
- t/40server-push-attrs.t
- t/40server-push-multiple.t
- t/40websocket.t
- t/50fastcgi-cgi.t
- t/50fastcgi-php.t
- t/50fastcgi.t
- t/50reverse-proxy-config.t
- t/50reverse-proxy-https.t
- t/50reverse-proxy-session-resumption.t
- t/50servername.t
- t/80invalid-h2-chars-in-headers.t
- t/80issues61.t
- t/90root-fastcgi-php.t
- t/Util.pm
Even after https://github.com/tokuhirom/Test-TCP/pull/59 went in, we have been seeing occasional CI errors (for an example, see https://travis-ci.org/h2o/h2o/builds/238598895?utm_source=github_status&utm_medium=notification).
This might be (at least partly) due to us calling `empty_port` with no argument (thus looking for an empty port on 127.0.0.1) and then trying to use that port on 0.0.0.0.
This PR fixes the issue in either of the two ways depending on the tests being run:
* look for an empty port on 0.0.0.0 (by calling `empty_port({ host => '0.0.0.0' })`)
* bind using the loopback address (i.e. 127.0.0.1) to the empty port being found
> check avialability of correct address

- deps/mruby-require/mrbgem.rake
- deps/mruby-require/mrblib/require.rb
- deps/mruby-require/test/d/required.rb
- deps/mruby-require/test/require.rb
This PR imports the following bugfix:
https://github.com/iij/mruby-require/commit/78d37057641336cb594ad3be5a728ff6127f9119
Before this patch:
```ruby
require "hoge.rb" # this file defining Hoge class
class Fuga; end
puts Hoge # => Kernel::Hoge
puts Fuga # => Fuga
```
This behavior is a bug because `Hoge` must be defined under top_self like `Fuga`, not under the `Kernel` . This issue makes it impossible to extend existing or built-in classes (without inserting explicit `::` prefix in the class name).
After this patch:
```ruby
require "hoge.rb"
class Fuga; end
puts Hoge # => Hoge
puts Fuga # => Fuga
```
Regarding the effect, strictly speaking, this PR breaks backward compatibility. But IMHO actually problems happen on rare occasion (e.g. using stringified value of required class for …
> update iij/mruby-require to the latest version

- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/chunked.c
- lib/handler/mruby/embedded.c.h
- lib/handler/mruby/embedded/http_request.rb
- lib/handler/mruby/http_request.c
- t/50mruby-http-request.t
This PR contains 2 fixes of mruby related bugs.
The first is, `h2o_mruby_http_request_context_t` (req-ctx) gets released unexpectedly when fast-path body streaming is used. After https://github.com/h2o/h2o/pull/1173, the lifecycle of req-ctx is not bound to the request lifetime, so we have to keep the HttpInputStream object from gc (as [slow-path does](https://github.com/h2o/h2o/blob/master/lib/handler/mruby/chunked.c#L156)). But it was forgotten, so as a result, occasionally req-ctx and http1client_t is freed and badaccess crashes happen when chunked body streaming is processed. To fix this issue I retained the body obj until generator->chunked is disposed, and added an additional assertion in
req-ctx disposal. The newly added `h2o_mruby_http_unset_shortcut` function is for clearing the …
> fix mruby gc problem for http request context

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/embedded.c.h
- lib/handler/mruby/embedded/core.rb
- lib/handler/mruby/sleep.c
- t/50mruby-sleep.t
Add `sleep` function to the Kernel.
What drove me to implement this is mainly H2O::Redis reconnect loop, but this can be useful for various situations as pointed out in https://github.com/h2o/h2o/issues/1283
NOTE: This PR is toward https://github.com/h2o/h2o/pull/1173.
> mruby sleep

- fuzz/driver.cc
Hello,
The h2o fuzz drivers can't be built in the latest commit to master (issue [here](https://github.com/google/oss-fuzz/issues/704)). This PR seems to fix the problem, but I ran into some odd behavior along the way: please read on.
The fuzz integration broke because the prototype for `h2o_proxy_register_reverse_proxy` changed. I updated the function invocation in the fuzz driver to fix the compile error (assuming `1` was the proper argument in this case), but this caused the first iteration of fuzzing to fail with an `abort`. The `abort` is raised by the `write_fully` function (which writes the fuzzed input the socket passed to h2o "server") due to a socket error.
```
Using seed corpus: ./h2o-fuzzer-http2_seed_corpus.zip
/out/./h2o-fuzzer-http2 -rss_limit_mb=2048 -timeout=25 /tmp/input …
```
> Fix fuzz driver (hopefully)

- CMakeLists.txt
This is due to a cmake oddity: when CONFIGURE_COMMAND is not set,
`ExternalProject_Add` defaults to running cmake with no arguments.
> Fix cmake build issue

- CMakeLists.txt
`cmake` can be invoked with an absolute path, and that just works. Use `${CMAKE_PROGRAM}` so that works to build h2get as well.
> Don't assume cmake is in the PATH

- srcdoc/configure/http2_directives.mt
It's extremely minor typo found while reading.
Because `100 * 100 = 10000 =~ 2^13`, `log2(100 * 100)` should be `=~ 13`.
> [doc] Fix minor typo in docs of http2-casper

- examples/h2o/h2o.conf
- examples/h2o_mruby/h2o.conf
- srcdoc/configure/base_directives.mt
since https://github.com/h2o/h2o/pull/1334 hasn't found an agreement we should at least encourage people to take modern defaults.
> add modern default ciphers to example configs

- .travis.yml
For some reason, cpanm in h2o builds tend to consistently hit
search.cpan.org as a CPAN mirror, but that mirror is unfortunately
unreliable, timing out often after connection.
This commit forces the CPAN mirror to be cpan.metacpan.org, which is
backed by Fastly, and can be reached via https:
```
cpan.metacpan.org.      2418    IN      CNAME dualstack.a.ssl.global.fastly.net.
dualstack.a.ssl.global.fastly.net. 30 IN A      151.101.40.249
```
> Force cpan.metacpan.org as a CPAN mirror

- include/h2o.h
- lib/core/configurator.c
- lib/handler/mimemap.c
- t/50mimemap.t
[file.mime.settypes document](https://h2o.examp1e.net/configure/file_directives.html#file.mime.settypes) says that using `file.mime.settypes` with empty mapping resets default mimetype mapping, but actually that's not the case. This PR fixes it.
> clear all default mimemap types on file.mime.settypes

- lib/common/socket.c
`setup_bio()` uses a mutex to guard the initialization of `bio_methods`, but the mutex is never released. As a consequence, if two threads find `bio_methods` to be `NULL` at the same time, or if one of them is in the critical section while the other one tries to acquire the mutex, one thread will go on and initialize bio_methods and the other one will wait for the mutex to be released indefinitely.
We have been able to reproduce this, bringing h2o to the following state:
```
(gdb) thread apply all bt
Thread 6 (Thread 0x7fdea534e700 (LWP 12695)):
#0  0x00007fdea8c7b0b3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000562180218fc7 in evloop_do_proceed (_loop=_loop@entry=0x7fde880008c0, max_wait=<optimized out>)
at ./lib/common/socket/evloop/epoll.c.h:115
#2 …
```
> Fix deadlock in setup_bio()

- t/50reverse-proxy-chunk-timeout-2.t
- t/50reverse-proxy-serialize-posts.t
- `t/50reverse-proxy-chunk-timeout-2.t` uses nghttp without precondition check
- in `t/50reverse-proxy-serialize-posts.t`:
- grep command in OSX no longer supports `P` option
- `wc` command possibly outputs leading white spaces
This PR fixes above issues
> fix test issues

- src/ssl.c
H2O currently signals OpenSSL to unconditionally renew a ticket if it was not encrypted using the latest key available. While this generally works, it assumes that the latest key is always valid for encryption,
which however may not be the case. When encryption keys are rotated, the newly-generated key's `not_before` is set to 60 seconds in the future, so the most recent key is not yet valid for a whole minute. This in turn leads to unnecessary ticket renewals, where a ticket will be re-issued using the same (active) encryption key.
We fix this by checking that if there is a newer key, it is indeed suitable for encryption, before requesting renewal.
> ssl: avoid spurious ticket renewals

- CMakeLists.txt
- t/40proxy-protocol.t
- t/50reverse-proxy-chunk-sizes.t
- t/50reverse-proxy-chunk-timeout-1.t
- t/50reverse-proxy-serialize-posts-3.t
- t/50status.t
- t/Util.pm
- https://github.com/h2o/h2o/commit/6d551af1a44897253c1f14bb5d1dd893e8645982
- As of Perl 5.26, `.` isn't contained in @INC in default. To workaround to this, add `-I.` option
- https://github.com/h2o/h2o/commit/990b7af47a85a054eea4c5f0b76d5d920d490a90
- nc's  `-q` option doesn't exist in some environments and seems to be not really necessary to run the test, am I correct? @deweerdt 
- https://github.com/h2o/h2o/commit/e17d0655ecf43e72120b0c7333fbe88e1f92950b
- h2get binary may not be placed in H2O_ROOT?
> fix miscellaneous test issues

- lib/common/socket.c
Hi,
_TL;DR: H2O's use of `SSL_get_error()` is not safe and may cause error propagation between different connections_
This came up while debugging abnormal connection terminations that happened sporadically during a POST request. We also had reports about connection terminations from browsers, but could not pinpoint the exact cause. The connections in question appeared to complete the SSL handshake normally and then H2O returned an encrypted alert as soon as the client sent a couple of application data TLS packets. Note that the failures were not logged by H2O at all, we only heard about them from the client side. Furthermore, it turned out the failures had some kind of correlation with a third client hammering us with SSLv3 handshakes, which were refused by our OpenSSL version; as soon …
> Clear OpenSSL's error queue before using it

- t/50reverse-proxy/test.pl
Before aa43cbd, `proxy.timeout.keepalive: 0` is meant to be applied to `/`, but by adding new path, that configuration unexpectedly gets disappeared from `/` and other paths.
I believe that the intension of this line was to switch keepalive ON/OFF **globally**, so.. just remove leading white spaces!
> fix a proxy test degration caused by commit aa43cbd

- lib/http2/stream.c
Seems like a bug introduced in 5a02364.
> fix dubious if; stream blocked state can never depend on the connection state

- examples/libh2o/http1client.c
- include/h2o.h
- include/h2o/http1client.h
- include/h2o/http2_internal.h
- lib/common/http1client.c
- lib/core/proxy.c
- lib/core/request.c
- lib/handler/mruby/http_request.c
- lib/handler/proxy.c
- lib/http2/connection.c
- lib/http2/http2_debug_state.c
- lib/http2/stream.c
Refactors the code to always rely on stream state to determine what can be received (or not). Also fixes following issues in streaming mode:
* set response_blocked_by_server when receiving end_stream
* check that the actual size of the body received matches content-length
* remove superfluous connection-level window update (was done twice at the top and bottom of handle_data_frame)
> refactor request body streaming

- lib/http1.c
otherwise results in an assertion failure.
fixes #1441 #1447
> send 100-continue after creating the entity reader

- lib/common/socket.c
The original code may access NULL pointer if cipher == NULL.
> fix ; return 0 if cipher is NULL

- lib/handler/mruby/sleep.c
As pointed out by @yannick (https://github.com/h2o/h2o/pull/1152#issuecomment-337566213), current implementations of mruby-sleep and mruby-redis have a problem which prevents gc from releasing objects generated in C layer. As a result, memory leaks happen.
This PR fixes the problem of mruby-sleep. As for mruby-redis, I'll make a commit to #1152
> fix mruby-sleep memory issue

- CMakeLists.txt
The compiler flags have changed for v5, add directives supporting the
new `-fsanitize=fuzzer` flag. The tricky part is that we can't pass that
for linking h2o since that links to libFuzzer.a which defines it's own
main.
> Fuzzer: Add support for clang 5.0

- h2o.xcodeproj/project.pbxproj
- include/h2o/socketpool.h
- lib/common/socketpool.c
- lib/handler/configurator/proxy.c
- lib/handler/fastcgi.c
- lib/handler/proxy.c
- t/50reverse-proxy-multiple-backends.t
- t/assets/upstream.psgi
Amends #1277, utilizing the fact that with #1434 socket pool can be used for non-persistent connections.
Also refactors the members of `h2o_socketpool_t` for simplicity.
> load balancing using non-persistent backends

- .travis.yml
- include/h2o.h
- include/h2o/http1client.h
- lib/common/http1client.c
- lib/common/socketpool.c
- lib/core/proxy.c
- lib/handler/configurator/proxy.c
- lib/handler/proxy.c
- t/50reverse-proxy-config.t
- t/50reverse-proxy-https.t
- t/50reverse-proxy-multiple-backends-with-down.t
- t/50reverse-proxy-multiple-backends.t
- t/50reverse-proxy-round-robin.t
- t/assets/upstream.psgi
This PR aims to remove the restriction that caused the introduction of `proxy.reverse.backends` and `proxy.reverse.path` in #1277.
With #1471 being merged, we can always accept the URL that h2o has connected to (including it's path) as an argument of `on_pool_connect`. It is no longer to require all the paths of the load-balanced backends to be equivalent.
Hence we can (should) switch to using `proxy.reverse.url` accepting list of URLs rather than having different configuration directives.
> [wip] allow different paths for load-balanced backends

- include/h2o.h
- lib/core/request.c
- lib/handler/chunked.c
- lib/http1.c
- lib/http2/stream.c
- t/50access-log.t
Currently, the access log `%b` specifier outputs *raw* body size ignoring compression, chunked encoding overhead, etc..
This PR fixes that issue.
> fix access log body size

- examples/libh2o/http1client.c
- fuzz/driver.cc
- include/h2o.h
- include/h2o/http1client.h
- include/h2o/socketpool.h
- lib/common/http1client.c
- lib/common/socketpool.c
- lib/core/config.c
- lib/core/context.c
- lib/handler/configurator/proxy.c
- lib/handler/proxy.c
The global socket pool determines which socket can be reused by looking at the (is_ssl, host, port) tuple. The fact means that SSL connections connecting to the same host:port using different SSL_CTXs cannot be shared within the global socket.
This PR implements the restriction by making SSL_CTX part of the socket pool. The added bonus is that SSL handshake can now be completed within the socket pool.
amends #1434 #1476
> SSL_CTX as part of socket pool

- lib/handler/mruby/chunked.c
- t/50mruby-http-request.t
This PR fixes the bug that h2o cannot persists the connections with clients when mruby's http_request is used and the response body of it is directory returned (so called `shortcut`).
The problem was caused by the fact that `chunked->bytes_left` had never been decremented when shortcut is used and so [this condition](https://github.com/h2o/h2o/blob/master/lib/handler/mruby/chunked.c#L59-L60) may accidentaly fall truthy. Thus, it only happens when the header hash of rack response contains `content-length` header.
> fix keepalive problem related to mruby's http_request shortcut

- lib/handler/mruby.c
- t/50mruby.t
Currently mruby env's `PATH_INFO` value is url-decoded. For example, if we access to `/foo%20bar`, `env['PATH_INFO']` will be `/foo bar` .
Facts:
- Popular Ruby application servers keeps it undecoded
- unicorn / thin / puma / webrick
- Rack specification is very ambiguous (says `This value may be percent-encoded`)
- https://github.com/rack/rack/blob/master/SPEC#L37-L39
- WSGI specification doesn't say anything about it
- https://www.python.org/dev/peps/pep-0333/#id19
- CGI specification defines 'Unlike a URI path, the PATH_INFO is not URL-encoded'
- https://tools.ietf.org/html/rfc3875#section-4.1.5
Considering mruby in h2o, the compatibility to other servers is important for portability and "least surprise". So I think it's best if we can change it undecoded, but it may break backward …
> keep mruby's PATH_INFO undecoded

- examples/libh2o/http1client.c
- include/h2o/http1client.h
- lib/common/http1client.c
- lib/core/proxy.c
- lib/handler/mruby/http_request.c
* merged build_request_line_host and build_request_rest_headers into single function (essentially reverts f4c9f48 of #1277)
* moves the signaling to use chunked encoding from when http1client is initialized to when the connection is established
> simplify proxy-http1client interaction

- lib/handler/fastcgi.c
- lib/handler/mruby/chunked.c
- t/50mruby-http-request.t
- t/50unexpected-upstream-body.t
- t/assets/upstream.psgi
When the upstreams (via fastcgi and mruby's http_request) respond a payload which length is smaller than content-length header value, the current implementation doesn't send RST_STREAM frame. This PR makes those handlers send RST_STREAM.
NOTE1: This PR depends on https://github.com/h2o/h2o/pull/1489 to make some tests pass
NOTE2: Desirable h2o behaviours
|Upstream Payload | h2o Payload | RST_STREAM (H2) | chunked (H1) |
| ----- | ----- | ----- | ----- |
| smaller than C-L | send all received body | YES | - |
| bigger than C-L | send body upto C-L | NO | - |
| TE:chunked ending in mid-of-chunk | send all received body | YES | append a broken chunk (`1\r\n`) |
| TE:chunked ending on chunk boundary but no eos | send all received body | NO | append an eos (`0\r\n`) |
SEE ALSO: …
> send RST_STREAM when received smaller payload than content-length header

- lib/core/request.c
- t/50internal-redirect.t
When you place `listen` directive under `hosts`,  like
```
hosts:
host1:
listen:
host: 0.0.0.0
port: 8080
paths:
/:
..
host2:
listen:
host: 0.0.0.0
port: 8081
paths:
/:
..
```
then, internal redirect (reproxy, redirect via location header, errordoc) between host1 and host2 doesn't work and external HTTP request happens.
This PR fixes that issue.
> fix internal redirect

- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/chunked.c
- lib/handler/mruby/embedded.c.h
- lib/handler/mruby/embedded/chunked.rb
- lib/handler/mruby/embedded/core.rb
- lib/handler/mruby/http_request.c
- lib/handler/mruby/sleep.c
The benefits:
- resolve concerns about confliction of integer ids in parallel development
- remove duplicate constant definitions of callback ids in `core.rb`
- remove difficulties of handling edge cases (like status `0`)
> refactor mruby callbacks

- lib/core/configurator.c
In configuration, currently path string keys under `paths` directive can be empty string, but it may cause some problems (because it's not supposed be in many cases). IMHO there're no reasons to allow that, so This PR explicitly forbid that and warn in configuration phase.
> forbid empty path string in configuration

- lib/handler/mruby.c
- t/50mruby.t
There are several bugs in calculating PATH_INFO and SCRIPT_NAME in mruby handlers.
1. `PATH_INFO` gets broken when `confpath_len_wo_slash` is zero and path normalization happens . This is caused by https://github.com/h2o/h2o/pull/1480
2. also `SCRIPT_NAME` can be broken when `req->pathconf->path.len` is zero and index overflow happens ([here](https://github.com/h2o/h2o/blob/4581462079ac140f8a32b37588f54495af7039f6/lib/handler/mruby.c#L453)). This is a long standing bug, maybe
3. both of them can be broken when req->path doesn't have a leading slash. This is caused by https://github.com/h2o/h2o/pull/1480
Especially 1. and 2. may leeds `ArgumentError: string size is too big` error in mruby layer. This PR fixes these issues.
Thank you for finding and reporting the bug @ykzts
> fix possible offset overflow of SCRIPT_INFO and PATH_INFO

- share/h2o/setuidgid
In #847 shebang for the perl interpreter was changed to respect the `H2O_PERL` environment variable. However, setuidgid script (only) has missed to receive the change.
> respect H2O_PERL environment variable in share/h2o/setuidgid

- deps/brotli/enc/fast_log.h
- lib/common/memory.c
- lib/common/serverutil.c
- lib/common/socket/evloop.c.h
- lib/handler/access_log.c
- src/main.c
Hello,
This PR enables building H2O for Android NDK r16 (Clang 5.0).  Validated on devices in the range of 15 - 26 (armeabi-v7a, arm64-v8a, x86, x86_64).
Regards,
Joel
> changes to build for Android

- include/h2o/mruby_.h
- lib/handler/mruby.c
- lib/handler/mruby/channel.c
- lib/handler/mruby/chunked.c
- lib/handler/mruby/embedded.c.h
- lib/handler/mruby/http_request.c
- misc/embed_mruby_code.pl
In the case of #1536, we saw just "(eval)" as the location of mruby methods.
These definitions should be eval-ed from embedded code (to help reading version-inconsistent definitions dynamically), but we can show filenames and consistent line numbers, like this:
```
FiberError:can't cross C function boundary
(h2o)lib/handler/mruby/embedded/core.rb:31:in _h2o__run_child_fiber
(h2o)lib/handler/mruby/embedded/core.rb:115:in task
test/h2o/frontend.conf:11:in initialize
test/h2o/frontend.conf:19:in eval
(h2o)lib/handler/mruby/embedded/core.rb:68
```
This patch is to embed mruby code with file paths and consistent line numbers of these code, by using 3rd and 4th arguments of `eval`. To make it possible, this change also does a fix to embed just same mruby scripts with …
> Show filenames and consistent lineno of embedded mruby code

- lib/common/socket.c
At the moment ssl record size doesn't increase as expected in some situations (connection via http1, or http2 but h2o is running in operating systems in which latency-optimization is disabled)
> count sock->bytes_written correctly

- lib/core/util.c
- lib/handler/proxy.c
- t/50reverse-proxy/test.pl
- t/assets/upstream.psgi
fixes #1560
It seems that this is a regression in master branch. When backported to 2.2.x, the test runs fine (see eaaf1af).
> don't add trailing slash to upstream request

- lib/handler/mruby.c
Amends #1511. It didn't output the caller location correctly.
> fix h2o_mruby_new_str

- lib/handler/fastcgi.c
- lib/handler/mruby.c
- t/50date-header.t
amends https://github.com/h2o/h2o/pull/1495: h2o_find_header's `cursor` argument should be `SIZE_MAX` here, otherwise we will pass over the first response header and duplicate date headers appear.
> fix duplicate date headers

- h2o.xcodeproj/project.pbxproj
- lib/core/request.c
- t/80no-handler-vs-h2-post.t
We allow the path-level configuration to omit an entry for `/`. In such case, access to a non-matching path is expected to return a 404 response.
Fixes regression in #1357.
> fix crash when trying to dispatch request body against `/` with no handler

- h2o.xcodeproj/project.pbxproj
- misc/docker-ci/Dockerfile
- t/40http2-h2spec.t
Currently uses h2spec pre-v2.0.0. We need to address the failures caused by v2.0.x on either of the two sides.
> run h2spec as part of  CI

- include/h2o/http2_internal.h
- lib/http2/connection.c
- lib/http2/scheduler.c
Fix bug found by h2spec version: 2.1.0 (d99d17171179c709cf23a3df1aadc9657addf825).
> correctly handle window size becoming negative

- h2o.xcodeproj/project.pbxproj
- t/50reverse-proxy-chunk-timeout-1.t
- t/50reverse-proxy-serialize-posts-3.t
- t/Util.pm
We need to check the existence of `h2get` before spawning the server that accepts request indirectly.
> fix test stall when h2get is missing

- lib/http2/connection.c
When the stream state is in SEND_BODY_IS_FINAL state and the stream gets activated (e.g. by receiving a WINDOW_UPDATE frame) and then is immediately disactivated (e.g. by another WINDOW_UPDATE frame), the stream remains in the scheduler.
In such case, we should not invoke `h2o_http2_stream_proceed` since the state means that there's pending data to sent (i.e. the DATA stream with the END_STREAM flag set). However a check was missing that caused that to happen.
This became a real issue as a side-effect of #1582.
> Don't call the proceed callback for a stream that has already sent a closing send-state

- include/h2o/websocket.h
- lib/websocket.c
wslay_event_send() may trigger  send_callback() more than once.
so we can buffer the send request's data and merge the real send with only one h2o_socket_write() call.
> queue 4 chunks for wslay's send_callback(), and merged with one h2o_socket_write() call

- lib/common/socket.c
- lib/core/proxy.c
- lib/http1.c
`t/50unexpected-upstream-body.t` would trigger an AddressSanitizer heap-use-after-free error though the test still passes. It is caused by `http1.c` where memory pool is released when last chunck of data is sent, but we still do some check on `struct rp_generator_t` which is already freed. This PR fix the problem by switching the order of the check mentioned above and `do_send`.
> fix heap-use-after-free when upstream response stops unexpectly

- misc/docker-ci/Dockerfile
- misc/docker-ci/check.mk
This PR introduces several optimizations for docker ci:
* Introduces [dumb-init](https://github.com/Yelp/dumb-init) as entrypoint for the building process, so that singals like `^C` a.k.a `SIGINT` could be used for canceling current build.
* Introduces `-t` argument for `docker run` so output could be colored, helping locating the failed tests (maybe?)
Docker image `zlm2012/h2o-ci` could be tested with.
> Docker CI Optimizations

- CONTRIBUTING.md
- misc/docker-ci/check.mk
* pull the CI image: `make -f misc/docker-ci/check.mk pull`
* enter the CI container: `make -f misc/docker-ci/check.mk enter` (runs bash)
relates to: #1551
> add utility commands for docker-based CI

- include/h2o/configurator.h
- lib/core/configurator.c
- lib/handler/configurator/access_log.c
- lib/handler/configurator/compress.c
- lib/handler/configurator/errordoc.c
- lib/handler/configurator/fastcgi.c
- lib/handler/configurator/proxy.c
- lib/handler/configurator/redirect.c
- src/main.c
- src/ssl.c
Until now, every configuration directive that (optionally) takes a YOML mapping has written it's own attribute parser.
The fact has not only made the code-base unnecessary complex but also has caused inconsistency between the parsers in how they deal with unknown or duplicate key.
This PR aims to resolve the issue by introducing a function to be used for fetching named values from a YOML mapping.
rework of #1068
> refactor YOML attribute parsing

- misc/docker-ci/Dockerfile
- misc/docker-ci/check.mk
address sanitizer requires `llvm-symbolize` binary to locate file:line, and it's located in `/usr/lib/llvm-4.0/bin`.
> add /usr/lib/llvm-4.0/bin to PATH to successfully run llvm-symbolize

- misc/clang-format-diff.sh
- misc/regen.mk
[clang-format-diff.py](https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py) makes our life easier by allowing us to re-format only changes. This requires clang-format-diff.py is installed in accessible path.
> add clang-format-diff make command

- include/h2o.h
- lib/handler/fastcgi.c
- lib/handler/file.c
- t/50file-custom-handler.t
As mentioned in https://github.com/h2o/h2o/issues/1630, index file name is missing from SCRIPT_NAME. This PR fixes it.
> append index file name to SCRIPT_NAME on dynamic request

- lib/handler/mruby.c
As discussed in https://github.com/h2o/h2o/issues/1552, when requiring `preloads.rb` failed with LoadError, current impl hides original exception message and only says `file "/h2o_root/share/h2o/mruby/preloads.rb" not found. Did you forget to run `make install`?`. But that makes harder to troubleshoot if nested require failed.
> better error message when preload failed

- CMakeLists.txt
- h2o.xcodeproj/project.pbxproj
- include/h2o.h
- include/h2o/http2_internal.h
- lib/core/logconf.c
- lib/core/util.c
- lib/handler/chunked.c
- lib/handler/configurator/server_timing.c
- lib/handler/server_timing.c
- lib/handler/status/durations.c
- lib/http1.c
- lib/http2/connection.c
- lib/http2/hpack.c
- lib/http2/stream.c
- src/main.c
- t/50server-timing.t
[Server Timing](https://www.w3.org/TR/server-timing/) allows the clients to get fine-grained performance metrics from the server. This PR only implement `total:dur=xxx` metrics as a trailer.
TODOs:
> implement Server Timing

- share/h2o/mruby/acl.rb
- share/h2o/mruby/dos_detector.rb
- share/h2o/mruby/preloads.rb
This fixes the issue Reported in https://github.com/h2o/h2o/issues/1660, by specifying relative paths
> specify relative paths required by preloads.rb and others

- include/h2o/balancer.h
- lib/tunnel.c
"h2o_balancer_t" type defined twice
"__builtin_expect" under clang
remove "inline"
> trivial changes

- lib/common/http1client.c
- t/50reverse-proxy-invalid-transfer-encoding.t
Fixes https://github.com/h2o/h2o/issues/1687: on_error_before_head can be called after setting `client->_do_keepalive` to 1. This is a long standing bug.
> fix abort when received invalid transfer-encoding header from upstream

- include/h2o/openssl_backport.h
Patch for #1706 
Needs https://github.com/h2o/picotls/pull/131 and https://github.com/h2o/neverbleed/pull/17 to work with LibreSSL 2.7.
> Add supporting LibreSSL 2.7

- lib/handler/mimemap.c
Unsurprisingly, we have plenty of formats encoded as JSON nowadays and some of them have `+json` media types. [ActivityPub](https://www.w3.org/TR/activitypub/), [GeoJSON](https://tools.ietf.org/html/rfc7946) and [JSON-LD](https://json-ld.org/spec/latest/json-ld/) are such examples.
> Mark `*/*+json` MIME types as compressible.

- fuzz/driver.cc
- include/h2o.h
- include/h2o/http2_internal.h
- include/h2o/socket/evloop.h
- include/h2o/socket/uv-binding.h
- lib/common/socket/evloop.c.h
- lib/core/context.c
- lib/core/request.c
- lib/core/util.c
- lib/http1.c
- lib/http2/stream.c
This PR adds `h2o_gettimeofday(h2o_loop_t *)` function. This function aims to decouple getting current timestamp (`struct timeval`) from h2o_context_t so that modules which don't have h2o_context_t (e.g. http1client) can get cached current timestamp too.
As a demerit of this approach, **timestamps are not cached at all if libuv is used**. But we don't address this issue at this point because we can expect VDSO in many environments. If the performance degrade becomes an actual problem in the future, we can introduce an extension point as a callback function to get cached timestamp.
> add h2o_gettimeofday

- examples/libh2o/redis-client.c
- h2o.xcodeproj/project.pbxproj
- include/h2o/hiredis_.h
- lib/common/redis.c
- lib/common/socket.c
- lib/core/util.c
- lib/handler/mruby/redis.c
- src/ssl.c
hiredis and openssl_hostname_validation have many value conversion (64-to-32) issues, which causes painful compiler warnings. This PR suppress that using diagnostic pragmas
> suppress value conversion warnings of third party libraries

- fuzz/driver.cc
This fixes a race between upstream_thread and sending a request.
It's possible that a request is injected via `created_accepted` before
the socket pair in `upstream_thread` is created.
If that request causes h2o to close the connection, and the socketpair
is created in the interm, it's possible that the socketpair gets the
same fd number as the closed request.
This means that the `is_valid_fd` test down the line doesn't fail,
resulting in a timeout.
This should address the issue reported by oss-fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8208
> fuzzer: fix init time race

- lib/handler/mruby.c
- t/50mruby.t
Fixes #1777 and #1779. This bug is happen when mruby handler returns 399  (fallthru) and then file handler serves the response.
https://github.com/h2o/h2o/pull/1495 forces lets mruby handler fill date header, but after that the file handler does it too.
> remove duplicate date headers

- lib/common/socketpool.c
Leased socket counting for targets becomes wrong when pooled sockets are reused or connection is cancelled, which would cause least connection load balancer not quite right. This PR fix those places.
> Fix leased socket counting in socketpool

- misc/generate_gitrev.pl
The `git` command succeeding is optional for the mechanism to work, don't make the error fatal.
> Don't die if the git command fails

- lib/handler/mruby/middleware.c
`struct sockaddr_in` also has a `sin_zero` member that needs to be
initialized
Coverity CID 1469824
> Fix uninitialized return

- examples/libh2o/latency-optimization.c
- examples/libh2o/simple.c
- examples/libh2o/websocket.c
Usages of  `SSL_CTX_use_certificate_file ` function in these examples were causing silent problems when used with fullchain PEM files of letsencrypt.
Because this function adds only the first certificate in the PEM file, root certificate is ignored and causing javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."... error when loaded with android devices.
Even note section on [openssl documentation](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_use_certificate.html) was indicating that '`SSL_CTX_use_certificate_chain_file` should be preferred'.
> Fix for ssl_setup function in some libh2o examples

- src/main.c
This reduces unneeded redirection from http:// to https://.
> Use https for the link to the document

- include/h2o.h
- include/h2o/socket/uv-binding.h
- lib/core/configurator.c
- lib/core/request.c
- lib/core/util.c
- srcdoc/configure/http2_directives.mt
- t/00unit/lib/core/util.c
- t/40server-push.t
This toggle allows H2O to push resources even if the authority doesn't
match the one in the pushed stream. It's up to the administrator to
determine whether this is a safe setting or not.
> http2-allow-cross-origin-push

- include/h2o.h
- lib/handler/chunked.c
- lib/handler/server_timing.c
- lib/http1.c
- lib/http2/connection.c
- lib/http2/stream.c
- t/50server-timing.t
Regarding https://github.com/h2o/h2o/pull/1790, I thought that the source of problem is rather chunked.c, not server-timing.c. I couldn't find any reasons to disable chunked encoding when the status is not 200, so this PR removes that behavior. Additionally I moved some code from chunked.c to http1.c.
@deweerdt Can this PR solve your issue?
> fix broken trailers issue

- include/h2o/socket/uv-binding.h
- lib/handler/access_log.c
This is useful for running H2O from within systemd as a worker (as
opposed to wrapped with start_server). In this case, /dev/stderr is a
unix socket to systemd-journal.
Minor tweak: silence warning in uv-binding about gettimeofday not being
defined.
> Add support for logging to unix sockets

- lib/http2/hpack.c
[RFC7540 8.1.2.3](https://tools.ietf.org/html/rfc7540#section-8.1.2.3) states:
`This pseudo-header field MUST NOT be empty for "http" or "https" URIs; "http" or "https" URIs that do not contain a path component MUST include a value of '/'.`
but currently h2o recognize empty `:path` as `/`.
> :path pseudo header field cannot be empty

- lib/http1.c
- t/50reverse-proxy-informational.t
- t/assets/upstream.psgi
When h2o receives continuous multiple informational responses from upstream, and handle those on one HTTP/1.1 keep-alive downstream connection, h2o may refer broken memory (used for prior request). If it happens it causes broken response, and may causes other problems.
This bug was introduced by h2o/h2o#1727. The cause of the bug is forgetting initializing st_h2o_http1_finalostream_t.
> fix broken memory problem on keepalived connection

- lib/common/memory.c
- lib/common/socket.c
- src/main.c
- srcdoc/configure/base_directives.mt
A revised PR that obsoletes #1757.
As requested, this PR:
* adds a new directive to the configuration file
* preserves the default threshold (32 MB) and behavior
* accepts `OFF` or a value of at least 1 MB
`OFF` disables the file-backed temporary buffers by setting the threshold to zero.  It requires an additional test, but in thhe cold path.
> Add global directive temp-buffer-threshold

- include/h2o.h
- lib/core/config.c
- lib/handler/status.c
- lib/handler/status/durations.c
- lib/handler/status/events.c
- lib/handler/status/requests.c
- src/main.c
- t/50status.t
This PR reimplements #1807 in a way that it does not cause issues when more than one globalconf is used.
Specifically, the deduplication logic is moved into `h2o_config_register_status_handler`, using the address of the handler as a tool to determine uniqueness.
> avoid redundant registration of status handlers

- include/h2o/socketpool.h
The `backtrace` family is only used in `src/main.c` and it already has a `#include <execinfo.h>` line, so it seems safe to remove it.
Fixes #1843
> Remove dependency to execinfo.h from socketpool.h.

- t/50internal-redirect.t
The race condition between the server emitting the log and the test script collecting them has sometimes resulted in CI failures like below (https://travis-ci.org/h2o/h2o/jobs/425131563).
This PR fixes the issue by killing the server (and waiting for it to terminate by calling `wait`) before collecting the logs.
```
t/50internal-redirect.t .............................. spawning plackup... Plack::Handler::Starlet: Accepting connections at http://0:35698/
done
spawning /home/ci/build/h2o... [INFO] raised RLIMIT_NOFILE to 1048576
h2o server (pid:12449) is ready to serve requests
done
not ok 1 - redirected internally[0m
killing /home/ci/build/h2o... received SIGTERM, gracefully shutting down
killed (got 0)
1..1[0m
[31mnot ok 1 - reproxy[0m
spawning /home/ci/build/h2o... [INFO] raised …
```
> wait for server to terminate before collecting the log lines

- t/50mruby.t
that errorneously refers to log before the server shuts down. see also #1411
> fix race condition in test

- lib/handler/proxy.c
fixes leak of socketpool registration.
> call unregister_loop when client_ctx is not built

- include/h2o/hiredis_.h
- lib/common/socket.c
- lib/common/url.c
- lib/http2/hpack.c
gcc7.3.0 dont recognize Wshorten-64-to-32.
Maybe it is better to add Macro to proect them, but I think we can just suppress Wpragmas.
In gcc7.3.0, PRIu16 is equal to 'u'. It is not accurate and it cause some print checking failed. For example, the buffer is shorter for int.
So just use 'hu', it is shorter and accurate.
In lib/http2/hpack.c , there is an assignment in assert.... It is a typo, I guess.
> Suppress GCC warnings

- lib/common/httpclient.c
Offending log (it is from a different branch and the function names are different):
```
h2o: /h2o/lib/http2/hpack.c:571: h2o_hpack_parse_response: Assertion `*status == 0' failed.
received fatal signal 6
[24819] /home/ci/build/h2o[0x4cac3e] on_sigfatal at /h2o/src/main.c:1497
[24819] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f38d5a15390] ?? ??:0
[24819] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f38d566f428] ?? ??:0
[24819] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f38d567102a] ?? ??:0
[24819] /lib/x86_64-linux-gnu/libc.so.6(+0x2dbd7)[0x7f38d5667bd7] ?? ??:0
[24819] /lib/x86_64-linux-gnu/libc.so.6(+0x2dc82)[0x7f38d5667c82] ?? ??:0
[24819] /home/ci/build/h2o[0x473895] h2o_hpack_parse_response at /h2o/lib/http2/hpack.c:571 (discriminator 1)
[24819] …
```
> zero-clear the memory used by http1/http2 client implementiation

- include/h2o.h
- include/h2o/http2.h
- include/h2o/httpclient.h
- include/h2o/redis.h
- include/h2o/socket.h
- include/h2o/url.h
- lib/common/httpclient.c
- lib/common/redis.c
- lib/common/socket.c
- lib/common/url.c
- lib/core/util.c
Rather than `const *`, because defining it as a pointer allows the value to be changed, which also has a negative effect on compile-time binding.
credit goes to @robguima.
> Non-numeric constants should be defined as `const []`

- include/h2o/socket.h
- lib/common/socket.c
- t/40ssl-cipher-suite.t
It has turned out that H2O has stopped sending TLS alerts upon handshake failure, when a recent version of OpenSSL is being used (the issue known to happen in 1.1.0g, but not in 1.1.0d). See 
https://github.com/h2o/h2o/pull/1865#issuecomment-428455419 for how it happens.
This PR brushes up the fix proposed in #1865 as well as adding a test.
> send TLS alert on handshake failure when recent versions of OpenSSL is used

- lib/common/http2client.c
I found SEGV that says `conn->super.link` is already unlinked, that happens when `enqueue_goaway` is called before the connection is closed.
It was easy to reproduce the bug by running test`t/50reverse-proxy-http2.t`, so I'm not sure when this bug emerged, but if necessary I'll do git bisect.
> do nothing in `adjust_conn_linkedlist` if conn is already unlinked

- include/h2o.h
- lib/core/config.c
- lib/core/context.c
- lib/core/request.c
- lib/handler/mruby/middleware.c
- lib/handler/status/durations.c
- t/50mruby-middleware.t
Currently `H2O.next` has a problem that filters and prefilters will be applied to the response multiple times, that is:
```
/:
- mruby-handler: proc {|env| H2O.next.call(env) }
- file.dir: /path/to/doc_root
- header.add: "x-foo: FOO"
```
responds `x-foo: FOO` 2 times. This PR addresses that issue.
> stop applying filters multiple times

- .travis.yml
- misc/docker-ci/Dockerfile
- misc/docker-ci/check.mk
This PR adds a build that tests openssl 1.1.0 (the other two builds are using openssl 1.0.2). Merging this PR does require a change to the docker image used for CI, I pushed a temporary image for testing to `deweerdt/h2o-ci:latest`.
Link to a passing CI build: https://travis-ci.org/deweerdt/h2o/jobs/443577367
Link to the docker image change used for testing: https://github.com/deweerdt/h2o/commit/d30f0c5c
> Add a CI build for openssl 1.1.0

- t/Util.pm
It's a bother thing to use debuggers with our e2e tests. This change mitigates that by allowing us to do the following:
```perl
my $server = spawn_h2o(...);
wait_debugger($server->{pid});
do_your_test_stuff_and_breakpoints_work_well_woo_hoo();
```
Actually this changes my h2o debugging life!
> add wait_debugger helper function

- lib/http2/connection.c
This might happen if a link is being pushed in a reverse proxying
environment: proxy.c would be handling HTTP/1 headers when the HTTP/2
side of the connection has been set to `H2O_HTTP2_CONN_STATE_IS_CLOSING`
> Don't push a path if a connection is closing.

- lib/common/socket/uv-binding.c.h
if you use libuv, `h2o_timer` never gets fired unless you wait 18 days.. lol
> pass proper timeout value to uv_timer_start

- misc/docker-ci/check.mk
passing the travis environment variable to docker and then sudo allows, if needed, to skip certain tests when ran on travis
> pass travis flag to docker and sudo

- CMakeLists.txt
based on https://www.virag.si/2015/07/use-ccache-with-cmake-for-faster-compilation/
to faster rebuild from scratch `ccache` can really improve build times
https://ccache.samba.org/
> enables support of ccache

- include/h2o/multithread.h
This PR remove 'h2o_multithread_send_request()' and related types.
> 'h2o_multithread_send_request()' is not used, so remove it

- lib/http2/connection.c
This fixes an issue seen when 'server-timing: enforced' is set in the
configuration: proceed would set the write callback, and we'd hit the
assert in `do_emit_writereq()` checking that `buf_in_flight` is NULL:
```
h2o: lib/http2/connection.c:1229: do_emit_writereq: Assertion `conn->_write.buf_in_flight == NULL' failed.
```
> Don't call `h2o_http2_conn_request_write` from `emit_writereq_of_openref`

- .gitignore
- lib/handler/mruby/middleware.c
Fix an invalid read in `convert_env_to_header_name (middleware.c:140)`.
```
==77960== Invalid read of size 1
==77960==    at 0x204630: convert_env_to_header_name (middleware.c:140)
==77960==    by 0x204630: handle_header_env_key (middleware.c:406)
==77960==    by 0x2002B7: h2o_mruby_iterate_header_values (mruby.c:1151)
==77960==    by 0x2056DD: create_subreq (middleware.c:598)
==77960==    by 0x2056DD: middleware_request_method (middleware.c:791)
... snip ...
```
We forward the `name` pointer by `KEY_PREFIX_LEN` and loop from there to copy byte-by-byte into the newly created `h2o_iovec_t`. The issue is that `len` remains the length of the string with `HTTP_` prefix.
Subtract `len` by `KEY_PREFIX_LEN` so that we don't over iterate. The case of `len < KEY_PREFIX_LEN` is handled earlier in …
> Fix an invalid memory access by an mruby middleware

- lib/http1.c
```
/lib/http1.c:887:27: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:43:28: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /lib/http1.c:887:27
```
> [minor] Fix UBSAN warning in lib/http1.c

- include/h2o/openssl_backport.h
Latest AOSP code base using boring ssl, this PR make libh2o can be built under AOSP Android O based on boring ssl
> fix build error under android o for boringssl

- lib/common/socket/uv-binding.c.h
'Unlink' the timer before calling the timer callback
> libuv timer fix

- include/h2o/httpclient.h
- lib/common/http1client.c
- lib/common/http2client.c
- lib/common/httpclient.c
This is an API we added to the Fastly fork that we'd like to contribute back to the H2O community.
- Add an API to `h2o_httpclient_t` for obtaining the underlying network socket
Thanks!
> Add an API to get the underlying socket from an httpclient

- include/h2o/hostinfo.h
- lib/common/hostinfo.c
This PR remove `h2o__hostinfo_getaddr_dispatch` from public header file and rename it with a static version
> rename 'h2o__hostinfo_getaddr_dispatch()' and make it static

- lib/http2/connection.c
We've seen the following assert trigger:
```
h2o[0x448ce1] update_stream_output_window at h2o/lib/http2/connection.c:312
h2o[0x44b256] handle_window_update_frame at h2o/lib/http2/connection.c:699
h2o[0x4489c0] expect_default at h2o/lib/http2/connection.c:799
h2o[0x44a761] parse_input at h2o/lib/http2/connection.c:834
h2o[0x423922] run_socket at h2o/lib/common/socket/evloop.c.h:536
h2o[0x423a85] run_socket at h2o/lib/common/socket/evloop.c.h:508
h2o(h2o_evloop_run+0x29)[0x4244b9] h2o_evloop_run at h2o-fastly/lib/common/socket/evloop.c.h:568
h2o[0x4a01a9] run_loop at h2o/src/main.c:1364
```
This is a regression introduced here: https://github.com/h2o/h2o/pull/1040.
Kazuho hypothesized that this is happening:
> * emit_writereq_of_openref calls h2o_http2_stream_send_pending_data
>  * within …
> Fix failed assertion in update_stream_output_window

- deps/picohttpparser/.gitignore
- deps/picohttpparser/picohttpparser.c
- deps/picohttpparser/test.c
- lib/common/http1client.c
- lib/http1.c
- t/40bad-request.t
- t/50mruby.t
- t/50reverse-proxy-multiline-header.t
This PR intends to add the following three changes:
- remove trailing whitespaces from header value (https://github.com/h2o/picohttpparser/pull/45)
- reject the requests like the following with 400 (https://github.com/h2o/picohttpparser/pull/46)
- no path (e.g. `GET  HTTP/1.1\r\n\r\n`)
- no method (e.g. ` / HTTP/1.1\r\n\r\n`)
- reject the requests that has multiline header with 400
> update picohttpparser and reject multiline headers

- include/h2o/httpclient.h
- lib/common/http1client.c
- lib/common/http2client.c
This PR add `const` for for httpclient1|2 struct size global variable prototype and definition.
> add 'const' for httpclient1|2 struct size global variable

- doc/install.html
- srcdoc/install.mt
Hi folks,
I realized today that the `WITH_BUNDLED_SSL` CMake option is no longer supported (since: a2da6caf9b6b829eb88048ddd372321450d9ce34). It's not the end of the world because CMake will only emit a warning:
```
CMake Warning:
Manually-specified variables were not used by the project:
WITH_BUNDLED_SSL
```
That said, I think the documentation deserves some grooming, especially for new users. Thanks!
> doc: remove mentions of WITH_BUNDLED_SSL

- lib/http1.c
From RFC7230 5.3.2.  absolute-form:
>  To allow for transition to the absolute-form for all requests in some
>  future version of HTTP, a server MUST accept the absolute-form in
>  requests, even though HTTP/1.1 clients will only send them in
>  requests to proxies.
> HTTP/1: handle the absolute url form

- include/h2o/httpclient.h
- lib/common/http1client.c
- lib/common/http2client.c
This PR try using `h2o_socket_is_reading` and `h2o_socket_is_writing` instead of `sock->_cb` directly for http client.
> use predifined function 'h2o_socket_is_reading|writing'

- lib/common/http2client.c
This is helpful in case the on_connect callback is interested in
examining the connection in question.
> [http2 client] Make sure the connection is registered with the stream before calling on_connect

- examples/libh2o/httpclient.c
Or else, on_body only called back once.
BTW, I'm not sure this should be fixed in http1client.c in `do_update_window`:
if ((*client->super.buf)->size >= client->super.ctx->max_buffer_size) {  // need judge  max_buffer_size > 0 or '>' instead of '>=' ?
> example: 'max_buffer_size' should NOT be 0 for http client context

- include/h2o.h
- lib/core/proxy.c
- lib/handler/configurator/proxy.c
- t/50proxy-forward-close-connection.t
Add an optional H1-specific behavior that enables H2O to forward the `Connection: close` response header from upstream. This behavior is triggered by the new `proxy.forward.close-connection` setting.
This contribution is based on our learning that some applications appreciate this behavior, whether it's for draining or ensuring that their clients start a fresh new connection.
> Optional H1 behavior to forward connection closure

- lib/handler/mimemap.c
We already cover most of the possible mime types for XML with ``MIME_STARTS_WITH("text/")`` and ``MIME_ENDS_WITH("+xml")``. But ``application/xml``, which is a common and correct mime type for XML, too, is still missing.
> Add application/xml to the is_compressible mime types

- lib/handler/mruby/middleware.c
`*((struct sockaddr_storage *)&sin);` would cause a read that's larger
than `sin`, reaching to other parts of the stack. We fix this with a
memcpy that only reads `sizeof(sin);` bytes.
> [mruby/middleware.c] Fix invalid read on the stack

- src/main.c
This PR introduces a `num-quic-threads` option, which can be used to limit the number of threads that will do QUIC processing. This is a way for deployments to progressively switch to QUIC while mitigating the CPU impact in might have on a given node.
> Restrict the CPUs running QUIC to a subset

- include/h2o/memory.h
- lib/common/hostinfo.c
- lib/common/http2client.c
- lib/common/memcached.c
- lib/common/memory.c
- lib/common/multithread.c
- lib/common/serverutil.c
- lib/common/socket.c
- lib/common/socket/evloop/epoll.c.h
- lib/common/socket/evloop/kqueue.c.h
- lib/common/socket/evloop/poll.c.h
- lib/common/socketpool.c
- lib/common/timerwheel.c
- lib/common/url.c
- lib/core/configurator.c
- lib/core/request.c
- lib/core/util.c
- lib/handler/access_log.c
- lib/handler/configurator/fastcgi.c
- lib/handler/configurator/mruby.c
- lib/handler/configurator/proxy.c
- lib/handler/file.c
- lib/handler/mruby.c
- lib/handler/mruby/http_request.c
- lib/handler/mruby/middleware.c
- lib/handler/status/requests.c
- lib/http2/connection.c
According to Issues #2006 
The fix focus on `lib` directory in the source tree.
Library uses can define this macro to something else to use their log function.
> add 'H2O_ERROR_PRINTF' macro, default is 'fprintf(stderr,...)'

- include/h2o/memory.h
- lib/common/memory.c
The GNU-specific strerror_r() returns a pointer to a string containing the error message.  This may be either a pointer to a string that the function stores in  buf,  or  a  pointer  to  some(immutable)  static string (in which case buf is unused).
`h2o_perror` should handle this case.
> fix issue in 'h2o_perror' about 'strerror_r'

- include/h2o/memory.h
- lib/common/hostinfo.c
- lib/common/memcached.c
- lib/common/memory.c
- lib/common/multithread.c
- lib/common/socket/evloop/epoll.c.h
- lib/common/timerwheel.c
- lib/core/configurator.c
- lib/handler/configurator/mruby.c
- lib/handler/file.c
- lib/handler/mruby.c
- lib/handler/mruby/http_request.c
"Note that the pthreads functions do not set errno" from PTHREADS(7)
so we should use return value instead of 'errno' when pthread_create error
> fix prototype for 'h2o_fatal' and replace 'abort(3)' with it

- t/00prop/prop.c
Due to an early return, one check (and the destruction of the timerwheel) has always been skipped. The issue was introduced in b78de0a4.
> activate error check in proptest

- t/40chunked.t
this might explain https://github.com/h2o/h2o/issues/2028 : most of the
time we should see a number between 1 and 2, but timing issues might
result in a larger hex number, causing the test to fail
> [test] 40chunked.t: convert the length of the chunk from hexadecimal

- CMakeLists.txt
- misc/cli2man.pl
- srcdoc/install.mt
minor changes
- fix the url for port status as it's defunct since months
- mention the additional beta port link maybe this could go somewhere else?
Also, I'm unable to generate the docs locally using the instructions in source, to check my changes. I'll commit a fix if somebody can clarify how that works today. Here's what I'm trying on FreeBSD:
```
git clone ...
cd h2o
git submodule update --recursive
mkdir _build
cd _build
cmake ..  -DCMAKE_INSTALL_PREFIX:PATH=/tmp/usr/local
...
[100%] Linking C executable h2o
[100%] Built target h2o
Scanning dependencies of target doc
mkdir -p doc/configure
../misc/oktavia/bin/oktavia-mkindex  -m html -u h2 -c 10 -t js -s english
Search Engine Oktavia - Index Generator
usage: oktavia_mkindex [options]
Common Options:
-i, --input [input folder/file ] : …
```
> clean up buildchain linuxisms & update FreeBSD URLs

- doc/configure/fastcgi_directives.html
- doc/configure/file_directives.html
- srcdoc/configure/fastcgi_directives.mt
- srcdoc/configure/file_directives.mt
It took me a while to find out about the `default` value for the `extension` property of the `file-custom-handler`. That's why I added some relevant documentation.
> Improve documentation about extension property

- include/h2o/socket/evloop.h
- include/h2o/socket/uv-binding.h
- lib/common/socket/evloop.c.h
- lib/common/socket/evloop/epoll.c.h
- lib/common/socket/evloop/kqueue.c.h
- lib/common/socket/evloop/poll.c.h
To gain better insight into the event loop latency. Nanosecond granularity will be useful.
- Add a `now_ns` member to `h2o_evloop_t`, alongside the existing `now`
- Calculate `now_ns` first, and then derive `now`
- ~For [libuv](https://github.com/libuv/libuv), simply call the [uv_hrtime](http://docs.libuv.org/en/v1.x/misc.html#c.uv_hrtime) function as suggested in their documentation~
Rename `now` to `now_ms` for clarity at a glance.
> Add an h2o_now_nanosec() func to the Event Loop API

- include/h2o/socket.h
- lib/common/socket.c
It looks like there is currently no way to retrieve the TLS Server Name Indication value sent by the client, if any, from the existing libh2o API. This new function provides access to this value when it is present.
> socket: Add h2o_socket_get_ssl_server_name()

- include/h2o/memory.h
- lib/common/memory.c
- lib/handler/status/events.c
Maintain a count of mmap failures, and make it accessible through the H2O Status API.
Declare a global `size_t` and operate on it using the `__sync_add_and_fetch` atomic built-in function. Code is added to a hot function but given that the error is rare, there should be no performance impact.
Native Response:
```
$ curl -s localhost:8080/status/json | grep mmap
"memory.mmap_errors": 0
```
Prometheus Response [via mruby](https://github.com/h2o/h2o/pull/1892):
```
$ curl -s localhost:8080/metrics | grep mmap
h2o_memory_mmap_errors{version="2.3.0-DEV@3aa238b1"} 0
```
> Keep track of mmap failures

- include/h2o/http2_common.h
- include/h2o/memory.h
- lib/common/memory.c
- lib/common/socket.c
- lib/common/socket/evloop.c.h
- lib/common/socket/uv-binding.c.h
- lib/handler/fastcgi.c
- lib/handler/file.c
- lib/handler/file/templates.c.h
- lib/handler/mruby/sender.c
- lib/handler/status/requests.c
- lib/http1.c
- lib/http2/connection.c
Ensure that unbounded memory allocation failures (e.g. buffers in non-streaming code path) are checked and handled peacefully. For bounded amount of memory allocations (e.g. low layer frame handling), abort with information of the underlying h2o_buffer_t, and the allocation amount.
- Add a variant of `h2o_buffer_reserve` that is forgiving on mmap failure
- Add a variant of `h2o_buffer_append` that is forgiving on mmap failure
- `h2o_buffer_(reserve|append)` to abort on mmap failure
Replace unbounded `h2o_buffer_(reserve|append)` calls with its forgiving variant, check the allocation result, and handle accordingly.
> Split up the buffer reservation API

- lib/common/http1client.c
It's possible that upstream says 'keep-alive', but that we're not
interested in keeping the sockets in a pool
> Don't store the socket in the socket pool if the timeout is zero

- include/h2o/multithread.h
- lib/common/socket.c
My affection to using closures instead of declaring callbacks (and global variables) is strong enough to define a replacement for `pthread_once` function that takes a closure as an argument.
Actually, this PR fixes theoretical race conditions in some of the initialization code that we run. 9c06f68 addresses two cases where an "index" might be used by a different thread, before the objects that are being referred to by that "index" is being written to memory.
> implement our own "once" function

- lib/common/http1client.c
- t/80reverse-proxy-truncated-chunked.t
Before this PR, H2O would send an empty body to the client, if upstream
sent chunked response headers but no response body. This fixes it by
checking that we've at least received one byte when deciding whether to
treat connection close as an error or not
Credit to @robguima for the finding and analysis
> [proxy] Forward broken chunk encoding upstream responses

- .travis.yml
- include/h2o/socket.h
- lib/common/socket.c
- lib/handler/configurator/proxy.c
- misc/docker-ci/Dockerfile
- misc/docker-ci/check.mk
- src/main.c
- src/ssl.c
hi, this PR enables ossl-1.1.1 session cache resumption support by moving from the get1 session api to the the new_session callback. Also sets the session cache context and the explicit client session behavior when creating new ossl CTXs (proxy).
this should make `t/50reverse-proxy-session-resumption.t` happy when linking against openssl-1.1.0 and openssl1.1.1
Note that Dockerfile has changed and the CI image will need an update to install openssl-1.1.1c in `/opt/openssl-1.1.1`
> add support for openssl1.1.1 session cache resumption
