CMakeLists.txt, h2o.xcodeproj/project.pbxproj, include/h2o/http2.h, include/h2o/http2/scheduler.h, lib/http2/connection.c, lib/http2/frame.c, lib/http2/scheduler.c, lib/http2/stream.c, t/00unit/lib/http2/scheduler.c, t/00unit/test.c, t/00unit/test.h, t/50reverse-proxy.t
Let's support dependency-based prirotization based on draft 16, now supported by Firefox.
refs:
- https://github.com/h2o/h2o/issues/50#issuecomment-68221693
- https://bugzilla.mozilla.org/show_bug.cgi?id=1003450
- http://bitsup.blogspot.se/2015/01/http2-dependency-priorities-in-firefox.html
=> Support draft 16 (w. dependency)

include/h2o.h, lib/core/request.c, lib/handler/file.c, t/00unit/lib/handler/file.c
First try to implement issue #78.
=> Added support for HEAD-requests to the file handler

CMakeLists.txt, h2o.xcodeproj/project.pbxproj, include/h2o.h, include/h2o/url.h, lib/common/url.c, lib/core/request.c, lib/handler/configurator/redirect.c, lib/handler/file.c, lib/handler/redirect.c, src/main.c, t/00unit/lib/common/url.c, t/50redirect.t
Implements a redirect handler with configuration directive `redirect` (fixes #146).
=> redirect handler

lib/core/request.c, lib/handler/access_log.c, lib/http1.c, t/50access-log.t
support logging `%H`, `%m` ,`%q` ,`%U` ,`%V`, `%v`, and refactors
relates to #36
=> support logging %H, %m ,%q ,%U ,%V, %v

examples/libh2o/simple.c, examples/libh2o/websocket.c, h2o.xcodeproj/project.pbxproj, include/h2o.h, include/h2o/http1.h, include/h2o/http2.h, include/h2o/memory.h, include/h2o/socket.h, lib/common/memory.c, lib/core/config.c, lib/core/configurator.c, lib/core/context.c, lib/core/request.c, lib/core/util.c, lib/http1.c, lib/http2/connection.c, src/main.c, t/00unit/lib/handler/file.c, t/00unit/test.c, t/00unit/test.h, t/40virtual-host.t, t/Util.pm
=> connections accepted by host-level listeners should not be handled by the handlers associated to other hosts

src/main.c
=> add configuration directive `pid-file`

README.md, lib/http1.c, lib/http2/connection.c
https://www.mnot.net/blog/2015/02/18/http2
=> support the finalized version of HTTP/2

src/main.c
The pipe-based IPC (introduced in #154) initializes all the pipes on the main thread.  However, since h2o_socket_t::input is initialized with reference to `h2o_socket_buffer_prototype` which is a TLS value, race condition bug (leading to random crash) arise once the pipes are used within the worker threads.
The PR fixes the issue by moving the initialization code to each thread.
=> fix crash in recycling allocator (amends #154)

examples/libh2o/simple.c
fixes https://github.com/h2o/h2o/issues/173#issuecomment-75218062
=> adjust the server example following the updates to the evloop interface

lib/http2/hpack.c, t/00unit/lib/http2/hpack.c, t/50reverse-proxy.t, t/assets/upstream.psgi
=> fix HPACK compressor output in case header is longer than 126 bytes

include/h2o.h, lib/core/proxy.c, lib/core/request.c, lib/handler/configurator/proxy.c, t/50reverse-proxy.t
=> amendments for #197

t/assets/upstream.psgi
t/50reverse-proxy.t frequently fails on my FreeBSD instance running on VMWare Fusion 7 with 1GB of RAM allocated.
The PR fixes the issue by using file-backed buffer to storing data to be echoed back (the size of the data is 50MB in case of tests).
relates to #211
=> fix test error on resource-constrained environments

src/main.c
Adjust the source code so that it could be linked to boringssl without modification.
note: follow the steps below to create the standalone server linked to  boringssl.
1. build boringssl
2. create a fake directory that simulates an OpenSSL directory structure, (the `include` directory should point to `boringssl/inculed`, and `lib` should contain links to `libcrypto.a` and `libssl.a`)
3. set enviroment variable `CMAKE_PREFIX_PATH` to the directory structure created by the step above
4. run cmake in a clean directory
5. run make
=> BoringSSL compatibility

src/main.c
Adds `cipher-preference` option for choosing the cipher list of which side should be used for selecting the cipher suite (default is `client`).
relates to #230
=> add directive for selecting the preferred side of cipher lists

doc/configure.html, doc/configure/command_options.html, doc/configure/quick_start.html, doc/configure/syntax_and_structure.html, doc/faq.html, doc/index.html, doc/install.html, srcdoc/snippets/wrapper.mt
I suppose `index.html` is better than `./` for using the document as offline document.
Because browser(Google Chrome, Firefox etc) shows list of files in the directory for the paths which ends with slash.
=> Better links for using as offline document

CMakeLists.txt, h2o.xcodeproj/project.pbxproj, lib/core/request.c, t/00unit/lib/handler/redirect.c, t/00unit/test.c, t/00unit/test.h
=> When redirecting do not send BODY if method is `HEAD`

lib/common/socket.c
I tried h2o and found it really fast and stable. But I found that the result of ALPN is h2-14 (on Chrome 43) or h2-16 (on Firefox 38.0.1), though they both support h2. I found this is because the original ALPN selector selects the protocol based on the order of protocols `Client Hello` provided. So I did some modification on the code so ALPN selection priority is based on the order of protocol args provided.
P.S. I know this change is too simple and maybe this small "issue" is ignored intentionally due to performance. I just really want to try to make my first pull request. Thanks :-P
=> Modified ALPN selector for h2 selecting.

CMakeLists.txt, examples/libh2o/http1client.c, h2o.xcodeproj/project.pbxproj, include/h2o.h, include/h2o/socket.h, include/h2o/socketpool.h, include/h2o/string_.h, lib/common/socket.c, lib/common/socket/evloop.c.h, lib/common/socketpool.c, lib/core/util.c, lib/handler/access_log.c, lib/handler/configurator/fastcgi.c, lib/handler/fastcgi.c, lib/handler/proxy.c, src/main.c, t/00unit/lib/handler/fastcgi.c, t/00unit/test.c, t/00unit/test.h, t/50fastcgi.t, t/Util.pm
(still wip)
The PR implements fastcgi handler.  The PR attempts to support fastcgi external servers / will not support spawning fastcgi servers by itself.
=> support FastCGI

lib/handler/configurator/fastcgi.c
Version 1.3 installs helper script named `share/h2o/kill-on-close`, and uses it to launch fastcgi process manager when `fastcgi.spawn` directive is used.
Unfortunately the code has two issues:
* the path is not resolved like other helper scripts
* the server does not report an error if it fails to launch the helper script
This PR fixes the two issues.
=> determine the path of `kill-on-close`, report error if failed to spawn the program

lib/handler/configurator/fastcgi.c, lib/http2/connection.c, lib/http2/frame.c, srcdoc/configure/file_directives.mt
Simple typo fix I noticed while configuring.
=> Fixing typo invaild -> invalid

include/h2o/multithread.h, lib/common/multithread.c, src/main.c
Added the check for the return-value of `pthread_create()`.
=> improved error handling for pthread_create().

lib/handler/mruby.c
Sorry, I forgot to modify test word.
=> Fix incorrect word

include/h2o.h
I implemented per-module filter context setter function.
=> Add per-module filter context setter function

lib/handler/mruby.c
I forgot to collect the `result` object as garbage after `h2o_send_error(req, 200, "OK", mrb_str_to_cstr(mrb, result), 0)`.
=> [h2o_mruby] Fix memory leak by `result` object

src/main.c
h2o_setuidgid(nobody) should be called (as warned), when invoked as root and if `user` directive is not used.
=> drop privileges (as warned) when run as root and if `user` directive is not used

include/h2o.h, lib/core/proxy.c, lib/core/request.c, lib/core/util.c, lib/handler/fastcgi.c, t/00unit/lib/core/proxy.c, t/00unit/lib/core/util.c, t/50fastcgi-php.t, t/assets/doc_root/hello.php
Support server-push in FastCGI handler as well.
* need to add tests
* moves the necessary logic from proxy.c to core
relates to #438
=> server-push support in fastcgi

lib/http2/hpack.c, t/00unit/lib/http2/hpack.c
Until now the HPACK encoder has not been utilising the static table entries with values for compressing request headers (e.g. `accept-encoding: gzip, deflate` was not compressed to single octet for the _first_ request; note that the use of dynamic table was compressing the header in following requests), and the fact was causing unnecessary bloat of `PUSH_PROMISE` frames.
This is practically not an issue, but we fix it anyways.
=> improve compression ratio of `PUSH_PROMISE` frames

srcdoc/configure/proxy_directives.mt
Please modify text as you like (just a drafting text).
=> Add note about multiple IPs for proxy setting.

include/h2o/mruby_.h, lib/handler/configurator/mruby.c, lib/handler/mruby.c, t/50mruby.t, t/50mruby/authority.rb, t/50mruby/headers_in.rb, t/50mruby/headers_out.rb, t/50mruby/hostname.rb, t/50mruby/max_header.rb, t/50mruby/method.rb, t/50mruby/query.rb, t/50mruby/remote_ip.rb, t/50mruby/return_declined.rb, t/50mruby/return_status.rb, t/50mruby/reverse_proxy.rb, t/50mruby/uri.rb
Would be nice to have such thing, since it makes us easier to make small modifications to the request handling using mruby.
=> in-line configuration directive to define mruby handlers

lib/handler/mruby/class/request.c, t/50mruby.t
The PR exposes `http2_server_push` property of the request object so that mruby can push things to the clients.
At the moment, only the `<<` operator is implemented.  We need to implement other operators (and methods) so that the property would behave like an ruby array.  The question is how it should be done.
relates to #421 #438.
=> expose server-push interface to mruby

lib/http2/connection.c, lib/http2/stream.c
=> do not push contents when client has requested not to

include/h2o/mruby_.h, lib/core/request.c, lib/handler/mruby.c, lib/handler/mruby/class/core.c, lib/handler/mruby/class/request.c, lib/handler/mruby/init.c, t/50mruby.t
WIP.  This PR includes bunch of improvements to the mruby handler to cover various pending issues.
=> resolve issues using mruby

lib/handler/file/_templates.c.h, lib/handler/file/templates.c.h
=> sort files in directory listing

examples/h2o_mruby/h2o.conf, examples/h2o_mruby/hello.rb, t/50mruby/hello.rb
cf. https://github.com/h2o/h2o/pull/467
=> rename mruby.handler_path -> mruby.handler-file

lib/handler/redirect.c, lib/handler/reproxy.c, t/50mruby.t
=> reproxy handler should preserve method if status is 307 or 308

lib/core/config.c, lib/handler/mimemap.c, t/00unit/lib/handler/mimemap.c
=> initialize mimemap of custom handler

lib/handler/file/_templates.c.h, lib/handler/file/templates.c.h
=> correctly sort directory listing

lib/http2/scheduler.c
Weight 257 is internally used by the server to mark streams that should be sent before any other streams with lower priority.
However since streams with weight equal to or above 64 may go into the first slot of the 64-level priority array, it has often been the case that the streams with weight 257 were sent interleaved with streams with lower weights.
This PR fixes the issue, by creating and using a dedicated slot for streams with weight 257.
=> always send 257 before any other stream with lower priority

lib/core/request.c
> Is it possible to also use Connection: keep-alive in 30x redirects (so that we can theoretically save one round-trip)?
https://github.com/h2o/h2o/issues/538#issuecomment-147081996
This PR modifies `h2o_send_redirect` function so that it would set the value of `content-length` header.  Without the value being set, the connection will be closed (for both HTTP/1.0 and HTTP/1.1, since the chunked output filter does not modify 30x responses).
=> preserve HTTP1 connection after redirect

CMakeLists.txt, share/h2o/setuidgid
fixes #537 the other way round :-)
=> reimplement setuidgid in perl

CMakeLists.txt
Just changed all `${CMAKE_SOURCE_DIR}` and `${CMAKE_BINARY_DIR}` to `${CMAKE_CURRENT_SOURCE_DIR}` and `${CMAKE_CURRENT_BINARY_DIR}`.
=> Update CMakeLists.txt to fix problem when h2o added as a subdirectory

include/h2o.h, include/h2o/string_.h, lib/common/string.c, lib/handler/file.c, lib/handler/mimemap.c, t/00unit/lib/common/string.c, t/00unit/lib/handler/mimemap.c
=> convert extension to lowercase before looking up the mime type

lib/handler/file/_templates.c.h, lib/handler/file/templates.c.h
=> uri_escape the filenames in `<a href>`

include/h2o/string_.h, lib/common/string.c, lib/common/url.c, lib/handler/file.c, lib/handler/file/_templates.c.h, lib/handler/file/templates.c.h, t/00unit/lib/common/url.c
=> decode url-encoded character at the end of path

.travis.yml, h2o.xcodeproj/project.pbxproj, include/h2o/http2_internal.h, lib/http2/connection.c, lib/http2/hpack.c, lib/http2/stream.c, t/40server-push.t, t/50fastcgi-php.t, t/50mruby.t, t/80issues579.t, t/80issues595.t
=> fix issues reported by h2spec 1.2.0

lib/common/socket/evloop/epoll.c.h
The epoll backend of H2O has relied on an incorrect assumption that:
* only the events specified by epoll_ctl are returned by epoll_wait
* if epoll_event::events is 0 (zero), then events will be never reported
However the fact is that the man page of epoll_wait says:
>```
>EPOLLERR
>        Error  condition  happened  on  the  associated file descriptor.
>        epoll_wait(2) will always wait for this event; it is not  neces‐
>        sary to set it in events.
>
>  EPOLLHUP
>        Hang   up   happened   on   the   associated   file  descriptor.
>        epoll_wait(2) will always wait for this event; it is not  neces‐
>        sary to set it in events.
>```
This PR address the flaw.
=> fix busy loop calling epoll_wait

CMakeLists.txt, h2o.xcodeproj/project.pbxproj, include/h2o.h, lib/core/proxy.c, lib/core/request.c, lib/handler/chunked.c, lib/handler/configurator/errordoc.c, lib/handler/errordoc.c, lib/handler/expires.c, lib/handler/gzip.c, lib/handler/headers.c, lib/handler/reproxy.c, src/main.c, t/50errordoc.t, t/assets/doc_root/404.html, t/assets/doc_root/subdir/index.txt
=> customized error pages

lib/handler/mruby.c
=> expose H2O_ROOT to mruby as well

include/h2o/mruby_.h, lib/handler/mruby.c, lib/handler/mruby/chunked.c, lib/handler/mruby/http_request.c
Code cleanups and bug fixes.
part of #643
=> mruby fiber cleanups

lib/handler/mruby.c, lib/handler/mruby/http_request.c, t/50mruby-http-request.t
=> adjust request header handling, add tests

lib/common/serverutil.c, src/main.c
In #618 (specifically commit d91c934), OCSP updater thread has started to access `environ` during its boot-up phase.  However at the same time main thread is trying to unset `SERVER_STARTER_PORT` environment variable.
This issue has caused a race condition issue that is easy to be observed on FreeBSD.
=> fix race condition in environ access

lib/handler/mruby/chunked.c, t/50mruby.t
fixes regression in #645, part of #643
=> `body#close` must be called

lib/core/config.c
=> destroy mimemap on global dispose

.travis.yml
https://github.com/joyent/libuv -> https://github.com/libuv/libuv
=> Change a archive URI of the libuv

lib/core/request.c, lib/handler/file.c
Proposed fix for #688.
Let me know anything I can to improve this patch.
=> Fix missing query component on directory related redirect

lib/common/string.c
=> use uppercase letters for `%XX`

lib/handler/mruby.c
fixes #705, turned out to be a regression in #667.
=> fix wrong type designation in qsort callback

include/h2o.h, lib/core/request.c, lib/handler/mruby.c, t/50mruby-http-request.t
=> support 399 response from mruby handler running async

include/h2o.h, lib/core/request.c, lib/handler/mimemap.c, t/00unit/lib/handler/mimemap.c, t/50mimemap.t
=> update mimemap configuration unless an exact map already exists

include/h2o/memory.h, lib/common/serverutil.c, lib/common/socket.c, lib/core/config.c, lib/core/configurator.c, lib/core/context.c, lib/core/headers.c, lib/core/request.c, lib/handler/configurator/access_log.c, lib/handler/configurator/errordoc.c, lib/handler/configurator/headers.c, lib/handler/errordoc.c, lib/handler/fastcgi.c, lib/handler/file.c, lib/handler/file/_templates.c.h, lib/handler/file/templates.c.h, lib/handler/gzip.c, lib/http1.c, lib/http2/casper.c, lib/http2/stream.c, src/main.c, src/ssl.c, t/00unit/src/ssl.c
=> simplify vector operations

lib/http2/hpack.c
=> fix promised_stream_id >= 256 misencoded

CMakeLists.txt, libh2o-evloop.pc.in, libh2o.pc.in
Fixes https://github.com/h2o/h2o/issues/396.
=> Provide pkg-config .pc files.

lib/common/socket/evloop/poll.c.h
reported in https://github.com/h2o/h2o/pull/777#issuecomment-183845950
=> fix memory leak in poll backend

lib/handler/fastcgi.c
reported in https://github.com/h2o/h2o/issues/762#issuecomment-184764138
=> fix off-by-one buffer overflow

CMakeLists.txt
It seems to have forgotten to change the installation settings.
=> fix installing `fastcgi-cgi` script

include/h2o/filecache.h, lib/common/filecache.c
=> retain open error in file descriptor cache

lib/handler/compress/brotli.cc
#848 was affected by this bug.
=> [brotli] fix SEGV while trying to encode multiple vectors

CMakeLists.txt
Install example files into $PREFIX/share/doc/h2o/examples directory
=> Install example files the $PREFIX/share/doc/h2o/examples directory

CMakeLists.txt, deps/libyrmcds/.gitignore, deps/libyrmcds/.travis.yml, deps/libyrmcds/Doxyfile, deps/libyrmcds/Makefile, deps/libyrmcds/README.md, deps/libyrmcds/USAGE.md, deps/libyrmcds/connect.c, deps/libyrmcds/counter.c, deps/libyrmcds/recv.c, deps/libyrmcds/send.c, deps/libyrmcds/send_text.c, deps/libyrmcds/strerror.c, deps/libyrmcds/t/t.h, deps/libyrmcds/t/text.c, deps/libyrmcds/text_mode.c, deps/libyrmcds/yc-cnt.c, deps/libyrmcds/yc.c, deps/libyrmcds/yrmcds.h, deps/libyrmcds/yrmcds_portability.h, deps/libyrmcds/yrmcds_text.h, examples/libh2o/simple.c, h2o.xcodeproj/project.pbxproj, include/h2o/memcached.h, lib/common/memcached.c, src/ssl.c, t/40memcached-session-resumption.t, t/40session-ticket.t
upstream: https://github.com/cybozu/libyrmcds/issues/17
=> add support for text-based memache protocol

lib/core/util.c, t/00unit/lib/core/util.c, t/50mruby.t
however this may add tiny overhead to parsing link headers.
=> support nopush for rel=preload

h2o.xcodeproj/project.pbxproj, include/h2o.h, include/h2o/configurator.h, include/h2o/memory.h, include/h2o/string_.h, lib/common/string.c, lib/core/config.c, lib/core/configurator.c, lib/core/logconf.c, lib/core/request.c, lib/handler/fastcgi.c, lib/handler/file.c, lib/handler/mruby.c, t/40env.t, t/assets/doc_root/printenv.cgi
=> per-request environment variables for FastCGI

lib/core/configurator.c, t/40server-push.t
=> fix error on setting custom capacity-bits

lib/http2/connection.c
RFC 7540 section 8.2.1 states as below, however H2O does not implement the restriction.
> PUSH_PROMISE frames can be sent by the server in response to any client-initiated stream
This PR adds a simple guard, that simply ignores push indications made by a pushed response.
Note that it is generally better to squash the dependency chain (of the resources that need to be preloaded) and include all the links in the response header of the client-initiated stream, since only by doing so we can start pushing all of them at the earliest moment.
=> ignore push indications made by a pushed response

lib/http2/connection.c
The reader should not be stopped even if we start queuing incoming requests (due to hitting the internally concurrency limit), or else we might fail to read WINDOW_UPDATEs of open streams, therefore the open streams never get closed, and the connection stalls.
=> fix potential stall when http2-max-concurrent-requests-per-connection is set to a small number

.gitmodules, lib/http2/cache_digests.c, t/00unit/lib/http2/cache_digests.c, t/40server-push.t
Corresponds to https://github.com/h2o/cache-digest.js/pull/1
relates to #967
=> Truncate sha256 digest (instead of taking the modulo)

t/50config-tag.t, t/50http2_debug_state.t
Fix this issue: https://github.com/h2o/h2o/issues/1058
=> fix broken tests (remove unnecessary mruby dependencies)

CMakeLists.txt, h2o.xcodeproj/project.pbxproj, lib/common/string.c, t/00unit/issues/percent-encode-zero-byte.c, t/00unit/lib/common/string.c, t/00unit/test.c, t/00unit/test.h
alternative approach for #1070
=> escape NUL to %00

lib/http2/connection.c
=> always check (and close the socket if necessary) after writing data

lib/http2/connection.c
Firefox sends a PRIORITY frame when receiving a PUSH_PROMISE frame.
Because of the racy nature of the protocol, it's very possible that the
PRIORITY frame is received once the stream is closed on H2O side.
This results in us opening a new stream that will be used to account
against `globalconf->http2.max_streams_for_priority`. Eventually, this
can lead to sending a GOAWAY frame with 'ENHANCE_YOUR_CALM'.
I believe it's safe to ignore PRIORITY frames that reference pushed
streams that are closed, since no current browser appears to use those
to reference them later.
I've tested the fix by using the following handler (and a dummy js file)
and verified that we hit the GOAWAY path without the fix, and not anymore
with the fix:
```
mruby.handler: |
Proc.new do |env|
case env["PATH_INFO"]
when …
```
=> Ignore PRIORITY frames that reference closed pushed streams

examples/libh2o/http1client.c, examples/libh2o/latency-optimization.c, examples/libh2o/simple.c, examples/libh2o/socket-client.c, include/h2o/socket/evloop.h, lib/common/socket/evloop.c.h, lib/common/socket/evloop/epoll.c.h, lib/common/socket/evloop/kqueue.c.h, lib/common/socket/evloop/poll.c.h, src/main.c, t/00unit/lib/common/multithread.c, t/00unit/test.c
fix #1100 with lesser changes to OS-dependent code.
@deweerdt Does this look OK to you?
=> fix busy loop on Linux after receiving SIGTERM

lib/http2/casper.c
=> add `Secure` attribute to the casper cookie

lib/handler/configurator/compress.c
=> fix parsing of quality

README.md
Let people know we are using Coverity.
=> Add Coverity badge to README.

lib/common/file.c, lib/common/memcached.c, lib/common/serverutil.c, lib/common/socket.c, lib/core/configurator.c, lib/handler/configurator/fastcgi.c, lib/http2/hpack.c
This branch contain miscellaneous fixes for defects that coverity found
=> misc fixes

fuzz/driver.cc
fuzzer listen to a socket in a temp directory.
=> Remove hardcoded www.ietf.org reproxy url, replace it by having the

fuzz/driver.cc
We can't actually pass a unix socket as an address in the reproxy header
currently, so let's register a proxy handler instead.
=> Fuzzer use proxy handler

src/main.c, src/ssl.c, srcdoc/configure/base_directives.mt
=> add directive to set max. TLS version

include/h2o.h, lib/core/logconf.c, lib/core/request.c, lib/http1.c, t/40bad-request.t
=> log connections that closed prior to sending a response

deps/yoml/yoml-parser.h, t/50mruby.t, t/Util.pm
* extract latest yoml
* added test case
=> fix mruby lineno vol.2

lib/common/socket/uv-binding.c.h
=> [libh2o][libuv] fix crash when abruptly closing an HTTP/2 connection

share/h2o/annotate-backtrace-symbols
for the ease of analyzing multiple crashes
https://github.com/h2o/h2o/pull/1173#issuecomment-293200116
=> include process id in the backtrace

lib/common/socket.c
Size of the decrypted data may exceed the size of the input if the TLS 1.3 stack already has part of the record in its buffer.
=> fix `decode_ssl_input: Assertion `!rbuf.is_allocated’ failed.`

lib/common/socket.c
=> fixes issues in #1264

src/ssl.c
This PR fix a leaking issue reported by coverity scan.
=> fix resource leak of redis context

include/h2o/http1client.h, lib/common/http1client.c, lib/core/proxy.c, lib/tunnel.c
#1272
websocket proxy will lost first frame if backend server fast enough.
=> fix BUG websocket proxy happens to drop first frame.

t/50reverse-proxy-added-headers.t, t/50reverse-proxy-disconnected-keepalive.t
maybe left to do in https://github.com/h2o/h2o/pull/1318 @kazuho
=> specify loopback address correctly for listen option

CMakeLists.txt, h2o.xcodeproj/project.pbxproj, include/h2o/mruby_.h, lib/handler/mruby.c, lib/handler/mruby/embedded.c.h, lib/handler/mruby/embedded/core.rb, lib/handler/mruby/sleep.c, t/50mruby-sleep.t
https://github.com/h2o/h2o/pull/1330 is merged but wasn't toward to master, sorry
=> mruby sleep

CONTRIBUTING.md
- maybe something should be added regarding what kind of modules would get accepted/not accepted. 
alternative: add a new file "Extending.md" that starts to collect information on how h2o can be extended
=> describe how to add mruby modules

lib/handler/file.c
=> never return 304 if the file is a dynamic handler (e.g., CGI)

deps/mruby-digest/src/digest.c
=> export Digest::SHA256 to mruby

lib/handler/configurator/expires.c, t/50expires.t
This addresses issue https://github.com/h2o/h2o/issues/1405
=> Expires fix

t/50reverse-proxy-chunk-timeout-2.t
The test was occasionally failing, and in such case, nghttp was returning immediately.
The most likely cause of such an issue is nghttp (via h2o) trying to connect to `$upstream_port` before nc binds to the port.
The PR tries to solve the issue by listening to `$upstream_port` in the test script itself.
=> fix race condition in t/50reverse-proxy-chunk-timeout-2.t

include/h2o.h, lib/core/request.c, lib/core/util.c, lib/http2/connection.c, t/00unit/lib/core/util.c, t/40server-push.t
=> add support for `critical` attribute of link: rel=preload

misc/fastcgi-cgi.pl, share/h2o/fastcgi-cgi, srcdoc/configure/cgi.mt
Would make resolving issues easier.
ToDo:
=> add verbose mode to fastcgi-cgi gateway

lib/common/socket.c
=> fix pointer corruption when connecting to origin via https (big-endian only)

deps/neverbleed/neverbleed.c, deps/picotls/lib/openssl.c
=> address TLS-related compiler warnings

doc/configure.html, doc/configure/access_control.html, doc/configure/access_log_directives.html, doc/configure/base_directives.html, doc/configure/basic_auth.html, doc/configure/cgi.html, doc/configure/command_options.html, doc/configure/compress_directives.html, doc/configure/dos_detection.html, doc/configure/errordoc_directives.html, doc/configure/expires_directives.html, doc/configure/fastcgi_directives.html, doc/configure/file_directives.html, doc/configure/headers_directives.html, doc/configure/http1_directives.html, doc/configure/http2_directives.html, doc/configure/mruby.html, doc/configure/mruby_directives.html, doc/configure/proxy_directives.html, doc/configure/quick_start.html, doc/configure/redirect_directives.html, doc/configure/reproxy_directives.html, doc/configure/status_directives.html, doc/configure/syntax_and_structure.html, doc/configure/throttle_response_directives.html, doc/faq.html, doc/index.html, doc/install.html, srcdoc/snippets/wrapper.mt
What I've been feeling stressed slightly but for a long time is, when I'm browsing Configure/* page in h2o.examp1e.net and want to back to the Configure index page, everytime, everytime I click `Configure` navigation tab, but it doesn't respond at all. This PR should be one of my best.
=> make document's selected tab navigatable

include/h2o/serverutil.h, lib/common/serverutil.c, src/main.c, t/00unit/lib/common/serverutil.c
add a macro SERVER_STARTER_ENV_NAME for environment variable "SERVER_STARTER_PORT".
also removed "env_var" in server_starter struct.
=> move "SERVER_STARTER_PORT" to macro "SERVER_STARTER_ENV_NAME"

deps/mruby-class-new-fiber-safe/.gitignore, deps/mruby-class-new-fiber-safe/.travis.yml, deps/mruby-class-new-fiber-safe/.travis_config.rb, deps/mruby-class-new-fiber-safe/README.md, deps/mruby-class-new-fiber-safe/mrbgem.rake, deps/mruby-class-new-fiber-safe/mrblib/class-new-fiber-safe.rb, deps/mruby-class-new-fiber-safe/src/class-new-fiber-safe.c, deps/mruby-class-new-fiber-safe/test/class-new-fiber-safe.rb, t/50mruby-channel.t
fixes #1536 (see also https://github.com/mruby/mruby/issues/3879)
=> allow fiber switch in constructor

lib/handler/mruby.c, lib/handler/mruby/embedded.c.h, lib/handler/mruby/embedded/core.rb, t/50mruby.t
Fixes https://github.com/h2o/h2o/issues/1575
=> handle mruby response array and generator correctly

src/main.c, srcdoc/configure/syntax_and_structure.mt
implements https://github.com/h2o/h2o/issues/1520 , replaces #1519
=> !env support in config

include/h2o/memory.h
=> replace "FILENAME_MAX" with "H2O_TMP_FILE_TEMPLATE_MAX"

lib/http2/connection.c
>  The entire DATA frame payload is included in flow control, including the Pad Length and Padding fields if present.
[RFC 7540 section 6.1](https://tools.ietf.org/html/rfc7540#section-6.1)
This PR adjusts the code that the behavior becomes compliant to the specification.
=> Entire DATA frame payload is included in flow control

examples/libh2o/simple.c
Merges the change suggested in #1595 by @Varbin.
=> enable ECDH in the example server

lib/common/socket/evloop.c.h
The nice side effect is that the possibility of `alloca(0)` returning `NULL` leading to undefined behavior in `write_core` can be eliminated in relation to #1534.
=> avoid copying vec when calling writev(2)

CMakeLists.txt, examples/libh2o/websocket.c
just like "examples/libh2o/simple.c".
=> "examples/libh2o/websocket.c" built support without libuv

lib/common/multithread.c, lib/common/socket/evloop.c.h, lib/common/socket/evloop/epoll.c.h, lib/common/socket/evloop/kqueue.c.h, lib/common/socket/evloop/poll.c.h
=> fix leaks on destroy

examples/libh2o/simple.c
fixes #1615.
We will keep the code turned on by default to prevent regression in the code that is commented out.
=> in examples/libh2o/simple.c, emit access-log to /dev/stdout as default

include/h2o.h, include/h2o/memory.h, lib/common/memory.c, lib/core/util.c, lib/http2/connection.c
The function can be used when needed to release the resources associated to the TLS
=> add interface to release thread-local data

h2o.xcodeproj/project.pbxproj
otherwise the build fails (or is it just me?)
=> add deps/brotli/c/include to Header Search Paths for Xcode

CMakeLists.txt
Fixes https://github.com/h2o/h2o/pull/1675#issuecomment-372081566
=> make gitrev target conditionally depend on libuv test

deps/mruby-input-stream/mrbgem.rake, deps/mruby-input-stream/mrblib/input_stream.rb, deps/mruby-input-stream/src/mruby_input_stream.c, deps/mruby-input-stream/test/input_stream.rb
https://github.com/takahashim/mruby-input-stream/pull/3
=> update mruby-input-stream gem

deps/mruby-json/README.md, deps/mruby-json/mrbgem.rake, deps/mruby-json/src/mrb_json.c, deps/mruby-json/src/parson.c, deps/mruby-json/src/parson.h, deps/mruby-json/test/json.rb
https://github.com/mattn/mruby-json/pull/30
=> make mruby-json great again

deps/mruby-json/src/parson.c, deps/mruby-json/test/json.rb
https://github.com/mattn/mruby-json/pull/32
=> make mruby-json great again returns

include/h2o/filecache.h, lib/common/filecache.c, lib/handler/file.c, t/00unit/lib/handler/file.c
This PR adds `if-range` condition header support for `lib/handler/file.c`.
=> Add if-range header support

lib/http1.c
=> on_send_informational potential use-after-free

lib/handler/mruby/channel.c
rewrite https://github.com/h2o/h2o/pull/1783
=> use mrb_data_get_ptr to handle irregular cases in ruby layer

src/ssl.c
=> check more errors returned by libcrypto

lib/core/logconf.c, misc/doc.mk, srcdoc/configure.mt, srcdoc/configure/access_log_directives.mt, srcdoc/configure/server_timing_directives.mt
Adds docs about `server-timing` directive and Proxy Timings access log extensions.
=> server timing doc

deps/cloexec/cloexec.c, lib/common/socketpool.c, src/ssl.c
Minor findings found by running https://github.com/facebook/infer nothing of note, but some of those might be a slight improvement.
=> Minor facebook/infer 0.15.0 finds

lib/common/balancer/roundrobin.c, lib/common/redis.c
error: control may reach end of non-void function
[-Werror,-Wreturn-type]
=> fix compiler error under android O

lib/common/socketpool.c
This PR try calculating the exact timeout for socketpool's pool entry.
=> socketpool: refine pool entry timeout

lib/handler/mruby/http_request.c
build h2o with ASAN, and run with the following configuration
```
mruby.handler: |
proc {|env|
req = http_request("http://example.com")
[200, {}, []]
}
```
and do `h2load -n 100000 -c 100 http://127.0.0.1:8080`, then you may see heap-use-after-free bug
1. proc execution finishes and `req` loses its reference
2. httpclient callback (e.g. on_head) is called
3. in the callback function , `mrb_obj_alloc` is called (e.g. mrb_str_new)
4. incremental gc starts and `req` gets released
5. `dispose_context` function is called, the httpclient and the context is freed
6. touch freed memory in the same callback function
In current design, 5. happens because `h2o_mruby_http_request_ctx_t`'s lifetime relies on mruby objects (I think it's reasonable itself)
I added the following two amendments:
- a) …
=> fix heap-use-after-free bug of http_request

lib/http2/connection.c
`h2o_http2_conn_unregister_stream` wants `_refs.link` set if
the state is pending.  However, when we sent `GOAWAY` (for
draining), we don't bother linking said struct member in
`execute_or_enqueue_request_core`. This fixes the issue by transitioning
the stream to `END_STREAM` in `h2o_http2_stream_reset`, making the
linking of `_refs.link` optional.
=> `h2o_http2_conn_unregister_stream` assert on shutdown

src/main.c
Ensure that [max-connections](https://h2o.examp1e.net/configure/base_directives.html#max-connections) is enforced against HTTP3 as well.
Keep the design consistent with H1/H2 (or UDS/TCP) by adding the check to `src/main.c`. A function that is responsible for the boundary check is used to wrap  `h2o_http3_server_accept`, and passed as a callback to the HTTP3 layer.
As for decrementing the connection count, `quicly_context_t`'s `closed_by_peer` pointer is set to point at a static structure with a function pointer to the newly added function: `on_http3_closed_by_peer()`. I had to shuffle couple of existing functions around in the process.
~If you ignore the signature, `on_http3_closed_by_peer()` is identical to `on_socketclose(void *data)`. Would it make sense to just call …
=> http3: respect and enforce conf.max-connections

include/h2o/header.h, lib/core/headers.c, lib/handler/fastcgi.c, lib/handler/file.c, lib/handler/headers_util.c, lib/handler/mruby.c, lib/handler/mruby/middleware.c, t/00unit/issues/293.c, t/00unit/lib/handler/file.c, t/00unit/lib/handler/redirect.c
This PR trying clean up some code for 'lib/core/headers.c'
=>  'ssize_t' should be used for h2o_find_header/h2o_find_header_by_str 

src/main.c
Make it possible for a service operator to limit the amount of HTTP3 requests that an H2O server can handle at any given point of time.
- Add a `max-quic-connections` configuration
- Validate the number of in-flight QUIC connections in `on_http3_accept`
=> HTTP3: Add a max-quic-connections configuration

lib/handler/mruby/middleware.c, lib/http1.c, lib/http2/connection.c, lib/http3/server.c, src/main.c
Builds upon #2188, cherry-pick from #2156.
Closes #2156.
=> Use designated initializers

lib/http3/qpack.c, lib/http3/server.c
Applied `clang-format-all.sh` to master.
=> [http3] Fix code formatting

deps/quicly/.travis.yml, deps/quicly/README.md, deps/quicly/include/quicly.h, deps/quicly/include/quicly/constants.h, deps/quicly/include/quicly/frame.h, deps/quicly/include/quicly/ranges.h, deps/quicly/include/quicly/sentmap.h, deps/quicly/lib/defaults.c, deps/quicly/lib/quicly.c, deps/quicly/lib/ranges.c, deps/quicly/misc/probe2trace.pl, deps/quicly/quicly-probes.d, deps/quicly/quicly.xcodeproj/project.pbxproj, deps/quicly/src/cli.c, deps/quicly/t/e2e.t, deps/quicly/t/loss.c, deps/quicly/t/simple.c, deps/quicly/t/stream-concurrency.c, lib/http3/common.c, src/main.c
To be followed up by another PR that removes EARLY_RESPONSE_ERROR.
=> [http3] minimal changes for -25

lib/http3/server.c
The send logic of the HTTP/3 handler is as below:
* `quicly_send` calls `scheduler_do_send`.
* `scheduler_do_send` picks the most urgent stream that has data, and calls `quicly_send_stream` specifying that stream.
* `quicly_send_stream` invokes `on_send_emit` callback, and when that callback runs out of data to be sent, it calls `h2o_proceed_response`.
* `scheduler_do_send` continues running until it consumes all the CWND, repeatedly picking the most urgent stream that has data, and calling `quicly_send_stream`.
* Once `quicly_send` returns, asynchronous callbacks including `h2o_proceed_response` are executed, and the additional data for what has been the most urgent stream is provided.
The problem here is that when the size of CWND is greater than the amount of data immediately available …
=> [http3] synchronous invocation of h2o_proceed_response

deps/quicly/include/quicly.h, deps/quicly/include/quicly/frame.h, deps/quicly/include/quicly/ranges.h, deps/quicly/include/quicly/recvstate.h, deps/quicly/lib/frame.c, deps/quicly/lib/quicly.c, deps/quicly/lib/ranges.c, deps/quicly/lib/recvstate.c, deps/quicly/quicly-probes.d, deps/quicly/src/cli.c, lib/common/http3client.c, lib/http3/common.c
Corresponds to https://github.com/h2o/quicly/pull/285.
=> [http3] read all packets before sending something

include/h2o.h, lib/core/logconf.c, lib/http3/server.c
Add log elements `%{http3.stream-id}x`, `%{http3.quic-stats}x`.
=> [http3] logging for http3

lib/handler/mruby.c
Use goto to have better split between the two code paths, rather than joining and then splitting based on state. This change has the side-effect of eliminating compiler warnings about unused variables.
=> use goto to have better split between the two code paths

lib/http3/common.c, src/main.c
FreeBSD does not have IP_PKTINFO, we need to use IP_SENDSRCADDR / IP_RECVSRCADDR.
Fixes #2128.
=> [http3] FreeBSD fixes

src/httpclient.c
=> httpclient: backtrace available when 'LIBC_HAS_BACKTRACE'

src/ssl.c
This commit renames functions related to QUIC keyset (st_quic_keyset_t)
to clarify they operate on QUIC keyset.
=> Rename QUIC keyset functions for clarification

lib/http3/common.c
Thanks to @tatsuhiro-t for reporting the issue.
=> process 0-RTT packet being coalesced with (or received at the same time as) the first Initial packet

h2olog/generated-quic.cc, h2olog/misc/gen-quic-bpf.py
amend c6810d38199e6f8c1a01086e50e1524ba6f20667
=> Fix crash by double-free problems on h2olog

lib/common/http3client.c, t/40http3.t
http3client has been incorrectly calling out an error when the server closes the request stream at the DATA frame boundary after quiescence.
=> [http3][client] correctly handle close-after-idle of a request stream

CMakeLists.txt
=> [h2olog] generate generated-quic.cc in correct directory

lib/http3/common.c, lib/probes_.h, src/httpclient.c
It seems that a violation had sneaked in. Fix that.
=> no dependency from lib/common to lib/core

lib/common/http1client.c
Refined from https://github.com/h2o/h2o/pull/2403
=> [refactor] extract start_request() from on_connection_ready() for further customization

include/h2o/socket.h, lib/common/socket.c, src/main.c
=> [http3] set DF bit

include/h2o/absprio.h, lib/common/absprio.c, lib/http3/server.c
This PR reflects the following changes that have gone into the draft:
* urgency levels no longer have semantics
* default is now 3
=> Update the definition of urgency (and the default)

h2o.xcodeproj/project.pbxproj, src/main.c, t/40http3-forward.t
Regarding how the test is implemented, please refer to the comment in t/40http3-forward.t.
=> [http3] add test-case for inter-node packet forwarding

h2o-probes.d, src/h2olog/generated-quic.cc, src/h2olog/misc/gen-quic-bpf.py
* Added `h2o:h3_packet_receive` and `h2o:h3_packet_forward`; it's tentative but we need now (cc: @hfujita )
* Renamed some param names in probes to keep naming conventions
=> [h2olog] more h3 probes

lib/common/socket.c
=> apply strlen to the result of setsockopt(TCP_CONGESTION)

deps/quicly/include/quicly.h, deps/quicly/lib/quicly.c, lib/http3/server.c
Builds on top of https://github.com/h2o/quicly/pull/397.
=> [http3] collect request information for the status handler

lib/http3/server.c
`next_stream_id - 4` could result in a negative number if
`next_stream_id < 4` <=> we have not processed any stream yet.
In such a case the original code would have passed a really large number
(close to UINT64_MAX) to h2o_http3_send_goaway_frame then
ptls_encode_quicint, which would then fails in an assertion because
it could not encode such a big number.
=> http3: handle a case in GOAWAY generation where we haven't processed any stream yet

src/main.c
When this option is `on`, H2O will set the `SO_REUSEPORT` option on
operating systems that support it.
The trade off that this option makes is that H2O might have slightly
worse latencies in favor for having the load better distributed across
H2O threads.
=> Introduce a 'tcp-reuseport' configuration option

src/h2olog/h2olog.cc
It amended <del># 440</del> <ins>#2440</ins>.
=> h2olog: fix a regression on conflict resolutions for #2440

lib/http3/common.c
=> fix a crash on qpack.ctx

lib/http3/server.c
This is a follow up/partial revert of https://github.com/h2o/h2o/pull/2451
(48bd91993b53549473bde7f375a28169e7ebe04e) to prevent NULL pointer
dereference.
When `quicly_accept` fails, `conn->h3.super.quic` is left unset
(NULL).  And if WITH_DTRACE is set, `on_h3_destroy` invokes a probe,
which then invokes `H2O_CONN_IS_PROBED`, which tries to access
`conn->h3.super.quic`. (`skip_tracing` is set to `get_skip_tracing`.)
This patch solves this crash and use-after-free solved in https://github.com/h2o/h2o/pull/2451
by inserting a connection to the connection list only when
`quicly_accept` succeeds.
=> http3: Link connection to list after accept succeeds

deps/quicly/include/quicly.h, deps/quicly/include/quicly/frame.h, deps/quicly/lib/defaults.c, deps/quicly/lib/quicly.c, deps/quicly/quicly-probes.d, deps/quicly/src/cli.c, deps/quicly/t/e2e.t
adopts https://github.com/h2o/quicly/pull/413
=> [quicly] skip the invocation of the scheduler callback inside quicly_accept

lib/common/socket/evloop.c.h
strace allows you to trace a process printing only failed system calls (which
is extremely useful for debugging). If lots of connections are generated
calling `setsockopt` on a socket that doesn't support NODELAY can fill your
strace logs with errors and make it harder to debug syscall failures you are
interested in.
This change avoids NODELAY for UNIX sockets. In addition to easier `strace`
debugging, we can also remove an unncessary system call.
=> Don't set NODELAY for non-inet sockets.

lib/common/socket/evloop.c.h
The regression that we caused with #2493 is that the code no longer compiles on macOS (or other operating systems that do not have `accept4`). Note also that on those platforms, `peeraddr` is NULL.
This PR addresses the problem by adding a NULL-check.
=> avoid null-deref of `peeraddr` depending on the environment

deps/quicly/CMakeLists.txt, deps/quicly/include/quicly/constants.h, deps/quicly/lib/quicly.c, deps/quicly/misc/quic-interop-runner/run_endpoint.sh, deps/quicly/parselog.py, deps/quicly/quicly-probes.d, deps/quicly/src/cli.c, deps/quicly/t/e2e.t, deps/quicly/t/simple.c, deps/quicly/t/test.c
This is to test h2o with newer quicly, namely with h2o/quicly#421.
=> extract https://github.com/h2o/quicly @ 8648403 () at deps/quicly

deps/quicly/lib/quicly.c, deps/quicly/misc/qlog-adapter.py, deps/quicly/quicly-probes.d
Hi there. The motivation behind this PR is to pull in the recent QLog work over from [h2o/quicly](https://github.com/h2o/quicly) @ [371a5a5](https://github.com/h2o/quicly/commit/371a5a5938f90c14ef19941919670b34fd04b3a1).
Command:
```
$ misc/dump-github-repository.pl https://github.com/h2o/quicly 371a5a59 deps/quicly
```
=> extract https://github.com/h2o/quicly @ 371a5a59 () at deps/quicly

t/Util.pm
The cause is the client connecting to the forked H2 server before the server starts listening on the specified port.
This PR address the issue by changing the code so that the port is opened for accepting new connections _before_ the server process is being forked.
See https://github.com/h2o/h2o/pull/2519#issuecomment-750791016 for the log that showed this problem.
=> t/50reverse-proxy-early-response.t occasionally fails with "conection failure"

.github/workflows/ci.yml
amending https://github.com/h2o/h2o/pull/2518 which accidentally deleted this test
=> retrieve "fuzz" test

deps/quicly/include/quicly/sendstate.h, deps/quicly/lib/quicly.c, deps/quicly/lib/sendstate.c
Hi there. My motivation behind this PR is to pull in https://github.com/h2o/quicly/pull/426
=> extract https://github.com/h2o/quicly @ bcd70c0 () at deps/quicly

.github/workflows/ci.yml, misc/docker-ci/check.mk
Extracted these fixes from https://github.com/h2o/h2o/pull/2520
=> Fix regressions in GHA migration

t/50http1-proxy-full-uri.t
This PR targeted at https://github.com/h2o/h2o/pull/2570 adds a test that verifies that h2o has the correct behavior.
=> add a test that demonstrates appropriate behavior when dealing with absolute form urls

src/h2olog/json.cc
Amends https://github.com/h2o/h2o/pull/2562
=> h2olog: quote pointer addresses in JSON

lib/http3/server.c
=> [http3] delay disposal of `h2o_req_t` only when the caller is the generator

lib/http3/server.c
The spec is still in flux, only require the elements that are needed,
ignore the others
=> connect-udp: only enforce `:scheme:` and `:path:`

deps/quicly/lib/quicly.c
Adopts https://github.com/h2o/quicly/pull/448 which is the quicly-side counterpart of https://github.com/h2o/h2o/pull/2656.
The two PRs together addresses issues around Initial decryption failure.
=> [http3] fix memory leak on Initial decryption failure

share/h2o/status/index.html
In #1229, omission of values in the JSON representation were changed from `"-"` to `null` however the change was not applied to the table view. Also changes how URI is represented when a CONNECT method is being used.
=> [status] fix discrepancies of the table view

lib/common/socket.c
amending https://github.com/h2o/h2o/pull/2655
Thanks to @hfujita for pointing it out (https://github.com/h2o/h2o/commit/626a3f44826746cfc3c377ca85928d38d3f8dc19#r50571561)
=> fix attribute validations for eBPF maps

lib/http3/server.c
`retain_sendvec` is a function that is used for copying data being provided from the generator.
At the moment, this function is used before calling the `h2o_proceed_response` function or `tunnel->proceed_read` callback, as the buffer being provided by the generator is discarded when the protocol handler asks the generator to "proceed."
In case of the tunnel API such action should also be made when the tunnel is about to be destroyed, otherwise, we'd hit a use-after-free bug when the http/3 protocol handler destroys the generator then tries to send the data provided by the generator.
Note: when serving an HTTP response, this is not an issue. That's because the generator is required to retain the last chunk of data it provided to the protocol handler until `h2o_req_t` is discarded.
=> [http3][tunnel] copy send data provided by the tunnel before destroying the tunnel

src/h2olog/generated_raw_tracer.cc, src/h2olog/h2olog.cc, src/h2olog/misc/gen_raw_tracer.py
=> [h2olog] fix sampling rate errors, by mapping 1.0 to 2**32

lib/http3/qpack.c
=> [QPACK] fix undefined behavior warning

lib/http3/qpack.c
ASAN complains that we're using `table->last` and `table->first` which
are possibly NULL in pointer arithmetic:
```
/build/lib/http3/qpack.c:758:54: runtime error: applying non-zero offset 8 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/lib/http3/qpack.c:758:54 in
/build/lib/http3/qpack.c:1180:64: runtime error: applying non-zero offset 8 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/lib/http3/qpack.c:1180:64 in
```
This PR casts the pointers to `uintptr_t`, making the warning go away
=> qpack ASAN UB warning

h2o.xcodeproj/project.pbxproj, lib/http2/connection.c, t/50timeout-on-max-concurrent-requests.t
Incorporates the test provided in #2700, fixes the problem differently.
=> [http2] request is pending until `h2o_process_request` is called

h2o.xcodeproj/project.pbxproj, include/h2o/rand.h, lib/common/rand.c, t/00unit/lib/common/rand.c
Amends #2745.
Please refer to each commit comment regarding the rationale.
=> editorial nitpicks to the UUID generator

CMakeLists.txt, deps/quicly/CMakeLists.txt, deps/quicly/include/quicly.h, deps/quicly/lib/quicly.c, deps/quicly/misc/probe2trace.pl, deps/quicly/quicly.xcodeproj/project.pbxproj, h2o.xcodeproj/project.pbxproj, include/h2o.h, lib/handler/configurator/self_trace.c, lib/handler/self_trace.c, lib/http3/server.c, src/main.c
Introduces the self-trace handler that can be used by clients to obtain the server-side view of the connection state.
=> [http3] self-trace handler

lib/core/proxy.c
This fix makes sure that added headers are added regardless of the flags
in `misc/tokens.pl`
=> Apply `proxy.headers.add` after header filtering

h2o.xcodeproj/project.pbxproj
For ARM devices, root path of homebrew has been changed from `/usr/local` to `/opt/homebrew`.
=> [xcode] ARM support

deps/quicly/lib/quicly.c, include/h2o/http3_common.h, lib/http3/common.c
builds on top of https://github.com/h2o/quicly/pull/478.
=> [HTTP/3] GSO

include/h2o/memory.h
=> h2o_vector_erase fix size

t/90h2olog.t
Adding these tests because I have problems with `h2olog -t` observed in our environment.
=> test: add tests about `h2olog -t`

lib/http3/common.c
The rationale can be found in https://github.com/h2o/quicly/pull/283. Apparently, we fixed this sender-side issue while we optimized the performance of quicly but did not incorporate the lesson learned there into h2o.
Send-side counterpart of #2794.
=> [http3] process other events after sending at most 10 datagrams

src/main.c
For each worker thread, h2o either duplicates the file descriptor using dup (2), or opens a new file descriptor with the SO_REUSEPORT.
The mode being used depends on certain factors:
* for TCP sockets, the default behavior is the former. The latter is used when SO_REUSEPORT is defined and `tcp-reuseport` option is being set.
* for UDP sockets serving QUIC, the latter is being used whenever SO_REUSEPORT is available, because we want the kernel to distribute ingress UDP traffic by the 4-tuple to the worker threads.
When dup (2) is being used, there is no need to set the socket options for the file descriptor being duplicated, because the options apply to the open file description that is being shared by the original file descriptor and the duplicated descriptor. But when opening new file …
=> set SO_RCVBUF & SO_SNDBUF for sockets being reopened

include/h2o/multithread.h, lib/common/multithread.c
This PR adds a getter to retrieve the event loop from the multithread module.
=> add method to fetch from h2o_loop_t from h2o_multithread_queue_t

include/h2o/socket.h, lib/common/socket.c
'H2O_USE_SELECT' and 'H2O_SOCKET_FLAG_IS_WRITE_ERROR'
=> remove dead code

lib/http2/connection.c
Doing so prevents `h2o_req_t` (and therefore generators being attached to the request object) while the generator is invoking the `proceed_req` callback.
Separately, the scheduler is disactivated so that DATA frames would not be sent after the RST_STREAM frame.
Amends #2823.
=> Delay the disposal of stream state until RST_STREAM is being sent

src/h2olog/generated_raw_tracer.cc, src/h2olog/misc/gen_raw_tracer.py
Thanks, @syohex!
amending https://github.com/h2o/h2o/pull/2835
=> h2olog: suppress warnings on -Wsign-compare

src/h2olog/http_tracer.cc
Same as https://github.com/h2o/h2o/pull/2835 but just forgot to tweak `http_tracer.cc`.
=> h2olog: fix UBSan errors in http_tracer.c

src/h2olog/http_tracer.cc
cf. https://github.com/h2o/h2o/pull/2840#discussion_r708934576
=> h2olog: use standard library functions instead of user-defined macros

include/h2o/socket.h, lib/common/timerwheel.c
for h2o/socket.h and timerwheel
=> libh2o: remove dead code

lib/common/socketpool.c
=> socketpool: check poll exipred after lisklist inserted

lib/common/memory.c, src/httpclient.c
As suggested by @deweerdt in #2803.
=> when ASAN is used, refuse to recycle memory chunks

misc/docker-ci/Dockerfile.ubuntu1604, misc/docker-ci/Dockerfile.ubuntu2004
=> Test::More is too outdated

t/40http3.t, t/50mruby-middleware.t, t/assets/50mruby-middleware.psgi
- t/40http3.t
- Remove 100 times loop, no longer needed now?
- t/50mruby-middleware.t
- Stop spawning h2o for each testcases (204 => 3)
- Test only plain H1 (https and H2 aren't related to this test)
=> speed up mruby-middleware.t

lib/handler/connect.c
This PR implements rfc8305 aka "Happy Eyeballs V2" by using separate calls to h2o_hostinfo_getaddr() for each address family
=> implement rfc8305 (Happy Eyeballs V2) 

t/Util.pm
I consider that it is useful if a test is failed when spawning server in test catches segv it can be aware of a crash in such a case of #2900. 
In this way, we make an opportunity to find a crash point in tests.
=> To be failed in a test if it catches segv in spawn_server

lib/common/socket.c
This is an alternative to #2910.
For the description of the problem and discussion, see #2910.
=> send TLS alert before closing the socket, when OpenSSL is used and certificate verification fails (alternative to #2910)

lib/common/socket.c, lib/common/socket/evloop.c.h, lib/common/socket/uv-binding.c.h
=> Ignore errors coming from SSL_write

lib/common/socket.c
amends [#2859](https://github.com/h2o/h2o/pull/2859)
=> Free ssl->output.buf.base

t/50connect-deadlock.t
At the moment, h3 test of t/50connect-deadlock.t is really flaky, due to the following reasons.
The intent of the test case is to confirm the following:
* amount of data being buffered on both direction is limited
* every byte that's being sent would be received on the other side
To confirm such behavior, the test-case uses an echo server and h2o-httpclient as the client. The test script sends data through h2o-httpclient while not reading anything. Eventually, that leads to h2o-httpclient becoming incapable of making progress on the receive-side. That in turn causes the send-side of the echo server to stall, which in turn blocks the receive-side of the echo-server, which in turn blocks the send-side of `h2o-httpcilent` from making progress.
The hope has been that, for the H3 test, such …
=> [t/50connect-deadlock.t] hack to avoid flakiness

lib/http3/server.c
Because request handlers that could stream a request (e.g. reverse proxy) could set `req.write_req.cb` to NULL, current code could fail to decrement the `conn->num_streams_req_streaming` counter in such a case.
This patch introduces a new flag inside the stream object so that the http3 module can independently keep track if the request is in streaming mode.
=> [http3] Fix potential counter leak with streaming reqs

lib/http1.c
Mostly editorial, with one exception:
* Fix theoretical concern that `req-->_ostr_top` might be pointing to something other than the final ostream (28e4cbc).
=> [h1] refactor handling of informational response

lib/common/http3client.c
=> http3client: do not abort when resolving name error

src/main.c, t/Util.pm
Addresses https://github.com/h2o/h2o/issues/2996
=> multiple listens as a sequence

srcdoc/configure/base_directives.mt
* Add the description of send-server-name: preserve
* Fix #3009
=> [doc] Change description of send-server-name.

lib/common/socketpool.c
=> Fix typo in socketpool.c

lib/common/http2client.c, t/50reverse-proxy-http2.t
When client sends a POST request with `content-length: 0`, h2o reverse proxy skips sending the data frame for the request because the size is 0. This is an incorrect behavior and could make the upstream h2 server get stalled waiting for the data frame to arrive. This patch fixes it so that it will send the data frame for the 0-byte body.
Added a unit test for the behavior, confirmed it failed without the patch in 5d0ee4cbdabacf4745064f4dc049e9fc7a04ccb1, and is fixed with the patch.
=> http2client: properly send request body with 0-bytes

lib/common/http2client.c, t/40http2-h2spec-proxy.t, t/40http2-h2spec.t, t/50reverse-proxy-h2-post.t
=> [http2client] fix issues in request body submission code

lib/http2/connection.c
=> Accept HTTP/2 non-CONNECT request without :authority

t/90h2olog-selective-tracing.t, t/Util.pm
As well as reducing `num-threads` to 1.
These changes do not reduce flakiness, but hopefully, we'd be able to gather more information.
=> add debug output to t/90h2olog-selective-tracing.t

lib/common/socket.c, t/40ssl-cipher-suite.t, t/50access-log.t, t/Util.pm
It erroneously reports bytes, rather than bits.
=> [access-log] %{ssl.cipher-bits}x is incorrect for TLS 1.3

t/Util.pm
By eliminating race condition between server setup and client access.
=> [CI] fix flakiness of t/50dnsresolver.t

.gitmodules
=> [misc/h2get] go back to origin with all the necessary changes incorporated

lib/core/proxy.c
When pipe is used, do not resume reading until the pipe becomes empty. Otherwise, `splice` can return EAGAIN due to the pipe being full and then we'd have a hot loop.
Note the design difference from when memory buffers are used. We have two memory buffers, one to which we read and another which is considered inflight. But when using pipe, there is only one buffer which is the pipe itself,shared on the read side and the write side.
Amends #2993.
=> [proxy] fix hot loop when using a pipe as a buffer

lib/common/socket/evloop/epoll.c.h
=> use epoll1_create for simplicity

lib/common/url.c, lib/core/logconf.c, lib/core/proxy.c, lib/core/request.c, lib/http3/server.c
All of them are the same type of UB: "applying (non-)zero offset to pointer".
=> fix UBs detected by UBSan

fuzz/h3_header_generator.c, include/h2o/configurator.h, lib/common/hostinfo.c, lib/common/socket/evloop.c.h, lib/core/proxy.c, lib/handler/compress.c, lib/handler/connect.c, lib/handler/self_trace.c, lib/http1.c, lib/http2/stream.c, lib/http3/common.c, lib/http3/qpack.c, src/httpclient.c, src/main.c
=> clang-format

lib/common/file.c
This is to fix test failures in `t/50file-shrink.t`.
=> Increment offset when looping with pread

h2o.xcodeproj/project.pbxproj, misc/docker-ci/Dockerfile.ubuntu2204
Preparation to land #3188, https://github.com/h2o/picotls/pull/432.
=> add boringssl to CI image

misc/docker-ci/Dockerfile.ubuntu2204
=> amend boringssl ci image

include/h2o.h, lib/core/logconf.c, lib/http3/server.c
`%{extensible-priorities}x` is the log directive.
=> log extensible priority values being applied

deps/neverbleed/neverbleed.c, deps/neverbleed/neverbleed.h, deps/neverbleed/test.c, src/main.c, t/40ssl-cipher-suite.t
Adopts https://github.com/h2o/neverbleed/pull/49.
=> [boringssl][neverbleed] fix handshake failure when TLS/1.2 client requests PKCS1 signature

src/httpclient.c
I'd like to use this option to long-live connections such as WebSocket.
=> add --io-timeout to h2o-httpclient

t/50access-log.t
I'm not sure if this is due to locale or the macOS port having a patch, but it seems to encode each byte of path `/\xe3\x81\x82` as different unicode character rather than sending them raw.
To address test failure due to this behavior, this PR stops using curl and uses perl to connect directly to the server and write the request.
=> [macos] fix test failure due to curl encoding bytes in an unexpected way

deps/neverbleed/neverbleed.c
see https://github.com/h2o/neverbleed/pull/59
=> update neverbleed to adopt https://github.com/h2o/neverbleed/pull/59

include/h2o.h, include/h2o/http2_internal.h, lib/core/config.c, lib/core/configurator.c, lib/http2/connection.c
=> [http2] rapid reset attack

doc/configure/http2_directives.html, doc/h2o.conf.5, h2o.xcodeproj/project.pbxproj, srcdoc/configure/http2_directives.mt, t/80http2-reset-flood.t
Followup on #3291, adding doc and test.
=> h2 rapid reset followup

misc/docker-ci/Dockerfile.ubuntu2204
Corresponding docker image has already been pushed.
=> add mbedtls to merge picotls backend using mbedtls

lib/core/context.c
If an h2o process starts and traffic arrives suddenly, the pipe cache may not have been populated which could trigger lock contention on the kernel's file table lock very suddenly.
Avoid this case by prefilling the pipe cache when the context is initialized. This should help reduce lock pressure when a newly started h2o process receives a sudden, large influx of initial traffic.
=> Prefill pipe cache at context init

lib/http3/server.c
=> add parens to suppress warning

lib/http3/qpack.c
I think this change got lost somewhere along the way.
=> this is H3 level

deps/quicly/.github/workflows/ci.yml, deps/quicly/include/quicly/sentmap.h, deps/quicly/lib/quicly.c, deps/quicly/t/e2e.t, deps/quicly/t/loss.c, deps/quicly/t/sentmap.c
Adopts https://github.com/h2o/quicly/pull/573.
=> [http3] improve detection of CC-limited state

lib/core/configurator.c, src/httpclient.c, src/main.c
None of them are harmful as the size are 32 or 64 bits.
=> fix scanf(PRI)

lib/handler/h2olog.c
#3430 introduced a memory leak when an h2olog connection is being established.
=> [h2olog] fix memory leak

deps/picotls/fuzz/fuzz-asn1.c, deps/picotls/fuzz/fuzz-client-hello.c, deps/picotls/fuzz/fuzz-server-hello.c, deps/picotls/include/picotls.h, deps/picotls/include/picotls/openssl.h, deps/picotls/lib/picotls.c, deps/quicly/include/quicly.h, lib/probes_.h
Update picotls, quicly, as well as adjusting the code slightly for consistency.
=> update picotls, quicly

deps/picotls/lib/picotls.c, lib/http3/server.c
Adopts #3424, including https://github.com/h2o/picotls/pull/556.
=> misc http/3 fixes

deps/quicly/include/quicly.h, deps/quicly/lib/quicly.c, deps/quicly/t/simple.c
See https://github.com/h2o/quicly/pull/603.
=> update quicly (adopts PR #603)

include/h2o/httpclient.h, lib/handler/proxy.c
Resolve one of the TODOs for using H3 to the origin.
=> [proxy] apply cert verify logic of SSL_CTX to H3 (QUIC)

lib/http2/hpack.c, t/00unit/lib/http3/qpack.c
=> HTTP/3: Reject leading and/or trailing space in Huffman-coded fields

deps/picohttpparser/picohttpparser.c, deps/picohttpparser/test.c
Adopt https://github.com/h2o/picohttpparser/pull/82.
=> [h1] reject chunks using bare LF

lib/http2/connection.c
Hi!
I was looking at 579ecfaca155d1f9f12bfd0cff6086dcda4b9692 which implements a mitigation against MadeYouReset, and I think the mitigation does not work against a variant of MadeYouReset where the client triggers a stream reset by sending an invalid window update, because right now the delay is only set up when processing a RST stream frame. Here is a fix that in my tests seems to handle both cases (RST stream frame and invalid window update), but I might have missed something obvious as it has been a while since the last time I looked at the h2o code.
Best regards,
Remi Gacogne
PowerDNS
=> Enforce DoS mitigations when unregistering a stream
