h2o/h2o

lib/common/http1client.c, t/50reverse-proxy-chunked-post-termination.t, t/50reverse-proxy-request-bytes.t
This is a fix for a long running bug originated from https://github.com/h2o/h2o/pull/1357. `0\r\n\r\n` is the right chunked terminator, not `0\r\n`. As a result, some server implementations (including h2o) indefinitely waits a terminator, or fires timeout causing error response.
FYI there're servers that don't wait final CRLF (ex: Varnish, Starlet). If the upstream is such one, problem never happens.
=> use correct chunked terminator

lib/common/serverutil.c
posix_spawnp can return ENOENT directory since glibc 2.24.
https://sourceware.org/bugzilla/show_bug.cgi?id=10354#c12
=> Update the comment for posix_spawnp

src/main.c
When TLS 1.3 is request to be disabled, we need to set the flag of OpenSSL (in addition to disabling picotls) now that OpenSSL supports 1.3.
=> Disable TLS v1.3 properly (when configured as such)

include/h2o/httpclient.h, lib/common/http1client.c, lib/common/http2client.c, lib/common/httpclient.c, t/50mruby-error-log.t, t/50mruby-http-request.t, t/50reverse-proxy-http2.t
httpclient error strings are a bit messy, and hard to handle because the users have to strcmp the error string to know what actual error happened. This PR exports all httpclient specific errors like existing `h2o_httpclient_error_is_eos` and allows the users to compare the errstr pointer to them.
As a preliminary work to it, I sorted out existing error messages as the following:
- There were some variants of `I/O error`, but I merged them into one `I/O error`
- In H1, there were two types of parsing errors, `failed to parse the response` and `failed to parse the response (chunked)`, but I merged the latter to the former.
- In H2, there were many types of errors caused by the upstream like `invalid DATA frame`, `buffered data size exceeds input window`, etc.. but I put them all together …
=> sort out httpclient errors

include/h2o.h, include/h2o/http2_internal.h, include/h2o/mruby_.h, lib/core/logconf.c, lib/core/request.c, lib/handler/compress.c, lib/handler/compress/brotli.c, lib/handler/compress/gzip.c, lib/handler/errordoc.c, lib/handler/file.c, lib/handler/mruby/middleware.c, lib/handler/mruby/sender.c, lib/handler/reproxy.c, lib/handler/throttle_resp.c, lib/http1.c, lib/http2/http2_debug_state.c, lib/http2/stream.c, t/00unit/lib/handler/compress.c, t/00unit/test.c
Introduces `h2o_sendvec_t`, uses that to convey HTTP response body in place of `h2o_iovec_t`. The difference is that `h2o_sendvec_t` has a callback that can be used to delay the fetching of data until it becomes actually needed.
It replaces the "pull-mode", simplifying the code. The other benefit would be that the proxy handler can stop using the double-buffer approach. Instead, it could just issue `h2o_sendvec_t` instances with a custom callback that, upon request from the protocol handler, fills the send buffer using the data stored in receive buffer of the httpclient.
=> [wip] iovec with callbacks

deps/quicly/include/quicly/defaults.h, deps/quicly/lib/defaults.c, deps/quicly/lib/quicly.c, deps/quicly/src/cli.c, src/httpclient.c, src/ssl.c
fixes #2115 using https://github.com/h2o/quicly/pull/207.
=> Update quicly to use the CID encryptor with concurrency support

include/h2o/memory.h, lib/handler/file.c
#1992, merged as part of #1846, introduced a resource leak in the file handler where the sendvec submitted with `send_state` set to final was not released when the protocol implementation did not send the contents of the sendvec.
This was causing memory and file descriptor leak on h2o.examp1e.net, as the website uses push, that gets cancelled without sending any data when the same resourec is attempted to be pushed for the second time on the same connection. This has been identified as the cause of #2134.
This PR fixes the issue by using the destruction of `h2o_req_t::pool` as the trigger to destruct the generator.
=> fix resource leak in file handler

lib/http2/stream.c
The on-the-fly compressor typically emits multiple vectors.
In #1992 that got merged as part of #1846, we switched the vector type being used for sending response chunks from `h2o_iovec_t` to `h2o_sendvec_t`. The size of the structs are different.
However, we failed to make the corresponding change in HTTP/2 handler, resulting in corrupt list of vectors when multiple vectors are split into different calls to writev.
Reported in #2135.
PS. This is a good (bad) example in showing the danger of using `typeof(typename)` in memory-related function calls (e.g., malloc, memcpy, memmove). Do we want to do a review and rewrite those?
=> fix data corruption when on-the-fly compression is used

include/h2o.h, include/h2o/http2_internal.h, lib/core/request.c, lib/http1.c, lib/http2/connection.c, lib/http2/http2_debug_state.c, lib/http2/stream.c, lib/http3/server.c
At the moment, the request streaming API is designed as a series of callbacks, and every protocol implementation is expected to use them in one particular way.
To be specific, the protocol implementations are expected to pass received data (i.e. chunk or a DATA frame payload) as a vector, which is either passed to the generator (when in streaming mode) or back to a callback provided by the protocol implementation (when not in streaming mode). Only one vector is inflight at a time.
This design does not fit well for H3, as the flattened input it obtains is as tiny as a fraction of a packet. To keep the number of interactions between the protocol handler and the generator low, and to keep the BDP reasonably large, the H3 implementation needs to concatenate the payload received in multiple …
=> Refactor request streaming API

t/90dtrace.t
This fixes occasional test issue in t/90dtrace.t.
Note that updated code is slightly different from the example that can be found in the DTrace book.
In Section 8, the book suggests using
```
this->foo = (char *)copyin(arg1, arg2 + 1);
this->foo[arg2] = '\0';
```
Compared to that, our code does not copy an extra byte, or use `this->`.
Our code seem to work fine on macOS 10.12, but it might become an issue on other platforms.
=> null-terminate strings in dtrace script

CMakeLists.txt
quicly probes weren't activated.
=> activate quicly probes too

deps/quicly/include/quicly.h, deps/quicly/lib/quicly.c, deps/quicly/src/cli.c, h2o.xcodeproj/project.pbxproj, include/h2o/ebpf.h, include/h2o/http3_common.h, include/h2o/http3_server.h, include/h2o/socket.h, lib/common/socket.c, lib/common/socket/evloop.c.h, lib/common/socket/uv-binding.c.h, lib/http3/common.c, lib/http3/server.c, src/main.c, src/ssl.c, src/standalone.h, t/40http3-asroot.t
* send and receive AEAD-encrypted tokens (incl. resumption tokens)
* add configuration knob to enforce retry
* as well as expanding the EBPF map value to 64-bit bitmap for fine-grained control of retries
* add dtrace-based test (for retries)
ToDo:
=> [h3] send and validate token

lib/common/socketpool.c, lib/core/context.c
We ensure this by only letting one thread update the timers: the first
one that called `h2o_socketpool_register_loop`. The other threads can
still expire sockets, just not adjust the timer for the next expiration.
=> Make sure several threads are not accessing the timerwheel

lib/http3/common.c
From `man 7 ip`:
> If IP_PKTINFO is passed to sendmsg(2) and ipi_spec_dst is not zero,
> then it is used as the local source address for the routing ta‐ ble
> lookup and for setting up IP source route options.
=> Fix pktinfo usage

h2o-probes.d
Hello! I noticed a trivial oversight while working on request-layer USDT probing. It's going to take me a bit longer to complete that work, so I'm submitting this nit-of-a-change ahead of time.
=> DTrace: Consistently use uint64_t for req_index 

h2o-probes.d, lib/http1.c, lib/http2/stream.c, lib/probes_.h, t/90dtrace.t
Hi! This PR adds a USDT probe and its test for tracing the HTTP response status. Only H1 and H2 requests are instrumented for consistency with the other req-level probes.
=> Add a USDT probe for tracing the response status

lib/common/http2client.c
Fixes https://github.com/h2o/h2o/issues/2180. It can be still linked when either IO error or IO timeout happen. It's hard to write a test for this case, because defer_timeout is zero-timeout
=> Remove wrong assertion of defer_timeout of http2client

lib/http1.c, lib/http2/stream.c, lib/probes_.h
There's no need for the caller to pass the status code, because the status is obtained through `req->res.status`. Apologies for the oversight.
=> Remove an unused arg from h2o_probe_log_response_status

t/50mruby-http-request.t, t/50mruby-redis.t, t/Util.pm
The assumption made by the test suite that certain ips will blackhole is not correct in all environments. e.g:
``` 
$ telnet 192.0.2.0 123
Trying 192.0.2.0...
telnet: Unable to connect to remote host: Network is unreachable
```
This adds a `find_blackhole_ip()` helper to help scenariis testing for
timeouts find an appropriate target ip.
=> Perl blackhole-ip finder

include/h2o/socket.h
OpenSSL exposes OPENSSL_NO_NEXTPROTONEG when the no-nextprotoneg flag is passed at build time which has the effect of disabling NPN support. ALPN is hard-coded on and cannot be disabled, so this flag shouldn't affect that at all.
Fixes #2056
Signed-off-by: James Taylor <james@jtaylor.id.au>
=> Detect NEXTPROTONEG (NPN) support on OpenSSL

lib/http3/server.c
Creates a utility function that can be called upon a stream-level error for transitioning to the stream state to CLOSE_WAIT. Also promotes UNEXPECTED_FRAME_ERROR from stream-level to connection-level.
=> [http3] refactor error handling

include/h2o/string_.h, lib/common/string.c, lib/core/proxy.c, lib/handler/mruby/http_request.c, lib/http2/hpack.c, lib/http3/qpack.c
Until now, we have used `H2O_UINT64_LONGEST_STR`, because it is hard to define `H2O_SIZE_T_LONGEST_STR` as a string constant, as it is impossible do `#if sizeof(size_t) == x`.
However, that has caused confusion and have led to inconsistent coding pattern.
Therefore, we will introduce `H2O_SIZE_T_LONGEST_STR`. It is defined as `H2O_UINT64_LONGEST_STR`, along with a guard that generates a compiler error when sizeof(size_t) exceeds 64 bits. We will be wasting some space when sizeof(size_t) == 4, but it is no worse than status quo.
=> Introduce H2O_SIZE_T_LONGEST_STR

src/main.c
The commit a42769ce4dceee6c57e9453e59af5e67ab9d267f removed H2O_USE_OCSP but it was still refered to, so OCSP stapling was always 'not used'. The [other piece where H2O_USE_OCSP was used](https://github.com/h2o/h2o/blob/572ba09118ecb84fe4daf530b3302a8997146b73/src/main.c#L93-L104) is now [enabled unconditionally](https://github.com/h2o/h2o/blob/47814cd5a7cf9ed76137d623d3bf91d3397b71c4/src/main.c#L91-L100), so I did the same.
=> Reinitiate OCSP stapling.

t/90dtrace.t
In #2194, I had neglected to update the test code for non-Linux platforms (in practice,  disrupting macOS users). The fix is a shameless copy of `receive_request_header` probe attachment, but it is sufficient to satisfy the failing test cases.
=> Fix the outdated non-Linux dtrace test setup

lib/http2/connection.c
This is harmless because there are no values that have the highest byte set
=> Nit: LIT16 wouldn't encode 16 bits values correctly

src/main.c
[They are declared as deprecated in picotls](https://github.com/h2o/picotls/blob/5efacc294212092683207c5a873e25ddb56f9f5d/include/picotls/openssl.h#L55) and I don't see any good reason to continue to use them in h2o except they save a byte per their occurrence in each developer's workspace.
=> Avoid deprecated PTLS_OPENSSL_HAS_*.

src/ssl.c
As reported by #2223, we use UINT_MAX in src/ssl.c, therefore need to include limits.h there.
=> add missing include

lib/http3/server.c
Hi! This PR adds `h2o_probe_log_request()` and `h2o_probe_log_response()` calls to hopefully the correct location in the http3 server code path. I checked using Linux with  h2o-httpclient + [h2olog](https://github.com/toru/h2olog) that the probes are indeed triggered.
=> Instrument H3 code path with req-level dtrace probes

h2o.xcodeproj/project.pbxproj, h2o.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Two minor improvements on h2o.xcodeproj:
1. Stop sticking to specific version of openssl (1.0.2). The user can symlink their preferred version
2. xcode generates xcshareddata as of version 9.3, that should usually be committed to repo
These changes removes annoying diffs.
=> h2o.xcodeproj

include/h2o/socket.h, lib/common/http1client.c, lib/common/socket.c, lib/common/socket/evloop.c.h, lib/common/socket/uv-binding.c.h, lib/tunnel.c
Follow up of https://github.com/h2o/h2o/pull/2197
As https://github.com/h2o/h2o/pull/2197#discussion_r356912066 stated, `sock->bytes_read` was contradicting to [the API comment](https://github.com/h2o/h2o/blob/master/include/h2o/socket.h#L114): it was delta from previous callback invocation, not total value. This PR makes it be real total size of bytes the socket ever read.
=> make sock->bytes_read cumulative

lib/http3/common.c
It's possible that `quicly_send_version_negotiation` returns NULL.
=> Avoid potential NULL deref

include/h2o.h, lib/core/request.c, lib/handler/mruby/middleware.c, lib/handler/redirect.c, t/50mruby-middleware.t
Thanks to https://github.com/h2o/h2o/issues/2255 reported by @utrenkner, I found and fixed several issues around `H2O.next` and `H2O.reprocess`.
1. H2O.reprocess didn't actively use internal redirect. If the authority of the sub request (which is generally constructed by host header) doesn't match to hostconf's name, it does proxying, which establishes a TCP connection. This PR applies the same logic as redirect handler to resolve authority, which uses `req->hostconf->authority` in a base url for resolving.
2. `rack.early_hints` was not removed when constructing sub request. As the result, it was set in env. This PR removes it.
3. Samely, `CONTENT_TYPE` was not handled correctly. It's a special env key that has no `HTTP_` prefix, but current implementation doesn't treat it specially, so …
=> fix mruby middleware issues

include/h2o.h, lib/core/config.c, lib/core/configurator.c, lib/core/context.c, lib/core/request.c, lib/handler/mruby.c, lib/handler/status/durations.c, t/00unit/lib/handler/fastcgi.c
Fix https://github.com/h2o/h2o/issues/2234
`hostconf->paths` may be reallocated in `h2o_config_register_path`, but currently mruby handler has its reference. This PR fixes it by registering all paths at first, then configuring all paths
=> two phase path configure

lib/http2/hpack.c
[Section 8.1.2.3 of RFC 7540](https://httpwg.org/specs/rfc7540.html#HttpRequest) states that _clients that generate HTTP/2 requests directly SHOULD use the :authority pseudo-header field instead of the Host header field_.
However, H2O simply drops the Host header field.
This PR fixes the problem. The logic is intentionally lax, as it is about dealing with intermediaries that possibly forwards a HTTP/1.0 request to a HTTP/2 (or HTTP/3) server.
Thanks to @martinduke for recognizing the interop issue, thanks to @mikebishop for explaining what is the correct behavior.
=> use Host header when `:authority` is absent

srcdoc/install.mt
I think this is worth adding to the doc because (1) `-DCMAKE_BUILD_TYPE=Release` is not the cmake default (2) the copy-and-paste-ready snippet `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=-g3` is useful for everyone who uses gdb for H2O.
=> mention to -DCMAKE_BUILD_TYPE=Debug

h2o-probes.d, lib/http2/connection.c, t/90dtrace.t
This PR introduces a DTrace probe point for logging unknown HTTP/2 frame type.
This is an improvement of #2225 and removes unconditional `printf`.
=> [http2] Add probe for unknown frame type

src/main.c
Setting the SO_REUSEADDR socket option is essential for TCP listen ports, in order to avoid TIME_WAIT.
However, we should not set the socket option for UDP sockets, because there is no TIME_WAIT phase in UDP, and because it has a different meaning. Quoting from http://www.kohala.com/start/mcast.api.txt:
```
More than one process may bind to the same SOCK_DGRAM UDP port if the bind()
is preceded by:
int one = 1;
setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one))
In this case, every incoming multicast or broadcast UDP datagram destined to
the shared port is delivered to all sockets bound to the port.  For backwards
compatibility reasons, THIS DOES NOT APPLY TO INCOMING UNICAST DATAGRAMS --
unicast datagrams are never delivered to more than one socket, regardless of
how many …
```
=> avoid setting SO_REUSEADDR on UDP sockets

lib/http3/common.c
This is necessary so that the length used here:
https://github.com/h2o/h2o/blob/master/lib/http3/common.c#L387 can't overflow the destination buffer
=> [http3] Ensure that the CID is lower than QUICLY_MAX_CID_LEN_V1

lib/http2/connection.c
When a dependency stream has already been closed, current priority
handling code would crash by an assertion failure, because under a
certain condition h2o_http2_scheduler_find_parent_by_weight may
return the current node itself as a parent, and simply passing it to
h2o_http2_scheduler_rebind later is an incorrect behavior.
This patch adds a check for the return value of
h2o_http2_scheduler_find_parent_by_weight, just like we already do
in send_headers (lib/http2/stream.c).
Input sequence to reproduce the crash (by h2get) is:
h2g.send_priority(7, 0, 1, 1)
h2g.send_priority(9, 7, 1, 0)
h2g.send_data(7, 0x2, "00000")
h2g.send_priority(7, 0, 1, 0)
h2g.send_priority(9, 7, 1, 0)
Credit to OSS-Fuzz: This bug was found by OSS-Fuzz
(https://github.com/google/oss-fuzz)
=> Prevent crash in PRIORITY frame handling

lib/http1.c
conn->sock->input can't be free'd before calling
`h2o_dispose_request(&conn->req);`, because `h2o_dispose_request` calls
the logging handlers, which in turn might log parts of the socket input
buffer.
=> Fix loggging user after free

lib/http3/server.c
Consider the following scenario:
1. handler provides data
2. the data gets sent
3. proceed callback is called and `H2O_SEND_STATE_FINAL` is delivered immediately
4. ACK is received
This behavior was observed when running t/40http3.t on macOS.
=> [http3] fix resource leak

src/httpclient.c
Eventually we might implement buffer size auto-tuning in quicly, but until then, we need this option (for benchmark).
=> [http3][client] add `-W` option for specifying window size

.github/workflows/main.yml
OSS-Fuzz was wondering if h2o would dogfood CIFuzz, a new feature being rolled out in OSS-Fuzz. It allows for pull requests to be fuzzed in CI using fuzz targets enabled in OSS-Fuzz. It will be active in dry_run mode meaning that it will never fail. Documentation for this feature can be found [here](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). Let us know if you have any questions!
=> CIFuzz Dog Food

t/50priority-overwrite.t
This commit adds a regression test case for a crash in PRIORITY frame handling. (#2273)
Credit to OSS-Fuzz: This input pattern was found by OSS-Fuzz
=> Add a test case for priority crash case

lib/http3/common.c
Identified thanks to quic.tech:8443 using extended unidirectional stream types. We should consider adding that to our self test.
=> [http3] consume data in a way that works correctly with the caller

lib/common/http1client.c
Not doing so would result in h2o timing out while the request body
was still being sent by the client.
=> Reset the timeout as we get body chunks

srcdoc/install.mt
The [out-of-source build](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#what-is-an-out-of-source-build) is officially recommended, and it makes us avoid some kinds of build errors like https://github.com/h2o/h2o/issues/2093 by removing the build directory easily.
Also, I've explained `H2O_ROOT` in the doc to run H2O on the project directory without installing it.
=> [doc] recommend out-of-source build, explain H2O_ROOT

CMakeLists.txt
The OpenSSL root path on macOS might not be `/usr/local/opt/openssl` _as of May 2020_ because:
* The basename of homebrew-provided OpenSSL is `openssl@1.1` by default, not `openssl`
* See https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl@1.1.rb or `brew info openssl`
* Some people use a non-default homebrew root path
So I believe CMakeLists.txt should use `brew --prefix openssl` as the default.
=> [build] Find OpenSSL in macOS with `brew --prefix openssl` automatically

lib/http2/connection.c
Here is the path that's causing this:
```
stream_send_error lib/http2/connection.c
proceed_request lib/http2/connection.c
on_head lib/core/proxy.c
on_error lib/common/http1client.c
on_send_timeout lib/common/http1client.c
```
=> Prevent an assertion if proceed_request needs to send an error while the http2 connection is shutting down

misc/docker-ci/Dockerfile
This PR is necessary because nghttp2-client doesn't ship with Ubuntu
16.04 (it does in successive releases, this is why there's no need for a
similar PR for 19.04).
This is using 1.30 because the latest nghttp2 (1.40 currently) can't
compile with 16.04's compiler.
This was pushed to docker.io/kazuho/h2o-ci as c677c72e674e
=> Add h2load to the Ubuntu 16.04 image

lib/handler/mruby/middleware.c
trivial one just to quiet the warning in modern gcc
=> fix warning for unused variable (trivial)

lib/common/http2client.c
otherwise it causes null pointer dereference when forward is 0 and the node found is immediate previous node of the node we're removing (i.e. `node` becomes identical to `&conn->super.link`)
=> skip connlist reorder when it expects no effects

lib/common/socket.c
It's better to check error condition early.
Thank you.
=> check error code of `decode_ssl_input()`

t/Util.pm
When the tests are run as root, then tests where h2o connects to an upstream server via a unix socket are failing.  The upstream server creates the socket 'file' as root, but h2o running as 'nobody' is not be able to access it, hence the tests are failing with an upstream connection error.  This change adds `user: root` to the h2o config used in tests, if the tests are run under root.
For example [GitHub Actions runners using Docker require running as root](https://help.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user).
=> add 'user: root' to h2o conf in tests when running as root

deps/quicly/lib/quicly.c, lib/http3/common.c
Makes one design change and one bug fix.
The design change is that incoming QUIC packets are grouped by a tuple of (path, DCID) and then dispatched, rather than just using the path as the key. The resolution of https://github.com/quicwg/base-drafts/issues/2844 was to prohibit such a design.
The bug fix is that the code used for comparing the paths of two incoming packets was broken, leading to something that looks like packet losses, as packets were misrouted to incorrect paths or to incorrect connection contexts. This PR addresses that bug.
Closes https://github.com/h2o/quicly/issues/345.
=> [http3] process incoming packets by group of (path, DCID), fix broken path comparison logic

deps/quicly/include/quicly.h, deps/quicly/lib/quicly.c, deps/quicly/misc/probe2trace.pl, deps/quicly/src/cli.c, deps/quicly/t/test.c, src/main.c, src/ssl.c, src/standalone.h, t/00unit/src/ssl.c
As stated in https://github.com/h2o/quicly/pull/356, our support for draft-28 came with a code that associates certain TPs to NEW_TOKEN tokens and validates them. This is incorrect.
What we should be doing is associate the TPs to TLS session tickets, and upon mismatch, reject 0-RTT.
This PR is the H2O-side of the fix (quicly-side fix is https://github.com/h2o/quicly/pull/356).
=> [http3] Check Transport Parameters associated to session tickets

.github/ISSUE_TEMPLATE/custom.md, README.md, SECURITY.md
Hello,
This PR adds a [github.com security policy](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) to the h2o repo. It also adds a basic [Github Issue Template](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository). Together, these changes should result in:
- A Github Issue workflow that directs users to report security issues privately
- Explicitly capturing the security policy using up-to-date github.com conventions
The security policy aims to reflect the existing vulnerability coordination and disclosure policies for h2o. Feedback and direct edits from maintainers are welcomed of course!
Thanks,
Jon
=> Add SECURITY.md

deps/neverbleed/README.md, deps/neverbleed/neverbleed.c, deps/neverbleed/neverbleed.h, deps/neverbleed/test.c, src/main.c
Previously, the only way that we could distinguish the h2o process serving requests and the neverbleed process was by checking their relationship (i.e. parent vs. child). This PR sets the name of the neverbleed process to "neverbleed" by overwriting `argv`. Doing so helps people using `pidof`.
The feature is currently limited to linux. Even though `argv` rewrite is a popular technique, it is not known to be safe or work across multiple platforms. As an example, it is impossible to change the command name detected by `pidof` of homebrew, by rewriting `argv` (or by changing the vector by calling `_NSGetArgv`).
=> Change process name of neverbleed

CMakeLists.txt, h2olog/generated-quic.cc, h2olog/quic.h
Reported by @syohex  at https://github.com/h2o/h2o/pull/2353#issuecomment-650887319
@kazuho `st_quicly_stats_t` is empty and thus `conn_stats` event is useless, but if you need some fields, I'll add them.
=> Fix h2olog to follow the latest quicly-probes.d (st_quicly_stats_t)

CMakeLists.txt
This change introduces a convenience target 'checkdepends'.
A usual sequence to build and test currently looks like this after running cmake (args omitted for brevity):  
`$ make`  
`$ make check`  
In this case `make check` still *builds* some dependencies before starting the actual test scripts.  This change will allow to run the tests in parallel by adding a target that builds all remaining dependencies for check:  
`$ make`  
`$ make checkdepends`  
After that one can run tests in parallel:  
`$ env H2O_ROOT=. BINARY_DIR=<bindir> prove -I. -v t/<filtersometestscripts>.t`  
I was able to cut the build+test time drastically running like eight test runners in parallel - see screenshot in the attachment.
In my current approach I am figuring out the remaining `make check` dependencies …
=> new checkdepends convenience target

t/40memcached-session-resumption.t, t/40session-ticket.t, t/Util.pm
This is a continuation of #2337 to allow tests to run on systems when root is required to run the tests. The tests involving memcached otherwise have error:  
`spawning memcached... can't run as root without the -u switch`.  
For example [GitHub Actions runners using Docker require running as root](https://help.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user).
=> add -u switch to memcached when tests run as root

t/50mruby.t, t/50unexpected-upstream-body.t
Double backslash in some test scripts break on system w/o backslash escape interpretation, hence removing them.  
The construct of `echo "something" | nc ..` is used in a few tests, but only the two files changed it is used with double backslash.  
```
$ grep -ir --include="*.t" -E "*.echo .* \| nc .*"
..
50mruby.t:        my $cmd = "echo 'GET $path HTTP/1.1\\r\\nHost: 127.0.0.1\\r\\n\\r' | nc 127.0.0.1 $server->{port}";
50unexpected-upstream-body.t:    my $resp = `echo 'GET $path HTTP/1.1\\r\\n\\r\\n' | nc 127.0.0.1 $server->{port}`;
..
```
=> remove double backslash in certain tests

include/h2o.h, lib/core/config.c, lib/core/configurator.c, lib/handler/status/events.c, lib/http1.c, t/40http1-timeouts.t
This PR adds a new `http1-request-io-timeout` parameter, in
milliseconds.
This allows to have a finer grained control on the activity on the http1 socket.
=> Add an IO timeout for http1

t/50server-timing.t, t/50suspend-body.t
On a system without nghttp tests in 50server-timing.t and 50suspend-body.t are failing.  This fix will skip those tests that rely on nghttp, just like it is done in other test scripts.
=> skip tests needing nghttp when nghttp is not available

include/h2o/openssl_backport.h, src/main.c
Otherwise compilation fails.
The dh.h header is for DH_free. It's normally implicit with ssl.h.
=> main: replace deprecated OpenSSL APIs

misc/docker-ci/check.mk
Mounting `tmpfs` uses 50% of the memory by default. It is enough for Travis because its Linux instances have [7.5G memory](https://docs.travis-ci.com/user/reference/overview/), but it's not for local VMs which tend to have less memory and to cause disk-full on a `docker build`. Adding `-o size=3G` is not a perfect solution, but likely to avoid disk-full.
=> [CI] allocate 3G for the workspace for non-travis env

t/50reverse-proxy/test.pl
... by increasing connection concurrency of Starlet.
The cause was a combination of the following factors:
* By default, Starlet accepts at most concurrent 10 connections.
* H2O creates a connection pool for each `proxy.reverse.url` directive, and another connection pool for "reproxy"-ing.
* One of the test case issues 10 concurrent requests using nghttp, then a different test case fetches an object through "reproxy"-ing.
When persistent connection to the backend server is turned on, 10 connections might be opened when handling concurrent requests from nghttp. If that happens, the reproxy test fails as Starlet would not accept a new connection.
=> Fix occasional test failures in t/50reverse-proxy*.t

t/50reverse-proxy-serialize-posts-3.t
I ran the tests on several systems including running locally (Fedora), on GitHub runners (Ubuntu), Alpine (docker and native) and last but not least via docker locally on kazuho/h2o-ci:latest. On all but running kazuho/h2o-ci:latest via docker on Travis CI the 50reverse-proxy-serialize-posts-3.t test script fails with an `Integer overflow in hexadecimal number` respectively `Hexadecimal number > 0xffffffff non-portable` error. Why?
The pattern of the chunked `body` tested is \<size in hex\>\r\n\<payload\>\r\n\<size in hex\>\r\n\<payload>... with a body size of 5000 bytes in the test scripts. On kazuho/h2o-ci:latest via docker on Travis CI it comes as `1388\r\naaaaaaaaa..` and succeeds (so basically it comes as one and only one chunk, so element 0, which is 1388 is the size (hex 1388 = …
=> fix chunk size accumulation in reverse proxy serialize post 3 test

.github/workflows/daily_coverity.yml
This patch adds a GitHub Actions setting to automatically submit the latest code to Coverity.
The script was tested using [act](https://github.com/nektos/act), but we'll need to monitor closely how it would work in the real GitHub environment.
=> Add GitHub Actions for daily Coverity Scan

lib/http3/qpack.c
This removes an unreachable statement and thereby fixing Coverity CID 1496168.
=> Fix incorrect condition in qpack

deps/quicly/include/quicly.h, deps/quicly/lib/defaults.c, deps/quicly/lib/quicly.c, deps/quicly/src/cli.c, src/main.c
Based on https://github.com/h2o/quicly/pull/377, adds `quic/amp-limit` property to the `listen` directive. The property accepts the amplification limit, the default being 3.
Below is the trace collected using h2olog when `quic/amp-limit` is set to 1.
```
{"type":"accept","seq":1,"conn":0,"time":1595728500650,"dcid":"d8d7e4120c6bfe89"}
{"type":"crypto-decrypt","seq":2,"conn":0,"time":1595728500650,"pn":1,"decrypted-len":1315}
{"type":"quictrace-recv","seq":3,"conn":0,"time":1595728500650,"pn":1}
{"type":"stream-receive","seq":4,"conn":0,"time":1595728500650,"stream-id":-1,"off":0,"len":512}
{"type":"stream-on-receive","seq":5,"conn":0,"time":1595728500650,"stream-id":-1,"off":0,"src":"010001fc03031fe63b4307c0b63d76db4461880ef34b011711d94df4e653cfa0ea163f4c8e90000006130113021303010001cd00000 …
```
=> [http3] knob for changing the amplification limit

include/h2o.h, include/h2o/socket.h, lib/core/logconf.c, lib/http1.c, lib/http2/connection.c, lib/http3/server.c
This feature is useful for checking which draft version of HTTP/3 was being used.
=> add `%{ssl.negotiated-protocol}x` for logging selected protocol

lib/common/socket.c
`h2o_socket_ssl_get_selected_protocol` currently sticks out, by using an assert.
=> SSL logging functions return NULL if SSL is not used

doc/configure/http1_directives.html, examples/h2o_mruby/h2o.conf, lib/handler/status/events.c, srcdoc/configure/http1_directives.mt
Hello! This PR accomplishes three things:
1. Export the `http1-request-timeout` and `http1-request-io-timeout` counters
2. Document `http1-request-io-timeout` (generated file is also checked in)
3. Enable the Prometheus handler in the example mruby h2o.conf (for dev convenience)
JSON output:
```
$ curl -s localhost:8080/status/json | grep http1-errors
"http1-errors.request-timeout": 1234,
"http1-errors.request-io-timeout": 1234,
```
Prometheus output via mruby:
```
$ curl -s localhost:8080/status | grep http1_errors_request
h2o_http1_errors_request_timeout{version="2.3.0-DEV@5ed940034"} 1234
h2o_http1_errors_request_io_timeout{version="2.3.0-DEV@5ed940034"} 1234
```
=> Document and export http1-request-io-timeout

include/h2o/file.h, include/h2o/memory.h, lib/common/file.c, lib/common/memory.c, src/main.c
[temp-buffer-path](https://h2o.examp1e.net/configure/base_directives.html#temp-buffer-path) must be a writable directory, but if not, h2o runs and will report errors when it is used in `h2o_buffer_try_reserve()`. I think it's better to validate if the spec of `temp-buffer-path` is correct.
=> validate temp-buffer-path in startup

lib/http1.c
`is_end_stream` must be always false in the else branch.
Fixes Coverity CID 1496186
=> http1: Remove redundant condition

include/h2o/http3_common.h, include/h2o/http3_internal.h, include/h2o/http3_server.h, include/h2o/httpclient.h, lib/common/http3client.c, lib/http3/common.c, lib/http3/server.c, src/httpclient.c, src/main.c
* split `h2o_http3_ctx_t` into `h2o_quic_ctx_t` and `h2o_http3_ctx_t`, where the latter is defined as a sub-class of the former.
* rename functions / structures unspecific to H3 from `h2o_http3_*` to `h2o_quic_*`
=> [http3] split H3 and QUIC layer

src/main.c
This change won't affect anything, but for consistency.
=> use SCNxXX constants for scanf-style functions

t/50status.t
In an attempt to not return until the server is up, `spawn_h2o` function actually tries to establish a connection against the server process being spawned. Once that succeeds, `spawn_h2o` closes that connection and returns.
The side-effect of that is that if the test script then immediately issues a request to the server, h2o might process that request before noticing that the aforementioned connection has been closed.
That leads to unexpected results that we see in the num-connections test in t/50status.t.
The obvious solution to this problem is to insert a wait right after returning from `spawn_h2o`. We have had that wait in some of the cases, but not all.
This PR add such wait to the locations that have been missed.
=> fix occasional CI failure in t/50status.t

include/h2o/httpclient.h, lib/common/http3client.c, src/httpclient.c, t/40http3-reconnect.t, t/assets/upstream.psgi
Thanks to the framework we introduced for HTTP/2 + TLS/1.3, we have been sending 425 whenever necessary in HTTP/3. But our client-side HTTP/3 code had not supported resumption, and it was impossible to test the feature.
This PR adds support for resumption incl. 0-RTT to the HTTP/3 client-side code, uses that for testing our support for 425.
=> [http3] add resumption and 0-rtt support to client, use that to test the server

doc/configure/access_log_directives.html, include/h2o.h, lib/core/logconf.c, lib/core/proxy.c, srcdoc/configure/access_log_directives.mt
Since it's convienient to provide information of both end for many occasion,
this patch provides following %{proxy.ssl.*}x format strings for server-side (upstream) TLS session:
proxy.ssl.protocol-version
proxy.ssl.cipher
proxy.ssl.cipher-bits
proxy.ssl.session-reused
Two dynamic data, server name and session id, are omitted to minimize memory use with use cases
which does not use this feature. By the way, server name at both ends must be same.
To do that, `h2o_req_t` remembers upstream SSL information at `on_connect()` and use it at logging.
proxy.ssl.* logging primitves are categorized as MAP_EXT_TO_TYPE.
This patch worked most PR comments of https://github.com/h2o/h2o/pull/2398.
--
I think that it is better not to leave cluttered commit history, so
I re-issue the PR#2398 here, to …
=> accesslog: upstream TLS info format strings for reverse proxy (reissue of PR#2398)

deps/quicly/include/quicly.h, h2o.xcodeproj/project.pbxproj, include/h2o.h, include/h2o/http3_common.h, include/h2o/http3_server.h, lib/core/config.c, lib/core/configurator.c, lib/http3/common.c, lib/http3/server.c, src/httpclient.c, src/main.c, t/40http3-concurrency.t
To mitigate slowloris attacks, our HTTP/2 stack restricts the concurrency of requests that are "streamed" to the upstream server to one per frontend connection.
We have had the code that does the same for HTTP/3, but it has not been exercised until now.
This PR enables the logic, by reducing the initial receive window size of a request stream to 32KB, then raising it up to 16MB (the same as the HTTP/2 "streamed" request receive window) once the request is promoted to "streamed" mode.
In addition, this PR adds a test case, delays the application of the globally configured settings to `quicly_context_t` until all the directives are processed, so that the order in which the configuration directives appear in the configuration file does not affect the values being used (amends #2423).
Builds …
=> limit POST concurrency

src/main.c
=> `mapping` is a mandatory field of `quic-nodes`

lib/http3/common.c
For example when there is no keyset corresponding to given CID (identified by the first byte).
=> [http3] sometimes it is impossible to generate stateless resets

include/h2o/qpack.h, lib/http3/qpack.c
H2O does not instantiate the QPACK encoder until it receives the SETTINGS frame, that contains the maximum QPACK table size that is accepted by the peer.
Note that the peer is required to send a QPACK decoder instruction when it resets the request stream, and that can arrive before the SETTINGS frame.
=> [http3] peer might send QPACK decoder instructions before the QPACK encoder is instantiated

lib/http3/server.c
Up until now, in the access log, the HTTP/3 protocol implementation has been reporting 0 bytes of response body being sent.
```
192.168.11.17 - - [08/Sep/2020:15:55:03 +0900] "GET /search/searchindex.js HTTP/3" 200 0 "https://127.0.0.1.examp1e.net:8443/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4257.0 Safari/537.36"
```
This PR fixes the issue by adding `entity_offset` field to each send vector, and using the value of that field to update `h2o_req_t::bytes_sent` as H2O emits data.
=> [http3] report correct values for `%b` (bytes_sent)

lib/http1.c, t/50file-config.t
While needed years ago, this is not needed anymore, and it can lead to
surprising behaviors if the intermediate modifies the header.
=> Remove MSIE `vary:` workaround

src/h2olog/h2olog.cc
Technically `h2olog` only needs root privilege to:
1. Attach the BPF tracepoints
2. Open the BPF ring buffer
Therefore drop the root privilege as soon as the two operations are complete. Error handling may seem unforgiving but it follows a consistent pattern in `h2olog`.
=> h2olog: drop the root privilege once BPF is set up

src/main.c
Worker threads refer to values on the stack of the main thread, the most notable one being `conf.threads[].ctx`.
In the current design, any thread can call `_exit`, and then threads will be destroyed in an unspecified order. If the main thread gets destroyed and then a worker thread refers to `conf.threads[].ctx`, SEGV can be raised.
=> retain the main thread until all the worker threads exit

lib/common/http3client.c, lib/http3/server.c, t/40http3.t, t/assets/upstream.psgi
Status quo fails to transmit FIN when all the bytes being sent to the client has been acked then upstream closes the connection. This PR, specifically 4df864d, addresses this bug.
Additionally, this PR fixes the http3 client reporting an abnormal close of a stream (including the behavior explained above) as "malformed frame."
=> [http3] transmit FIN when upstream closes after all the response body have been acked by the client

lib/http3/common.c
This PR adds an early return to `discard_handle_input()` if the `src` pointer is NULL. This happens on a rare occasion when handling a RESET.
=> http3: check the pointer before dereferencing

deps/quicly/include/quicly.h, deps/quicly/include/quicly/frame.h, deps/quicly/lib/quicly.c, deps/quicly/misc/probe2trace.pl, deps/quicly/misc/quic-interop-runner/Dockerfile, deps/quicly/misc/quic-interop-runner/run_endpoint.sh, deps/quicly/src/cli.c, deps/quicly/t/lossy.c, deps/quicly/t/test.c, include/h2o.h, lib/core/config.c, lib/core/configurator.c, lib/http3/server.c
* updates quicly to the revision that has support for delayed ack -01 (https://github.com/h2o/quicly/pull/411)
* adds a knob (`http3-delayed-ack`) for turning on / off the extension (default is ON)
=> Update support for delayed ack extension

include/h2o/http3_common.h, include/h2o/http3_server.h, lib/common/http3client.c, lib/http3/common.c, lib/http3/qpack.c, lib/http3/server.c, src/main.c
Following #2467, this PR does the following:
* QPACK table capacity of the encoder is now configurable using the `qpack-encoder-table-capacity` parameter of the `listen.quic` attribute. The default value is 4096.
* Reducing the table capacity of the encoder to zero will help when _clients_ have issues with decoding the _response_ header fields that h2o sends.
* Renames the SETTINGS values following the changes to the spec.
* Adds code to respect `SETTINGS.QPACK_BLOCKED_STREAMS` advertised by the peer. Until now, we have used a hard-coded value of 100.
=> turn QPACK table capacity (encoding side) into a configurable parameter

lib/http3/qpack.c, t/00unit/lib/http3/qpack.c
When receiving a header name that is an uncompressed literal, the QPACK decoder was using the address of the literal, rather than the literal itself, as the header field name.
This PR addresses the issue as well as adding a round-trip test that uses an uncompressed literal.
=> fix error in QPACK header decoder

include/h2o.h, lib/handler/compress.c
There is a small typo in include/h2o.h, lib/handler/compress.c.
Should read `explicitly` rather than `explicitely`.
=> docs: fix simple typo, explicitely -> explicitly

lib/http3/server.c
This aligns http3's behavior to http2's.
=> http3:  Reset graceful shutdown timer cb once fired

include/h2o.h, lib/handler/status/events.c, lib/http2/connection.c
Just like as `http1-errors.request-timeout` and `http1-errors.request-io-timeout` in the "events" status handler. 
JSON output:
```
$ curl -sfL http://127.0.0.1:8080/status/json | grep http2.idle-timeout
"http2.idle-timeout": 8,
```
=> add a status field: http2.idle-timeout

share/h2o/annotate-backtrace-symbols
As commented, `backtrace_symbols_fd(3)` shows different output in clang 10 and gcc 9 on Ubuntu 20.04 , especially if `-rdynamic` is not specified. 
This PR is checked with `backtrace(3)`'s sample program: https://man7.org/linux/man-pages/man3/backtrace.3.html
=> fix the compatibility of annotate-backtrace-symbols with the latest gcc

lib/common/socket.c, src/main.c
macOS SDK for 10.16 added support for IP_DONTFRAG, but macOS 10.15 does not provide runtime support for the socket option.
Hence, failure to set that socket option should not be consider a fatal issue.
=> [http3] fix startup failure when OS does not provide support for IP_DONTFRAG

include/h2o.h, include/h2o/http3_common.h, include/h2o/qpack.h, lib/common/http3client.c, lib/core/request.c, lib/http3/qpack.c, lib/http3/server.c, t/00unit/lib/http3/qpack.c
This PR addresses the following two complexities:
* Eliminates use of `memmove`. Existing API let's the user supply an existing buffer, to which the HEADERS frame and the QPACK payload is appended. That design requires use of `memmove`, as the size of the frame header and QPACK header depend on the QPACK payload. This PR eliminates `memmove` by changing the API to instead return a memory buffer allocated from the memory pool.
* Eliminates unnecessary duplication of send vector containing the HEADERS frame. At the moment, the send vector containing the HEADERS frame is initialized by calling `h2o_sendvec_init_raw`. The downside is that the vector gets duplicated when `on_send_emit` calls `retain_sendvecs`. This PR avoids duplication by leveraging the fact that memory used to build the …
=> [http3] refactor header field encoding process

src/h2olog/h2olog.cc
As discussed at https://github.com/h2o/h2o/pull/2492#issuecomment-730737191.
This PR has slightly changed the semantics of `-l` in order to test what`-t` actually select, like:
```
h2olog quic -t 'quicly:*' -l
```
The behavior of `-l` does not change without `-t`.
=> h2olog: make -t to accept a glob pattern like "quicly:*"

CMakeLists.txt
Some cmake generators like Ninja cannot handle implicitly generated files, failing with messages like (in case of Ninja):
> ninja: error: 'mruby/host/lib/libmruby.a', needed by 'h2o', missing and no known rule to make it
The solution is just to define files with `BYPRODUCTS libmruby.a libonigumo.a` in `ADD_CUSTOM_TARGET`.
With this patch, `cmake -G Ninja -Bb . && cmake --build b` works!
=> cmake: state libmruby.a and libonigmo.a are generated on building mruby

lib/http3/common.c
This patch replaces raw hex numbers for QUIC packet types with macro
constants defined in quicly.
=> [http3] Use QUIC packet type macro constants

t/50reverse-proxy-early-response.t
There are two problems in the test:
* `is_alive`'s implementation where `recv()` returns always falsey.
* timing issues in `Subtest: (1) h2 up x h1 down`
Thanks to @kazuho and @i110 for debugging sessions.
=> fix a possible failure in t/50reverse-proxy-early-response.t

include/h2o/string_.h, lib/core/request.c
A bit pedantic I know, but avoids a `memcpy` per request.
`strtolower_cpy` could go into `string_.h` (prob as something like `h2o_strtolower_cpy`) but thought those are very specific.
thank you.
=> avoiding a memcpy in find_hostconf

lib/http1.c, t/50reverse-proxy-early-response.t
This PR fixes a coverity defect https://scan7.coverity.com/reports.htm#v29627/p11912/fileInstanceId=85147268&defectInstanceId=16919126&mergedDefectId=1496212.
As of https://github.com/h2o/h2o/pull/2010 `handle_one_body_fragment` function may invoke `cleanup_connection`, so we have to consume the buffer before the connection gets freed (or reused for the next request).
=> consume buffer at once

t/40tls13-early-data.t
This is not a fix for h2o/h2o#2509, but because it is difficult to investigate and is a blocker to #2501, I've made this workaround so far.
=> workaround to avoid t/40tls13-early-data.t timing issue (h2o/h2o#2509)

.github/workflows/ci-default.yml, .github/workflows/ci-dtrace.yml, .github/workflows/ci-fuzz.yml, .github/workflows/ci-openssl_1_1_0.yml, .github/workflows/ci-openssl_1_1_1.yml
There are cases where maintainers want to run CI without creating a branch (e.g., testing CI issues). We have been using Travis CI that way, and there's no reason to change the work pattern for GitHub Actions.
=> Run CI when pushed, like we do for Travis

t/40tls13-early-data.t
When the standalone server is spawned, [an independent thread is created for updating the session ticket encryption keys](https://github.com/h2o/h2o/blob/5de9a86/src/ssl.c#L1112). Until the thread fetches the necessary keys (or generates one by itself), the encryption key is not available.
When a client connects to the server before the encryption keys become available, [a dummy key is used for generating the session ticket](https://github.com/h2o/h2o/blob/5de9a86/src/ssl.c#L274-L280). When a client uses such session ticket, resumption will fail, and 0-RTT data would de rejected.
t/40tls13-early-data.t is our end-to-end test that makes sure that 0-RTT works as expected, and therefore depends on the availability of a valid session ticket encryption key on the server-side. However, at the …
=> [test issue] avoid race condition bet. 0-RTT test and session ticket encryption key generation

t/50proxy-max-buffer-size.t
The timing requirement seems to be a bit too severe for GitHub Actions.
The three failed attempts reported values of: 2.0137, 2.0535, 2.0143. Therefore, changing 2 to 2.2 hoping that it would be sufficient.
=> [GitHub Actions] address failures in t/50proxy-max-buffer-size.t

include/h2o/socket/uv-binding.h, lib/common/socket/uv-binding.c.h
Fixes libuv timer handling to avoid random corruptions, as explained in details in #2511.
=> libuv: fixes timer handling (resolves #2511)

include/h2o/absprio.h, t/00unit/lib/common/absprio.c
This commit adopts quiche's priority to weight conversion formula for better interoperability with Chromium.
This is a follow up PR to #2431.
=> Update absolute priority -> H2 weight conversion formula

t/50reverse-proxy-early-response.t
Below is the log of a failed run on GitHub Actions.
If we look carefully, we notice the following:
* `spawn_h2o` returned some time around 06:33:10.329.
* H2O started accepting new connections at 06:33:10.826.
* H2O succeeded in connecting to the upstream server, but the socket was closed before receiving anything at 06:33:10.829.
The plausible explanation of this behavior is that the upstream server was killed too early, before accepting the connection from H2O or handling the requests. At the moment, we kill the upstream server 0.5 seconds after `spawn_h2o` returns.
This PR increases the timeout from 0.5 seconds to 1 second.
```
2020-12-24T06:33:10.2218559Z         # Subtest: body send error after sending headers[0m
2020-12-24T06:33:10.3292582Z spawning /home/ci/build/h2o... done …
```
=> [t/50reverse-proxy-early-response.t] don't kill upstream server before it receives a request

t/50graceful-shutdown.t
As discussed in #2526, the 0.5-second delay to kill the server is too small when running the test on GitHub Actions.
Looking at the log below, we do not see the message that says "h2o server ... is ready to serve requests" for 
the first subtest. The server was killed before it started handling requests. No wonder the client failed to connect to the server.
For the second subtest, we see the server barely succeeding in handling the request; the time window is just 0.03 seconds between when it started handling the request and when it received SIGTERM.
This PR addresses the issue by adding 1 second to all the delays being used. Note that this is the minimum addition delay that we can introduce, as the `sleep` method of h2get only accepts integers.
```
2020-12-29T00:42:08.9913769Z …
```
=> [t/50graceful-shutdown.t] more delay until the server starts handling the connection

src/h2olog/generated_raw_tracer.cc, src/h2olog/json.cc, src/h2olog/json.h, src/h2olog/misc/gen_raw_tracer.py
h2olog has assumed all the `char*` fields are null-terminated, but some strings passed to USDT probes are not null-terminated strings. This PR handles such non-null-terminated strings, assuming there's the corresponding `<name>_len` param.
=> h2olog: fix a bug that non-null-terminated strings are not handled correctly

src/main.c
At the moment, the logic tests the current value of the counter to see if it is below the limit, accepts the connections, then increments the counter. This design has TOCTOU issue as multiple threads might be running concurrently.
This PR addresses the issue by changing the logic from test-then-increment to increment-then-test-and-decrement-if-necessary.
While this issue might sound like theoretical, I think that it is why t/40max-connections.t fails occasionally, as shown in the log below. When H2O is being spawned, all worker threads are notified to start receiving new connections at the same moment. This TOCTOU issue will be observed if the time difference between when the threads receive that notification is smaller than the time required to accept a new connection.
``` …
```
=> [t/40max-connections.t] fix TOCTOU that leads to accepting more connections than configured

.github/workflows/ci.yml
As discussed in #2532, adding timeouts for CI jobs.
ref. https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
=> ci: add job-level `timeout-minutes: 60`

include/h2o/memory.h, lib/common/http3client.c
The second argument of `h2o_buffer_reserve` accepts the amount of additional space that has to be reserved. However, http3client has been over-allocating memory, by passing the entire size of the buffer.
This PR address the issue as well as adding clarification to the doc-comment of `h2o_buffer_reserve`.
In addition, it removes the unnecessary assertion around the use of `h2o_buffer_reserve`. It is unnecessary because `h2o_buffer_reserve` is guaranteed to succeed (or abort).
=> [http3client] fix incorrect use of `h2o_buffer_reserve`

lib/http3/server.c, t/50reverse-proxy-informational.t
Up until now, when the generator provides an informational response, our HTTP/3 implementation has been writing the response to the send buffer, without actually sending it.
This PR addresses the bug.
=> [http3] send informational response as they become available

lib/common/socket/evloop.c.h
Fix performance regression that went in with #2502. We fail to set TCP_NODELAY on linux. Also enables the test that we have had in the code path.
=> call setsockopt(TCP_NODELAY) when the address family is unknown

misc/docker-ci/Dockerfile.ubuntu2004
I've made sure an h2olog E2E test (https://github.com/h2o/h2o/pull/2520) works with this image. If it looks good, I'll push the image to DockerHub, restart this CI, and then merge this PR.
=> ci: update iovisor/bcc from a revision of 0.11.0-6021958a to 0.12.0

src/h2olog/h2olog.cc
`-p` should appear right in front of a process ID.
=> [h2olog] Fix parameter position in example usage

deps/quicly/include/quicly.h, deps/quicly/include/quicly/cc.h, deps/quicly/lib/cc-reno.c, deps/quicly/lib/defaults.c, deps/quicly/lib/quicly.c, deps/quicly/src/cli.c, deps/quicly/t/lossy.c, src/main.c
This PR does the following:
* Adds `initcwnd` parameter to the `listen` directive, that specifies INITCWND by the number of packets.
* Updates quicly to latest, incorporating https://github.com/h2o/quicly/pull/428, https://github.com/h2o/quicly/pull/429. https://github.com/h2o/quicly/pull/430.
Sample configuration file:
```yaml
listen:
port: 8443
type: quic     # set type to QUIC
cc: reno       # set CC to reno
initcwnd: 2    # set IW to 2
ssl:
certificate-file: tmp/127.0.0.1.examp1e.net/fullchain.pem
key-file: tmp/127.0.0.1.examp1e.net/privkey.pem
```
https://gist.github.com/kazuho/d520afd466e23edeb1a1939cb6ec49d5 shows the traces for iw2 and iw10; they look correct to me.
=> [http3] add knob to configure IW

examples/libh2o/socket-client.c, src/httpclient.c
`TLSv1_client_method` has been deprecated in OpenSSL 1.1.0. `TLS_client_method` is not available in older OpenSSL, but `SSLv23_client_method` is portable and not deprecated, which is `#define SSLv23_client_method    TLS_client_method` as of OpenSSL 1.1.1i.
=> fix deprecated warnings by s/TLSv1_client_method/SSLv23_client_method/

lib/core/proxy.c
At the moment, any HTTP version number above 1 is sent as "2."
=> [http3] set correct version number in the `via` header field

lib/common/memory.c
According to the documentation of `posix_fallocate`
> RETURN VALUE
>       posix_fallocate() returns zero on success, or an error number on failure.  Note that errno is not set.
Since errno is not set by `posix_fallocate`, potentially confusing error
messages can be printed as `h2o_perror` (called below) expects errno
to be set appropriately.
This change fixes this, so that h2o will print correct error messages if
`posix_fallocate` fails.
=> Fix fallocate error message.

.github/workflows/ci.yml
This PR tries to login DockerHub in order to mitigate a limitation-exceeded problem of docker-pull, which we have occasionally run into.
Authenticated users have doubled quota for docker pull, as https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/ describes:
> We detailed the following pull rate limits to Docker subscription plans that will take effect November 1, 2020:
> 
> Free plan – anonymous users: 100 pulls per 6 hours 
> Free plan – authenticated users: 200 pulls per 6 hours
---
I don't touch Travis CI settings until the limitation-exceeded problem arises again. 
The credentials are defined in this repository. See `Settings` -> `Secrets` if you have an admin permission.
=> ci: login DockerHub

src/main.c
SO_ACCEPTFILTER relies on the accf_http kernel module here, which is loaded only explicitly, thus we treat it only as a warning.
Other key difference, the connection needs to be listened firsthand.
=> connections listener, TCP_DEFER_ACCEPT's FreeBSD equivalent.

include/h2o.h, include/h2o/httpclient.h, lib/common/http3client.c, lib/core/proxy.c, lib/handler/proxy.c, src/httpclient.c
#2524 streamlined the httpclient API so that the reverse proxy handler could use HTTP/3 to the backend. But we do not have tests, nor was it ever used. Therefore, unsurprisingly, it did not work.
This PR makes it work at least, even if there aren't tests (yet).
Some things that are still missing:
* No tests yet.
* HTTP/3 client implementation does not validate the certificate chain or SNI.
* H3 reverse proxy does not use the load balancing mechanisms provided by the socket pool.
This PR also addresses bugs in the reverse proxy H2 initialization code. Up until now, it failed to initialize `client_ctx->http2.latency_optimization` and `client_ctx->http2.max_concurrent_streams`.
=> reverse proxy using H3 fixes

src/h2olog/generated_raw_tracer.cc, src/h2olog/json.cc, src/h2olog/json.h, src/h2olog/misc/gen_raw_tracer.py
This is useful for tracking objects that can be identified by their addresses (e.g., events that happen with same `h2o_socket_t *`).
=> [h2olog] dump unknown types by their addresses

CMakeLists.txt, misc/regen.mk
To follow the code generation manner in h2o.
=> [h2olog] define how generated_raw_tracer.cc is generated in regen.mk

lib/http1.c, t/50http1-proxy-full-uri.t
I think this is a bug that was introduce unintentionally as part of #1941.
=> [http1] respect the authority part of the absolute form

lib/common/socket.c
This PR amends #2397.
Before #2397, h2o had been delegating the handshake to OpenSSL regardless of the error being observed. That led us sending something.
With #2397, we stopped delegating the handshake to OpenSSL when CH is broken but known to be of TLS 1.3. However, in such case, h2o has been silently closing the connection without sending an alert.
This PR address the problem.
=> Send TLS alert before closing the connection, when h2o fails to process CH known to be of TLS 1.3

lib/http3/server.c
- make sure we don't use `datagram_flow_id` for CONNECT tunnels
- use datagram_flow_id as index in `conn->datagram_flows`
=> A couple of CONNECT-UDP fixes

h2o.xcodeproj/project.pbxproj, lib/http1.c, t/40http1-pipeline.t
When `phr_decode_chunked` concludes the processing of a chunked request body, it moves the input that followed the chunked-encoded request body to immediately after the decoded bytes. However, lib/http1.c assumes that the remaining bytes would not be moved.
That has caused h2o to process unexpected input as the next request.
This PR addresses the problem. In relation, the behavior of `phr_decode_chunked` is clarified in https://github.com/h2o/picohttpparser/pull/72.
=> [http1] fix error when handling a pipelined request following a chunked request

h2o.xcodeproj/project.pbxproj, lib/common/http1client.c, lib/common/socket.c, lib/http1.c, t/80chunked.t
When the request body is being closed without any additional data, and if the request body has been streamed, protocol handlers call `write_req.cb` with zero-length data. In response, http1client invokes `proceed_req` synchronously when a zero-byte chunk is being provided as part of request body streaming.
However, such behavior is unexpected on the caller side. To give an example, `proceed_request` of http1.c starts reading from the socket even after all the request body has been read. This is rather nasty, though the condition eventually gets fixed as the calls return.
This PR makes sure that `proceed_req` is called asynchronously.
=> [http1client] don't invoke `proceed_req` synchronously

src/main.c
it can touches `&conn->super` in the following line even if `conn == NULL`, which causes UBSAN warnings like 
```
runtime error: member access within null pointer of type 'h2o_http3_conn_t' (aka 'struct st_h2o_http3_conn_t')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/main.c:3256:19 in
```
=> suppress ubsan warning

lib/handler/connect.c
When the client discards a CONNECT request while the generator is trying to establish a connection, the connect timeout should be unregistered.
=> [connect handler] clear timer when the generator is disposed

src/h2olog/generated_raw_tracer.cc, src/h2olog/misc/gen_raw_tracer.py
When adding or removing USDT probes, it might make a large diff in  ` h2o_raw_tracer::do_handle_event()`'s switch-case at `generated_raw_tracer.cc` clause, which was really noisy in development & code review. This PR will fix this problem.
=> [h2olog] refactor to use enum for event ids to prevent making a large diff on changing USDT probes

CMakeLists.txt
Amends https://github.com/h2o/h2o/pull/2569. It has a regression that `generated_raw_tracer.cc` is not regenerated when one of its dependencies is updated.
https://stackoverflow.com/a/31518137/805246 (listing a dummy file in OUTPUT) doesn't work well for this case, causing recompile the generated file for each time. Instead, I've created a phony target just like as we do with `make`.
=> h2olog: force to triger regen.mk command  since dependencies are managed in the makefile

misc/docker-ci/build
`docker build` uses caches by default, which may result in build failures.
=> ci: do not use docker caches on building CI images

t/50mruby-error-log.t
The test assumes that once the server port becomes open, the only message being emitted to the log is that from the request handler.
However, messages like `h2o server (pid:19023) is ready to serve requests with 2 threads` are also emitted, and depending on the number of worker threads running, that message might appear _after_ the error message from the request handler.
As an example, see https://github.com/h2o/h2o/pull/2520/checks?check_run_id=2020292112.
This PR addresses that race by setting `num-threads` to 1.
=> [t/50mruby-error-log.t] set `num-threads` to 1 to avoid race bet. messages emitted from different threads

lib/common/socket/evloop.c.h
In case the origin sends data fast, it's possible that we read tens of
megabytes at once, which hurts latency without improving throughput in a
noticeable way. This PR limits the reads done per event loop to 1M.
=> limit reads to 1M

h2o.xcodeproj/project.pbxproj, lib/http3/server.c, t/50reverse-proxy-h3-early-response.t
When upstream server starts sending a response while request body is inflight, that response is called an early response. Upon observing an early response, h2o should continue forwarding both the request and response until the entire response is being received from upstream. FWIW, the reason why h2o can stop forwarding the request at that moment is because the completion of a response is a sign that the remainder of the request is no longer needed by upstream; see other issues related to early response.
In #2508, we introduced a regression. H3 server has started to refuse receiving request body as soon as it receives the response headers from upstream.
This PR fixes that bug, as well as addressing a crashing bug that has been revealed due to the fixture of that bug.
=> [http3] fix mishandling of early response

lib/http3/server.c
This is necessary since the stream could be closed (and thus `stream->tunnel` freed) before `establish_tunnel` has been called
=> detach the tunnel when disposing request

src/main.c, t/40reuse-port.t
This is necessary because `bind()` will fail on SO_REUSEPORT listeners if
these binds are made by different uids, from `socket(7)`:
> all of the processes binding to the same address must have the same effective UID.
=> Make sure all `bind()` calls are made before calling `setuid()`

t/50mruby-error-log.t
fixes CI failures like:
```
t/50mruby-error-log.t ................................ 
spawning /home/ci/build/h2o... done
[INFO] raised RLIMIT_NOFILE to 1048576
ok 1
not ok 2 - access log count
ok 3 - error log count
not ok 4 - access log
ok 5 - error log
1..5
not ok 1 - http/1
```
=> avoid timing issue bet. when response is being received vs. when log is being written

lib/http3/server.c
This further fixes the case described in https://github.com/h2o/h2o/pull/2616
=> Further fix: if the tunnel wasn't established, it's not in datagram_flows either

src/httpclient.c
Since `ctx.http3` is always set, one cannot determine if h3 was in
use by comparing `ctx.http3` with NULL.
=> [httpclient] Fix a way to detect h3 use

CMakeLists.txt
amends #2590. 
I'm not sure why I was confident that #2590 worked, but anyway it was wrong, so I've noted how I've tested this PR.
```shell
rm -rf build.cmaketest
cmake -Bbuild.cmaketest .
make -Cbuild.cmaketest h2olog
make -Cbuild.cmaketest h2olog
```
And then make sure the following two targets are shown:
```
[ 93%] Generating phony_force_trigger_command
[ 93%] Generating ../src/h2olog/generated_raw_tracer.cc
```
=> [fix] amends #2590; cmake does nothing for a phoney target with no dependencies

lib/handler/connect.c, lib/http3/server.c, lib/udp_tunnel.c
1) Destroy the tunnel in `establish_tunnel()` since `establish_tunnel()`
might know the stream has closed
2) Since `tunnel` might have been freed by `establish_tunnel()`, move
`proceed_read()` calls before `establish_tunnel()` is called
3) Remove the udp tunnel read from socket creation, and delay it to
`on_getaddr()`
=> Frontend-side tunnel close

lib/http1.c, lib/http3/server.c
This PR cherry-picks two bug fixes from upcoming PR #2607.
Commit 5e0232c fixes a bug in the http1 protocol handler that disarms the idle timer without rearming it, when receiving bytes that consists of only the chunk header of a chunked encoding.
Commit 30cf4e0 fixes a bug in the http3 protocol handler that erroneously raises an assertion failure when receiving FIN at the end of request body without any data being accompanied.
=> small fixes from pr 2607

src/httpclient.c
Previously, h2o-httpclient had `h2o_httpclient_ctx_t::http2.max_concurrent_streams` set to zero, and therefore H2 connections were never reused even though pooled. This PR changes the maximum to hard-coded value of 100.
Note however that even with this change, h2o-httpclient running with `-2 100 -C x` would open _x_ connections, because it tries to issue all requests simultaneously. At that moment, no HTTP/2 connection has been established and therefore the client cannot assume that the server can speak HTTP/2. Therefore, h2o-httpclient tries to create _x_ connections, each of them specifying both `h2` and `h1` in ALPN.
=> [h2o-httpclient] set H2 concurrency limit to 100

include/h2o/httpclient.h
Not doing so breaks the compilation of standalone programs that include `h2o.h`:
```
/usr/bin/ld: /tmp/ccghrRPU.o: warning: relocation against `h2o_httpclient_upgrade_to_connect' in read-only section `.text'
/usr/bin/ld: /tmp/ccghrRPU.o: in function `h2o_httpclient__tunnel_is_ready':
test.c:(.text+0x29): undefined reference to `h2o_httpclient_upgrade_to_connect'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
```
=> Make `h2o_httpclient__tunnel_is_ready` `static inline`

src/main.c
As pointed out by @hfujita in https://github.com/h2o/h2o/pull/2653#discussion_r608020734.
This is bug during configuration phase and therefore I'm going to omit tests.
=> fix error handling on TLS cipher-suite config failure

src/main.c, t/40http3-corrupted-scid-initial.t
Upon receiving a QUIC Initial packet, the current logic first increments
the connection counter, but fails to decrement it when it turns out to be
a non-decryptable Initial. This would cause a "leak" of the counter when
such a packet is received.
=> [http3] Revert connection count on Initial decryption failure

src/h2olog/misc/gen_raw_tracer.py
We need to support Python 3.5 for the time being.
=> h2olog: fix python 3.5 compatibility issues

lib/http3/common.c
E.g.,
```
lib/http3/common.c: In function 'h2o_quic_send_datagrams':
lib/http3/common.c:134:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
((struct in_pktinfo *)CMSG_DATA(&cmsg.hdr))->ipi_spec_dst = src->sin.sin_addr;
```
Current code is assumed to not cause any harm (as the values being written are referred to only by the kernel), but it is embarrassing nonetheless. Hence the fix.
=> use memcpy to avoid warnings from `-Wstrict-aliasing`

t/40error-log-escape.t
Found `t/40error-log-escape.t ` failed  in https://travis-ci.org/github/h2o/h2o/jobs/767003907 
The test uses an empty port as an upstream that is expected to cause "connection failure", but sometimes it causes "first byte timeout". I guess that's because someone uses the port so that connect() succeeds.
=> fix a flaky test to ensure an upstream port to cause "connection failure"

t/40running-user.t, t/90dtrace.t, t/90root-fastcgi-php.t, t/Util.pm
This is required by https://github.com/h2o/h2o/pull/2655 but I've made a separate PR here to make sure this change does not break existing tests.
=> test: make "user" configuration overridable in spawn_h2o()

lib/http2/connection.c
h2olog cannot handle the `h2o:h2_unknown_frame_type.frame_type` field correctly. The type of `frame.type` is `uint8_t`, and the USDT `h2o:h2_unknown_frame_type` has the param `uint8_t frame_type`, so the passed value should be a `uint8_t` expression. 
FWIW I found it because Chrome Canary 92 sent the frame type `135`.
* https://gist.github.com/gfx/f42db370eb2296d4806a153479919323
* the difference in `gcc -S` between master's and this PR's connection.c
=> usdt: fix the type of frame.type

lib/udp_tunnel.c
Zero-sized datagrams are allowed and `get_next_chunk` recognizes those. The caller must handle them.
=> zero-sized datagram is legal

include/h2o/multithread.h, lib/common/multithread.c, lib/http3/common.c
In #2259, we introduced a mechanism for rate-limiting a particular warning message, that has turned to be pretty useful. In #2655, we figured out that we need something similar, and reimplemented it.
While reviewing #2655, I noticed that existing code has a tiny race condition. `h2o_quic_send_datagrams` invoked from multiple threads test if `track_sendmsg.locked.timer` is being linked while taking the mutex. But `h2o_timerwheel_run` does not take a lock when it clears the link.
As unlinking an object from a double-linked list is not an atomic operation, we have a theoretical race condition that might end up breaking the linked list.
Being aware that such subtle mistakes can go into the source tree unnoticed, I'm inclined to fix the issue as well as making the concept reusable, so that we …
=> Extract the rate-limiting mechanism of warning message as reusable concept

lib/http3/common.c
And we have `h2o_strerror_r` as the wrapper. Fixes regression in #2675.
=> strerror_r does not always write the result to provided buffer

lib/http3/common.c
Because a connection is always registered to both `conns_by_id` and
`conns_accepting` throughout its lifetime, counting `conns_by_id`
is enough to know the total number of connections.
=> [http3] Count conns_accepting alone for quic_num_connections

lib/common/socket.c, t/40mtls.t, t/40tls-raw-pubkey.t, t/Util.pm
H2O may hang up when mTLS is used. The added `subtest "tls1.3 with picotls-cli"` reproduces this problem in 10/10 frequency, as picotls-cli sends the request with a single `write(2)`. 
close #2679
=> fix a timing issue in picotls handshake + mTLS

lib/common/socket.c
This PR does two things:
* Use `syscall(SYS_gettid)` instead of calling `gettid()`. By doing so, we avoid build issues with older versions of glibc. The PR proposes of using `syscall(SYS_gettid)` even when `gettid()` is available, based on the understanding that the former is a public / stable API. Alternative #2683.
* Use `SYS_bpf` instead of `__NR_bpf`. It seems that the former is preferred; see https://stackoverflow.com/questions/64123402/what-are-the-nr-prefixed-symbols-in-glibc.
=> fix build issues around ebpf

lib/common/socket.c, t/40mtls.t
Up until now, when TLS 1.3 is being used, h2o has been dropping the TLS fatal alert generated when receiving 2nd handshake flight from the client.
As we added support for client authentication in #2670, this issue has become a practical shortcoming, because there's chance that clients might not be possible to generate 2nd flight satisfying the expectation of server (i.e. send correct client certificate).
This PR addresses the issue.
Note that the impact of the problem has been limited to TLS 1.3 client authentication, because h2o has always been sending TLS alerts in the following two cases:
* when OpenSSL backend is used for pre-1.3 TLS handshake,
* when first flight of TLShandshake received from the client,  regardless of the TLS version, cannot be accepted.
=> [tls13 client auth] send alert when handshake fails

src/h2olog/h2olog.cc
Looks like BCC does not resolve a relative path in `-I`, so h2olog does it for BCC.
This PR is made against https://github.com/h2o/h2o/pull/2706.
=> [h2olog] resolve H2O_ROOT for BCC

src/h2olog/generated_raw_tracer.cc, src/h2olog/h2olog.cc, src/h2olog/http_tracer.cc, src/h2olog/misc/gen_raw_tracer.py, t/90h2olog-sampling.t
`BPF_TABLE_PINNED()` in BPF programs always fails if the pinned map file does not exist, which makes h2olog fail to run when h2o does not have `usdt-selective-tracing: ON`. This PR fixes the problem by hiding the definition of `h2o_return` and its use when h2olog has no selective-tracing options (i.e. -S and -A). 
Also, this PR happens to pursue that approach (1) https://github.com/h2o/h2o/pull/2706#discussion_r637292863
=> [h2olog] fix a bug that h2olog fails to start if /sys/fs/bpf/h2o_return does not exist

src/httpclient.c
Currently, there is no way to control the `max_udp_payload_size` transport parameter of `h2o-httpclient`.  The client always sends the initial message size equal to [DEFAULT_INITIAL_EGRESS_MAX_UDP_PAYLOAD_SIZE](https://github.com/h2o/quicly/blob/345b8e16d5a323b1568b11318ab7992be0be740f/lib/defaults.c#L25) and that dictates the entire conversation as of the current implementation of [h2o/quicly](https://github.com/h2o/quicly), so it is not easy to control or test that aspect of the protocol.  This change allows a user to specify the option which is used to both set the size of the initial handshake message as well as the advertised `max_udp_payload_size` transport parameter.
When used alongside #2710 the packet size in both directions can be controlled.
```
$ ./h2o-httpclient.9d9a993 -k -3 …
```
=> [httpclient] [quic] Implement --max-udp-payload-size option to control the corresponding transport parameter

lib/handler/connect.c
The `h2o_socket_read_start` is unnecessary because we immediately call `h2o_send`,
which will call `tcp_on_proceed`, which will set the socket in a read
state.
It's a bug to have start reading because we might have
`tcp_on_read` called on its own right before `tcp_on_proceed`
is called, and we will assert in `http2::finalostream_send` in
`h2o_http2_conn_register_for_proceed_callback` because the stream is
already linked
=> Do not start reading on tunnel since h2o_send will call tcp_on_proceed

src/main.c
This gets rid of an ASAN UB warning:
```
/build/src/main.c:445:16: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:93:34: note: nonnull attribute specified here
```
=> Gate memchr call behind a check on the lenght of the list

fuzz/driver.cc
H2O_FUZZER_CLIENT_TIMEOUT is read from environment but never used.
This patch actually uses it so the behavior matches what README says.
=> [fuzzer] Use timeout specified by envvar

src/main.c
[h2o/h2o/issues/2704](https://github.com/h2o/h2o/issues/2704)
Currently it is possible to configure `h2o` with a `max-connections` value that is greater than the file descriptor limit of the process, `RLIMIT_NOFILE`.  Instead the process should log an error and exit.
Tested with `h2o.conf`:
```
max-connections: 1048577
hosts:
"www.example.com":
listen:
port: 80
paths:
"/":
file.dir: doc-root
```
The log:
```
[FATAL] The 'max-connections'=[1048577] configuration value should not exceed the file descriptor limit of the process 'RLIMIT_NOFILE'=[1048576]
```
=> max-connections should not exceed hard limit of RLIMIT_NOFILE

src/main.c
On macOS, `rlim_t` is `uint64_t`, and the default value of RLIMIT_NOFILE (hard limit) is 2<<63-1. Therefore, `conf.max_connections > (int)limit.rlim_max` always return false.
Amends #2704.
=> fix startup failure on macOS

h2o.xcodeproj/project.pbxproj, include/h2o/hpack.h, include/h2o/http2_common.h, lib/http2/hpack.c, lib/http3/qpack.c, t/00unit/lib/http2/hpack.c, t/00unit/lib/http3/qpack.c
* QPACK: report invalid characters found in the header fields. Up until now, the decoder has passed through header fields containing line feeds that lead to response splitting when the reverse proxy handler connects upstream using H1.
* HPACK: do not inherit the invalid flag when receiving a literal header field that uses an indexed "name", of which the corresponding "value" was invalid.
=> [HPACK][QPACK] fix bugs in handling of soft errors

src/h2olog/generated_raw_tracer.cc, src/h2olog/misc/gen_raw_tracer.py, t/90h2olog.t
Alternative to #2719. Adding a common field `tid` for h2o's tid.
=> h2olog: add tid to identify QUIC connections (QUIC conn master_id + tid)

include/h2o.h, lib/handler/status/events.c, src/main.c, t/40http3-forward.t
This PR adds two event counters, `http3.packet-forwarded` and
`http3.forwarded-packet-received` to track intra-cluster QUIC packet
forwarding.
=> [http3] Add intra-cluster forwarding event counter 

include/h2o/socket.h, lib/common/socket.c, lib/common/socket/evloop.c.h, lib/common/socket/uv-binding.c.h
Make `h2o_socket_getsockname` cache the result (just like `h2o_socket_getpeername`). This should reduce the number of syscalls in certain code paths.
being extra pedantic, would it make sense to also invert the order of the functions `get_peername_uncached` and `get_sockname_uncached` in both evloop and uv-binding files.
=> make h2o_socket_getsockname cache the result

fuzz/driver.cc
`connect_timeout` and `first_byte_timeout` need to be explicitly
set to non-zero values.
This patch aligns these values with `io_timeout`, as done in
https://github.com/h2o/h2o/blob/35401aeb71bd9b8f97e543c524aae50af24e0978/lib/handler/configurator/proxy.c#L46
=> [fuzzer] Set proxy timeouts

src/h2olog/generated_raw_tracer.cc, src/h2olog/misc/gen_raw_tracer.py
`gen_raw_tracer.py` has a problem that it discards an original parameter name in a USDT if it's a pointer to a struct, for example, if there is `struct st_quicly_conn_t *` in a USDT, `gen_raw_tracer.py` always uses a pre-defined name  "conn" whatever the parameter name is. This results in a problem that `h2o:h3s_accept` emits such a JSON line:
```json
{"type":"h3s-accept","seq":13,"conn-id":2,"conn":107133664429568,"conn":0,"time":1618988758393}
```
where the definition of the USDT is:
```
probe h3s_accept(uint64_t conn_id, struct st_h2o_conn_t *conn, struct st_quicly_conn_t *quic);
```
In the above JSON, the first "conn" is the pointer value of `struct st_h2o_conn_t *conn`, and the second "conn"  is `quic->super.local.cid_set.plaintext.master_id`, which should not be named as "conn". …
=> [h2olog] fix a bug in h3s_accept which has two "conn" fields for h2o_conn_t and quicly_conn_t

include/h2o/socket/evloop.h, lib/common/socket/evloop.c.h, lib/handler/connect.c
CONNECT tunnels have to balance between throughput and latency.
At the moment, h2o_socket_read tries to read at most 1MB, which is too large for slow connections. Not only it is a performance issue, but it is also reliability issue, because reading too much at once ends up in reading too frequently, which in turn leads to the peer believing that the connection might have died, and thereby closing the connection (where it should not).
=> [CONNECT] do not buffer more than 64KB

t/40reuse-port.t
`t/40reuse_port.t` fails when the output of `ss` is differs in how it reports the bind address, on some platforms it might be `*:12345` and on others `0.0.0.0:12345`. This change makes the match less restrictive.
=> adjust regex in t/40reuse-port.t to only match bind address port

t/Util.pm
It seems to me that we are starting to see warnings from bcc when running h2olog on GitHub CI.
That breaks our test script, as H2ologTracer assumes that h2olog is attached to h2o when something is emitted by h2olog to stderr.
This PR address the issue. Now, H2ologTracer waits for "Attacting pid=" message before returning the execution to the test script.
Ideally, we should fix the root cause, though I am not sure why we are starting to see these lines. To me it seems like a weird interaction between bcc (in our Docker image) and the kernel source files (in GitHub CI). The latter might have changed recently.
If that's the case, I'm not sure how much we can do, or should do. Hence just fixing the test script.
Below is the output from GitHub CI running the test with proposed changes:
``` …
```
=> [CI][h2olog] do not return until boot process is complete

h2o-probes.d, include/h2o/socket.h, lib/common/socket.c, src/h2olog/generated_raw_tracer.cc, src/h2olog/h2olog.cc, src/h2olog/misc/gen_raw_tracer.py, src/main.c
This PR adds `-N` option to h2olog so that we can limit the traces being obtained to specific hosts.
* For connections being selected by `-N`, events prior to processing the SNI is not recorded.
* `-N` option can be repeated multiple times. All entries specified by `-A` and `-N` are logically ORed. Ratio specified by `-S` is applied to the set of connections specified by `-A` and `-N`. To give an example, when `-A 127.0.0.1/32 -N www.example.com -S 0.25` is specified, 25% of connections that either originate from 127.0.0.1 or carry an SNI value of www.example.com will be traced.
=> [h2olog] -N option for SNI-based sampling

include/h2o.h, lib/handler/status/events.c, lib/http3/server.c
We currently keep track of packet statistics at the connection level, for example in [on_loss_detected()](https://github.com/h2o/quicly/blob/f2d244f5d7b6df9849d3d108333933febbefbb6c/lib/quicly.c#L3600), but we do not include those counts in the statistics output.  This patch implements this output.
```
$ ./h2o-httpclient -k -3 100 -C 100 -t 1000 -H "user-agen: nalramli/1.0" -b 2800 -c 1400 https://127.0.0.2:1443/Fastly.html 1>/dev/null 2>&1
$ ./h2o-httpclient -H "user-agen: nalramli/1.0" http://127.0.0.1:1444/server-status/json 2>/dev/null | grep "http3"
"http3.packet-forwarded": 0, 
"http3.forwarded-packet-received": 0, 
"http3.num_packets.received": 10445, 
"http3.num_packets.decryption_failed": 0, 
"http3.num_packets.sent": 571860, 
"http3.num_packets.lost": 215, …
```
=> [quic] [stats] Implement http3.* statistics output

lib/http3/server.c
CONNECT and CONNECT-UDP requests are submitted to `h2o_process_request` through a special code path, but that path has not been calling `quicly_stream_set_receive_window` that raises the stream-level receive window from the initial size to that of a streaming request.
In effect, this changes the window size from 32KB to 16MB (the default values).
=> [CONNECT][CONNECT-UDP] promote receive window size

deps/quicly/lib/quicly.c, lib/http3/common.c
This is a rebase of #2763 against master, with tweaks.
For background, see https://github.com/h2o/quicly/pull/467.
=> Handle QUICLY_ERROR_STATE_EXHAUSTION errors

lib/http3/server.c
* Retarget #2748 against master.
* Remove invocations of `h2o_linklist_unlink` that become redundant.
=> Always unlink pending write requests when entering close_wait

README.md
since travis-ci.org is shutting down.
=> README: change the CI badge from Travis' to GitHub Actions'

lib/handler/headers_util.c
With the changes introduced in #2757, it's possible for [build_request()](https://github.com/h2o/h2o/blob/babd505298b73f3cf501f80f326237243bb24555/lib/core/proxy.c#L135) to result in an empty cookie header, because the call to [h2o_rewrite_headers](https://github.com/h2o/h2o/blob/babd505298b73f3cf501f80f326237243bb24555/lib/core/proxy.c#L276) and then to `cookie_cmd()` happens after [the length of cookie has been checked](https://github.com/h2o/h2o/blob/babd505298b73f3cf501f80f326237243bb24555/lib/core/proxy.c#L240).
This change ensures that `cookie_cmd()` removes the cookie header if its length becomes zero.
=> [handler] bug-fix: cookie_cmd() can result in empty 'cookie' header

t/40http3-shutdown-reject-conn.t, t/50date-header.t, t/50priority-headers.t, t/50proxy-max-buffer-size.t, t/50reverse-proxy-timings.t, t/50server-timing.t, t/50stop-opening-new-push-streams.t, t/50suspend-body.t
There are some tests that are missing the guard to detect mruby and fail during `make check` when compiled with `WITH_RUBY=OFF` 
If the expectation is that the full suite is only run under CI where all dependencies are known to be installed then kindly disregard this PR.
=> add missing mruby guard to tests which reference mruby.handler

t/50access-log.t
The test sometimes fails spuriously because curl requests end up being
interleaved
```
not ok 1
#
'GET::/query?abc=d::HTTP/1.1::127.0.0.1:41975::default'
'(?^:^GET::/::HTTP/1\.1::127\.0\.0\.1:[0-9]+::default$)'
not ok 2
1..2
not ok 5 - ltsv-related
'(?^:^GET::/query\?abc=d::HTTP/1\.1::127\.0\.0\.1:[0-9]+::default$)'
```
=> [test fix] Single thread 50access-log.t

t/Util.pm
Tests that run as root may fail if any tools are installed in non-standard locations.  This is due to `run_as_root()` starting a new shell that does not have the user's original `$PATH`.
For example, I am running a dev build of `curl` in my home directory.  This results in the following test failure:
```
$ BINARY_DIR=build PERL5LIB=. perl t/40running-user.t
spawning build/h2o... [INFO] raised RLIMIT_NOFILE to 1048576
h2o server (pid:31580) is ready to serve requests with 6 threads
done
not ok 1
killing build/h2o... received SIGTERM, gracefully shutting down
killed (got 0)
1..1
not ok 1 - set-user
spawning build/h2o... [INFO] raised RLIMIT_NOFILE to 1048576
h2o server (pid:31595) is ready to serve requests with 6 threads
done
not ok 1
killing build/h2o... received SIGTERM, gracefully …
```
=> [test] [bug-fix] t/Util.p path should be preserved in run_as_root()

t/50reverse-proxy-https.t
In my test environment, `t/50reverse-proxy-https.t` fails regularly because of connect errors to [wikipedia.org](https://wikipedia.org).
```
$ BINARY_DIR=build PERL5LIB=. perl t/50reverse-proxy-https.t
spawning plackup... HTTP::Server::PSGI: Accepting connections at https://0:50590/
done
spawning build/h2o... [INFO] raised RLIMIT_NOFILE to 1048576
h2o server (pid:26061) is ready to serve requests with 6 threads
done
[lib/core/proxy.c] in request:/:unable to get local issuer certificate
ok 1
127.0.0.1 - - [14/Jul/2021:18:31:08 -0400] "GET / HTTP/1.1" 404 9 "-" "curl/7.77.0-DEV"
ok 2
ok 3
1..3
ok 1 - http/1
[lib/core/proxy.c] in request:/:unable to get local issuer certificate
ok 1
127.0.0.1 - - [14/Jul/2021:18:31:08 -0400] "GET / HTTP/1.1" 404 9 "-" "curl/7.77.0-DEV"
ok 2
ok 3
1..3
ok 2 - …
```
=> [proxy] [test] t/50reverse-proxy-https.t replace wikipedia.org with localhost.examp1e.net because of connect errors

include/h2o.h, lib/handler/status/events.c, lib/http2/connection.c, t/50reverse-proxy-http2.t
This implements a counter for HTTP/2 streaming requests in statistics output.  We would like to monitor this counter for fluctuations.
Most of the changes were made by `clang-format`.
```
$ ./h2o-httpclient -H "user-agent: nalramli/1.0" http://127.0.0.1:1444/server-status/json 2>/dev/null | grep "http2.streaming-requests"
"http2.streaming-requests": 0,
```
=> [http2] Implement streaming request counter

lib/http3/common.c
Use of recvmmsg is an optimization.
In addition, this PR limits the number of datagrams being read before an ACK is being sent. Doing so makes sure that an ACK is sent in a fraction of RTT even when the receiver is receiving packets at a rate no slower than it can read.
=> [http3] recvmmsg, prevent pulsation

lib/http3/common.c
Fixes regression introduced by #2794.
Previously, we have been zero-clearing everything except the buffer to which we read the payload (see https://github.com/h2o/h2o/blob/462a44e0ae8f08fd24f3a67bc88d295b0d8fdb7b/lib/http3/common.c#L711).
But with #2794, as a side-effect of the structure being refactored (to support `recvmmsg`), we have switched the approach to initialize the individual fields that we have to, rather than zero-clearing everything.
Unfortunately, we forgot to initialize `destaddr` used for conveying the destination address of the datagram, even though `recvmsg` / `recvmmsg` might not provide the address through CMSG.
This PR addresses this behavioral change by zero-clearing `destaddr`.
=> zero-clear, as `recvmsg` might not provide destination address through CMSG

include/h2o.h
There is a pending update to QUIC in https://github.com/h2o/quicly/pull/482 that implements a counter for lost and resent Bytes.  This change implements the output of those statistics.
**DO NOT MERGE** until https://github.com/h2o/quicly/pull/482 has been merged and the corresponding commit imported to [h2o/h2o](https://github.com/h2o/h2o).
```
$ ./h2o-httpclient -k -3 100 -C 10 -t 100 -H "user-agent: nalramli/1.0" -b 2800 -c 1400 https://127.0.0.2:1443/1GB.dat 1>/dev/null 2>&1
$ ./h2o-httpclient -k -H "user-agent: nalramli/1.0" http://127.0.0.1:1444/server-status/json 2>/dev/null | grep "quic.num-bytes."
"quic.num-bytes.received": 61253512,
"quic.num-bytes.sent": 102950747761,
"quic.num-bytes.lost": 212945920,
"quic.num-bytes.stream-data-sent": 100214927406, …
```
=> [quic] [stats] Implement quic.num-bytes.lost, quic.num-bytes.stream-data-sent, quic.num-bytes.stream-data-resent statistics

lib/http3/qpack.c
This fixes a ClusterFuzz issue 35675.
=> qpack: do not derefence a pointer before range check

lib/common/memory.c
thus the allocator could be reused after 'h2o_mem_clear_recycle()'
=> assure 'allocator->cnt' is zero after clear

lib/http2/connection.c
Before this PR, we could call `stream_send_error` possibly without
closing the stream and definitely without reseting it.
This is problematic, because its possible that `stream_send_error`
queues a write, without setting the stream state to
`H2O_HTTP2_STREAM_STATE_END_STREAM`, allowing a subsequent write to
happen and eventually assert.
=> lib/http2/connection.c::proceed_request reset streams on error

fuzz/quicly_mock.c, lib/http3/server.c
kazuho/connect-udp (#2568) branch started using two new quicly functions. Hence add corresponding entries to the mock.
=> [connect-udp] add mock definitions

h2o.xcodeproj/project.pbxproj, lib/common/socket.c
'H2O_USE_PICOTLS' removed in a42769ce4dceee6c57e9453e59af5e67ab9d267f
=> libh2o: remove macro 'H2O_USE_PICOTLS' judge

include/h2o/httpclient.h, lib/common/httpclient.c, src/httpclient.c
I'm not sure this even makes sense, but the idea is that the client has previous knowledge of a server listening on a socket and expecting HTTP/2 (there's no SSL, so it's clear text HTTP/2, but not h2c).
=> Allow connecting to HTTP/2 servers over unix sockets

src/h2olog/generated_raw_tracer.cc, src/h2olog/h2olog.cc, src/h2olog/misc/gen_raw_tracer.py, t/90h2olog.t
Fixed three errors in h2olog, reported by AddressSanitizer and UndefinedBehaviorSanitizer.
* 422cbb69f94f58935e3f2e290ef61a990461df40 fixes LeakSanitizer errors. I think it's harmless.
* f887f818ae16789c408c0689229cdfb3d5957eb9 fixes UBSanitizer errros since it involves null ponter calculations, but it's harmless
* 5d3ef259844abd8183de30ea120fd010b9991f8d fixes UBSanitizer errors about "misaligned address". I've picked the same approach as bpftrace: https://github.com/iovisor/bpftrace/pull/1520 I guess it's harmless, though.
=> [h2olog] Fix three asan/ubsan errors

misc/docker-ci/Dockerfile.ubuntu1604, misc/docker-ci/Dockerfile.ubuntu2004, t/50dnsresolver.t, t/Util.pm
This PR integrates the `Net::DNS::Nameserver` module to implement a mock dns server that can be used by the test suite.
A sample test is included which tests:
1. That each query type responds to the correct address family
2. That configurable delays per query type work
=> add mock dns server to test suite

CMakeLists.txt, deps/quicly/CMakeLists.txt, deps/quicly/include/quicly.h, deps/quicly/include/quicly/rate.h, deps/quicly/include/quicly/sentmap.h, deps/quicly/lib/quicly.c, deps/quicly/lib/rate.c, deps/quicly/quicly.xcodeproj/project.pbxproj, deps/quicly/t/rate.c, deps/quicly/t/test.c, deps/quicly/t/test.h, fuzz/quicly_mock.c, h2o.xcodeproj/project.pbxproj, include/h2o.h, include/h2o/socket.h, lib/common/socket.c, lib/core/logconf.c, lib/http1.c, lib/http2/connection.c, lib/http3/server.c
Introduces`%{delivery-rate}x` that maps to `tcp_info::tcpi_delivery_rate` when TCP is used, or to `quicly_delivery_rate_t::delivery_rate.latest` when QUIC is used.
Also adds missing / new fields `%{http3.stats}x` to, including `delivery-rate.latest`, `delivery-rate.smoothed`, `delivery-rate.variance`.
Incorporates https://github.com/h2o/quicly/pull/486
=> expose delivery rate to log

src/h2olog/generated_raw_tracer.cc, src/h2olog/misc/gen_raw_tracer.py
As [open_memstream(3)](https://man7.org/linux/man-pages/man3/open_memstream.3.html) describes:
> After closing the stream, the caller should free(3) this buffer.
This is detected by Coverity.
=> h2olog: fix a resource leak in setting up BPF souce code

lib/http2/connection.c
This `h2o_http2_stream_close` calls (https://github.com/h2o/h2o/blob/master/lib/http2/connection.c#L346) can cause `h2o_http2_conn_request_write` calls, which in turn links `conn->_write.timeout_entry`. It causes this assertion (https://github.com/h2o/h2o/blob/master/lib/http2/connection.c#L377) to be failed. This PR fixes the issue by forcing `conn->state == H2O_HTTP2_CONN_STATE_IS_CLOSING` before closing streams, so that this block (https://github.com/h2o/h2o/blob/94c7448b78bb840564b7a78b18e251237c8edd0b/lib/http2/connection.c#L334-L337) never gets executed.
=> mark the conn as is_closing to prevent sending any more frames

CMakeLists.txt, fuzz/quicly_mock.c
This fixes 2 minor issues of h2o-fuzzer-http3 which I faced on macOS.
- `malloc.h` is Linux specific and we even don't use malloc and others in this program
- Couldn't find `<openssl/openssl.h>` without adding $OPENSSL_INCLUDE_DIR as include directory
=> http3 fuzzer fixes

deps/picotls/include/picotls.h, lib/http3/qpack.c
According to the current implementation (and what the QPACK spec suggests), `ctx->base_index` can be negative, but it's not sure that such situation actually exists and it can cause int64_t overflows in `resolve_dynamic_postbase` function. This PR tries to make our decoder require that base index not to be negative, i.e. ensures `0 <= ctx->base_index <= INT64_MAX`.
See also: https://github.com/quicwg/base-drafts/issues/4938
=> add overflow checks to ensure that 0 <= ctx->base_index <= INT64_MAX

t/50access-log-delivery-rate.t, t/50access-log-transport.t
adding E2E tests for  h2o/h2o#2832.
BTW seemingly the values of `delivery_rate` seem unstable (you can see the values by setting `TEST_DEBUG=1` to `prove`):
* For HTTP/1: `delivery_rate` is _sometimes_ `"0"`
* For HTTP/2: `delivery_rate` always seems to be set
* For HTTP/3:  `delivery_Rate` is always `null` (under `access-log.escape: json`)
Is it expected?
=> [test] add tests for delivery rate (TCP/QUIC)

lib/http1.c
http1 protocol handler tries to defer `on_send_complete`, but in request streaming mode
the client can continue to send the request body while that. If it happens `handle_one_body_fragment`
mistakenly clears that timeout, which can causes the connection never gets closed by both side,
i.e. connection stalling.
Thanks to https://github.com/h2o/h2o/pull/2786, we can call h2o_socket_write even if bufcnt == 0, so this PR fixes the issue by using unconditional h2o_socket_write to avoid timeout_entry reuse.
=> prevent http1 completion timeout from mistakenly getting cleared

lib/common/socket/evloop.c.h
Otherwise we see the warning below.
```
warning: comparison of array 'peeraddr' not equal to a null pointer is always true [-Wtautological-pointer-compare]
```
=> avoid comparing an array to NULL pointer

include/h2o.h, include/h2o/http3_common.h, lib/core/config.c, lib/core/configurator.c, lib/handler/proxy.c, lib/http3/common.c, src/httpclient.c, src/main.c
This commit introduces `http3-udp-gso` directive, which controls
whether UDP GSO is used.
Default is on if UDP_SEGMENT is defined. This is the same behavior
as the current code.
=> [http3] Enable UDP GSO based on configuration directive 

CMakeLists.txt
Bundled mruby cannot be built with Ruby 3.0.0 or higher versions by keyword argument problems. It's Rakefile is written in older Ruby syntax. And the error message is difficult to understand what is problem as below.
```
rake aborted!
wrong number of arguments (given 2, expected 1)
Rakefile:37:in `install_D'
make[2]: *** [CMakeFiles/mruby.dir/build.make:76: CMakeFiles/mruby] Error 1
make[1]: *** [CMakeFiles/Makefile2:816: CMakeFiles/mruby.dir/all] Error 2
```
Related issue #2789
=> Check Ruby version when WITH_MRUBY is ON

include/h2o/rand.h, lib/common/rand.c
=> `rand` might not be MT-safe, use `rand_r` instead

CMakeLists.txt
When developing C projects, `incompatible-pointer-types` is almost always a bug so that I want C compilers to stop compilation. What do you think?
=> [build] add -Werror=incompatible-pointer-types to help development

src/main.c
TLS Handshakes take about 1ms, this effectively limits the latency
induced by TLS handshakes to 10ms per event loop.
QUIC doesn't suffer from this problem since we're limiting the packets handled to 10 at a time.
=> TCP: hardcode the accepts to 10 per loop.

src/h2olog/h2olog.cc
As h2olog becomes complex, we need to debug its internals by investigating LLVM IR and BPF bytecode.  This PR adds a flag `-D` to enable implementation-defined debug flags.
=> h2olog: add -D<name> to enable BCC debug flags

lib/http3/server.c
Some fields in `quicly_stats_t` were not emitted by the `%{http3.quic-stats}x` directive.
=> [http3][access-log] add missing fields

lib/common/serverutil.c
One sets incorrect flag (though assuming that there's no overlap, behavior is fine), another fixes potential memory leak.
=> fix two bugs in serverutil.c

t/40server-push.t
Until now, "push-unpriotized" has assumed that using a small stream-level window leads to more predictable scheduling between requests.
That is an incorrect assumption. When the stream-level window is small, every stream will make equal amount of progress (as indicated by the window size) every round-trip. To paraphrase, use of a small window preserves the timing differences between the TTFB of the responses.
This PR changes the handler that generates the responses for this test from a upstream.psgi to a mruby handler. Doing that prevents the timing issues caused by IPC between h2o and upstream.psgi.
=> [t/40server-push.t] use mruby handler to avoid timing issues between h2o and upstream

include/h2o.h, lib/core/request.c, lib/http1.c, t/50errordoc.t
At the moment, doing so leads to a crash, as reported in #2900.
The excuse for skipping filters (e.g., error-doc) when receiving a broken request is that there is no point in trying to return something fancy in such case, because legitimate clients would never send broken requests.
=> don't apply filters when request is broken

lib/handler/proxy.c
The problem only appears when we set H2 ratio 100: h2o may ignore ALPN even if that flag isn't set
https://github.com/h2o/h2o/blob/master/lib/common/httpclient.c#L125-L130
=> add missing initialization of newly added flag

t/Util.pm
Depending on the system configuration, `h2o` could run out of file descriptors on start up while running tests in docker on a machine with a large number of cores.
=> set num-threads to 2 to prevent tests running out of file descriptors

lib/common/socket.c
`shutdown_ssl` seems unnecessarily complicated. This refactors the code for simplicity.
Some of the complexity stems from the attempt to support clean bidirectional shutdown, waiting for the receipt of an TLS alert after sending one. While such shutdown is necessary for application protocols that rely on TLS alert to identify message identity to prevent truncation attack, it is unnecessary for most application protocols including HTTP. HTTP has its own mechanism of indicating message boundary, or truncation is considered a known issue when using HTTP/1 with connection close being end of the message.
Anyways, `shutdown_ssl` has never closed the connection in such a clean manner, and we can simplify the code.
The other issue related to closing the socket immediately after sending a TLS …
=> simplify `shutdown_ssl`

fuzz/driver.cc, include/h2o/multithread.h, lib/common/multithread.c, src/main.c
Subsumes #2913.
Fixed issues are:
* barrier:
* SIGTERM:
=> fix issues with SIGTERM handling and h2o_barrier_t

include/h2o/http2_common.h, include/h2o/http2_internal.h, lib/common/http2client.c, lib/http2/connection.c, lib/http2/frame.c, lib/http2/hpack.c, lib/http2/stream.c, t/00unit/lib/http2/hpack.c, t/40protocol.t
Handle SETTINGS_HEADER_TABLE_SIZE.
As discussed in HTTPWG, we can ignore if the value is no less than default (4096), but should handle it when given value is less than 4096, by evicting items from the table and sending a Dynamic Table Size Update instruction.
ToDo:
=> Respond to SETTINGS_HEADER_TABLE_SIZE

t/40mtls.t
Need to use Time::HiRes version of `sleep` to be able to sleep for subseconds. Without it, it's essentially the same as `sleep(0)`. 
I ran a combination of `git grep` to find the use of sub-second sleep without importing Time::HiRes and it showed this test file only. (There were a few false positives due to Ruby version of `sleep` in mruby tests, though)
=> use Time::HiRes sleep

lib/common/socket.c
This brings back the pre #2859 behavior where we ignore `SSL_write`
errors since they are due to a previous independent `SSL_read`.
Another possibility would be to only ignore `ret == -1` and `
SSL_get_error == SSL_ERROR_ZERO_RETURN`, but this fix is more
conservative by just reviving the old behavior.
=> Ignore errors coming from SSL_write

include/h2o.h
Remove unused quic stats field
Fix missed from: https://github.com/h2o/h2o/pull/2923
=> fix: remove unused quic stats field

lib/common/http1client.c
Fixing UB warnings in `h2o-httpclient` to make its output be machine-readable. This is the easiest one:
> lib/common/http1client.c:664:49: runtime error: applying zero offset to null pointer
=> fix a UB in http1client.c

t/40ssl-cipher-suite.t, t/40tls13-early-data.t, t/50mruby-error-log.t, t/50mruby-redis.t, t/50reverse-proxy-disconnected-keepalive.t, t/50reverse-proxy-early-response.t, t/50reverse-proxy-http2.t, t/50reverse-proxy-proxy-protocol.t, t/50reverse-proxy/test.pl, t/Util.pm, t/run-tests
I saw some mysterious ci log in which there were several `not ok` but the test was regarded as `success` by `t/run-tests`.
It should be due to `$?` being overwrote in object destructor within Scope::Guard - one possible solution is localizing `$?` before calling destructor function.
=> localize $? by using wrapped guard function

misc/docker-ci/Dockerfile.ubuntu1604, misc/docker-ci/Dockerfile.ubuntu2004
Test::TCP 2.21 has been widely available on CPAN and there shouldn't be a need to pin to a specific version on Git.
=> Dockerfile cleanup: unpin Test::TCP

t/50errordoc.t
Fix a perl warning `"my" variable $resp masks earlier declaration in same scope at t/50errordoc.t line 195.`
=> fix perl warnings in tests

CMakeLists.txt, lib/core/config.c, lib/core/configurator.c, lib/http3/common.c, src/main.c
#2017 introduced use of `pthread_setaffinity_np` on linux, and #2574 extended that to NetBSD. So far, we have relied on `CHECK_C_SOURCE_COMPILES` to detect the availability of the feature.
However, that has led to issues on FreeBSD: see #2933 and #2934.
In reality, feature detection using duck-typing (compile some code, and if that succeeds, assume that the API can be used) works only if support for an API is provided in a consistent way between platforms that support that API.
This is not the case for `phread_setaffinity_np`. Linux uses `cpu_set_t`. FreeBSD uses `cpuset_t`. NetBSD uses `cpuset_t`, but requires applications to allocate the structure on heap using API.
Considering the fact that we have to have different code for each platform, it is simpler to just to `#if platform` in the …
=> [FreeBSD] use pthread_setaffinity_np

lib/handler/compress.c, t/50compress.t, t/Util.pm
Fixes: #2896 
in #2896, @Jxck proposed the etag adding W/ for alternative representation (e.g. gzip, br, zstd). I implemented this.
=> Etag alternative representation for compress #2896

lib/common/hostinfo.c
In #2568, we switched from using `gai_strerror` to using our own function that converts error codes to strings, as `gai_strerror` is locale-dependent and therefore cannot be included in the `proxy-status` response header.
However, that has caused the FreeBSD to break, because it does not define EAI_NODATA, AI_ADDRFAMILY, constants that were obsoleted in RFC 3493.
Fixes #2944.
=> constants obsoleted in RFC 3493 may not be available

t/40memcached-session-resumption.t, t/40redis-session-resumption.t, t/40session-ticket.t, t/40ssl-cipher-suite.t, t/40tls-multiple-certs.t, t/50status.t, t/90live-fetch-ocsp-response.t, t/Util.pm
There are many tests that utilize `openssl s_client` which are flaky.  They sometimes fail randomly with an error that includes the tool’s output.  The failures are usually timing issues which are not predictable and subsequent attempts to run the tests often succeed.
This patch unifies the way that the tool is called across all unit tests using the `run_openssl_client()` method to get a more consistent behavior.  The method has been enhanced to use `open3()`, then `waitpid()` until the process ends with a configurable timeout, optionally insert data using `stdin`, and capture `stdout`  and `stderr` separately.
=> [test] [bug-fix] Many openssl s_client tests fail occasionally due to timing issues

t/50config.t, t/Util.pm
This PR is an attempt to fix a regression in #2909, that causes occasional errors in tag/env/nonexist subtest of t/50config.t, i.e.,
```
2022-02-23T23:24:08.5063454Z   2.451822         # Subtest: nonexist
2022-02-23T23:24:08.5063714Z   2.556424 spawning /home/ci/h2o... done
2022-02-23T23:24:08.5064072Z   2.557273 [/tmp/26wzLxCoij:6] in command header.add, failed to parse the value; should be in form of `name: value`
2022-02-23T23:24:08.5064587Z   3.564353             ok 1 - server should be down due to misconfiguration
2022-02-23T23:24:08.5066054Z   3.564763 killing /home/ci/h2o...             not ok 2 - server die with signal 19968
2022-02-23T23:24:08.5066545Z   3.565127             #   Failed test 'server die with signal 19968'
2022-02-23T23:24:08.5067107Z   3.565130             #   at …
```
=> Fix timing errors in t/50config.t

src/ssl.c
Secret used for generating address token encryption keys is partially-uninitialized, leading to address validation failures.
=> [http3] secret passed to `ptls_aead_new` must be of the digest size

lib/core/request.c, t/50reverse-proxy-null-host-header.t
As pointed out by @cwyang in #2955, reverse proxy handler crashes when receiving a request carrying a zero-length authority.
This PR addresses the problem in a different way than #2955. We already have the path to handle the case where the Host header field is missing - in which case we pretend as if we received the "default" hostname. This PR adjusts the condition check so that the same path would be taken when the given authority is zero-length.
Closes #2955.
=> treat zero-length authority the same way as no host header

t/Util.pm
This amends https://github.com/h2o/h2o/pull/2947.
I discovered a minor issue that `eof()` could return `0` even when writing to the file handle would result in a `SIGPIPE` signal, and then the `print` fails and the script exits.  The more correct way to deal with the child's `STDIN` file is to handle the `SIGPIPE` signal by ignoring it while writing.
=> [test] [bug-fix] run_openssl_client() should ignore child's SIGPIPE on STDIN instead of EOF test

lib/http3/common.c
When gcc 5.4.0 that comes with ubuntu16.04 is being used, we see type aliasing warnings. We do not see them when gcc 9.4.0 (ubuntu20.04) is used. Also, it is somewhat questionable if all the warnings are legit.
However, the send-side is at least hard to understand. Also, there is theoretical concern that copies involved might generate bus error due to unaligned access; there is no guarantee that `CMSG_DATA()` returns addresses that we can read and write using `=` (assignment operators) for all the types that we use.
Closes #2963.
=> [http3] safer handling of CMSG (in terms of type aliasing)

lib/http2/connection.c, lib/http2/stream.c
Our HTTP/2 implementation is capable of internally replaying an HTTP request that is received too early (i.e., carried by TLS/1.3 early data).
When the HTTP/2 implementation takes that path, the stream state should be kept unmodified, as the request is "replayed" and a new HTTP response would be delivered. However, as being detected by the assertion added in #2953, we seem to be making unnecessary changes.
This PR address the issue, subsuming #2953.
=> [http2] fix state inconsistency when a request is replayed internally

lib/http2/stream.c
When `finalostream_send`, the stream must be in progress, and the
function can't be called a second time after FINAL or ERROR was passed
to `h2o_send` by the generator.
=> http/2 in finalostream_send assert that stream is in progress

include/h2o.h, lib/core/config.c, lib/core/configurator.c, lib/core/request.c
I want to configure `max_reprocesses` just like `max_delegations`.
=> add `max-reprocesses` configuration variable

lib/common/http2client.c
This PR corrects #2971, which introduced a check that was overly strict.  An empty data frame (presumably carrying the END_STREAM flag) is valid in a response that must not have a response body.
=> `http2client.c`: a 0-byte data frame is ok in the message-body-forbidden cases.

lib/http3/server.c
This is likely a regression in #2568, specifically cdc55bd.
`shutdown_by_generator` is called from `do_send` when the given send_state indicates that it is the last invocation. Prior to #2568, in `shutdown_by_generator`, we have been using `1` as the last argument (`in_generator`) of `set_state`. But in the aforementioned commit, value of the flag was changed to zero.
Now, `h2o_req_t` is disposed before `do_send` returns, and therefore, if the generator tries to use `h2o_req_t` or memory allocated from the memory pool of `h2o_req_t` _after_ calling `h2o_send`, that can to lead to use-after-free. Though I'm not sure if there's a path that would actually lead to such failure.
This PR addresses the concern by changing the value of the flag back to 1.
=> [http3] Delay disposal of `h2o_req_t` even when `do_send` is called for the last time

lib/http2/stream.c
=> [http2] when request body is absent, release stream when the write side completes

CMakeLists.txt, h2o.xcodeproj/project.pbxproj, lib/handler/throttle_resp.c, t/00unit/lib/handler/throttle_resp.c, t/00unit/test.c, t/00unit/test.h, t/50throttle-response.t
At the moment, throttle response handler invokes `h2o_ostream_send_next` every 100ms. This would violate the contract (call `h2o_ostream_send_next` exactly once per invocation of `do_send`) when the generator is slow in calling `do_send`, either due to the generator itself being slow or the connection being slow (that delays the invocation of `h2o_proceed_request`).
This PR refactors the design of the throttle response handler so that the timer would be set only when `do_send` is called with an accurate timeout value.
=> [throttle-response] fix crash when either generator or client is slow

src/main.c
We've had this for QUIC (that controls the UDP socket handling all QUIC connections), but have not had a knob for TCP / UNIX sockets that sets these variables for each connection.
This PR adds `sndbuf`, `rcvbuf` attributes as direct members to the `listen` directive. The new attributes only affect TCP / Unix sockets; QUIC still refers to those set within the `quic` attribute. The rationale is that they are different - the new ones are per-connection; the ones for QUIC are global.
=> add knobs for tuning sndbuf / rcvbuf

misc/docker-ci/Dockerfile.ubuntu1604, misc/docker-ci/Dockerfile.ubuntu2004
Run `dumb-init` with `--rewrite 1:0` to ignore SIGHUP.
Otherwise the installation of `runit` in the container kills the container because the pre and post scripts in the package send SIGHUP to pid 1, presumably to tell a normal init to reload its configuration.
=> `misc/docker-ci/Dockerfile.ubuntu*`: Run `dumb-init` with `--rewrite 1:0` to ignore SIGHUP.

misc/docker-ci/Dockerfile.ubuntu2004
While the current plan is to ditch #2976 in favor of #2993, we do plan to using io_uring for non-blocking disk reads in the file handler.
So let's have liburing installed now on CI.
=> [CI] install liburing to h2oserver/h2o-ci:ubuntu2004

include/h2o/multithread.h, lib/common/multithread.c, src/main.c
In #2915, we introduced the capability to run code immediately before a barrier opens. That has caused issues that led to #2949, #2951, #2998.
When I was reviewing #2949, #2951 seemed the right solution, based on my understanding that we need to have the capability of running some code from the barrier, as the barrier opens.
But #2998 made me realize that we can use two barriers for the same purpose. So, how about exercising that option to revert the complexity introduced by #2915? If we use two barriers, we do not need the two-phased barrier thing that allows the user to run code immediately before the barrier opens.
Builds on top of #2998. Essentially reverts #2915.
=> simplify barrier

share/h2o/mruby/prometheus.rb
remove the h2o_requests response in the prometheus scrape output as the JSON object that is returned causes a parsing error
=> Fix up Prometeus by removing the requests JSON object

t/90live-fetch-ocsp-response.t
I fixed the fetch-ocsp-response tests on ubuntu 20.04 (openssl1.1.1).
As you can see, 90live-fetch-ocsp-response.to had failed for `openssl s_client -showcerts` command error.
```
ci@51de20a1a5b5:/h2o.ro$ LIVE_TESTS=1 H2O_ROOT=. BINARY_DIR=/home/ci/ prove -I. -v t/90live-fetch-ocsp-response.t
t/90live-fetch-ocsp-response.t ..
not ok 1 - chain has more than 2 certificates
fetch-ocsp-response (using OpenSSL 1.1.1f  31 Mar 2020)
unable to load certificate
140287124342080:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
OpenSSL exitted abnormally: openssl x509 -in /tmp/raHXDk_ETX -noout -ocsp_uri: at share/h2o/fetch-ocsp-response line 143.
not ok 2 - fetch-ocsp-response exitted with status:256
1..2
not ok 1 - www.verisign.com
... …
```
=> Fix fetch-ocsp-response_test to pass

src/main.c
Recently, we are seeing multiple crashes like below.
Apparently, h2o is "gracefully shutting down," and the ticket updater thread is having trouble using an rwlock. The cause is likely a race condition between [`OpenSSL_cleanup` run as an atexit (3) callback](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/init.c#L140) and the ticket updater thread trying to generate random bytes.
This PR addresses the problem by preventing the invocation of `atexit` handlers. This looks like a regression introduced by #2460, which changed the shutdown method from `_exit` to returning from `main`.
With this PR, we would be having two ways of destroying threads: we will be joining worker threads that handle requests, but we will be letting `_exit` kill other threads abruptly.
That is …
=> Fix crash inside `RAND_bytes` while h2o is shuting down

lib/http1.c
This is necessary in the case where h2o forwards the request to a
backend that does the upgrade
=> Return a 'connection: upgrade' in the upgrade path

h2o.xcodeproj/project.pbxproj, lib/handler/file.c, lib/http1.c, lib/http2/stream.c, t/50file-shrink.t
When pull vectors are used, we might encounter an error while trying to read from those vectors. The most prominent case is a file getting truncated while being served by h2o.
This PR adds a test that replicates that behavior, as well as fixing issues being found by that test.
=> Fix bugs in the error handling path of pull vectors

src/main.c
As of https://github.com/h2o/picotls/pull/311, picotls invokes the client hello callback even when the handshake is to be delegated to OpenSSL. However, when incorporating that pull request to h2o in #2335, we made no change to h2o.
Now, when receiving a TLS 1.2 handshake, all the per-SNI setup is done in `on_client_hello_ptls`, then OpenSSL calls `on_sni_callback`, at which point we once more do the per-SNI setup.
This might be considered no more than waste of some CPU cycles, but it becomes an actual issue when there are setup procedures that cannot be run more than once. #3007 attempts to introduce `h2o_socket_use_zerocopy`, which can be called only once. If we call this function in `on_client_hello_ptls`, then in `on_sni_callback`, an assertion failure is raised.
This PR addresses the …
=> when falling back to OpenSSL, do not apply per-SNI config to picotls

lib/handler/connect.c, t/50connect.t
When the connect function returns with an error immediately, do not carry over the already tried server_address into the next connect attempt, because that can cause an infinite loop.
The test case demonstrates the problem using `255.255.255.255`. A non-blocking connect to this address fails immediately on the operating systems that I have access to (Linux, MacOS and OpenBSD), albeit with a different errno on each (ENETUNREACH, EAFNOSUPPORT and EINVAL respectively).
=> Do not try to connect to the same address repeatedly in the connect handler.

include/h2o/memory.h, lib/common/memory.c, lib/common/socket.c
* Improves memory locality by retaining an array of pointers pointing to chunks being recycled. Previously, chunks were linked.
* Add `size_t *` to `h2o_mem_recycle_t` that contains the size of the chunks being recycled. This change makes `h2o_mem_recycle_t` more standalone. Previously, callers of `h2o_mem_alloc_recycle` had to specify the correct size that is retained somewhere else.
=> [h2o_mem_recycle_t] improve memory locality and API

lib/http3/server.c
This PR cherry-picks tunnel priority fix from https://github.com/h2o/h2o/compare/kazuho/connect-fixes
=> when CONNECT method is used, pretend as if `priority: i` was sent

CMakeLists.txt, h2o.xcodeproj/project.pbxproj, lib/core/config.c, lib/core/configurator.c, t/00unit/lib/core/config.c, t/00unit/test.c, t/00unit/test.h
We've always done this when the configurator is being used, but not when `h2o_config_register_path` is being called. I tend to believe that it is a bug to _not_ do that inside `h2o_config_register_path`, therefore changing the logic there.
Closes #2956.
=> Sort paths in the descending order of length at libh2o-level

lib/http3/server.c
There is a case where we have started streaming, received all data from the stream, but have not processed it all before cleaning up, resulting in truncation and the client waiting for more data.
=> check if available bytes is 0 before cleaning up

src/httpclient.c, t/10httpclient-lowercase.t
This is for user convenience, as it is easy to forget the fact that header field names on the wire are supposed to be in lower case in HTTP/3 (and in HTTP/2).
HTTP/2 https://datatracker.ietf.org/doc/html/rfc9113.html#section-8.2
> Field names MUST be converted to lowercase when constructing an HTTP/2 message.
HTTP/3 https://datatracker.ietf.org/doc/html/rfc9114.html#section-4.2
> Characters in field names MUST be converted to lowercase prior to their encoding.  A request or response containing uppercase characters in field names MUST be treated as malformed.
=> `h2o-httpclient`: lowercase the header field name from `-H`.

include/h2o/memory.h, include/h2o/socket.h, lib/common/memory.c, lib/common/socket.c, lib/http3/server.c, src/main.c
Spin-off of #3007.
H2O has a struct called `h2o_mem_recycle_t`. Along with the functions that deal with the struct, it acts as a buffer between h2o and malloc, reducing fluctuation of memory requirement observed by malloc.
Without `h2o_mem_recycle_t`, the fluctuation being observed by malloc often becomes so large that it starts returning memory to kernel then soon asking for kernel to allocate again. This kind of behavior is especially painful for multi-threaded servers like h2o, because returning memory to kernel involves TLB shootdown that affects all the threads, not to mention the cost of pagefaults when writing to newly allocated memory.
Up until now, each `h2o_mem_recycle_t` has been provided a fixed number of slots (`h2o_mem_recycle_t::max`). With #3007 doing zero-copy, adequate …
=> auto-tuning of memory recycler

lib/common/socket.c
The negative effect impact is cosmetic, as this at worst leads to some overlap of one TLS record across multiple TCP packets.
=> fix typo leading to miscalculation of record size when tls1.2 w. chachapoly is used

src/h2olog/generated_raw_tracer.cc, src/h2olog/misc/gen_raw_tracer.py
See https://github.com/h2o/h2o/pull/3049#discussion_r918482711 for the discussion.
As long as I've checked this PR + #3049 + the following patch, it does compile:
```diff
diff --git a/h2o-probes.d b/h2o-probes.d
index d6228135b..aab0319ca 100644
--- a/h2o-probes.d
+++ b/h2o-probes.d
@@ -173,7 +173,7 @@ provider h2o {
/**
* Error trying to establish a CONNECT or CONNECT-UDP tunnel.
*/
-    probe connect_error(uint64_t conn_id, uint64_t req_id, const char *error, const char *details);
+    probe connect_error(uint64_t conn_id, uint64_t req_id, const char *error_type, const char *rcode, const char *details);
/**
* Idle timeout on a CONNECT or CONNECT-UDP tunnel.
*/
diff --git a/lib/handler/connect.c b/lib/handler/connect.c
index 5ce367a74..258d82237 100644
--- a/lib/handler/connect.c
+++ …
```
=> [h2olog] reduce the use of stack in BPF programs

t/Util.pm
I was a bit confused by a test failure where h2o cannot parse the config file when `/tmp` was full. This patch should help us find such unusual situations.
=> [test] check the test conf is written to the disk

.github/workflows/ci.yml, deps/mruby-digest/src/picohash.h, deps/neverbleed/Makefile, deps/neverbleed/neverbleed.c, misc/docker-ci/Dockerfile.ubuntu2204, misc/docker-ci/check.mk, src/httpclient.c, src/ssl.c, t/50origin-frame.t, t/50reverse-proxy/test.pl, t/50server-starter.t
=> add support for OpenSSL 3.0

src/main.c, t/50server-starter.t
In #2460, we decided that the main thread should call `_exit` after waiting for all worker threads to exit from `run_loop`. However, the very last portion of `run_loop` has a race condition, and `run_loop` might not return forever, in which case h2o gets stuck while trying to shut down gracefully.
https://github.com/h2o/h2o/blob/c84934285d92c0936e93409f8830c99295b3cf91/src/main.c#L3345-L3349
The problem here is that if the main thread owns zero connections, while other threads own some, the main thread can call `h2o_evloop_run` and that would block forever.
This behavior has likely lead us to seeing t/50server-starter.t fail often. In retrospect, it is no wonder because the test creates one connection to the server and then sends SIGTERM immediately. If the connection was accepted by a …
=> Fix deadlock while gracefully shutting down

h2o.xcodeproj/project.pbxproj, t/50connect-eyeballs.t, t/90h2olog-selective-tracing.t, t/90h2olog.t, t/Util.pm, t/run-tests
Tentative fix for #3057.
When running h2olog on Ubuntu 22.04, the monitored process is specified by the executable *[and PID -1](https://github.com/h2o/h2o/issues/3057#issuecomment-1189121025)* meaning that any h2o running on the same host will be traced.
This leads to CI failures, as we run several tests in parallel.
While we expect this to be a bug inside libbcc that should be fixed, we cannot rely on such a fix even after it gets released, because we have to support distros that already exist with this bug.
Therefore, in this PR, we introduce a lock that is taken when running h2olog tests, as a tentative workaround.
=> Serialize h2olog tests to prevent CI failure

.gitmodules
amends #3053 
It seems that GitHub Actions seems no problem fetching correct commit of misc/h2get without this change (maybe because there's a PR?), but we needed this at least on Ubuntu 22.04 that already had h2get from an older commit being fetched.
=> change h2get repository

.gitignore
This untracked file seems to be new with the recent mruby upgrade.  Here is what is inside it:
```yaml
---
mruby:
version: 3.1.0
release_no: 30100
```
Should it be `.gitignore`d or checked-in?
=> Add `misc/mruby_config.rb.lock` to `.gitignore`

t/50throttle-response.t
We see it fail occasionally, e.g., https://github.com/h2o/h2o/runs/7478611158.
=> [t/50throttle-response.t] relax time-sensitivity

CMakeLists.txt, h2o.xcodeproj/project.pbxproj, include/h2o/socket.h, lib/common/socket.c, lib/common/socket/evloop.c.h, lib/common/socket/evloop/epoll.c.h, lib/handler/status.c, lib/handler/status/memory.c
Observed values are:
* `h2o_mem_pool_buffer_allocator`
* `h2o_socket_ssl_buffer_allocator`
* `h2o_socket_zerocopy_buffer_allocator`
* number of zerocopy bytes currently owend by the sockets
=> collect and emit memory stats through status handler

include/h2o/socket/evloop.h, lib/common/socket/evloop.c.h
When HTTP/1 handler writes a huge response from the file handler through a very fast network, it might end up writing too much at once, as we do not cap the amount of data that can be written before yielding control to other sockets.
To be specific: `h2o_socket_write` always tries to write to socket, and if the write fully succeeds, the write completion callback is invoked before events for other sockets are handled. That in turn invokes the `do_proceed` callback of the file handler synchronously, then `h2o_sendvec`, `finalostream_send`, `h2o_socket_write`.
This PR fixes the problem by checking the amount of data being written for each socket within one invocation of `h2o_evloop_run`. When more than `h2o_evloop_socket_max_write_size` (default: 1MB) is written, we will wait for write ready …
=> do not write more than 1MB at once

lib/common/hostinfo.c, lib/common/memcached.c, src/ssl.c
* Use `PTHREAD_CREATE_DETACHED` instead of the constant `1` for `pthread_attr_setdetachstate(3`
* Call `pthread_attr_destroy(3)` to release pthread attrs
=> tidy up the use of pthread API

lib/common/http1client.c
Follow-up of #3075.
When the proxy handler is using pipe as an intermediary buffer, read synchronously.
Doing so has two benefits:
* For prioritization logic of HTTP handlers to work correctly, it is important to provide additional data synchronously in response to the invocation of `h2o_proceed_response`. When memory buffers are used, lib/core/proxy.c uses a double buffering to prepare next chunk of data while a chunk of data is being fed to the HTTP handlers via `h2o_sendvec`. But when using splice, the pipe is the only one buffer available. Therefore, we invoke `splice` and `h2o_send` synchronously.
* Reduce calls to `epoll_ctl`, `epoll_wait`. By synchronously invoking `splice` and `h2o_send` synchronously, we can run a hot loop of that repeatedly sends data to client then reads more …
=> [proxy] call `splice` and `h2o_send` synchronously

lib/core/proxy.c
This is necessary, because some frontends (h2 in particular) will dispose of the generator when on_body_close is called with an error.
=> Add a boolean to track whether the generator was disposed. If so don't call do send

lib/common/socket.c, lib/common/socket/evloop.c.h
#3074 added code that delays writes to a socket. However, that happens _after_ the content is being read from a pull vector. That means that when serving files above 1MB (`h2o_socket_max_write_size`), each connection would retain 64KB buffer across one event loop.
This PR delays the read from a pull vector to when the content is to be encrypted and written to the socket for the first time, after `h2o_socket_sendvec` is invoked.
Another followup PR of #3074.
=> Do not read into buffer when we are about to yield to other sockets

CMakeLists.txt, t/00unit/lib/core/util.c
Refuse to build when the printf format string is incorrect.
Based on #3098. But instead of setting `-Wno-nonnull`, this PR addresses non-null warnings.
=> Use `-Werror=format`

lib/common/socket.c, lib/http1.c
They are undefined in C, from the c99 draft:
> 6.7.5.2 Array declarators § 5
> If the size is an expression that is not an integer constant
> expression: if it occurs in a declaration at function prototype scope,
> it is treated as if it were replaced by *; otherwise, each time it is
> evaluated it shall have a value greater than zero.
=> Avoid 0 sized VLAs

.github/workflows/daily_coverity.yml
Ubuntu 18.04 is no longer supported as a runner image.
See https://github.com/actions/runner-images/issues/6002
=> Use Ubuntu 20.04 for daily Coverity job

.github/workflows/daily_coverity.yml
This is a follow up to https://github.com/h2o/h2o/pull/3100, which failed to update the distribution code name from `bionic` to `focal`.
=> [daily coverity] Ubuntu 20.04 is `focal`

src/httpclient.c
Sometimes we test the return code is not an error with regexp, such as `like $stderr, qr{^HTTP/[^ ]+ 200\s}s;` in tests, but it would be easy if `h2o-httpclient` implements `curl -f` equivalent.
Unlike `curl -f`, this PR implements `curl --fail-with-body` (`-f` or `--fail` does not print the body, but `--fail-with-body` does). I think there's no reason to omit the body on errors, and that's why `--fail-with-body` has been implemented in curl 7.76.0 (Mar 31, 2021).
=> h2o-httpclient: add -f for the same semantics for `curl --fail-with-body`

CMakeLists.txt, misc/docker-ci/check.mk
Minimalist approach to fixing #3105.
See https://github.com/h2o/h2o/pull/3107#pullrequestreview-1106855105 for rationale.
We can do better if there's appetite, but this is the minimum we need.
=> Use `-Werror=format` only on some CI

include/h2o/rand.h
Maximum return value of h2o_rand() can vary depending on whether arc4random does exists or not, so it's better to provide our own macro to make it portable.
=> define H2O_RAND_MAX

include/h2o/configurator.h, src/main.c
At the moment, the `tcp-fastopen` configuration directive has effect only if it appears before the `listen` directive.
This PR address the problem by setting SEMI_DEFERRED flag for the `listen` directive. In essence, now the global-level directives are processed in the following order:
* all directives other than `file.custom-handler`, `listen`, `hosts`, in the order they appear
* `file-custom-handler` and `listen` in ther order they appear (this is fine because these two do not affect each other)
* `hosts`
This also helps #2415, as the `quic-dsr` directive introduced in that PR affects the ports being opened by the `listen` directive.
=> `tcp-fastopen` should be applied regardless of where it is set

src/main.c
It must not raise fatal errors because a request is being accepted at that time, so extracting these parts in a method and sharing it with the QUIC setting up routine do not make sense.
discussions:
* https://github.com/h2o/h2o/pull/3003
* https://github.com/h2o/h2o/pull/3095
=> check setsockopt return values

lib/common/hostinfo.c
It was applied in https://github.com/h2o/h2o/pull/3079 but it makes `hostinfo.c` not work in some situations, probably because it's too small.
=> remove unnecessary `pthread_attr_setstacksize()`

deps/yoml/Makefile, deps/yoml/README.md, deps/yoml/deps/picotest, deps/yoml/test-yoml.c, deps/yoml/yoml-parser.h, deps/yoml/yoml.h, lib/common/timerwheel.c, src/main.c
We have been using `-std=c99` for some time though we have refrained from using all features of C99. It would be reasonable to assume that all compilers support FAM.
We might start seeing compile errors with C++ projects using libh2o, because yoml.h included by h2o.h is now using FAM. If that turns out to be an issue, then we can fix it.
=> to avoid compiler warnings, use c99 flexible array member nonation

lib/core/proxy.c
Calling `build_request_merge_headers` everytime we find cookie header requires O(n^2) space since it allocates enough buffer on mempool for each call. This PR first collect cookie header values and then join them at last.
TODOs
=> merge cookie headers in O(n) order

include/h2o/socket.h, lib/common/memory.c
Fixes #3109 
It can be compiled both ubuntu latest and alpine latest(with docker).
At first, it can be removed the compile error
to add time.h. It refferred to here.
https://www.openembedded.org/pipermail/openembedded-core/2016-January/115069.html
Second, it doesn't choose XSI-compliant strerror_r. Because the alpine with musl isn't considered to gnu linux distributions (it has not `__gnu_linux__`) despite it defined `_GNU_SOURCE`.
=> Enable build with musl alpine (#3109)

lib/core/proxy.c
We merged https://github.com/h2o/h2o/pull/3121 but it'd be better to have a fast path when we only have one cookie header, especially for h1 requests which is expected to have already merge headers.
=> add a fast path to avoid unnecessary allocation and copy

lib/http1.c
After upgrading a h1 connection to bi-directional data stream, both of `http1-request-timeout` and `http1-request-io-timeout` become meaningless and should not be fired (we can rely on `proxy.timeout.io` for general idle timeout). This PR disables those timeout mechanisms by respecting `req->is_tunnel_req` field.
=> Disable http1 req timeout after upgrade

.github/workflows/ci.yml, .github/workflows/daily_coverity.yml
Github actions are starting to warn with:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, docker/login-action, docker/login-action, actions/checkout
=> update gh actions to latest

include/h2o/http3_common.h, lib/common/http3client.c, lib/http3/common.c, lib/http3/frame.c, lib/http3/server.c
The HTTP/3 `PRIORITY_UPDATE` frame format [changed](https://www.ietf.org/rfcdiff?url1=draft-ietf-httpbis-priority-01&url2=draft-ietf-httpbis-priority-02&difftype=--html) in `draft-ietf-httpbis-priority-02` and h2o still expects the old one.
=> Update HTTP/3 `PRIORITY_UPDATE` handling as per RFC9218

lib/common/http3client.c, lib/common/socket.c, lib/http3/server.c, t/40ssl-cipher-suite.t, t/50access-log.t
This PR changes code and tests to use the IANA name under `cipher->name` instead of `cipher->aead->name`
=> use iana tls 1.3 cipher names

src/ssl.c
```
commit 031d8a38a066f27ebfcd07105ce5832be1fd7f41
Author: Kazuho Oku <kazuhooku@gmail.com>
Date:   Tue Feb 21 16:00:05 2017 +0900
set `ticket_lifetime` to maximum until https://bugzilla.mozilla.org/show_bug.cgi?id=1340841 gets resolved
diff --git a/src/ssl.c b/src/ssl.c
index e94156074..1b18e3f26 100644
--- a/src/ssl.c
+++ b/src/ssl.c
@@ -897,7 +897,7 @@ void ssl_setup_session_resumption(SSL_CTX **contexts, size_t num_contexts)
#if H2O_USE_PICOTLS
static ptls_encrypt_ticket_t encryptor = {encrypt_ticket_key_ptls}, decryptor = {decrypt_ticket_key_ptls};
ptls_context_t *pctx = h2o_socket_ssl_get_picotls_context(ctx);
-            pctx->ticket_lifetime = conf.lifetime;
+            pctx->ticket_lifetime = 86400 * 7; // FIXME conf.lifetime;
pctx->encrypt_ticket = &encryptor; …
```
=> Fix session ticket lifetime

include/h2o.h, lib/core/util.c, src/main.c
Up until now, we have had two location at which we GC resources that are recycled, the `run_loop` function in src/main.c, and the other is `h2o_cleanup_thread` function.
As pointed out by #3150, the former was failing to recycle memory retained by the mempool allocator. The latter seems to have been failing to invoke `h2o_socket_clear_recycle`.
This PR address streamlines the design, merging the two functions, in the hope that the chance would be reduced of failing to add invocation on either side.
See also: #1624.
=> GC resources at one place

lib/handler/file.c
This is a follow up to #3124, which failed to return a newly created DSR sender object.
=> Return newly created DSR sender correctly

src/main.c
Current code enables QUIC DSR whenever a configuration `quic-dsr` is specified, regardless of its value. This patch fixes it by checking the actual value specified in the configuration.
=> Enable QUIC DSR only when "ON" is specified

lib/common/socket.c
When using async resumption mode, we have been generating the full TLS handshake response including public key signatures, even when the only intent is to fetch the session ID. With OpenSSL 1.1.1 and above, we can eliminate this cost by using SSL_CTX_set_client_hello_cb.
Honestly, I'm not sure if we need to retain async resumption as a feature, because it is need by operators running a server cluster willing to support session resumption against old clients that support resumption but not session tickets (i.e., old TLS 1.2 clients that are configured to use session stores on client side).
But anyways this is the fix.
This is An old efficiency problem found while reviewing #3064.
=> [async resumption] don't generate full handshake response just to discard it

deps/picotls/include/picotls.h, deps/picotls/lib/openssl.c, deps/picotls/lib/picotls.c, deps/picotls/picotls-probes.d, deps/picotls/picotls.xcodeproj/project.pbxproj, deps/picotls/t/cli.c, deps/picotls/t/ech-live.t, deps/picotls/t/minicrypto.c, deps/picotls/t/openssl.c, deps/picotls/t/util.h, deps/quicly/include/quicly.h, deps/quicly/lib/quicly.c, deps/quicly/src/cli.c, include/h2o/socket.h, lib/common/socket.c, src/main.c
This is a followup on #3064 / #3162, that enables async signature generation on HTTP/3 / QUIC.
Builds on top of https://github.com/h2o/picotls/pull/452, https://github.com/h2o/quicly/pull/538.
=> async signature generation for HTTP/3

src/main.c
This bug was overlooked in #3162 because the incorrect assignment yields always as zero in practice.
=> fix incorrect assignment and condition on platforms that do not have eventfd

deps/neverbleed/neverbleed.c, deps/neverbleed/neverbleed.h, deps/picotls/include/picotls.h, deps/picotls/include/picotls/openssl.h, deps/picotls/lib/fusion.c, deps/picotls/lib/openssl.c, deps/picotls/t/openssl.c, include/h2o/openssl_backport.h, include/h2o/socket.h, lib/common/socket.c, src/main.c, src/ssl.c
At the moment, async neverbleed support with picotls depends on OpenSSL async API. There are some drawbacks with the approach:
* Async neverbleed cannot be used when h2o is built with libressl. It would also be the case with boringssl (should we support it).
* There is the cost of using fibers and notification file descriptors, though that cost might be negligible compared to calculating signatures and doing IPC.
This pull request builds on top of the new high-level API added to neverbleed (that wraps EVP_DigestSign* rather than the ENGINE API backend calls and hence assumed to be compatible with async API of boringssl). It does not create a separate stack, nor allocates a file descriptor. A callback is used for resuming the handshake.
As picotls only handles TLS/1.3 handshakes, we …
=> [picotls][async neverbleed] remove dependency on OpenSSL async API

include/h2o/token_table.h, lib/common/token_table.h, misc/tokens.pl
The use of the header is discouraged in general:
https://www.rfc-editor.org/rfc/rfc9112#appendix-C.2.2-4
> As a result, clients are encouraged not to send the Proxy-Connection
> header field in any requests.
https://www.rfc-editor.org/rfc/rfc9110.html#section-7.6.1-7
> Furthermore, intermediaries SHOULD remove or replace fields that are
> known to require removal before forwarding, whether or not they appear
> as a connection-option, after applying those fields' semantics. This
> includes but is not limited to:
> - Proxy-Connection (Appendix C.2.2 of [HTTP/1.1])
> - Keep-Alive (Section 19.7.1 of [RFC2068])
> - TE (Section 10.1.4)
> - Transfer-Encoding (Section 6.1 of [HTTP/1.1])
> - Upgrade (Section 7.8)
And responses can't use the header in HTTP/2: …
=> Drop `proxy-connection:` in requests and responses

deps/neverbleed/neverbleed.c
https://github.com/h2o/neverbleed/pull/45.
Even though h2o calls `neverbleed_finish_digest_sign` only after the bytes are being read, `iobuf_shift_bytes` may return NULL if the following conditions are met:
* the compiler returns NULL for `malloc(0)` (such behavior is allowed by ISO C), and
* neverbleed returns a zero-byte signature for whatever reason.
If that happens, `memcpy` below becomes an undefined behavior because it dereferences a NULL pointer (`src`).
The fix in https://github.com/h2o/neverbleed/pull/45 explicitly calls out that a zero-byte signature is invalid. Doing so is better than trying to handle a zero-byte signature "corectly," because a zero-byte signature makes no sense at all.
=> merge neverbleed PR #45

lib/handler/mruby.c, lib/handler/mruby/middleware.c, t/50mruby-middleware.t
In Rack, headers appearing more than once are represented as arrays of strings.
When h2o receives such an array,
1. if the name of the header is `set-cookie` they can be concatenated using semicolon,
2. if the name is `cookie` they must not be concatenated,
3. otherwise can be concatenated using comma.
In contrary to these rules, we have been concatenating `cookie` headers (violating rule 2), as well as  applying `Array#to_s` under certain occasions instead of concatenating them using a delimiter of comma or semicolon under certain occasions.
This PR adds tests and fixes the incorrect behaviors.
Closes #3120.
=> [mruby] fix handling of headers appearing more than once

lib/http3/server.c
=> pointer in the direction of h3 -> quic is not initialized until `h2o_quic_setup` is called

CMakeLists.txt
Extend checking code from #3179.
Some versions of x86 CPU  do NOT support [AVX-512](https://en.wikipedia.org/wiki/AVX-512#CPUs_with_AVX-512), which provides following instructions and corresponding inline functions used in `deps/picotls/lib/fusion.c` . That will lead to compile error at assembly level.
| instruction (opcode) |  C inline functions |
|----------------------------|-----------------------|
|`vaesenc` | `__m256i _mm256_aesenc_epi128 (__m256i data, __m256i RoundKey)` |
|`vaesenclast` | `__m256i _mm256_aesenclast_epi128 (__m256i a, __m256i RoundKey)` |
|`vpclmulqdq` | `__m256i _mm256_clmulepi64_epi128 (__m256i b, __m256i c, const int Imm8)` |
reference:
[Intel Intrinsics Guide](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html)
=> improve FUSION check, ensure compiler can handle VAES instruction

include/h2o.h, lib/core/util.c, src/main.c, t/50file.t
#3151 has been the last change in the area though it has introduced the following issues:
* `h2o_cleanup_thread` is never called, because `next_buffer_gc_at` is initially set to `UINT64_MAX` and remains as such, because `h2o_now(...)` is always smaller than `UINT64_MAX`.
* Apparently, the (failed) intent has been to call `h2o_cleanup_thread` when `h2o_now(...)` becomes no less than `next_buffer_gc_at`. But that design is also incorrect. `h2o_filecache_clear` has to be called once per event loop, because otherwise we would not reopen the files that have been replaced.
This PR addresses these two issues, as well as adding a test for the latter.
=> make sure files are closed, unused resources are freed

lib/handler/connect.c
The connect handler currently keeps the the io timeout armed after a write has been issues to front end handlers. This is a problem because it's possible that the timeout fires when there's a write is already in filght, which is not the contract that handlers have with frontends (only one outstanding h2o_send can be inflight).
We fix this by simply disabling the timeout when a write is in flight, relying on the frontend idle timeout instead in these cases. The timeout is re-armed in the 'proceed' callbacks, as soon as the frontend is done with the write.
=> Potential assert when the timeout coincides with a write

lib/handler/connect.c, lib/http3/server.c
When packets are reordered or dropped, we might receive a CONNECT-UDP request and prepare a 200 response before receiving a SETTINGS frame expressing the client's intent to receive DATAGRAM frames.
When that happens, current code decides to _not_ use H3 datagrams for serving the UDP datagrams flowing to the client, fallback back to capsules sent on the stream.
This pull request changes the behavior. Instead of _not_ using H3 datagrams, the server waits for client's H3 SETTINGS frame, then decide how to send the UDP datagrams encapsulated.
With this change, clients that advertise support for H3 datagrams will have the guarantee that h2o would send encapsulated UDP datagrams using H3 datagrams.
=> [masque] queue 200 responses until H3.SETTINGS is received

h2o.xcodeproj/project.pbxproj, lib/handler/connect.c, t/50connect-inflight.t
If a write to the client is in progress when `proxy.timeout.io` expires, and there is data in the send buffer from the client to the origin, then `close_readwrite` will run the first time, close the origin socket, set `self->sock` to NULL, and it will schedule itself to run again.
When `close_readwrite` runs the second time, `self->sock` is already NULL, `close_socket` will not be called and `send_inflight` will not be determined correctly.  As a result of that, `close_readwrite` will call `h2o_send` even though a write to the client is still in progress.
The test `t/50connect-inflight.t` replicates the problem.
The fix in this PR is to determine `send_inflight` from the detached write buffer when `self->sock` is NULL.
#3200 (06f8e782a) fixed a problem with CONNECT-UDP when a write to the …
=> Fix a crash in the CONNECT handler after timeout with a write to client still pending.

deps/neverbleed/neverbleed.c, deps/neverbleed/neverbleed.h, src/main.c
In an environment where keys are frequently deleted/updated, the overhead of draining the asynchronous transaction queue to perform the synchronous "del_pkey" operation can be noticed.
This PR proposes an optimization to this specific command, by not requiring a response (fire-and-forget). In this case, the error condition is a warning and can't really be handled by the application which is why it can be response-less.
neverbleed: https://github.com/h2o/neverbleed/pull/52
(note by Kazuho): update of neverbleed incorporates https://github.com/h2o/neverbleed/pull/54
=> [neverbleed]: Response-less "del_pkey"

lib/handler/fastcgi.c
According to FastCGI specification (https://fastcgi-archives.github.io/FastCGI_Specification.html ): "Lengths of 127 bytes and less can be encoded in one byte, while longer lengths are always encoded in four bytes"
=> Fix fcgi encoding length problem

src/main.c
Fixes occiansional SEGV during boot on FreeBSD that was caused due to access contention on `environ`, by delaying the invocation of `h2o_spawnp` by the OCSP updater threads until `unsetenv` is called.
The updater thread was invoking `h2o_spawnp` that in turn calls `build_spawn_env` that uses `environ`, while the main thread calls `unsetenv` which is not required to be MT-safe.
=> fix access contention on `environ` leading to SEGV on boot

lib/common/memory.c
Because `posix_fallocate` may fail due to the underlying fs not supporting the semantics (of reserving disk blocks), see [`man posix_fallocate`](https://manpages.ubuntu.com/manpages/xenial/man3/posix_fallocate.3.html) as well as the behavior of zfs on FreeBSD.
=> Fall back to `ftruncate` if `posix_fallocate` returns EINVAL

deps/neverbleed/neverbleed.c, deps/neverbleed/neverbleed.h, src/main.c
neverbleed exdata: https://github.com/h2o/neverbleed/pull/55
responless `buf`: if the async socket isn't available, the transaction will be performed synchronously and the buf must be free'd after use
=> [neverbleed]: Fix memory leaks

lib/handler/configurator/proxy.c, lib/handler/proxy.c
The connect handler and the proxy handler requires the value of `max_buffer_size` be set to a non-zero value (this value designates the capacity of the internal buffer used for forwarding the bytes).
Inside the connect handler we have had an assert that complains if the value is set to zero.
However, neither in the proxy handler nor the configurator have we had the logic to reject such configuration, as pointed out by #3225.
This PR adds such logic that enforce correct setup.
=> [proxy] reject max_buffer_size of zero

lib/core/proxy.c
When handling certain type of malformed request received in HTTP/1, the reverse proxy uses an uninitialized pointer to read from memory.
Closes #3228. Security Advisory is coming.
=> [reverse proxy] invalid memory read

t/Util.pm
#2947 introduced `run_openssl_client` with an unconditional `sleep $timeout` after `open3` before the point at which the request is written (if set).  I do not think that that sleep is necessary.  
The correct use of `$timeout` is in the loop later that waits (at most `$timeout` seconds) for openssl to exit.
=> run_openssl_client: do not delay by $timeout before writing request

src/httpclient.c
In `filler_proceed_request` make sure to exit on error, otherwise this leads to a use after free.
=> Trivial h2o-httpclient h3 fix

lib/http3/server.c
```
h2o: /um/lib/http3/server.c:1069: proceed_request_streaming: Assertion `!h2o_linklist_is_linked(&stream->link)' failed.
(gdb) bt
#4  0x00007ffff77629f6 in __assert_fail () from /usr/lib/libc.so.6
#5  0x000055555567feb9 in proceed_request_streaming (_req=0x7fff3401ae30, errstr=0x5555557a4cd0 <h2o_httpclient_error_refused_stream> "refused stream")
at /um/lib/http3/server.c:1075
#6  0x0000555555630e67 in on_head (client=0x7fff3402e3d0, errstr=0x5555557a4cf8 <h2o_httpclient_error_io> "I/O error", args=0x0)
at /um/lib/core/proxy.c:566
#7  0x00005555555f3d92 in call_on_head (client=0x7fff3402e3d0, errstr=0x5555557a4cf8 <h2o_httpclient_error_io> "I/O error", args=0x0)
at /um/lib/common/http1client.c:129
#8  0x00005555555f3f40 in on_error (client=0x7fff3402e3d0, errstr=0x5555557a4cf8 …
```
=> h3 server/proxy: It's possible that `proceed_request_streaming` gets called before a body chunk is received

lib/common/http3client.c, src/httpclient.c
The API contract around `proceed_req` is that if the callback is available, the client implementation first sends the bytes then call `proceed_req` to obtain more data to send.
That is the design and production ready code like lib/common/http1client.c, lib/common/http2client.c, lib/core/proxy.c behaves according to the design.
However, src/httpclient.c and lib/common/http3client.c did not obey to the contract.
That led to src/httpclient.c raising assertion failure when command line arguments like `-b 100 -d 100 -t 1000 -m POST` is given. Once the problem was fixed, lib/common/httpclient.c started to stall because it shared the incorrect assumption with src/httpclient.c.
=> [httpclient][http3] fix incorrect assumption leading to crashes when streaming request

h2o.xcodeproj/project.pbxproj, lib/http2/hpack.c, t/00unit/lib/http2/hpack.c, t/40http2-header-softerror.t
As pointed out and discussed in #3250, RFC 9113 (2nd revision of HTTP/2 specification) tightened the requirements against HTTP/2 intermediaries rejecting invalid header fields.
This PR makes necessary changes so that we are conformant to the new revision. Specifically, header fields carrying values surrounded by whitespace are rejected, and also those with empty (i.e., zero-length) names.
Latter is not an explicit requirement of RFC 9113 though RFC 9110 defines field names as carrying at least one character.
=> [http2][http3] tighten header validation

misc/docker-ci/check.mk
Default size is 1GB, which is too small if test concurrency is like 16.
=> make tmpfs size adjustable, to allow high concurrency of tests

t/50dnsresolver.t, t/Util.pm
In CI, we have occasionally seen t/90h2olog.t time out.
It seems that this is due to a stale process with the name being `t/50dnsresolver.t` hanging around. As the process owns the shared lock of the lock file that is used for serializing the h2olog-related tests, t/90h2olog.t fails to obtain an exclusive lock and times out.
This PR addresses the issue by switching the signal used from KILL to TERM, so that whatever child process spawned by Net::DNS::Nameserver will be collected, as well as making sure that child processes will be collected before global destruction which could be unstable.
=> [CI] fix t/90h2olog.t timing out

misc/docker-ci/Dockerfile.ubuntu2204, misc/docker-ci/check.mk, t/Util.pm
ToDo: forbid skip in other forms too (e.g., `curl_supports_http2`, `perl -MStarlet`), if SKIP_PROG_EXISTS is set.
=> skip checking for dependency executables if SKIP_PROG_EXISTS is set

src/main.c, t/50linux-capabilities.t
The `capabilities` directive is ignored when no `user` directive is set. This is not a problem in production because most of prod config files will have `user` with root privileges.
However, it is a problem in making tests for `capabilities`. If one starts h2o with a normal user and `capabilities` in the config file, h2o starts with no messages even if `capabilities` is not effective. Instead, h2o should not start and show error messages such as:
> failed to setup capabilities: cap_set_proc: Operation not permitted
This is what the PR does. 
FWIW `t/50linux-capabilities.t` is not a test case for the above change, but I'm adding it because there is no test case that uses `capabilities`.
=> do not ignore `capabilities` directive when `user` directive is not set

lib/common/http2client.c
A possible scenario before this PR is as follows:
1) Server does something that causes `parse_input` to receive an error
when calling `conn->input.read_frame`.
For example, receiving a HEADERS stream for a stream that we just
reset appears to trigger `H2O_HTTP2_ERROR_STREAM_CLOSED`.
In this case `parse_input` is going to call:
```
call_stream_callbacks_with_error(conn, h2o_httpclient_error_protocol_violation);
return close_connection(conn);
```
when using the proxy handler, `call_stream_callbacks_with_error`
can to call `proxy.c::on_head()`. That in turn detaches the client
from the generator:
```
h2o_httpclient_t *client = self->client;
client->data = NULL;
```
Then `close_connection` might have a non-empty write buffer, in which
case the input buffer is going to be queued for a write. …
=> [http/2 client] Make sure we don't invoke callbacks twice

misc/docker-ci/Dockerfile.ubuntu2004
At the moment, it is only added to ubuntu2004 variant (which is the default used by picotls).
=> [ci] for https://github.com/h2o/picotls/pull/478, add libaegis to CI image

lib/common/http2client.c, t/50http2_client_rst_streams.t, t/Util.pm
In the current code base, the following can happen:
1) h2o h2 client sends HEADERS
2) h2o h2 client sends RST_STREAM
3) server sees HEADERS, processes it, and sends a HEADERS back
4) h2o h2 client sees the HEADERS belonging to a closed stream and closes
the entire connection: https://github.com/h2o/h2o/blob/326ab4671639f9321a2288fbb8735411c320420f/lib/common/http2client.c#L974-L980
Attached is a PoC, but it's unsatisfying:
- reset streams are kept forever
- the number of streams to record might be more than the 10 i've hardcoded.
Better options seem to include:
- add a timer and periodically reset `recently_rst_streams`
- sending a PING frame along with the reset, and clear the stream when receiving the PONG
But before embarking in this i figured i would ask for opinions.
=> [RFC][http/2 client] Do not reset recently closed streams

include/h2o.h, include/h2o/http2_common.h, include/h2o/qpack.h, lib/core/logconf.c, lib/http1.c, lib/http2/hpack.c, lib/http2/stream.c, lib/http3/qpack.c, lib/http3/server.c, t/50access-log.t
We currently have the ability to log body bytes via %b. This PR adds the ability to also log the header bytes via %{header_bytes}
=> Add the ability to log header bytes

t/50http2_client_rst_streams.t, t/50reverse-proxy-early-response.t, t/50reverse-proxy-http2-trailers.t, t/50reverse-proxy-http2.t, t/Util.pm
1. As https://github.com/h2o/h2o/pull/3270 revealed that `spawn_forked` captures stderr and it may make debugging hard from time to time. This PR makes that behavior OFF by default. To capture stderr, the user has to pass `+{ stderr => 1 }` options explicitly.
2. Writing to pipes can be blocked. This PR uses temporary files instead of pipes.
3. Since reading stdout and stderr implicitly requires `kill` callback has been called beforehand. This PR has modified it to return `(stdout, stderr)` as the return value of `kill`.
=> Improve spawn_forked

include/h2o/hpack.h, lib/http2/hpack.c
This PR also contains a change to have `h2o_hpack_parse_response` document the reason for the rejection, which would have made troubleshooting the `host:` issue easier.
=> [http/2 client] Do not reject responses containing a `host:` header

lib/common/http1client.c, lib/common/http2client.c, lib/common/memory.c, lib/http2/connection.c, lib/http2/hpack.c, lib/http2/stream.c, src/main.c
To avoid any bikeshed, our coding style is dictated by clang-format (`make -f misc/regen.mk clang-format-all`).
=> clang-format-all

lib/http2/connection.c, lib/http3/server.c
This makes it clear from `h2olog` output whether the request actually came in with `:scheme` or not.
=> Log the request to h2olog before defaulting `stream->req.input.scheme` for HTTP/2 and 3.

lib/core/request.c, lib/http2/connection.c, lib/http3/server.c
For #3278
* Allow `:scheme https` in draft-mode CONNECT-UDP in HTTP/2 and HTTP/3.
* Make `:authority` optional in HTTP/3 like it is in HTTP/2.
* Convert `lib/http3/server.c` to `must_exist_map`/`may_exist_map` like `lib/http2/connection.c`.
=> Allow `:scheme https` in draft-mode CONNECT-UDP.

deps/neverbleed/neverbleed.c, lib/http2/cache_digests.c, lib/http2/casper.c, src/ssl.c
As pointed out in #3285, we have code that uses OpenSSL API declared legacy in 3.0.
This PR suppress them instead of diverging code between different TLS stacks, as suppression is considered to be the lower-cost option.
=> Suppress legacy API warnings generated by OpenSSL 3.0 and above

t/50access-log-delivery-rate.t, t/Util.pm
It is often helpful to retain debug logging in tests, because they help us find out why the test are failing. The requirement for such debug logging is that they should be off by default and have a way to be turned on.
This pull request introduces a convenient function called `debug`.
Test cases can call `debug()` to supply information that would be helpful for debugging issues with tests.
`debug()` will be a no-op by default, but will call `diag()` if the TEST_DEBUG environment variable is set to a truthy value.
=> [test] define standard way of emitting debug output (call `debug(args)`)

include/h2o.h, include/h2o/http2_internal.h, lib/core/config.c, lib/core/configurator.c, lib/core/context.c, lib/http2/connection.c
Hi!
This is a backport of 94fbc54b6c9309912fe3d53e7b63408bbe9a1b0d from https://github.com/h2o/h2o/pull/3291 to the v2.2.x branch.
I know that all the tagged releases should be considered deprecated, and that no new version will be released in the future, therefore I don't expect this pull request to be merged. While we are transitioning from `libh2o-evloop` to `nghttp2` in DNSdist, we unfortunately need to keep our `h2o` support alive for a little bit longer while the transition is complete, so we have been working on backporting the HTTP2 rapid reset fix on top of 2.2.6, and we decided to share the result in case it helps others. 
Please note that we unfortunately had to break the ABI to introduce the new timer, so this change will require a rebuild of applications dynamically linked …
=> Backport to v2.2.x: [http2] delay processing requests upon observing suspicious behavior

deps/quicly/examples/echo.c, deps/quicly/include/quicly.h, deps/quicly/include/quicly/cc.h, deps/quicly/include/quicly/frame.h, deps/quicly/lib/cc-cubic.c, deps/quicly/lib/cc-pico.c, deps/quicly/lib/cc-reno.c, deps/quicly/lib/defaults.c, deps/quicly/lib/frame.c, deps/quicly/lib/quicly.c, deps/quicly/quicly-probes.d, deps/quicly/src/cli.c, deps/quicly/t/frame.c, deps/quicly/t/test.c, lib/http3/server.c, src/h2olog/generated_raw_tracer.cc, src/main.c
Incorporates https://github.com/h2o/quicly/pull/561.
New fields added to `quicly_stats_t` are logged as part of `%{http3.quic-stats}x` logging directive.
Use of ECN as a sender can be turned off by setting the `ecn` parameter of `listen` -> `quic` to `OFF` (default: `ON`).
=> [http3] support ECN

lib/http3/server.c
This is for `%{http3.quic-stats}x`.
I did take a look at what are being emitted by the old and new code, extracting all the names found in the list. Then compared the two, and made sure that they are identical.
=> [access-log] to ease merging, use one line of source code per each attribute

deps/quicly/lib/quicly.c, lib/common/socket.c
Builds on top of https://github.com/h2o/quicly/pull/563.
As reported in #3298, h2o fails to accept HTTP/3 connections when it it configured to send Retries (i.e., when having `retry: ON` in the configuration file).
This PR fixes the issue. For more information, please refer to the quicly PR.
Closes #3298.
=> [ipv6] fix address token validation failures

deps/picotls/cmake/fusion.cmake
Adopts https://github.com/h2o/picotls/pull/493. Closes #3289.
=> [fusion] to activate, test availability of _mm_insert_epi64

include/h2o.h, lib/common/http2client.c
Before this commit, we would erroneously imply that the request could be safely retried.
=> Only forward a RST_STREAM as REFUSED_STREAM if the error code is actually REFUSED_STREAM

lib/http3/server.c
=> [access-log] fix emission of extra `NUL` char by `%{http3.quic-stats}x`

lib/common/url.c, t/00unit/lib/common/url.c
However, according to RFC 3986, this is a valid URL as `path`/`path-abempty` part of the grammar allows for this (section 3.3):
"If a URI contains an authority component, then the path component
must either be empty or begin with a slash ("/") character."
Solution: ensure h2o_url_parse accommodates this case
=> Problem: h2o_url_parse fails on http://example.com:8080?abc

t/run-tests
In our CI environment, we occasionally see the log files of each `.t` file to be incomplete. I suspect that this is due to the `fork` in the `log_add_timestamp` sub, because the main test runner only waits for the parent process which writes to the pipe, and does not wait for the child process that reads from the pipe, to finish.
This patch adds an flock to the reader/writer of the output log file, making sure that the reader of the log file would wait for the child process to finish. I've also tried to swap the parent/child process relationship, but the flock approach is a smaller change and is more generic.
=> lock the logfiles for read/write to wait for the timestamp appender

lib/handler/proxy.c, lib/http3/common.c, src/main.c
There are few places where `fprintf` and `abort` is used, replaced it with `h2o_fatal`
#3244
=> replace `fprintf` and `abort` with `h2o_fatal`

t/40http1-pipeline.t
In this test, `$server` hash containing Scope::Guard object is referenced from `send_and_receive` sub, making a static reference to it, and prevents it from garbage collected in a regular lexical way. The reference will be eventually destroyed with the global destruction, so it's not an issue, but this PR makes it avoid it so the object gets garbage collected regularly.
=> Pass server port to avoid $server statically referenced

t/run-tests
in #3324 flock is introduced so `run-tests` will wait for the test to actually finish before reading the log file. With that change, when a test actually times out (after 600s), the parent cannot acquire the lock because the child process (test) is never terminated.
This PR adds a `kill` to reap the timed out tests.
=> kill timed out tests

deps/picohttpparser/.github/workflows/ci.yml, deps/picohttpparser/.travis.yml, deps/picohttpparser/Makefile, deps/picohttpparser/picohttpparser.c, deps/picohttpparser/picohttpparser.h, deps/picohttpparser/test.c, h2o.xcodeproj/project.pbxproj, t/80http1-chunk-overhead.t
Adopts https://github.com/h2o/picohttpparser/pull/81; please refer to the PR for context.
In this PR, h2o's own tests are also added. They might not be strictly necessary, though they do assert that error responses are sent correctly upon detecting malicious behavior.
=> Detect and reject excess overhead in chunked encoding

lib/http2/hpack.c
In #3278, specifically in commit de9c6af, we started passing NULLs to `h2o_hpack_parse_request` when parsing trailers, as pseudo headers are not expected to seen.
This almost worked, as the `pseudo_header_exists_map` is also set to NULL. Due to this argument set to NULL, pseudo headers are simply rejected.
But there was one regression, and that is that if a host field is found, the hpack decoder tries to store the value by dereferencing a pointer that points to the storage of the `:authority` pseudo heaoder, without NULL-checking the pointer, hence leading to a crash.
=> avoid NULL deref when `host` field appears in trailer (amends #3278)

misc/docker-ci/Dockerfile.ubuntu2204, t/50connect-proxy-status.t, t/50connect.t
Based on https://github.com/h2o/h2o/pull/2990. This PR just updates the image without making any changes to the tests to actually use it. Follow-on PRs will address that.
=> Update CI image (ubuntu 22.04) to contain curl with support for H3

lib/http3/server.c
This check has been missing in the h3 side.
=> [http3] if send-informational is set to NONE, suppress 1xx

lib/http3/server.c, t/50reverse-proxy-timings.t
Partially resolves one of the TODOs in #3346.
Trailer support is still missing as we need a complex logic to obtain the moment the final byte of the response body is emitted onto the wire. To observe that moment and then build trailers, we need to keep the stream open after all the response body becomes ready.
=> [http3] send server-timing header

t/50mruby-http-request.t
Closes one of the TODOs in #3346.
Two issues were both due to abrupt close leading to total loss of response, likely due to curl-ngtcp2 not reporting any byte (even the headers) as received when the stream is reset without delay.
=> fix h3 CI issues with t/50mruby-http-request.t

t/50mruby-middleware.t
This is also an issue with incorrect content-length header; see #3348.
Closes one of the TODOs in #3346.
=> fix h3 CI issues with t/50mruby-middleware.t

include/h2o.h, include/h2o/configurator.h, lib/core/config.c, lib/core/request.c, lib/handler/configurator/access_log.c, lib/handler/configurator/compress.c, lib/handler/configurator/errordoc.c, lib/handler/configurator/expires.c, lib/handler/configurator/fastcgi.c, lib/handler/configurator/headers.c, lib/handler/configurator/headers_util.c, lib/handler/configurator/reproxy.c, lib/handler/configurator/server_timing.c, lib/handler/configurator/throttle_resp.c, lib/handler/file.c, t/50file-custom-handler.t
The configuration file of h2o uses a lexical structure.
In the example below, a response to `example.com/` will include headers not only "p" but also "g" and "h", because they are defined at "global" or "host" level.
```yaml
header.add: "g: 1"
hosts:
example.com:
paths:
"/":
...
header.add: "p: 3"
header.add: "h: 2"
```
Up until now, `file.custom-handler` has worked the same way, but that has caused confusion. In the following example, when processing a request to `example.com/index.php`, the access will not be logged in `/path/to/log`. This is because the custom handler for extension `.php` is defined at the global level, rather than within the lexical scope of the path that has the `access-log` directive being used.
```yaml
file.custom-handler:
extension: .php
fastcgi.spawn: …
```
=> apply filters and loggers at host and path level, when file.custom-handler at global level is applied

lib/common/socket.c
Hi,
I am a new contributor looking forward to contribute to the h2o project :).
Fixes #3354. The leak occurs because buf is allocated within `h2o_socket_log_tcp_congestion_controller` but not freed if `getsockopt` fails. 
The patch in this case checks if pool is NULL. If so the allocated memory `buf` is not referenced by `pool`. Therefore  we are free to deallocate `buf` after `getsockopt` branch in this case.
Let me know if this is a good patch! If not let me know what changes need be done. I am eager to contribute more to this repository :)
=> Fix leak in socket.c

src/main.c, t/40http3-forward.t
Current inter-node forwarding doesn't work for for mismatching address
families: if the internode address is ipv4, it cannot process forwarded
ipv6 packets and vice versa.
This fix instruments the listener creation logic by marking which
listeners are each other's 'siblings', meaning they come from the same
configuration directive, which resolved to one ipv4 listener on one hand
and ipv6 on the other.
The forwarding logic then uses that sibling fd in order to reach the
worker thread with the context matching the address family.
=> http/3 quic: fix inter node forwarding for mismatched address families

fuzz/driver_h3.cc, include/h2o.h, include/h2o/http3_common.h, include/h2o/http3_server.h, lib/common/http3client.c, lib/core/context.c, lib/handler/proxy.c, lib/http3/common.c, lib/http3/server.c, src/httpclient.c, src/main.c
When creating a new QUIC connection, CIDs are cloned from `h2o_quic_ctx_t::next_cid`, and `h2o_quic_ctx_t::next_cid.master_cid` is incremented.
If there are multiple accepting contexts (e.g., due to multiple `listen` directives in use, or due to one `listen` directive binding to both IPv4 and IPv6), there will be multiple instances of `h2o_quic_ctx_t` and therefore, there could be multiple QUIC connections sharing the same thread id and master id.
While this is behavior is fine in terms of operations, it causes confusion to the log collected by h2olog. This is because each log line of `h2olog` contains only the thread-id and conn-id (corresponds to master id).
This PR address the confusion by changing the code so that all instances of `h2o_quic_ctx_t::next_cid` refer to one thread-local …
=> [h2olog] ensure uniqueness of connection id

src/httpclient.c
The default size is surprisingly small and would become the connection bottleneck even with relatively low RTTs. This increases it to 128k, which might make a better default.
=> h2o-httpclient: increase the max_buffer size

include/h2o/memory.h, lib/common/memory.c
Follows the suggestion of @yrashk in #3244 to make the `h2o_fatal` macro call through a function pointer call whose default is the current `h2o__fatal` function. This makes it possible to configure and reset `h2o_fatal` at runtime.
=> make h2o_fatal use h2o__fatal_redirect function pointer #3244

lib/common/http3client.c
Before this fix, if name resolution was used by the http3 client, it might have returned a result that didn't correspond to the socket used in `st_h2o_quic_ctx_t`.
=> http3client: socket pool DNS resolution must only return addresses corresponding to the address family of `st_h2o_quic_ctx_t`

src/h2olog/h2olog.cc
t/90h2olot-socket.t uses debug message "Attaching..." as an indication that h2olog has started receiving events from h2o. But when the socket mode is used, the message is emitted immediately after h2olog sends the HTTP request, which could be earlier than when h2o recognizes the request and start sending the events, leading to a race.
This PR fixes the issue by changing the moment the message is emitted to when h2olog receives the HTTP response headers indicating that h2o has accepted the request to forward events.
=> fix race in t/90h2olog-socket.t

lib/http3/server.c, t/80issues3388.t
#3388 is an attempt to continue forwarding a response even when the request side that is streamed is reset (i.e., `h2o_req_t::proceed_req` callback is invoked with a non-NULL error string). But as stated in https://github.com/h2o/h2o/pull/3388#issuecomment-2174642752, as the callback error signals termination of both the request and the response, it is not always possible to forward a response under such situation; the only possible case is when the entire response is provided prior to the callback error.
Therefore, this PR adjusts #3388 in the following ways:
* refactor the provided test as a unit test case
* do not reset the response if the entire response is available, unless the client asks h2o to stop.
While this PR does not address the case where a request streaming error is …
=> [http3] when streamed request is reset, continue sending response if possible

lib/common/socket/evloop.c.h, src/httpclient.c, t/40http3-reconnect.t
At the moment, the flag works only when H3 is used.
Also, this PR incorporates a mitigation against broken logic that perpetually set a zero-timeout. As of d327485, h2o will continue to process events even if something starts doing that (at the cost of consuming 100% CPU cycles), rather than ceasing to work due to missing I/O events or updates to the internal clock.
Full fix for the issues is https://github.com/h2o/quicly/pull/587.
=> [h2o-httpclient] add `-s` option for resumption

src/main.c
https://boringssl.googlesource.com/boringssl/+/e95b0cad901abd49755d2a2a2f1f6c3e87d12b94 made calling `SSL_CTX_set_min_proto_version()` mandatory to support lower (than 1.2) versions of TLS.
Verified that options via min-version is still honored as expected. 
I believe `t/50status.t` enforces that the configured minimum version (`min-version`) is still honored.
=> Latest BoringSSL to support TLS1.0 and TLS1.1

CMakeLists.txt
`ADD_CUSTOM_COMMAND()` in `CMakeLists.txt` might not support shell commands in some environments and `sh -c` forces it to be interpreted as a shell command. I encountered this issue when building `h2o` nested inside `meson`. Related:
- https://stackoverflow.com/questions/66656004/shell-commands-using-cmake-add-custom-command-on-linux
- https://cmake.org/cmake/help/latest/command/add_custom_command.html
`h2o` does not seem to support Windows so `sh` should be available.
=> Use `sh -c` for shell commands in `CMakeLists.txt`

include/h2o.h, lib/http1.c, lib/http2/stream.c, lib/http3/server.c
This PR adds assertions that detect improper invocations `h2o_send` that do provide no data to make progress.
Rather than adding the assertions to `h2o_send`, the checks are added to the `do_send` callbacks found in the http server-side implementations due to the following reasons:
* `h2o_send` does not know if it is invoked for the first time (invocation with zero-byte body is permitted for the first time only),
* output filters (e.g., on-the-fly compression) might modify the data then call `h2o_ostream_send_next` that call the `do_send` callbacks; it is better to have the check where the data is actually used
=> validate h2o_send (do_send) is called when progress can be made

lib/http1.c, t/40no-h2c.t
The current behavior lets the request through and depending on whether the handler lets an `upgrade:` request through or not, might forward the request and attempt an upgrade or return a 403.
This PR makes h2o forward the request to the backend.
=>  When h2c is disabled, ignore the upgrade: header

src/main.c
Due to h2o using the PTLS_HAVE_ macros incorrectly, the change introduced in https://github.com/h2o/picotls/pull/532 has caused CI errors on flavors that use OpenSSL 1.0.2 (i.e., ones without X25519).
It might be time to get rid of flavors that use versions of Ubuntu no longer maintained. But regardless, this PR changes h2o to use the macro correctly.
=> fix build issue on CI

include/h2o/http2_common.h, lib/common/http2client.c, lib/http2/hpack.c, t/50reverse-proxy-expect-100-continue.t
This is a follow up to https://github.com/h2o/h2o/pull/3316/ -- adding support for the same configuration knob for the http2 client.
=> Add support for proxy-expect: for http2client

deps/picotls/include/picotls.h, deps/picotls/lib/picotls.c, deps/picotls/picotls.xcodeproj/project.pbxproj, deps/picotls/picotlsvs/bcrypt-test/bcrypt-test.vcxproj, deps/picotls/picotlsvs/fusiontest/fusiontest.vcxproj, deps/picotls/picotlsvs/picotls-bcrypt/picotls-bcrypt.vcxproj, deps/picotls/picotlsvs/picotls-core/picotls-core.vcxproj, deps/picotls/picotlsvs/picotls-fusion/picotls-fusion.vcxproj, deps/picotls/picotlsvs/picotls-minicrypto-deps/picotls-minicrypto-deps.vcxproj, deps/picotls/picotlsvs/picotls-minicrypto/picotls-minicrypto.vcxproj, deps/picotls/picotlsvs/picotls-openssl/picotls-openssl.vcxproj, deps/picotls/picotlsvs/picotlsvs/picotlsvs.vcxproj, deps/picotls/picotlsvs/ptlsbench/ptlsbench.vcxproj, deps/picotls/picotlsvs/testopenssl/testopenssl.vcxproj, deps/picotls/t/cli.c, deps/picotls/t/picotls.c, doc/configure/base_directives.html, src/main.c, srcdoc/configure/base_directives.mt
Integrates https://github.com/h2o/picotls/pull/548 and adds `max-tickets` property to `listen` -> `ssl`.
=> add support for ticket-requests (RFC 9149)

include/h2o/memory.h, lib/common/memory.c
in gcc, it seems unclear if the compiler should generate an error: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80495
in clang, I get the following error:
```
error: '_Noreturn' can only appear on functions
```
see https://clang.llvm.org/docs/AttributeReference.html#noreturn
=> Fix H2O_NORETURN for fn pointers on clang

src/main.c
In #3433, we introduced a new configuration knob called `key-exchange-tls13` for specifying the key exchange algorithms to be used.
Unfortunately, the knob did not correctly handle invalid names. Rather than printing an error message and refusing to start up, the server starts running with an invalid configuration.
This PR fixes the bug.
=> correctly error-exit when given invalid key exchange names

lib/http3/common.c
In #3430, PTLS_LOG was added for consistency with H2O_PROBE, but we need a null check here.
=> [h2olog] Add NULL check for h3_frame_receive.payload

deps/quicly/lib/quicly.c, deps/quicly/src/cli.c, deps/quicly/t/test.c, t/40http2-header-softerror.t, t/40session-ticket.t, t/40tunnel.t, t/50chunked-encoding-proxying.t, t/50compress-hint.t, t/50compress-wetag.t, t/50proxy-max-buffer-size.t, t/50reverse-proxy-chunk-sizes.t, t/50reverse-proxy-chunk-trailing-headers.t, t/50reverse-proxy-request-bytes.t, t/50reverse-proxy-round-robin-weighted.t, t/50too-much-data.t, t/50too-much-headers.t, t/80http1-chunk-overhead.t, t/80reverse-proxy-truncated-chunked.t
Adopts https://github.com/h2o/quicly/pull/599. Also fixes deadlocks found in tests.
Note one test (t/80chunked.t) still gets stuck on Alpine. This is due to it having a different version of `nc` that does not listen to the specified host:port when given auguments of `-l host port`. At the moment, we use this form so that the tests run as expected on ordinary linux, FreeBSD, macOS.
=> fix `make checkdepends` failure on alpine linux

src/main.c
Some clients appear to only support that one
=> Add secp384r1 as a key exchange algorithm

misc/docker-ci/build.mk
When host supports IPv6 and the DNS is returning AAAA results, setting `--network=host` makes sense, because otherwise the guest might not have IPv6 support and fail to build.
But as the situation might depend on each environment, we stop by providing a knob for changing arguments, with the example suggesting the use of `--network=host`.
=> allow users pass options to docker build

lib/common/http1client.c
the optimization doesn't make sense in this case since it would result in encrypted bytes being fed to the pipe.
=> [http1client] do not opt-in the pipe reader if the client is using ssl

h2o.xcodeproj/project.pbxproj, lib/http3/common.c, src/httpclient.c, src/main.c, t/40http3-hrr.t, t/40http3-key-exchange.t
As stated in #3505, h2o silently discards 2nd flight of QUIC initial packets sent by the client.
ToDo:
Closes #3505.
=> correctly route 2nd flight of QUIC Initial packets

t/50connect-eyeballs.t
As stated in #3521, when a tunnel is closed, the client might notice that either by observing a FIN or a STOP_SENDING, though it is worth noting that in either case, no data downstream will be lost.
While it is arguable that all the components should support half-close correctly, it is known that intermediaries often do not provide such support, and knowing that, we have intentionally avoided the hassle of implementing proper support.
Therefore, under the premise that we would not revisit that decision, we should either:
* in h2o-httpclient or lib/common/http3client.c, stop reporting STOP_SENDING as errors, or
* in the tests, ignore error messages emitted due to STOP_SENDING.
This PR adopts the latter appoarch, because, generally speaking, it is better to ignore errors (or this exact …
=> [t/50connect-eyeballs.t] I/O error is expected under the current architecture
